### ISSUE TITLE
Better geo handling in Druid

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1055]
Currently Druid geographic/spatial index handling and filtering assumes completely Euclidian coordinates in only one coordinate projection. This means that the coordinates have to essentially already be in a rectangular space in order to have a completely expected behavior.

This feature request is to add better Geo support in the following manner:
- Allow the use of [wgs84](http://en.wikipedia.org/wiki/World_Geodetic_System) or rectangular coordinates when specifying data
- Allow the use of [WKT](http://en.wikipedia.org/wiki/Well-known_text) (or WKB) or a limited subset

**Comment by cheddar** [comment]
Fwiw, the integration of the geospatial indices is also quite clunk-clunk, to use the technical term.

It would be great to see about extending the types of things that columns can do to support a GeoSpatial index or figure out a way to make the geo spatial indexing fit the current set of things that columns can do a little better...

**Comment by mazorigal** [comment]
Hi,

Is there in work in progress regard geo index and queries ?
for wgs84 coordinates, the euclidian distance is indeed the wrong one to use.
Some workaround that I thought about could be to reprocess the data before indexing to druid by 
projecting wgs84 coordinates (latitude, longitude) to a cartesian coordinates system (x, y, z)
Then the euclidian distance can give good enough estimation to the distance between 2 points (especially important for the radius filter), however I was not able to index spatialDimensions using 3 points (x,y,z), I did managed to index only using 2 points (x,y), however using only 2 points with the  euclidian distance give wrong results. (https://math.stackexchange.com/questions/636993/different-ways-for-calculating-distance-between-two-geodetic-points-give-me-diff)
Not sure also why using more then 2 points for the spatialDimensions should fail, as calculating euclidian distance can be done based on an arbitrary number of points in any N-dimensional space.

**Comment by b-slim** [comment]
@mazorigal  i don't think there is ongoing effort to fix this any contribution is welcome.

**Comment by mazorigal** [comment]
I would be happy to contribute, but unfortunately I am not a java developer, hence would not know even where to start.
But as a staring point, how hard would it be to allow the spatialDimensions accept cartesian geo points with 3 dimensions (x,y,z) so the euclidian distance which druid is using would be much more accurate than the current status ?

**Comment by hevansDev** [comment]
I've recently been working with measuring the distances between simple lat, lon, and alt coordinates rather than wgs84 but am interested in working on contributing some functions for doing these calculations, potentially something like [ST_Distance_Sphere](https://tighten.com/insights/a-mysql-distance-function-you-should-know-about/)? I've been using variations on the formula ```ACOS((SIN(RADIANS(Lat1)) * SIN(RADIANS(Lat2))) + (COS(RADIANS(Lat1)) * COS(RADIANS(Lat2))) * (COS(RADIANS(Lon2) - RADIANS(Lon1)))) * 6371``` which could potentially be an improvement on Euclidean distance?
