### ISSUE TITLE
Optimize IndexTask to generate multiple partitions concurrently.

### ISSUE THREAD

**Issue by luxuec** [apache/incubator-druid#1062]
currently generateSegment() method is called sequentially in task runner thread. Making it run multiple threaded will improve performance.

**Comment by drcrallen** [comment]
Right now the incremental index row adding is very single-threaded. Do you have any sort of profile to show the bottleneck is completely in the firehose rather than in the incrementalIndex?

**Comment by luxuec** [comment]
What I am seeing is the generateSegment() is one of the places that can speed up. Based on my use cases, I execute index task 3 times faster by running generateSegment() in 8 threads(8 shard partitions). Also IncrementalIndex.add() is called in generateSegment(), if I understand correctly.

**Comment by nishantmonu51** [comment]
I think the title of the issue is a bit misleading, generateSegment() is part of indexTask not the firehose, 
will it be better framed as - "Optimize IndexTask to generate multiple partitions concurrently" ?

**Comment by luxuec** [comment]
Make sense. Changed the title. thanks.

**Comment by drcrallen** [comment]
#1065 is a major PR on the ingestion side of things which is likely part of this.
