### ISSUE TITLE
TopN Aliasing

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1134]
TopN currently has a problem with aliasing of results. For example, consider the following two queries and their results:
## Aliased Query

``` json
{
    "aggregations": [
        {
            "fieldName": "L_QUANTITY_longSum",
            "name": "L_QUANTITY_",
            "type": "longSum"
        },
        {
            "name": "count",
            "type": "count"
        }
    ],
    "context": {
        "bySegment": false,
        "finalize": true,
        "offHeap": false,
        "populateCache": false,
        "useCache": false
    },
    "dataSource": "tpch_year",
    "dimensionBasic":"l_orderkey",
    "dimension": {
        "dimExtractionFn": {
            "function": "function(str) { var re = /(^103136$|^1648672$)/; return str.replace(re,\"KING\"); }",
            "type": "javascript"
        },
        "dimension": "l_orderkey",
        "outputName": "l_orderkey_",
        "type": "extraction"
    },
    "granularity": "all",
    "intervals": [
        "1900-01-09T00:00:00.000Z/2992-01-10T00:00:00.000Z"
    ],
    "metric": "L_QUANTITY_",
    "queryType": "topN",
    "threshold": 1
}
```
## Aliased Result

``` json
[ {
  "timestamp" : "1992-01-02T00:00:00.000Z",
  "result" : [ {
    "count" : 10,
    "l_orderkey_" : "KING",
    "L_QUANTITY_" : 417
  } ]
} ]
```
## Non-aliased Query

``` json
{
    "aggregations": [
        {
            "fieldName": "L_QUANTITY_longSum",
            "name": "L_QUANTITY_",
            "type": "longSum"
        },
        {
            "name": "count",
            "type": "count"
        }
    ],
    "context": {
        "bySegment": false,
        "finalize": true,
        "offHeap": false,
        "populateCache": false,
        "useCache": false
    },
    "dataSource": "tpch_year",
    "dimensionBasic":"l_orderkey",
    "dimension": {
        "dimExtractionFn": {
            "function": "function(str) { var re = /(^103136$|^1648672$)/; return str.replace(re,\"KING\"); }",
            "type": "javascript"
        },
        "dimension": "l_orderkey",
        "outputName": "l_orderkey_",
        "type": "extraction"
    },
    "filter": {
        "fields": [
            {
                "dimension": "l_orderkey",
                "type": "selector",
                "value": "103136"
            },
            {
                "dimension": "l_orderkey",
                "type": "selector",
                "value": "1648672"
            }
        ],
        "type": "or"
    },
    "granularity": "all",
    "intervals": [
        "1900-01-09T00:00:00.000Z/2992-01-10T00:00:00.000Z"
    ],
    "metric": "L_QUANTITY_",
    "queryType": "topN",
    "threshold": 1
}
```
## Non-aliased result

``` json
[ {
  "timestamp" : "1992-01-02T00:00:00.000Z",
  "result" : [ {
    "count" : 14,
    "l_orderkey_" : "KING",
    "L_QUANTITY_" : 530
  } ]
} ]
```

This data is the TPCH 1GB data segmented by year. As can be seen, quantity and count are too low in the aliased query.

This is due to the fact that topN is really a _sampled_ topN, where a sample of the top1000 values are used from each segment, and the top `threshold` values are resolved by merging the top1000 from each segment.

**Comment by drcrallen** [comment]
This means that the current topN algorithm is ok at determining "who is in the topN", but not so great at getting exact values.

I propose the following solutions:

1. Change the name of the current query to "aliasingTopN" or some other name to indicate it is not a true TopN.
2. Implement a smarter topN algorithm.

**Comment by drcrallen** [comment]
For "smarter topN" I have three initial thoughts.

### 2-Query topN
The first is to simply do a topN with ONLY the aggregate of interest to find the expected topN of the dimension of interest, then do a second topN with all aggregates using only the topN values we think will end up in the topN. So 1 query would be expected to be quick because there would be almost no aggregates, and the second would be quick as well, because the results that need aggregating are greatly decreased as well due to the filter on the first results

### Probably topN
The second thought is to have the query service be smarter about the topN results it is merging. Specifically, it could have knowledge of the individual topN results and the results relative rankings. For example: If a dimension value has the following ranks in the resultant segments: `[1, 2, 1, 4, 1]`, it is probably a perfect representation of the underlying data. But if another value has the following ranks in the returned segments : `[N/A, 2, 800, N/A, 5, 300]` Then it is very possible the results do not contain all the data for the value. This approach would essentially look at the variance in segment rank for each value and figure out how confident it is that the value has all its underlying data.


### groupBy topN
The broker issues a groupBy query to the historicals and does the topN on the results that come back. I'm not a huge fan of this approach because it requires a lot of communication overhead.


These are just some initial brainstorms and I'm very open to any other suggestions.

**Comment by drcrallen** [comment]
After chatting with @xvrl  for a bit, I think the solution for now is to update the docs to clarify when NOT to use a topN and either close this or leave it as a feature request.

**Comment by vogievetsky** [comment]
I think after #1135 this can now be closed.
