### ISSUE TITLE
new datasource doesn't show up in 0.7.0 coordinator console until handed off

### ISSUE THREAD

**Issue by ethanocentricity** [apache/incubator-druid#1198]
When we launch a new realtime datasource (hourly segment size), it doesn't show up in the new coordinator console until after the first segment is handed off.  .

I believe the problem is that:
<COORDINATOR_URL>/druid/coordinator/v1/metadata/datasources
doesn't seem to include the new datasource until after the handoff occurs.

The other services do return metadata about that datasource: 
- <COORDINATOR_URL>/druid/coordinator/v1/datasources/<DATASOURCE>/intervals?simple
- <COORDINATOR_URL>druid/coordinator/v1/datasources/<DATASOURCE>/intervals/<INTERVAL_RANGE>?full

**Comment by fjy** [comment]
@ethanocentricity Thanks for this catch. We'll take a look. We've wanted to include more management and visualization around data ingestion in the console.

**Comment by vogievetsky** [comment]
I believe this has been fixed a while ago (@clintropolis I think this can be closed)
