### ISSUE TITLE
Define granularities in UTC

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#1204]
"hour" should mean "UTC hour", "day" should mean "UTC day", and so on. This is because otherwise, hilarity will ensue when folks change their timezones and that causes storage granularity to change too.

**Comment by nmarasoiu** [comment]
Hi, I would like to try this

**Comment by gianm** [comment]
@nmarasoiu, to me this issue is about making things work better when not necessarily everything on the server side is running in UTC.

**Comment by gianm** [comment]
A couple of places this comes up are the driver running Hadoop indexing jobs, or the actual mappers and reducers themselves.

**Comment by leventov** [comment]
Is this problem still present?

**Comment by gianm** [comment]
I believe #4611 fixed this.
