### ISSUE TITLE
Allow distinction between port to bind to and port to announce

### ISSUE THREAD

**Issue by bobrik** [apache/incubator-druid#1253]
Docs for `druid.port` say:

```
This is the port to actually listen on; unless port mapping is used, this will be the same port as is on druid.host 
```

I want to run druid in container with virtualized network and fixed port, but expose it on different random ports to host (think mesos). I was unable to find documentation about port mapping, it looks like it only appears in `druid.port` description and code prohibits any port mappings.

**Comment by drcrallen** [comment]
Related discussions on ports:

https://github.com/druid-io/druid/issues/1124
https://github.com/druid-io/druid/pull/1125

**Comment by xvrl** [comment]
@bobrik Druid currently always announces itself on the port it binds to. It would require some work to make those two distinct. Druid announces itself externally, but also uses some of those mechanisms internally to talk between nodes, so it would require clarifying whether internal communication between nodes should go over the announced port or the port it binds to.

I will update the title of the issue to make it more clear what you are referring to.

**Comment by bobrik** [comment]
> it would require clarifying whether internal communication between nodes should go over the announced port or the port it binds to.

Announced port should be used for communication between nodes. My use-case is docker image where druid always binds to port 8080 in private net, but exposed port can be arbitrary (e.g. assigned by mesos). Nodes can only see each other on announced (exposed) port.
