### ISSUE TITLE
HadoopIndexTasks should kill hadoop jobs on shutdown

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#1346]
Currently, I believe that HadoopIndexTasks do not kill their hadoop jobs when they are shut down. This isn't the end of the world, because the outputs of the hadoop jobs will be ignored if the parent task is dead, but it is kind of a waste of resources.

**Comment by korablevalexander** [comment]
It about this case:

1. Druid task was killed(shut down through Overlord api?) and down mind don't mind about any Hadoop stuff.
2. Hadoop know nothing about Druid and has no reason to kill task?
