### ISSUE TITLE
io.druid.segment.realtime.RealtimeMetricsMonitor does not inject properly

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1372]
If `io.druid.segment.realtime.RealtimeMetricsMonitor` is specified in `druid.monitoring.monitors` then `io.druid.server.metrics.MetricsModule#getMonitorScheduler` fails to build an injected instance because there is no bound `List<io.druid.segment.realtime.FireDepartment>`

**Comment by drcrallen** [comment]
It is worth noting that the realtime tasks build their own RealtimeMetricsMonitor independent of the global MetricsModule.

**Comment by zen201415** [comment]
I had the same problem. How to use this function？、
