### ISSUE TITLE
add datasource and task type to response for task lists

### ISSUE THREAD

**Issue by tarekrached** [apache/incubator-druid#1376]
Right now, /druid/indexer/v1/runningTasks just returns the task id, the created time, and the queue insertion time for the running tasks.  It would be great if this endpoint (and pendingTasks, waitingTasks, and completeTasks) could also return the datasource and the task type.  This would enable better organization and filtering of the results.

In addition, it would be great to get an endpoint for tasks filtered by datasource, so that we can quickly show all tasks for a specific datasource - something along the lines of /druid/indexer/v1/dataSources/$DATASOURCE/runningTasks, or some such.

**Comment by NirajaM** [comment]
Implemented the same - https://github.com/druid-io/druid/pull/5260
