### ISSUE TITLE
SQLMetadata managers do not have retry strategy on polling

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1380]
SQL metadata mangers do not have a smart retry strategy when they are polling their databases. A retry strategy should retry (with backoff) on acute errors and emit an alert if the retries fail. 

This conversation came up in https://github.com/druid-io/druid/pull/1366

Currently the managers simply skip that polling period and try again the next time around.

**Comment by gianm** [comment]
Would wrapping the calls in something like SQLMetadataStorageActionHandler.retryingHandle work? (It would have to be made into a static I suppose)

Fwiw, I just noticed that Postgres doesn't have a reasonable implementation of isTransientException, and filed #1382 for that.
