### ISSUE TITLE
Document schema-less ingestion

### ISSUE THREAD

**Issue by xvrl** [apache/incubator-druid#1439]
- We are missing documentation to explain how to configure schema-less ingestion.
- `dimensionsSpec` documentation does not explain the default behavior in terms of excluded fields and how dimensions are treated if one passes an empty list of dimensions.

**Comment by thedrow** [comment]
It is documented now. http://druid.io/docs/latest/ingestion/schema-design.html#schema-less-dimensions
Is that enough or is there something else we need to add?
