### ISSUE TITLE
Add a way to see what kinds of events were rejected from the druid indexing service

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1492]
Currently the events that were rejected in the indexing service are a bit of a black box. This ask is to have a means to be able to get information about rejected events.

A simple solution could be to have a bound round-robin buffer in the peon that simply stores the last X rejected events. Another solution could be to have the events emitted to an external source (like a kafka topic).

**Comment by fjy** [comment]
:+1: I think this would be tremendously helpful

**Comment by nishantmonu51** [comment]
Probably we can emit the rejected events to an http end point and the listener of the end point can do whatever he wants i.e log to a kafka topic or save in some other place or take some action.

**Comment by gianm** [comment]
By "rejected" do you mean dropped because they are unparseable, or outside of the expected interval, or something like that?

If the rejected events tracking is going to be something not-pluggable, I think the round robin buffer is best. If it's pluggable then I think it's probably fine for the round-robin buffer to be the only builtin implementation (unless whoever's implementing it wants to do something else too).

**Comment by drcrallen** [comment]
My concern with making it pluggable is that while making the event logging could be pluggable, the method by which the events are fetched may not be so. For example, if I have one implementation which emits the events locally to a bound buffer, and another implementation which emits the events over the network, then there is not a clear way (to me at least) to have a unified impl for reading back the rejected events. For a local buffer it could be easy to put in an endpoint, but then would you also want that endpoint to read from the kafka topic?

**Comment by gianm** [comment]
That's kind of how TaskLogs works. The interface there is:

```java
  public Optional<ByteSource> streamTaskLog(String taskid, long offset) throws IOException;
  public void pushTaskLog(String taskid, File logFile) throws IOException;
```

There's also a SwitchingTaskLogStreamer that tries a bunch of different streamTaskLog implementations until one works. The reason for that is that task logs might be on S3 (if a task ended) or might be on the middle manager (if the task is still running).

But, I think that level of complexity is probably not needed for this, and it would be fine to have it not pluggable and just do the bounded buffer thing.
