### ISSUE TITLE
Preemption for indexing service locks 

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#1513]
From https://groups.google.com/forum/#!topic/druid-development/kHgHTgqKFlQ,

> There's potential for conflicts between merging and appending new data. Consider a merge task that reads a set of segments with version A (let's say A0, A1, A2) and then publishes a new set of segments with version B (let's say B0, B1). If a realtime task spins up between those two points and wants to add a new segment, it could create A3, which is bad, because it will end up being shadowed by set B and the writes will be lost. Or it could create B2, which is also bad because it will not be visible until B0 and B1 are published and uploaded. Even worse, if a new merge task can start up after the first one finishes (but while B2 is still ingesting) and create a set of C-segments, that will cause the writes in B2 to be lost forever.
> 
> There are a few different ways to handle this:
> 
> a) Merging wins and ingestion loses. This is the current method and is mediated through exclusive interval locks. Ingestion “losing” would probably mean ingestion blocks.
> 
> b) Ingestion wins and merging loses. This could be done by aborting a merge in progress if new data comes in. This has the advantage of not affecting ingestion at all, but will cause liveness issues with merging if a trickle of data comes in for the same interval for an excessive amount of time.
> 
> c) Something else?
> 
> For the first version, I think (b) is best since I think most people would prefer liveness issues in merging to liveness issues with ingestion.

To do **Ingestion wins and merging loses**, we need a way for an ingestion task to pre-empt locks held by a merge task. This could possibly be done by having a lock priority such that higher priority locks cancel out lower priority locks. The task that has the pre-empted lock would presumably figure that out when it tries to insert a segment and fails. It could also be notified about it proactively somehow, but it's unclear how that would happen.

**Comment by nishantmonu51** [comment]
what would be the behaviour for case when there is a collision between realtime ingestion for late incoming data and any batch indexing job running at the same time ? Will it be the same as realtime ingestion wins over the batch job ?

**Comment by gianm** [comment]
It would depend on the priority you set, I think. I think most people would want priorities to be in this order:

1) Realtime
2) Normal batch ingestion
3) Reindexing/compaction batch ingestion

I think some people will differ on whether (1) and (2) should be the same priority or different priorities. IMO a reasonable default is for them to be different, so realtime indexing always preempts anything else. But, if there are sites that want to set (1) and (2) to the same priority (maybe they want to avoid liveness issues with batch) then that should be doable too. That would just mean that there's a potential of realtime ingestion stalling for a bit when a batch task is running.

**Comment by gianm** [comment]
Talked a bit to @himanshug and we thought that optimistic locking for batch is going to be simpler to implement than priorities.

I think for that to work we'll need some way of getting versions to tasks other than LockAcquireAction. Possible splitting that into two steps- one that optimistically gets a version for an interval and one that actually locks the interval.

**Comment by himanshug** [comment]
@pjain1 can you please look into this one.

**Comment by pjain1** [comment]
@himanshug sure

**Comment by himanshug** [comment]
@gianm I though more about this and discussed with @pjain1 as well. I believe a combination of priorities and optimistic locking would be a good way to go.

All kind of tasks get assigned some priority (hard coded), 0 being highest priority
realtime-ingestion: 0
batch-ingestion: 1
merge-task: 2
(note that the priorities assigned is a matter of policy and can be changed independently of the algorithm suggested below)

Tasks implement following algorithm to do the work
```
lock = aquire_lock(datasource, interval, my_assigned_priority)
if(successful) {
  //do the work, but, do not commit
} else {
  //fail or maybe repeat from beginning
}

upgrade_lock_to_superpower(datasource, interval, my_assigned_priority)
if(successful) {
  //commit the work
  release_lock(..)
} else {
  //fail
}
```

Overlord implements following 3 APIs:
```
//trusted that client will make this call with appropriate
//priority that has been assigned to it
synchronized aquire_lock(datasource, interval, priority) {
  lock = get_cached_lock_with_overlapping_interval(datasource, interval)

  if(lock == null || (priority < lock.priority && !lock.isSuperPower()) {
    //accept request, put/update lock datasource,interval,priority in cache
  } else {
    //reject request
  }
}

//trusted that client will make this call iff it had the lock
synchronized upgrade_lock_to_superpower(datasource, interval, priority) {
  lock = get_cached_lock_with_same_interval_and_priority(datasource, interval, priority)
  if(lock != null) {
    lock.setSuperPower()
  } else {
    //reject request
  }
}

//trusted that client will make this call iff it had the lock
synchronized release_lock(datasource, interval, priority) {
  lock = get_cached_lock_with_same_interval_and_priority(datasource, interval, priority)
  if(lock != null) {
    //remove it
  }
}
```

I guess this can be improved more a little bit so that lock keeps some metadata inside the lock such as task id and timestamp when the lock was created etc, so that we can detect that some task aquired the lock and crashed without releasing the lock and remove such zhombie locks.

**Comment by gianm** [comment]
That seems reasonable- so basically you're advising the overlord that you will want a lock in the future (acquire_lock), then actually asking for the lock (upgrade_lock_to_superpower; which will succeed if nobody else with a higher priority has asked for one in the meantime), then releasing the lock.

**Comment by drcrallen** [comment]
I commented in https://github.com/druid-io/druid/pull/1679#issuecomment-139008613 but I think the concept of priority proposed here needs a bit of tweaking.
