### ISSUE TITLE
Query time lookups need a tutorial

### ISSUE THREAD

**Issue by fjy** [apache/incubator-druid#1573]
Query time lookups need a tutorial of the problems they solve and how they can be used. It is also worthwhile to add an entry in the TOC under "Operations" about QTL, described in a way that folks facing the problem can find and understand.

**Comment by drcrallen** [comment]
This is blocked by https://github.com/druid-io/druid/pull/1576

**Comment by b-slim** [comment]
This is blocked by the implementation of a lookup manager as a druid component not as an extension.
First milestone will be the following PR [https://github.com/druid-io/druid/pull/2291]

**Comment by rasahner** [comment]
I think it's not necessary, or even desirable, to wait until the implementation is complete before having user-facing documentation, at least in draft form.  It's a useful way to state what problem is being solved (what the requirements are).  It can also suggest integration tests.

**Comment by drcrallen** [comment]
@rasahner I think what you're describing is a proposal.The User docs are a major pain to keep in sync with the development docs as code reviews change things.

**Comment by fjy** [comment]
Removing milestone as this issue isn't getting much love
