### ISSUE TITLE
ClassLoader problem for Hadoop with Kerberos auth

### ISSUE THREAD

**Issue by zhihuij** [apache/incubator-druid#1588]
When use Kerberos with HDFS, I have got a exception like:

PriviledgedActionException as:user@xxx.com (auth:KERBEROS) cause:
org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]

and after diving into the problem, I have found it's a class loader related problem:

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.hadoop/hadoop-common/2.3.0/org/apache/hadoop/security/SecurityUtil.java#SecurityUtil.getKerberosInfo%28java.lang.Class%2Corg.apache.hadoop.conf.Configuration%29

http://grepcode.com/file/repo1.maven.org/maven2/org.apache.hadoop/hadoop-common/2.3.0/org/apache/hadoop/security/SecurityUtil.java#270

Hadoop SecurityUtil use ServiceLoader to load the provider, and ServiceLoader use Thread.currentThread().getContextClassLoader() to load the actual provider, but seems that when Druid loads the provider, the thread context loader doesn't include the path for hadoop related classes.

I have fixed the problem with java agent which set the URLClassLoader which contains the path for hadoop related classes to the thread context class loader, and that's worked, but I think there should be a more graceful way to fix the problem. 

I have found two way, but I'm not sure which one is better:
1. https://github.com/druid-io/druid/blob/master/server/src/main/java/io/druid/initialization/Initialization.java#L153, 
after this line, add a call to Thread.currentThread().setContextClassLoader
2. https://github.com/druid-io/druid/blob/master/extensions/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsStorageDruidModule.java#L93
after this line, add a call to Thread.currentThread().setContextClassLoader

I haven't try none of the above fixes, I still use the java agent fix in my test env, maybe there are better fix for this problem.

**Comment by fjy** [comment]
@onlychoice Thanks for this catch. We are looking and will update this issue.

**Comment by himanshug** [comment]
@onlychoice are you adding hadoop libs directly on the classpath or you're getting them by putting hdfs-storage extension in the druid configuration?

**Comment by onlychoice** [comment]
@himanshug putting hdfs-storage extension in the druid configuration

**Comment by onlychoice** [comment]
by the way, Kerberos auth have a expire time, with the command 'kinit', the auth info can be renewed, if I didn't run 'kinit' after the expire time, Druid will fail with a auth failed exception.  

Question is if Druid deal with the auth issue or there is any config options to solve the problem?

Currently, I use crontab to run the 'kinit' command periodically, but I don't think it's a good fix.

**Comment by himanshug** [comment]
@onlychoice
1) I have noticed many problems with hadoop classloader being different. As a workaround, instead of adding hdfs-storage as extension in the configuration, can you try to include the druid-hdfs-storage and all the hadoop configuration, dependencies (that can be obtained by running command hadoop classpath on a machine where hadoop has been setup) in the classpath. And, provide necessary HDFS settings as described in Deep Storage ( http://druid.io/docs/latest/dependencies/deep-storage.html )  . Then auth should work without any of the code changes.

2) regarding the problem with auth expiration, can you try to specify following environment variables to the druid java process.. (and that should let druid automatically do the periodic kinits without you having to do anything externally like cron)
KRB5KEYTAB=/path/to/keytab/file
KRB5PRINCIPAL=your-krb5-principal

**Comment by drcrallen** [comment]
@himanshug / @onlychoice Beware of #1016 with such an approach

**Comment by himanshug** [comment]
@drcrallen thanks, #1016 looks related to specifying same extension in both configuration and manually on the classpath. things should be fine if hdfs-storage is removed from properties file and only put on the classpath.

**Comment by b-slim** [comment]
FYI, i was able to run druid with a secured Kerberos/Hadoop cluster with loading both hdfs module and hadoop dependencies separately and without having any extra path on the actual classpath.
Second for the TGT key, it is true that if you run kinit once before starting druid, the hadoop libs will keep renewing that  TGT ticket by running `kinit -R` (so i guess no need to export any envi variables), although TGT tickets usually have a limited life time (by default 7d i guess), so you have to run again `kinit -kt keytab user` and `kinit -R` won't work. Having https://github.com/druid-io/druid/pull/3419 in, should slove the problem of re-running the `kinit` periodically.
