### ISSUE TITLE
consider merging segments with hashed or dimension shardSpec with only 1 shard

### ISSUE THREAD

**Issue by nishantmonu51** [apache/incubator-druid#1623]
At present coordinator segment merge logic only works for segments indexed with NoneShardSpec. 
It should also consider merging segments with other shardSpecs but have only 1 shard for a given interval.

**Comment by GaryHuangBD** [comment]
Is there any progress on this issue?

**Comment by dclim** [comment]
#1998 is pretty close to finished and I believe should support arbitrary shardSpecs; you can take a look at that PR and see if it meets your requirements.

**Comment by GaryHuangBD** [comment]
LGTM~   @dclim Thanks!
