### ISSUE TITLE
 Inner Query should build on sub query

### ISSUE THREAD

**Issue by Hailei** [apache/incubator-druid#1641]
Like following query:

``` sql
SELECT 
   device, LONG_SUM(pv) as pv, HYPER_UNIQUE(hyper_uv) as hyper_uv 
FROM
  (SELECT
         device, cast, LONG_SUM(pv_sum) as pv, HYPER_UNIQUE(uv) as hyper_uv 
   FROM dsp_report        
   WHERE interval BETWEEN 2015-08-04T00:00:00 AND 2015-08-05T00:00:00
   AND area = '0A' BREAK BY 'all' GROUP BY device, cast
   ) 
WHERE interval BETWEEN 2015-08-04T00:00:00 AND 2015-08-05T00:00:00 AND cast = 1 BREAK BY 'all' GROUP BY device ;
```

don't return anything,not as except.

I think this is a bug.
The reason why this query of output is empty: inner query group by 'cast' and 'device' two dimensions, and outer query only group by 'device',meanwhile filter 'cast' dimension.
as following code

``` java
 // We need the inner incremental index to have all the columns required by the outer query
      final GroupByQuery innerQuery = new GroupByQuery.Builder(subquery)
          .setAggregatorSpecs(aggs)
          .setInterval(subquery.getIntervals())
          .setPostAggregatorSpecs(Lists.<PostAggregator>newArrayList())
          .build();

     IncrementalIndex index = makeIncrementalIndex(innerQuery, subqueryResult);
```

If inner query group by outer query's GROUP BY,the increment index only contains 'cast',So can't filter by 'cast=1'.
I submit PR https://github.com/druid-io/druid/pull/1632,but I don't think this is good solution.

**Comment by saulfrank** [comment]
I am still getting an error using a subquery - should this be doable?

Unknown exception (org.apache.druid.java.util.common.ISE): Cannot build plan for query:

select * from "druid"."table" 
where file_date = (
select max(file_date) as file_date from "druid"."table")

**Comment by prsaini** [comment]
Hi, I am getting the same error on druid 0.15

select * from druid.top_seller where __time in (select max(__time) from druid.top_seller)

error:"Unknown exception / Cannot build plan for query: SELECT * FROM (select * from druid.top_seller where __time in (select max(__time) from druid.top_seller)) LIMIT 5000 / org.apache.druid.java.util.common.ISE"
