### ISSUE TITLE
Use isolated classloader for javascript related items

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1671]
Various queries can use java script for filtering or aggregating. This ask is to allow those javascript items to be associated with a classloader that is isolated to that query. In such a case, any generated classes from the javascript compilation should be able to be unloaded at the GC's discretion once the query has completed.

**Comment by drcrallen** [comment]
I may be misunderstanding how some of the javascript class stuff gets GC'd here.

**Comment by vogievetsky** [comment]
I am glad that with the new expression system we are moving away form javascript (you did not hear me say this). Is this still something that should be fixed?

**Comment by gianm** [comment]
I suppose it's valid as long as we support javascript at all, so we could leave it open. I am not sure if anyone has quantified the impact or not so I am not sure how big of a deal this is.
