### ISSUE TITLE
[HttpPostEmitter] druid.emitter.http.recipientBaseUrl=http://domain:port causes invalid http header

### ISSUE THREAD

**Issue by gx578007** [apache/incubator-druid#1684]
For example, if we set `druid.emitter.http.recipientBaseUrl=http://127.0.0.1:12345`, the header of HTTP post request is incorrect. A standard HTTP server fails to receive any request from `HttpPostEmitter`.
The following shows the first line of the request header, which is lack of path information:
`POST  HTTP/1.1`

However, if we set `druid.emitter.http.recipientBaseUrl=http://127.0.0.1:12345/test`, the resultant header is valid and the POST request can be received by a HTTP server.

Since `http://127.0.0.1:12345` is a valid address, the POST request generator should be fixed to handle this kind of URLs to build a correct HTTP connection.

**Comment by gianm** [comment]
Does ```http://127.0.0.1:12345/``` work?

**Comment by gx578007** [comment]
It works for `http://127.0.0.1:12345/`. It fails only when using `http://127.0.0.1:12345`.
Currently we work around by using `http://127.0.0.1:12345/`.
However, we still expect that the POST generator is able to handle `http://127.0.0.1:12345`. Or to illustrate this limitation on documents is also good to avoid this problem.

**Comment by gianm** [comment]
ok, it's good to know that there is a workaround. Probably the best way to make things work without the slash is to edit NettyHttpClient in http://github.com/metamx/http-client such that empty paths are replaced with /.

**Comment by vogievetsky** [comment]
Did @drcrallen 's PR fix this?

**Comment by gianm** [comment]
Certainly looks like it would have.
