### ISSUE TITLE
Why Deep storage No data？but realtime node can find 3413610 num data

### ISSUE THREAD

**Issue by zengzhihai110** [apache/incubator-druid#1692]
curl -X POST 'http://localhost:8082/druid/v2/?pretty' -H 'content-type: application/json'  -d  

@timeseries.json
[ {
  "timestamp" : "2015-09-01T16:00:37.000Z",
  "result" : {
    "count_added" : 3.584021E7,
    "count" : 3413610
  }
} ]

How to make history node work?

**Comment by fjy** [comment]
@zengzhihai110 Have you taken a look at http://druid.io/docs/0.8.0/ingestion/faq.html?

**Comment by zengzhihai110** [comment]
@fjy  finish watching  i have A little dizzy  but i don't kown why.

**Comment by fjy** [comment]
@zengzhihai110 :)

The biggest problems with handoff generally pertain to misconfiguration. What deep storage are you using? How is it being set up?

**Comment by vogievetsky** [comment]
@zengzhihai110 can this issue be closed?
