### ISSUE TITLE
Tasks that are waiting on locks are reporting as RUNNING

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1746]
```
"status":"RUNNING"
```

If a task is waiting on a lock, it still reports as RUNNING. when querying the tasks `/status` endpoint.

**Comment by gianm** [comment]
This is "intended" in that tasks have a lifecycle that goes RUNNING -> SUCCESS/FAILED. There is no such thing as a "pending" or "waiting" status. We could change that if we want, but that is why things are the way they are.

**Comment by vogievetsky** [comment]
@gianm I believe this has been greatly improved and is no longer and issue. I see pending tasks all the time now.

![image](https://user-images.githubusercontent.com/177816/43605024-087d19bc-964c-11e8-973c-bf1d401b42c5.png)

Can this be closed?

**Comment by gianm** [comment]
Ah yes. Now they are "WAITING" if they are waiting on locks.
