### ISSUE TITLE
Deprecate dimension / metric endpoints on broker

### ISSUE THREAD

**Issue by xvrl** [apache/incubator-druid#1810]
See #1474

**Comment by himanshug** [comment]
many ppl use batch-only pipelines and segments are always present in historical (when they are available for read), endpoints at broker are faster (and less resource consuming) than doing a segmentMetadata query. I am not sure if we need to remove these from brokers.

**Comment by fjy** [comment]
@himanshug i thik we should encourage ppl to use segment metadata

**Comment by himanshug** [comment]
@fjy we will start using segmentMetadata query, but note that we have many druid clusters with different teams managing those. I am notifying the users internally for this deprecation and asking to use segmentMetadata query but we should not remove these endpoints for at least a quarter more and it is proven that segmentMetadata query is truly efficient enough to replace those.

**Comment by gianm** [comment]
@himanshug segmentMetadata will not be as efficient as these endpoints, but with caching enabled and restriction of analysisTypes, it should be able to get pretty close and should be 'efficient enough'.

FYI the query that we use for metadata is:

```json
{
  "queryType": "segmentMetadata",
  "dataSource": "datasource",
  "merge": true,
  "analysisTypes": []
}
```

and in 0.9.0 will change to:

```json
{
  "queryType": "segmentMetadata",
  "dataSource": "datasource",
  "merge": true,
  "analysisTypes": [
    "aggregators"
  ],
  "lenientAggregatorMerge": true
}
```

**Comment by gianm** [comment]
I also think there is no need to remove the broker endpoints any time soon, but would like to encourage people to use segmentMetadata anyway as it is generally "better" (it shows dimensions on realtime, it gives more info about metric types and, in 0.9.0, aggregations)

**Comment by gianm** [comment]
Brought up on the dev sync and @himanshug pointed out some people prefer these due to speed. Maybe instead of deprecating the old endpoints we could document that they don't include the freshest information?

Or we could do best of both worlds, maybe, and cache segment metadata query based stuff on the brokers.

**Comment by himanshug** [comment]
@gianm I did a quick check with some people who were using these endpoints. They now use similar endpoints provided by coordinator. so those at broker can be removed now.
