### ISSUE TITLE
Druid 0.8.1 coordinator throws a bunch of exceptions at startup

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#1816]
Here are the logs:
https://gist.github.com/pdeva/d90e12e2207801e6908a

I noticed this while upgrading from 0.8.0 to 0.8.1.
We use realtime nodes only. We have never had separate overlord nodes for indexing in our cluster.

**Comment by fjy** [comment]
Hmmm, we need to look into this as this means the coordinator is trying to
talk to the indexing service by default.

**Comment by drcrallen** [comment]
We need confirmation of this so it can be an official bug.

**Comment by pdeva** [comment]
i had to remove the logs from that gist since it contained our cluster's ips.
happy to answer any specific questions you guys have or paste a stacktrace if still needed.

**Comment by vogievetsky** [comment]
This issue is super pretty old and does not look actionable (Who even knows where to get Druid 0.8.1 these days). @fjy I suggest we close it.
