### ISSUE TITLE
JsonConfigurator does not escape quoted options

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1827]
`io/druid/druid-api/0.3.13/druid-api-0.3.13-sources.jar!/io/druid/guice/JsonConfigurator.java:85` (or there-abouts) puts property values in quotes, this makes https://github.com/druid-io/druid/pull/1748 have to have a lot of extra escape characters. So the runtime.properties file has to have something like this: `druid.indexer.runner.javaOpts=-server -Xmx256m -XX:OnOutOfMemoryError=\\\"kill -9 %p\\\"` in order to actually pick up the options properly whenever `value = jsonMapper.readValue(modifiedPropValue, Object.class);` is called.

The proper behavior would be to escape quotes in the modifiedPropValue when it encapsulates the property value in `"%s"`

**Comment by vogievetsky** [comment]
Does https://github.com/apache/incubator-druid/pull/2033 address this?

**Comment by gianm** [comment]
I think the real fix was to add druid.indexer.runner.javaOptsArray (https://github.com/apache/incubator-druid/pull/2533).
