### ISSUE TITLE
Schema differences of GroupBy vs TopN/TimeSeries return data should be not be present

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#1835]
both TopN and TimeSeries return data in the form:

```
timestamp: xxx
result: xxx
```

but GroupBy does:

```
timestamp: xxx
event: xxx
```

Naming the field `event` instead of `result` causes havoc when trying to use the return value in java for reusable code.

GroupBy should also name the field 'result' instead of 'event'.

**Comment by vogievetsky** [comment]
+1

**Comment by vogievetsky** [comment]
I 👍ed this issue back in the day but since then groupBy v2 drastically improved the situation if you are using Rune (Druid's JSON based language). If you want 100% standard results you should now use DSQL 🎆 
@gianm I think this issue can be closed.

**Comment by gianm** [comment]
Sure, let's close it won't-fix.
