### ISSUE TITLE
MapCache needs re-written

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#1836]
Under very heavy contention, MapCache has really screwy locking which can cause issues in which result gets returned.

I also know some devs have looked at some things to replace LRU with in order to prevent large scans from clobbering cache.

This ask is to have a better MapCache implementation that can handle high concurrency better.

**Comment by vogievetsky** [comment]
Did https://github.com/apache/incubator-druid/pull/3028 address this?

**Comment by gianm** [comment]
Yes.
