### ISSUE TITLE
Option to use system time as event time for realtime indexing

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#1848]
Not everyone cares about the origin timestamp of the actual event. It would be cool for druid to be able to insert the current time as the timestamp in these cases.

**Comment by drcrallen** [comment]
When there are realtime indexing tasks running in a redundant manner this will be very interesting because you'll end up with eventually consistent queries, where "eventually" means "the winner that gets handed off to historicals"

**Comment by gianm** [comment]
I think it's actually not that bad right now, since right now the only redundancy we have is with tranquility, which is leader/follower based where one thing actually decides what to do (the tranquility client). There's a tranquility version of this issue too (druid-io/tranquility#45) and that should be done totally on the tranquility client side to avoid this sort of consistency problem.

Other forms of realtime ingestion don't really support redundancy in a sane way at this point anyway.

For the future kafka stuff we're imagining, this feature will probably not be supported and your data will have to have timestamps in it.

**Comment by zhxiaogg** [comment]
@gianm  when you mentioned "the future kafka stuff" do you mean this issue #764 ?

**Comment by zhxiaogg** [comment]
I would like to implement this feature for druid to be able to use current time as event time. My Implementation considerations are:

1. only support realtime ingestion
2. refactor TimestampSpec as a interface
3. rename previous TimestampSpec as default implementation or some how
4. add a new TimestampSpec implementation with type “serverTime”. Users would specify this type in ingestion time spec when they want current time as event time.
5. set “eventTime” as the type to the previous TimestampSpec and set it as the default implementation when type field is missing. This is for the backward compatibility consideration.

The TimestampSpec seems to be in the API project.

Could somebody tell if my imagined implementation is ok.

**Comment by himanshug** [comment]
@zhxiaogg it wouldn't work when you have multiple indexing tasks getting replicated stream of data, they might potential get different timestamp for same event.
as @gianm mentioned, it has to be done in tranquility
