### ISSUE TITLE
Rack-aware availabilityGroup assignment

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#1884]
Currently in the RTR we make sure that replicas are placed on different machines by ensuring that each machine is only running tasks from a single availabilityGroup. It would be nice to have an option to make this "rack-aware" by having the restriction apply to an entire set of machines rather than a single machine. This would make it possible to group your middleManagers into two "racks" and know that you could safely restart an entire rack en masse without nuking more than one replica of a task.

**Comment by drcrallen** [comment]
The plan internally here is to use task tiers to accomplish part of this.

**Comment by gianm** [comment]
talked to @xvrl about this, another use case is for AWS- having half your replicas on demand and half on spot.
