### ISSUE TITLE
Graphite Metric Emitter for druid

### ISSUE THREAD

**Issue by rohitkochar** [apache/incubator-druid#1905]
Currently Druid provide two types of Emitter i.e Logging Emitter and HttpEmitter.
Since graphite is being used as the metric collection tool in many organisations it would be great to have Graphite Emitter for druid metrics.
This will enable easy monitoring of druid deployments.

**Comment by rohitkochar** [comment]
All the current metric emitters are part of "metamx/emitter" project so should this new emitter be also added to that project or it can be part of the druid codebase??

**Comment by b-slim** [comment]
We have an implementation for such emitter, will send the PR Soon this week.
