### ISSUE TITLE
RealtimeIndexTask ioConfig should ignore the plumber field

### ISSUE THREAD

**Issue by xvrl** [apache/incubator-druid#1952]
Currently if I take the `wikipedia_realtime.spec` from the examples folder and use it as the `spec` to make a realtime index task, it causes the task to fail epically with cryptic lifecycle errors.

The workaround is to remove the `plumber` field form the `ioConfig` in the spec.

```
1) Error in custom provider, com.metamx.common.ISE: Cannot add a handler after the Lifecycle has started, it doesn't work that way.
  at io.druid.guice.DruidProcessingModule.getProcessingExecutorService(DruidProcessingModule.java:90)
  at io.druid.guice.DruidProcessingModule.getProcessingExecutorService(DruidProcessingModule.java:90)
  while locating java.util.concurrent.ExecutorService annotated with @io.druid.guice.annotations.Processing()
```

**Comment by fjy** [comment]
What about to set a flushing plumber?

**Comment by gianm** [comment]
@fjy The RealtimeIndexTask has never allowed user-defined plumbers, because it has to inject a bunch of overridden stuff into the plumber in order to get it to communicate properly with the overlord.
