### ISSUE TITLE
Ganglia Emitter for druid metrics

### ISSUE THREAD

**Issue by b-slim** [apache/incubator-druid#1980]
Currently Druid doesn't provide a Ganglia emitter
Since Ganglia is being used as the metric collection tool in various organizations and various project like hadoop, it would be great to have Ganglia Emitter for druid metrics.

**Comment by michaelschiff** [comment]
@b-slim have you started work on this?

**Comment by b-slim** [comment]
@michaelschiff yes, any suggestion or thing that i should know about for your use case ?

**Comment by michaelschiff** [comment]
@b-slim nothing in particular. Just want to be able to graph all of the metrics available here http://druid.io/docs/latest/operations/metrics.html per host.

**Comment by michaelschiff** [comment]
@b-slim is the code for this available anywhere? I have pretty urgent need for this feature, so I would otherwise start writing something myself.

**Comment by michaelschiff** [comment]
@b-slim submitted PR https://github.com/druid-io/druid/pull/2384
