### ISSUE TITLE
Support descending ordered queries

### ISSUE THREAD

**Issue by navis** [apache/incubator-druid#2013]
Queries are returning rows ascending order of timestamp, but generally we prefer recent results to be shown first.

**Comment by vogievetsky** [comment]
+1

**Comment by vogievetsky** [comment]
This has been added in 0.15.0:

try:

```sql
SELECT * FROM "wikiticker" 
WHERE "__time" >= CURRENT_TIMESTAMP - INTERVAL '1' HOUR
ORDER BY __time ASC
```

and:

```sql
SELECT * FROM "wikiticker" 
WHERE "__time" >= CURRENT_TIMESTAMP - INTERVAL '1' HOUR
ORDER BY __time DESC
```

Smash the `Explain` button to see how it works

![image](https://user-images.githubusercontent.com/177816/60743699-942c8f80-9f27-11e9-992d-6a7e04e63fc9.png)
