### ISSUE TITLE
Invalid results of topN of recent data.

### ISSUE THREAD

**Issue by kzarzycki** [apache/incubator-druid#2059]
Hi druid maintainers!
I have a very serious problem: a simple topN query gives me an incorrect aggregation of a metric (I know about approximate nature of topN queries, but I pretty sure that's not it). It's only about the latest data, possibly stored in memory of realtime node. It looks for me like a very high priority bug. Let me explain:

I send few  ( 5 in this example) JSON events to Kafka that are ingested by realtime node. These events look like this:

<pre>
{
"date":"2015-12-07T18:29:48",
"dual_orientation":null,
"orientation_change":null,
"traffic_source_id":35,
...
}
,<other 3 events between 18:29 -18:31>
{
"date":"2015-12-07T18:31:42",
"dual_orientation":null,
<b>"orientation_change":null,</b>
"traffic_source_id":35,
...
}
</pre>

Then instantly I query broker or just realtime node (no matter), with topn query: 

<pre>
{
    "queryType":"topN",
    "dataSource":"clicks",
    "intervals":"2015-12-07T18:25:00Z/2015-12-08"
    ,"granularity":"all",
    "aggregations":[
        {"type":"longSum","name":"click","fieldName":"click"}   ,
        {"type":"count","name":"count"}    ],
    <b>"dimension":"orientation_change",</b>
    "threshold":100000,
    "metric":"click",
    "filter":{"type":"or","fields":[
        {"type":"selector","dimension":"traffic_source_id","value":"35"} 
    ]}
}

$ druid-query topn.json 
[ {
  "timestamp" : "2015-12-07T18:25:00.000Z",
  "result" : [ {
    <b>"count" : 3,</b>
    "orientation_change" : null
  } ]
} ]

</pre>

As you see, topn gave me only 3  events! 

Now, I send a corresponding timeseries query (I also tried groupBy with same results as timeseries):

<pre>
{
    "queryType":"timeseries",
    "dataSource":"datasource-topic-click",
    "intervals":["2015-12-07T18:20:00Z/2015-12-08"]
    ,"granularity":"all",
    "aggregations":[
        {"type":"count","name":"count"}
    ],
    "filter":{"type":"or","fields":[
        {"type":"selector","dimension":"traffic_source_id","value":"35"}
    ]}
}

$ druid-query timeseries.json 
[ {
  "timestamp" : "2015-12-07T18:20:00.000Z",
  "result" : {
    "count" : 5
  }

</pre>

And timeseries gives me the right result (5 events). So something is seriously wrong here. Now, I wanted to look into data, so I submitted a select query:

<pre>
{
    "queryType":"select",
    "dataSource":"datasource-topic-click",
    "intervals":"2015-12-07T18:25:00Z/2015-12-08"
    ,"granularity":"all",
    "dimensions":["orientation_change", "dual_orientation", "platform"], 
    "threshold":100000,
    "metrics":["click"],
    "filter":{"type":"or","fields":[
        {"type":"selector","dimension":"traffic_source_id","value":"35"}
    ]}
    ,  "pagingSpec":{"pagingIdentifiers": {}, "threshold":100}
}

$ druid-query select.json                                                                         
[ {
  "timestamp" : "2015-12-07T18:25:00.000Z",
  "result" : {
    "pagingIdentifiers" : {
      "datasource-topic-click_2015-12-07T18:00:00.000Z_2015-12-07T19:00:00.000Z_2015-12-07T18:00:00.000Z" : 1
    },
    "events" : [ {
      "segmentId" : "datasource-topic-click_2015-12-07T18:00:00.000Z_2015-12-07T19:00:00.000Z_2015-12-07T18:00:00.000Z",
      "offset" : 0,
      "event" : {
        "timestamp" : "2015-12-07T18:29:48.000Z",
<b>        "orientation_change" : null,</b>
        "dual_orientation" : null,
        "platform" : null,
        "click" : 1
      }
    }, {
      "segmentId" : "datasource-topic-click_2015-12-07T18:00:00.000Z_2015-12-07T19:00:00.000Z_2015-12-07T18:00:00.000Z",
      "offset" : 1,
      "event" : {
        "timestamp" : "2015-12-07T18:29:51.000Z",
<b>        "orientation_change" : null,</b>
        "dual_orientation" : null,
        "platform" : null,
        "click" : 1
      }
    }, {
      "segmentId" : "datasource-topic-click_2015-12-07T18:00:00.000Z_2015-12-07T19:00:00.000Z_2015-12-07T18:00:00.000Z",
      "offset" : 2,
      "event" : {
        "timestamp" : "2015-12-07T18:29:53.000Z",
<b>        "orientation_change" : null,</b>
        "dual_orientation" : null,
        "platform" : null,
        "click" : 1
      }
    }, {
      "segmentId" : "datasource-topic-click_2015-12-07T18:00:00.000Z_2015-12-07T19:00:00.000Z_2015-12-07T18:00:00.000Z",
      "offset" : 0,
      "event" : {
        "timestamp" : "2015-12-07T18:31:39.000Z",
<b>        "orientation_change" : [ ],</b>
        "dual_orientation" : null,
        "platform" : null,
        "click" : 1
      }
    }, {
      "segmentId" : "datasource-topic-click_2015-12-07T18:00:00.000Z_2015-12-07T19:00:00.000Z_2015-12-07T18:00:00.000Z",
      "offset" : 1,
      "event" : {
        "timestamp" : "2015-12-07T18:31:42.000Z",
<b>        "orientation_change" : [ ],</b>
        "dual_orientation" : null,
        "platform" : null,
        "click" : 1
      }
    } ]
  }
} ]
</pre>

As you see, some rows _have null_ in orientation_change field, some have _an empty array_! That's very weird... Notice that some other field that is null all the time does not have this problem. 

Next, I wait some time (probably until after realtime persists the partial segment to disk) and _the result gets fixed!_ Topn query returns a valid result, select query return nulls in orientation_change, all back to normal. 

One more fact: running topn query with different dimension gives correct result.

I'm on druid version 0.8.2. Using 2 realtime nodes working for redundancy. 

Please help, I will very appreciate it. 

Kind regards,
Krzysztof

**Comment by fjy** [comment]
@kzarzycki your topN query includes an "or" filter. Please remove it.

**Comment by gianm** [comment]
@kzarzycki Please see "Counting the number of ingested events" here: http://druid.io/docs/latest/ingestion/schema-design.html

**Comment by fjy** [comment]
@kzarzycki also, your topN query's "intervals" field doesn't match your raw data

**Comment by kzarzycki** [comment]
@fjy , Sorry for small error in intervals, they were just mistakes in pasted queries. I also used 5 minutes earlier interval in timeseries but it's also irrelevant to the result.
@fjy, about the filter. But I need it, it's a live system and I wanted to limit data to only a test account. 
I submitted topn and groupby queries without a filter, at once hoping that both run between events (no events happen between). Here is a result: 
<pre>
$ druid-query groupby_all.json ; druid-query topn_all.json
[ {
  "version" : "v1",
  "timestamp" : "2015-12-07T18:25:00.000Z",
  "event" : {
<b>    "count" : 161,
    "orientation_change" : null </b>
  }
}, {
  "version" : "v1",
  "timestamp" : "2015-12-07T18:25:00.000Z",
  "event" : {
    "count" : 1870,
    "orientation_change" : "0"
  }
}, {
  "version" : "v1",
  "timestamp" : "2015-12-07T18:25:00.000Z",
  "event" : {
    "count" : 7331,
    "orientation_change" : "1"
  }
} ][ {
  "timestamp" : "2015-12-07T18:25:00.000Z",
  "result" : [ {
    "count" : 7331,
    "orientation_change" : "1"
  }, {
    "count" : 1870,
    "orientation_change" : "0"
  }, {
<b>    "count" : 133,
    "orientation_change" : null </b>
  } ]
} ]
</pre>

Please note the difference between groups with orientation_change: null . 

@gianm , If you mean I should use longSum instead of count, then actually, I was using longSum of count in my original queries. I replaced them with counts to simplify examples for this issue submission.

**Comment by kzarzycki** [comment]
I understand, that realtime spec might be valuable to you. Here is the excerpt:
```
{
    "dataSchema" : {
      "dataSource" : "datasource-topic-click",
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "format" : "json",
          "timestampSpec" : {
            "column": "utcdt",
            "format": "iso"
          },
          "dimensionsSpec" : {                                                                                                                                                                  
            "dimensions": [],                                                                                                                                                                   
            "dimensionExclusions" : [],                                                                                                                                                         
            "spatialDimensions" : []                                                                                                                                                            
          }                                                                                                                                                                                     
        }                                                                                                                                                                                       
      },                                                                                                                                                                                        
      "metricsSpec" : [                                                                                                                                                                         
        {                                                                                                                                                                                       
            "type" : "count",
            "name" : "click"
        },
     ...
    ],
  "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "hour",
        "queryGranularity" : "NONE"
      }
  },
    "ioConfig" : {
      "type" : "realtime",
      "firehose": {
        "type": "kafka-0.8",
       ...
      },
      "plumber": {
        "type": "realtime"
      }
    },
    "tuningConfig": {
      "shardSpec": {
            "type": "linear",
            "partitionNum": 0
      },
      "type" : "realtime",
      "maxRowsInMemory": 500000,
      "intermediatePersistPeriod": "PT10m",
      "windowPeriod": "PT10m",
      "basePersistDirectory": "\/ebs\/druid\/realtime\/basePersist",
       "rejectionPolicy": {
        "type": "serverTime"
      }
    }

}
```
(Please note queryGranularity: NONE, so AFAIK longSum of count is not needed.)

**Comment by fjy** [comment]
@kzarzycki I am having a really hard time understanding the logs you are posting.

Please provide:
1) The raw data (the 5 lines of raw data)
2) Your topN query.

Ensure all timestamps across all machines are UTC. I highly doubt this is a bug but rather an error in the query.

**Comment by kzarzycki** [comment]
@fjy , I generated a script doing the test for me. Here are the things You asked for.
Ad. 1. Here are the 3 events I ingest (well, they are projected to just few fields involved in the issue. The whole event has tens of fields): 
```
{
  "date": "2015-12-09T15:46:28",
  "orientation_change": null,
  "dual_orientation": null,
  "traffic_source_id": 35
}
{
  "date": "2015-12-09T15:46:29",
  "orientation_change": null,
  "dual_orientation": null,
  "traffic_source_id": 35
}
{
  "date": "2015-12-09T15:46:30",
  "orientation_change": null,
  "dual_orientation": null,
  "traffic_source_id": 35
}
```

Ad.2. Here is a TopN query:
```
----- TopN query ----
{
  "queryType": "topN",
  "dataSource": "datasource-topic-click",
  "intervals": "2015-12-09T15:46:27+0000/P1D",
  "granularity": "all",
  "aggregations": [
    {
      "type": "count",
      "name": "count"
    }
  ],
  "dimension": "orientation_change",
  "threshold": 100000,
  "metric": "count",
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "selector",
        "dimension": "traffic_source_id",
        "value": "35"
      }
    ]
  }
}
----- Result -----
[
  {
    "timestamp": "2015-12-09T15:46:27.000Z",
    "result": []
  }
]
```
Note the empty result. 

3) Let me add to this a select query:
```
----- Select query -----
{
  "queryType": "select",
  "dataSource": "datasource-topic-click",
  "intervals": "2015-12-09T15:46:27+0000/P1D",
  "granularity": "all",
  "dimensions": [
    "orientation_change",
    "dual_orientation"
  ],
  "metrics": [
    "click"
  ],
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "selector",
        "dimension": "traffic_source_id",
        "value": "35"
      }
    ]
  },
  "pagingSpec": {
    "pagingIdentifiers": {},
    "threshold": 100
  }
}
----- Result -----
[
  {
    "timestamp": "2015-12-09T15:46:27.000Z",
    "result": {
      "pagingIdentifiers": {
        "datasource-topic-click_2015-12-09T15:00:00.000Z_2015-12-09T16:00:00.000Z_2015-12-09T15:00:00.000Z": 2
      },
      "events": [
        {
          "segmentId": "datasource-topic-click_2015-12-09T15:00:00.000Z_2015-12-09T16:00:00.000Z_2015-12-09T15:00:00.000Z",
          "offset": 0,
          "event": {
            "timestamp": "2015-12-09T15:46:28.000Z",
            "orientation_change": [],
            "dual_orientation": null,
            "click": 1
          }
        },
        {
          "segmentId": "datasource-topic-click_2015-12-09T15:00:00.000Z_2015-12-09T16:00:00.000Z_2015-12-09T15:00:00.000Z",
          "offset": 1,
          "event": {
            "timestamp": "2015-12-09T15:46:29.000Z",
            "orientation_change": [],
            "dual_orientation": null,
            "click": 1
          }
        },
        {
          "segmentId": "datasource-topic-click_2015-12-09T15:00:00.000Z_2015-12-09T16:00:00.000Z_2015-12-09T15:00:00.000Z",
          "offset": 2,
          "event": {
            "timestamp": "2015-12-09T15:46:30.000Z",
            "orientation_change": [],
            "dual_orientation": null,
            "click": 1
          }
        }
      ]
    }
  }
]

```

**Comment by kzarzycki** [comment]
Let me wait few minutes until realtime persist the data and I will send you result of the same(!) topN query, this time with correct result.

**Comment by kzarzycki** [comment]
OK, done. Here is the same topN query repeated after these 10 minutes passed between my posts:
```
----- TopN query ----
{
  "queryType": "topN",
  "dataSource": "datasource-topic-click",
  "intervals": "2015-12-09T15:46:27+0000/P1D",
  "granularity": "all",
  "aggregations": [
    {
      "type": "count",
      "name": "count"
    }
  ],
  "dimension": "orientation_change",
  "threshold": 100000,
  "metric": "count",
  "filter": {
    "type": "and",
    "fields": [
      {
        "type": "selector",
        "dimension": "traffic_source_id",
        "value": "35"
      }
    ]
  }
}

----- Result -----
[
  {
    "timestamp": "2015-12-09T15:46:27.000Z",
    "result": [
      {
        "count": 3,
        "orientation_change": null
      }
    ]
  }
]
```

**Comment by fjy** [comment]
Hmmm, I think the issue you are reporting actually is because of the "intervals" field in the topN

If you issue the same query with "intervals": "2015-12-09T15:00:00/P1D", or a much less granular interval, what do you see?

**Comment by kzarzycki** [comment]
I saw the same issue with intervals like "2015-12-09T15:00:00/P1D", "2015-12-09T15:00:00/2015-12-09T16:00:00", or "2015-12-09/2015-12-10". 

(The intervals above are so granular, because I generate them in the script).

**Comment by fjy** [comment]
@kzarzycki can you submit a unit test to report this problem? i haven't seen it before or seen anyone else report it

**Comment by kzarzycki** [comment]
@fjy what precisely would you like me to submit?
