### ISSUE TITLE
Please include processType attribute in druid metrics emitter.

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#2065]
I would like the metrics emitted by Druid to include a hard coded `processType` attribute. The values of this attribute would be "broker", "realtime", "historical", e.t.c based on where they were emitted from.

I know that it is possible to code these into the `service` attribute but is hard to get everyone to follow a convention and this attribute is much too important for that since it pretty much defines the meanings of all other metrics.

**Comment by gianm** [comment]
Seems very useful. I think it should be called `serviceType` though.

**Comment by dclim** [comment]
I can pick this one up.
