### ISSUE TITLE
Page build.html on druid.io is outdated

### ISSUE THREAD

**Issue by liuqiyun** [apache/incubator-druid#2069]
On the page http://druid.io/docs/0.8.2/development/build.html, it says 'mvn clean package' will generate tarball 'services/target/druid-VERSION-bin.tar.gz', however the act is that 'mvn clean install' will generate  tarball 'distribution/target/druid-VERSION-bin.tar.gz' . So should update the page build.html.

**Comment by fjy** [comment]
Thanks for the catch! Do you mind editing the file here: https://github.com/druid-io/druid/blob/master/docs/content/development/build.md?

**Comment by guobingkun** [comment]
@fjy I think the current doc in the master branch is up-to-date. It's just that the doc on the website is still using 0.8.2. We can update the website for that specific development doc.

**Comment by Vadi** [comment]
I just wasted 2hrs. Would love to help if any hand needed to update the website. Thanks.

**Comment by rasahner** [comment]
Can you be more specific?  Was this more than the "services/distribution" update indicated above?

**Comment by rasahner** [comment]
I will try to de-confuse some of the build instructions in the latest docs with regard to the mysql metadata jar.
