### ISSUE TITLE
Version conflict  in guava with Clouder Hadoop

### ISSUE THREAD

**Issue by kupferk** [apache/incubator-druid#2088]
I found another version conflict between Druid and Cloudera Hadoop once I tried to batch ingest some data and enabled a cardinality aggregator. It turns out this time Guava was the offender which is stuck in Hadoop at 11.x while Druid uses Guava 16.x.

Since I had a similar issue with the Jackson libraries, I thought about shading and relocating the relevant dependencies (maybe a better solution would be if Hadoop itself shaded its dependencies, but that is out of scope for me). So the idea would be to relocate com.google.guava.\* to io.druid-project.guava.\* and something similar with the jackson libraries. But things do not seem so simple, as I have hoped for. 

Did anyone investigate in this approach so far? Are are there any opinions if this would be a good way to solve the dependency conflicts? I am asking, maybe I will have some time to work out something, but I'd like to hear the experts before spending too much time on that issue.

**Comment by drcrallen** [comment]
@kupferk shading stuff for Druid would be worth a discussion but should be brought up in its own topic :)

**Comment by kupferk** [comment]
@drcrallen thanks for your mental support, I'll open a ticket, so we can discuss the required steps. I'll try my best at implementing this task then.
