### ISSUE TITLE
Transient failure on io.druid.curator.announcement.AnnouncerTest testSessionKilled

### ISSUE THREAD

**Issue by fjy** [apache/incubator-druid#2167]
io.druid.curator.announcement.AnnouncerTest
testSessionKilled(io.druid.curator.announcement.AnnouncerTest) Time elapsed: 2.233 sec <<< FAILURE!
java.lang.AssertionError: expected null, but was:<10,10,1451284237249,1451284237249,0,0,0,95111363629613057,25,0,10

**Comment by fjy** [comment]
Seeing timeout failures:

io.druid.curator.announcement.AnnouncerTest
testSessionKilled(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 61.08 sec  <<< ERROR!
java.lang.Exception: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at io.druid.curator.announcement.AnnouncerTest.testSessionKilled(AnnouncerTest.java:177)

**Comment by fjy** [comment]
@cheddar @himanshug so I think this failure might actually be a problem with the code where the announcer will not always clean up curator paths correctly when it is shutdown. I haven't bug into why this is the case though.

**Comment by himanshug** [comment]
reopening as #2213 doesn't have a fix but hopes to provide more information when it fails.

**Comment by gianm** [comment]
failed here: https://travis-ci.org/druid-io/druid/builds/103912940, perhaps that provides the more information.
