### ISSUE TITLE
I would like JavaScript filters to be able to work on multiple columns

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#2187]
I would like to do something like this:

```
{
  "type" : "javascript",
  "dimensions" : ["dim1", "dim2"]
  "function" : "function(d1, d3) { return d1 === d2 }"
}
```

Here is a thread about how useful this would be: https://groups.google.com/forum/#!topic/druid-user/-MEsJOUX_5I

**Comment by donpinkus** [comment]
Has this functionality been added? Or does a JS filter still only work on one column?

**Comment by leventov** [comment]
@donpinkus this specific type of filter is implemented in #3928

**Comment by vogievetsky** [comment]
Closing as this has been added.

**Comment by MakDon** [comment]
I would like to do something like
```
 {
  "type" : "javascript",
  "dimensions" : ["__time", "product_release_day"]
  "function" : "function(t, rt) { return inTheSameDay(t,rt) }"
}
```

in which the `product_release_day`'s layout is `2006-01-02`, making that the Selector filter could not work in this case
is there any method could i use to compare `__time` with another dimensions?
