### ISSUE TITLE
Suggest to support raw query in JDBCExtractionNamespace

### ISSUE THREAD

**Issue by sirpkt** [apache/incubator-druid#2280]
Currently, JDBCExtractionNamespace requires table, key column, and value column names.
Then, it makes query like "select keyColumn, valueColumn from table" and issues it through JDBC interface.
If we can specify the raw query to retrieve (key, value) pairs, we can get more flexibility to get source namespace.
For example, we can have namespace from joins of multiple tables like "select A.a2, C.c3 from A join B on A.a1 = B.b1 and B.b2 = C.c2 order by A.a2 limit 1000".

**Comment by sirpkt** [comment]
With a little trick, current JDBCExtractionNamespace also supports above namespace like
```
"table": "(select A.a2 as key, C.c3 as value from A join B on A.a1 = B.b1 and B.b2 = C.c2 order by A.a2 limit 1000) sq",
"keyColumn": "key",
"valueColumn":"value"
```
I think it is not intuitive so it is better to support new parameter ```query```.
However, it may require sanity check of the given query that it actually returns two columns (or three columns if tsColumn is used).

**Comment by zhangxin0112** [comment]
is it could use join in the extraction namespace?

**Comment by zhangxin0112** [comment]
if join is supported . could u give me some join conf.json files ,i could not find the example .tks u

**Comment by b-slim** [comment]
@sirpkt have you seen, https://github.com/druid-io/druid/pull/2819/files.
This can be done by implementing `DataFetcher` that does provide what you need thought.

**Comment by zhangxin0112** [comment]
@b-slim  execuse me . it is mean i must implement the interface `DataFetcher` and load it via another druid module by myself at now if i want "join" two different datasources ?

**Comment by b-slim** [comment]
@zhangxin0112 yes, that API offers an abstraction between your fact tables and the cache used for lookups.

**Comment by zhangxin0112** [comment]
@b-slim got it .thank u .
