### ISSUE TITLE
Some questions of Druid?

### ISSUE THREAD

**Issue by alan2018** [apache/incubator-druid#2298]
How does one upgrade the druid software with minimal system downtime, and what's the impact on system performance? 
How does one recover from common failures? What is the impact on system performance?
What's the model for supporting multiple tenants? Or does each tenant need to install its own?
 Is there a way to apply elasticity per tenant?

**Comment by pjain1** [comment]
Hello,

Please go through this [document](http://druid.io/docs/latest/operations/rolling-updates.html) for questions about rolling updates to druid cluster. For questions about multitenancy go through this [document]( https://github.com/druid-io/druid/blob/master/docs/content/operations/multitenancy.md).

If you have any further questions please use druid-user google group for asking questions as you can expect much faster response there. Here's the [link](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/druid-user)
