### ISSUE TITLE
[proposal]datasketches lib based quantiles/histogram support in druid

### ISSUE THREAD

**Issue by himanshug** [apache/incubator-druid#2406]
http://datasketches.github.io/ is adding support for quantile sketch which can be used to estimate quantiles and histograms. however to use them inside druid it is desirable for quantile sketches to provide merging of sketches with different sizes which is being worked on.

upcoming code and documentation for druid aggregators and post-aggregators for same can be seen at https://github.com/himanshug/druid/tree/quantiles/extensions/datasketches . (scroll down to "quantiles aggregator" section)

**Comment by fjy** [comment]
@himanshug according to http://datasketches.github.io/docs/QuantilesAccuracy.html, a tremendous amount of storage is required for reasonable accuracy at scale. How do you solve this problem?

**Comment by gianm** [comment]
From the table it looks like the error is bounded but the size of the sketch is unbounded. It looks like it grows logarithmically and wouldn't get too crazy at ~trillions of points. But it also seems like the offheap code would have to either tweak the algorithm to make it bounded in size, or start returning errors at some point, as it has to be able to pick a number for max storage.

Is that right @himanshug? if so how were you thinking of handling that?

**Comment by himanshug** [comment]
@gianm @fjy yes that is correct, they are not memory bound but growth with n is not linear.
i spoke to the local experts about this and the reason to make this choice is to be able to provide predictable errors independent of input distribution and still be able to be fast enough.

**Comment by pdeva** [comment]
if anyone is working on this, is there is a specific branch/fork that I can know about?
I would like to contribute and finish this feature since this is something we need a lot.

**Comment by himanshug** [comment]
@pdeva i have the code for this, was hesitating from putting it in druid too quick coz the quantile aggregators are still evolving a bit until now (and possibly will evolve even more)
considering,  community needs it... I will probably put it in as "experimental" aggregator for now.

**Comment by fjy** [comment]
@himanshug put it as part of extensions-contrib

**Comment by pdeva** [comment]
@himanshug can i what the current issues with the quartile implementation are? 
The datasketch github has no issues listed and there doesnt seem to be a separate mailing list for datasketch project, so i am not sure what state it is currently in.
We plan to use it in production, so very helpful to know current set of issues. 
Again happy to contribute fixes if needed.

**Comment by himanshug** [comment]
@pdeva @fjy ok, I am submitting the aggregators for quantiles/histograms in https://github.com/druid-io/druid/pull/2660 . I am marking the as experimental primarily to keep things open for a little while wrt change. It should be totally usable though.
current/future activity is around providing a true off-heap implementation for quantiles sketches, some other issues related to merging sketches of different sizes were resolved in sketches-0.4.0 version.
