### ISSUE TITLE
I would like the javascript postAggregation to auto finalize sketches

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#2434]
If I run a query like this:

``` json
{
  "queryType": "timeseries",
  "dataSource": "wikipedia",
  "granularity": "all",
  "intervals": [
    "2016-02-01/2016-02-05"
  ],
  "aggregations": [
    {
      "fieldNames": [
        "page"
      ],
      "name": "NumPages",
      "type": "cardinality"
    }
  ],
  "postAggregations": [
    {
      "type": "javascript",
      "name": "NumPagesMod1337",
      "fieldNames": [
        "NumPages"
      ],
      "function": "function(NumPages) { return NumPages % 1337 }"
    }
  ]
}
```

`NumPagesMod1337` will return as `"NaN"`

This is because the javascript postAgg does not finalize the input sketch. There is absolutely nothing that a JS Post Agg can do with an un finalized input so please make it finalize.

Alternatively allow javascript post agg to accept other post aggregators (as opposed to raw fields) as inputs. Making this possible:

``` json
    {
      "type": "javascript",
      "name": "NumPagesMod1337",
      "fields": [
        { "type": "hyperUniqueCardinality", "fieldName": "NumPages" }
      ],
      "function": "function(NumPages) { return NumPages % 1337 }"
    }
```

**Comment by vogievetsky** [comment]
if the JS postagg could accept `"fields"` and #2433 was done then this problem would be totally solved.

**Comment by gianm** [comment]
@vogievetsky I think the JS postagg can already take other postaggs as fieldNames so would it be ok to close this and just do #2433?

**Comment by gianm** [comment]
In that case the query would look like:

```json
{
  "queryType": "timeseries",
  "dataSource": "wikipedia",
  "granularity": "all",
  "intervals": [
    "2016-02-01/2016-02-05"
  ],
  "aggregations": [
    {
      "fieldNames": [
        "page"
      ],
      "name": "NumPages",
      "type": "cardinality"
    }
  ],
  "postAggregations": [
    {
      "type": "finalizeFieldAccess",
      "name": "NumPages",
      "fieldName": "NumPagesFinal"
    },
    {
      "type": "javascript",
      "name": "NumPagesMod1337",
      "fieldNames": [
        "NumPagesFinal"
      ],
      "function": "function(NumPagesFinal) { return NumPagesFinal % 1337 }"
    }
  ]
}
```

**Comment by vogievetsky** [comment]
@gianm this issue is more about usability than is being possible to do something. Neither what I am proposing here nor #2433 unlock any functionality that is otherwise impossible to achieve. 

Look at this through the eyes of a new Druid user: the JS post agg getting unfinalized values is simply useless. There is literally no scenario where you would want that.

Consider:

```json
{
  "queryType": "timeseries",
  "dataSource": "wikipedia",
  "granularity": "all",
  "intervals": [
    "2016-02-01/2016-02-05"
  ],
  "aggregations": [
    {
      "fieldNames": [
        "page"
      ],
      "name": "NumPages",
      "type": "cardinality"
    }
  ],
  "postAggregations": [
    {
      "type": "javascript",
      "name": "NumPagesMod1337",
      "fieldNames": [
        "NumPages"
      ],
      "function": "function(NumPages) { return typeof NumPages === 'number' }"
    }
  ]
}
```

It gives back: 

```json
{
  "error" : "Invalid JavaScript value of type io.druid.query.aggregation.hyperloglog.HLLCV1 (fn#1)"
}
```

`NumPages` in being passed in a way that can not even be used by the JS language.

As such it would be an improvement to the **usability** of the Druid query API if the inputs to a JS port agg were auto finalized for you. That is what my issue is about at it's core.

**Comment by vogievetsky** [comment]
Yeah, Druid SQL make it so we do not need to think of finalizing stuff :-)
