### ISSUE TITLE
Internal query planner for Druid?

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#2455]
I am opening an issue to track discussion on whether/when it makes sense to develop a query planner within Druid, similar to what https://github.com/implydata/plywood provides.

**Comment by jon-wei** [comment]
Perhaps related to this, I briefly experimented with integrating Apache Calcite with Druid as an SQL parser/query planner; I wasn't familiar with query planning and didn't pursue this very far. 

If anyone is interested, I have an old fork with my rough attempts at:
https://github.com/jon-wei/druid/tree/calcite2

It copies some logic/structure from parts of Apache Drill, I was able to get an SQL query from a POST and get a logical plan generated, but didn't go any farther than that.

**Comment by Jhors2** [comment]
+1, This would be extremely useful.  We use plywood/plyql quite heavily and would like to simplify our query stack if possible.

**Comment by nelgau** [comment]
Huzzah! It appears that Druid support will debut in Apache Calcite 1.8! 😀 

https://issues.apache.org/jira/browse/CALCITE-1121 (resolved)
https://issues.apache.org/jira/browse/CALCITE-1206 (pending)

The first commit landed in master 9 days ago. 
https://git1-us-west.apache.org/repos/asf?p=calcite.git;a=commit;h=dd8d3c58

@jon-wei Does your rough integration contain any missing pieces or polish that might be of use here?

I see there was some discussion of adding an artificial aggregation (as a workaround) and some uncertainty about whether it's valid for a push down to yield a "topN" query:

> Consider using "topN" Druid queries if the SQL query is of the right form. Druid's documentation claims that they are more efficient. (However, they may be approximate.)

Can we offer any words of wisdom in response to [this comment](https://issues.apache.org/jira/browse/CALCITE-1121?focusedCommentId=15252715&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15252715), the pending [CALCITE-1206](https://issues.apache.org/jira/browse/CALCITE-1206), or general advice that might help this adapter to become as idiomatic as possible?

**Comment by gianm** [comment]
@nelgau AWESOME

IMHO an idiomatic adapter would use approximate features like topN, the "cardinality" aggregator, hyperUnique, etc, by default when possible but also support a hint to trigger an exact mode. Most of the larger Druid installations I'm aware of (including the ones at metamarkets and yahoo) make heavy use of those approximation features to keep query response time fast.

PS: Note that topN is actually exact if you are doing a lexicographic sort on the topN dimension. It's only approximate if you are sorting on a measure.

**Comment by jon-wei** [comment]
@nelgau I don't think so, I didn't get very far with that branch.

**Comment by vogievetsky** [comment]
This exists now: http://druid.io/docs/latest/querying/sql

**Comment by vogievetsky** [comment]
Closing as DONE 🎆
