### ISSUE TITLE
can't disable segments with DELETE datasource kill=false any more

### ISSUE THREAD

**Issue by rasahner** [apache/incubator-druid#2467]
This is about disabling segments.

Before 0.9.0, it was possible to disable segments using one of these two endpoints (the second one with kill=false)
  /druid/coordinator/v1/datasources/{dataSourceName}
  /druid/coordinator/v1/datasources/{dataSourceName}?kill={value}&interval={myISO8601Interval}

The second way wasn't documented, and it may just be an accident of coding that it worked. The integration tests were using it.

PR #2276 replaced the second endpoint above with one having a different syntax:
  /druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval}?kill=true
It modified the integration tests to use this new endpoint, including trying to use it to disable segments by setting kill=false.  The new endpoint won't allow kill=false; it returns an error and doesn't do anything.
Some of the integration tests are failing when run on druid 0.9.0 because they can't clean up the segments.

I will modify the integration tests to use the first endpoint above to disable segments.  This seems to be the correct (documented) way to do it anyway.

But, I think that when the deprecated code goes away, that first endpoint will stop working.  Both of the old endpoints were handled by the same  (deprecated) function, which would be reached whether or not kill was present in the url. It would disable segments if kill was absent or false.  I think that with the syntax of the new function, the URL
  /druid/coordinator/v1/datasources/{dataSourceName}
will not map to anything.

**Comment by rasahner** [comment]
The integration test modification is done with https://github.com/druid-io/druid/pull/2470.
Perhaps the other part could be handled by adding a comment to the deprecated function saying that only part of it is actually deprecated, and that the function should not be removed, only have the part of it that handles kill=true removed.

**Comment by l15k4** [comment]
Have this issue too on [distribution-docker](https://github.com/implydata/distribution-docker). 

```
root@d93e783f7ae1:~/imply-1.1.0# curl -XGET http://localhost:8081/druid/coordinator/v1/datasources/wikiticker/segments                                                                                            
["wikiticker_2015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z_2016-03-21T23:38:16.629Z"]

root@d93e783f7ae1:~/imply-1.1.0# curl -XDELETE http://localhost:8081/druid/coordinator/v1/datasources/wikiticker/segments/wikiticker_2015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z_2016-03-21T23:38:16.629Z   

root@d93e783f7ae1:~/imply-1.1.0# curl -XGET http://localhost:8081/druid/coordinator/v1/datasources/wikiticker/segments                                                                                         
["wikiticker_2015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z_2016-03-21T23:38:16.629Z"]
```

The same with `/druid/coordinator/v1/datasources/{dataSourceName}/intervals/{interval}`
where I assume that `/` should be substituted with `_`

**Comment by pjain1** [comment]
@l15k4 Once you disable a segment it takes a while for coordinator to update it's view of "used" segments depending on `druid.coordinator.period` and `druid.manager.segments.pollDuration` both of which by default is set to a minute. In worst scenario it can take up to `druid.coordinator.period + druid.manager.segments.pollDuration` for changes to reflect. Do you still see the segment after a while ?

**Comment by l15k4** [comment]
@pjain1 I waited 5 minutes, it is easily reproducible : 
```
$ docker run -d --name imply imply/imply
167958bb727f544db2d4f9d093a5f247a4cc2b65c3ad783670bc13515b310572
$ docker exec -it imply /bin/bash
root@167958bb727f:~/imply-1.1.0# bin/post-index-task --file quickstart/wikiticker-index.json
Task started: index_hadoop_wikiticker_2016-03-22T08:19:07.802Z
Task log:     http://localhost:8090/druid/indexer/v1/task/index_hadoop_wikiticker_2016-03-22T08:19:07.802Z/log
Task status:  http://localhost:8090/druid/indexer/v1/task/index_hadoop_wikiticker_2016-03-22T08:19:07.802Z/status
Task index_hadoop_wikiticker_2016-03-22T08:19:07.802Z still running...
Task index_hadoop_wikiticker_2016-03-22T08:19:07.802Z still running...
Task index_hadoop_wikiticker_2016-03-22T08:19:07.802Z still running...
Task index_hadoop_wikiticker_2016-03-22T08:19:07.802Z still running...
Task finished with status: SUCCESS
root@167958bb727f:~/imply-1.1.0# curl http://localhost:8081/druid/coordinator/v1/datasources/wikiticker/segments
["wikiticker_2015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z_2016-03-22T08:19:07.863Z"]
root@167958bb727f:~/imply-1.1.0# curl -X DELETE http://localhost:8081/druid/coordinator/v1/datasources/wikiticker/segments/wikiticker_2015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z_2016-03-22T08:19:07.863Z
root@167958bb727f:~/imply-1.1.0# curl http://localhost:8081/druid/coordinator/v1/datasources/wikiticker/segments                                                                                                
["wikiticker_2015-09-12T00:00:00.000Z_2015-09-13T00:00:00.000Z_2016-03-22T08:19:07.863Z"]
```

**Comment by pjain1** [comment]
@l15k4 Oh I see...I think it is a known bug in case all the segments on the cluster are disabled, the last last one remains, see this - https://github.com/druid-io/druid/pull/1274

**Comment by tdingus** [comment]
I tried the delete operation the same as "l15k4 commented on Mar 22, 2016".
I don't see the segment got deleted. 

I also googled for solutions but none of them worked. Please help.

**Comment by fjy** [comment]
@cheddar @pjain1 please look into this

**Comment by pjain1** [comment]
@tdingus are you hitting this - https://github.com/druid-io/druid/pull/1274
Do you have a single segment in the cluster ? Are you getting any error while deleting ?

**Comment by tdingus** [comment]
Yes. I have a single segment in the cluster. I don't see any error log while deleting. If I should expect any error log, where should I look for it.thanks

**Comment by pjain1** [comment]
you can check the coordinator logs for any error after you send the kill request. However, given you have a single segment in the cluster unfortunately you are hitting #1274 and even after the segment is marked as unused, coordinator will still think it is present. However, it should not be a problem for production systems when you have multiple segments

**Comment by pjain1** [comment]
However, lets say you really want to **completely clean** the cluster because you are running integration tests or something then as per the current druid code base you can do this by -

1. stop coordinator node and delete all entires in the druid_segments table in the metadata store
2. stop historical node and delete everything inside the directory pointed by `druid.segmentCache.locations` at historical node
3. start coordinator and historical nodes

**REMEMBER THIS WILL DELETE EVERYTHING FROM DRUID CLUSTER, YOU WILL LOOSE ALL YOUR DATA**
