### ISSUE TITLE
Realtime exact count

### ISSUE THREAD

**Issue by eLod** [apache/incubator-druid#2481]
the issue is described at: https://groups.google.com/forum/#!topic/druid-user/XUyMunhftks

i understand this may not be fixed, but @fjy said a test would help and @nishantmonu51 was kind enough to help me finish it: https://github.com/eLod/druid/commit/33176e4e5810b2d7740929be3f50c89c7b02e1f6

**Comment by gianm** [comment]
IMO this is not a bug but is an intentional design choice and is reasonable for what Druid is intended to do. (see also post @ https://groups.google.com/d/msg/druid-user/XUyMunhftks/oItttIycCgAJ)

@fjy, @nishantmonu51, any thoughts?
