### ISSUE TITLE
Curator Version needs a bump. Causes Server starts to fail when ZK encounters UnknowHostException

### ISSUE THREAD

**Issue by vikramakrishnan** [apache/incubator-druid#2495]
**Version**
Currently on 0.8.0, but looking at maven dependency this should be reproducible on latest rc as well.

**Issue Description:** ZK version used by the curator dependency has a bug that causes the ZK init to fail even if one of the hosts in the ZK connect string returns an UnknowHostException.

**Related ZK Bug:** https://issues.apache.org/jira/browse/ZOOKEEPER-1576

**Druid Stacktrace:**

> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_51]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
>         at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
>         at com.metamx.common.lifecycle.Lifecycle$AnnotationBasedHandler.start(Lifecycle.java:331) ~[java-util-0.27.0.jar:?]
>         at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:250) ~[java-util-0.27.0.jar:?]
>         at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:136) ~[druid-api-0.3.8.jar:0.8.0]
>         at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:71) [druid-services-0.8.0.jar:0.8.0]
>         at io.druid.cli.ServerRunnable.run(ServerRunnable.java:38) [druid-services-0.8.0.jar:0.8.0]
>         at io.druid.cli.Main.main(Main.java:91) [druid-services-0.8.0.jar:0.8.0]
> Caused by: java.net.UnknownHostException: somerandomzk1.xyzcorp.com : Name or service not known
>         at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.7.0_51]
>         at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901) ~[?:1.7.0_51]
>         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293) ~[?:1.7.0_51]
>         at java.net.InetAddress.getAllByName0(InetAddress.java:1246) ~[?:1.7.0_51]
>         at java.net.InetAddress.getAllByName(InetAddress.java:1162) ~[?:1.7.0_51]
>         at java.net.InetAddress.getAllByName(InetAddress.java:1098) ~[?:1.7.0_51]
>         at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
>         at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
>         at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:160) ~[curator-framework-2.7.0.jar:?]
>         at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.HandleHolder.internalClose(HandleHolder.java:128) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.HandleHolder.closeAndReset(HandleHolder.java:77) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.ConnectionState.reset(ConnectionState.java:217) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:193) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.utils.EnsurePath$InitialHelper$1.call(EnsurePath.java:148) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:140) ~[curator-client-2.7.0.jar:?]
>         at org.apache.curator.utils.EnsurePath.ensure(EnsurePath.java:99) ~[curator-client-2.7.0.jar:?]
>         at io.druid.server.coordination.BaseZkCoordinator.start(BaseZkCoordinator.java:98) ~[druid-server-0.8.0.jar:0.8.0]

**Comment by gianm** [comment]
@vikramakrishnan do you know of a Curator version that works around this? It looks like the ZK bug is not fixed until 3.5.0, which hasn't been released yet.

**Comment by vikramakrishnan** [comment]
@gianm - curator-3.1.0 has a fixed version of zk.

**Comment by gianm** [comment]
@vikramakrishnan this version of Curator is using ZK 3.5.1-alpha, IMO we would prefer to use released versions.
