### ISSUE TITLE
Optional pre-indexing rollup job as part of Hadoop indexing

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#2594]
See also: https://groups.google.com/d/topic/druid-user/FjU68ZoQ4OM/discussion

The problem is that for datasets where rollup is really effective, we can funnel a huge amount of data through each reducer. Rollup ratios of 100:1 or 1000:1 are not unheard of. This creates a bottleneck in the IndexGeneratorJob.

Possible solution,
- add an optional job before IndexGeneratorJob that pre-aggregates your data and writes it to a tmp location, using as many reducers as necessary
- teach the IndexGeneratorJob how to operate on that pre-aggregated data (should be skipping a bunch of things it would have done, and reading from that tmp location instead of your actual data location)
- add a config to enable the extra pre-aggregation job
- bonus: possibly also enable pre-aggregation automatically if the determine-partitions job determines that the rollup ratio is above a certain threshold

**Comment by erikdubbelboer** [comment]
Wouldn't it be possible to have the map task do a rollup on its data? This way a lot less data will hit the reducer.

**Comment by gianm** [comment]
Ah, that is already an option, you can try that to see if it's enough for your dataset. I guess it depends on how much data you're sending through each mapper. You can turn that on by setting useCombiner to true in your tuningConfig.

**Comment by himanshug** [comment]
erikdubbelboer  @gianm I believe "useCombiner" should be able to handle this. ( doc http://druid.io/docs/0.8.3/ingestion/batch-ingestion.html )

**Comment by erikdubbelboer** [comment]
@himanshug It did, as I wrote in [https://groups.google.com/forum/#!topic/druid-user/TvwIBUEzqwM](druid-user/TvwIBUEzqwM) it made things much much faster and better.
