### ISSUE TITLE
Inconsistent responses from batch and real-time wrt null handling

### ISSUE THREAD

**Issue by boneill42** [apache/incubator-druid#2603]
During real-time ingest, for multi-value fields, empty dimensions are treated as null values.  When the real-time task completes, and the segment is transitioned to a historical node, the same query returns a response that omits the null value.

**Comment by boneill42** [comment]
This repo contains code to reproduce the issue:
https://github.com/boneill42/druid-ingestion

**Comment by boneill42** [comment]
RE: this topic
https://groups.google.com/forum/#!topic/druid-user/In8I20MElGk

**Comment by CHOIJAEHONG1** [comment]
Hi,
If I can put a little of clue here, refering to the following would be helpful. 
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/IndexIO.java#L607

When the index is persisted into a disk(and handed-off), a dimension whose dictionary is empty is to be skipped.

Thank you.

**Comment by boneill42** [comment]
thanks for that pointer...
Interestingly enough, when the IndexIO task runs, it sees a cardinality of 4.  (which appears to include the null value)  

```shell
Starting dimension[products] with cardinality[4]
```

**Comment by boneill42** [comment]
Looking at the code...
We spin through the multi-values here:
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/IndexIO.java#L622

Then do some null checking here?
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/IndexIO.java#L630
