### ISSUE TITLE
Change spatial index handling in DimensionsSpec

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#2622]
I propose changing the way spatial dimensions are expressed in DimensionsSpec:
- When configurable index types on dimensions is supported, "spatial" should then be an option within a dimension's choice of indexes, instead of a separate type of dimension
- Spatial handling has another unique requirement: combining two dimensions into one via the spatialRowTransformer in IncrementalIndex. I propose having that functionality expressed as part of a more generic "RowTransformerSpec" within the ingestion spec.

**Comment by fjy** [comment]
:+1:
