### ISSUE TITLE
Allow user-configurable indexing strategies for dimensions

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#2654]
Druid could support a wider range of index strategies beyond bitmap indexes. Possible configurations could include:
- String dimensions without bitmap indexes
- Range indexes
- Spatial indexes on multiple data types (e.g., long coordinates)
- tries for String dimensions

---

Related issues:
https://github.com/druid-io/druid/issues/2622
https://github.com/druid-io/druid/issues/2292

**Comment by fjy** [comment]
:+1:
