### ISSUE TITLE
Coordinator console doesn't work for dynamic config.

### ISSUE THREAD

**Issue by guobingkun** [apache/incubator-druid#2746]
Coordinator dynamic config doesn't work when you post a JSON object. 

For example,

![image](https://cloud.githubusercontent.com/assets/11789051/14082054/7e20dbf8-f4d3-11e5-99d8-45418858b0c0.png)

Posting `["wikipedia"]` to killDataSourceWhitelist will not work as expected. I think the reason is that Coordinator console automatically added quotes to `["wikipedia"]`, which makes it 

![image](https://cloud.githubusercontent.com/assets/11789051/14082096/b700a21e-f4d3-11e5-9684-f2e244727c3b.png)

**Comment by vogievetsky** [comment]
This is not an issue with the new console

![image](https://user-images.githubusercontent.com/177816/65645160-474ad900-dfab-11e9-981e-c4892e0345bc.png)

Considering this fixed (in Druid 0.14.0) :-D
