### ISSUE TITLE
removing a single zookeeper node in quorum makes coordinator forget datasources

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#2877]
druid 0.8.3

**steps to reproduce:**
1. use a typical druid installation with a 3 node zookeeper cluster.
2. restart the leader of zookeeper quorum ( zookeeper keeps running fine with new leader elected).
3. go to coordinator console web ui.

**Expected:**
console ui should show all the available datasources on the left bar (as it usually does)

**Actual:**
console ui doesnt list any datasources at all

**Comment by fjy** [comment]
@pdeva did you wait for the coordinator to reacquire leadership and start up after its startup period?

**Comment by pdeva** [comment]
hmm so not knowing the internals of coordinator:

- the coordinator was already running while i rebooted the zk node.
- i am fairly sure the `coordinator.period` (of 60s default) had passed when i checked the console.

if there is indeed a different timer at which coordinator would have resumed showing datasources, the console ui should show some indication atleast. it is very alarming to see the console ui and not see any of your datasources listed.
