### ISSUE TITLE
mysql connections need a shorter timeout

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#2968]
results from our apm:
![](http://content.screencast.com/users/PrashantDeva/folders/Jing/media/cb405b23-60a5-4ba3-ae1a-911e2d87e25e/2016-05-13_1417.png)

Query stacktrace:

![](http://content.screencast.com/users/PrashantDeva/folders/Jing/media/c32df552-c201-4747-9b9e-920f5b95f2f5/2016-05-13_1419.png)

Our mysql instance is hosted on google cloud sql.

Gcloud sql is notorious for killing connections that are inactive for longer than a minute.

Druid's mysql connector should add shorter socket and connection timeouts to prevent this delay. 

Druid version 0.8.3

**Comment by drcrallen** [comment]
0.9.1 adds ability to stream back mysql query results per https://github.com/druid-io/druid/pull/2859

But Here it looks like it is blocking on publishing the segment, so I'm curious what is holding onto the db lock preventing this.

**Comment by pdeva** [comment]
You are right this is during the segment publishing.

Its the db connection actually. its trying to communicate on a connection that gcloud doesnt want to anymore.
we ran into this problem a ton when trying to use gcloud's mysql instance ourselves.
The solution was to have much shorter timeouts for everything.
I am fairly sure tweaking dbcp's timeout settings will fix this.

**Comment by drcrallen** [comment]
Any chance you can get the line number in SQLMetadataSegmentPublisher?

**Comment by pdeva** [comment]
yup. Here are the full stack traces from:

Realtime:
http://screencast.com/t/pdpBOdq2pBoo

Coordinator:
http://screencast.com/t/UlKeWMXzL

**Comment by gianm** [comment]
That looks like the validation query failing (we use "SELECT 1" by default, maybe the driver decided to parameterize that). I'm not sure why the duration is reported as so high though, did it really take that long or is that possibly some measurement error?

At any rate, I'm not sure what the default validation timeout is, but we could lower it by calling `dataSource.setValidationQueryTimeout` in `SQLMetadataConnector.getDatasource`

**Comment by pdeva** [comment]
it really is taking this long. since we switched to gcloud sql for
metadata, persisting a segment takes almost 20-30 mins post the time period
window.

On Friday, May 13, 2016, Gian Merlino <notifications@github.com> wrote:

> That looks like the validation query failing (we use "SELECT 1" by
> default, maybe the driver decided to parameterize that). I'm not sure why
> the duration is reported as so high though, did it really take that long or
> is that possibly some measurement error?
>
> At any rate, I'm not sure what the default validation timeout is, but we
> could lower it by calling dataSource.setValidationQueryTimeout in
> SQLMetadataConnector.getDatasource
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/druid-io/druid/issues/2968#issuecomment-219169750>
>


-- 
Prashant
