### ISSUE TITLE
Ability to apply extraction function transformations at ingestion time

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#2977]
I would like to be able to use extraction functions to transform dimensions in my ingestion spec.

It might look like this:

``` javascript
"dimensionsSpec" : {
  "dimensions" : [
    "sometimeLater",
    "channel",
    "comment",
    {
      "extractionFn": {
        "function": "function(d){d=Number(d); if(isNaN(d)) return 'null'; return Math.floor(d / 10) * 10;}",
        "type": "javascript"
      },
      "dimension": "commentLength",
      "outputName": "commentLengthBucketsOf10",
      "type": "extraction"
    },
    "isAnonymous",
    "isMinor",
    "isNew",
    "isRobot",
    "isUnpatrolled",
    "metroCode",
    "namespace",
    "page",
    "user",
    "userChars"
  ]
}
```

This would allow users to do simple transformations on the data (e.g. basic cleanup) without the need for a stream processor. It would also facilitate renaming dimensions at ingestion.

**Comment by hamlet-lee** [comment]
I like this proposal.

**Comment by SreeHarshaGudise** [comment]
Is it working or not? Because when i tried this transformation function over dimensions while ingestion it gives me error that dimension name could not be null it is not accepting dimension name

**Comment by gianm** [comment]
@SreeHarshaGudise It's just a feature request, so it does not work yet.

**Comment by SreeHarshaGudise** [comment]
Thankyou @gianm  for the reply

**Comment by SreeHarshaGudise** [comment]
So, can u help me up i have a small situation where i have to use timstamp and change it into day of  a week and add it to dimensions .
Thanks in advance @gianm

**Comment by Crystark** [comment]
That would be really great! I wanted to use the following but realized it was only possible at query time.

```
{
  "type" : "extraction",
  "dimension" : "uuid",
  "outputName" :  "has_uuid",
  "extractionFn" : { "type" : "stringFormat", "format" : "Y" }
}
```

**Comment by gianm** [comment]
This can now be done with transform specs: https://druid.apache.org/docs/latest/ingestion/transform-spec.html
