### ISSUE TITLE
Ability to make derived dimension from multiple dimensions

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#3000]
Right now extraction functions only work on one input.

I would like to express something like:

``` sql
SELECT CONCAT(`country`, "->", `city`) AS "place", COUNT(*) AS "count"
FROM wikipedia
GROUP BY CONCAT(`country`, "->", `city`)
ORDER BY count DESC LIMIT 5
```

Or

``` sql
SELECT CONCAT(LOOKUP(`id`, "my-lookup"), " [", `id`, "]") AS "blah", COUNT(*) AS "count"
FROM wikipedia
GROUP BY CONCAT(LOOKUP(`id`, "my-lookup), " [", `id`, "]")
ORDER BY count DESC LIMIT 5
```

As topNs.

Maybe it could look like this:

``` json
{
  "queryType": "topN",
  "dataSource": "wikipedia",
  "granularity": "all",
  "intervals": "2000/3000",
  "dimension": {    
    "outputName": "place",
    "type": "multi",
    "fn": "sprintf",
    "string": "%s->%s",
    "args": [
      "country",
      "city"
    ]
  },  
  "aggregations": [
    {
      "name": "Count",
      "type": "count"
    }
  ],
  "metric": "Count",
  "threshold": 5
}
```

and

``` json
{
  "queryType": "topN",
  "dataSource": "wikipedia",
  "granularity": "all",
  "intervals": "2000/3000",
  "dimension": {    
    "outputName": "place",
    "type": "multi",
    "fn": "sprintf",
    "string": "%s [%s]",
    "args": [
      "id",
      {
        "type": "extraction",
        "dimension": "id",
        "extractionFn": {
          "lookup": {
            "namespace": "my-lookup",
            "type": "namespace"
          },
          "type": "lookup"
        }        
      }
    ]
  },  
  "aggregations": [
    {
      "name": "Count",
      "type": "count"
    }
  ],
  "metric": "Count",
  "threshold": 5
}
```

**Comment by drcrallen** [comment]
This is directly related to some discussions I've had with people internally about if this is appropriate to do in Druid, or is better handled at a layer above Druid.

If the data mapping / concat has a direct manipulation of the results of the data (like how QTL can merge multiple IDs together) then it is an obvious candidate for a feature in druid.

But just like Druid isn't really an ETL engine for data coming in, I'm not convinced it is always a good candidate for ETL going out.

I *CAN*  see where maintaining access to lookups might be cumbersome if it has to be maintained in both Druid and an external system though. Especially if the lookup isn't a simple "query some DB and get a value for some ID". So I think having some kind of *ease-of-use* and *operational-sanity* capacity to have some form of "dimension explosion via lookups" at the query level for druid makes sense.

**Comment by gianm** [comment]
IMO something like this makes sense in Druid, it's always possible for functions to map things to a smaller output space, and pushing that down as far as possible will help performance and memory use.

**Comment by drcrallen** [comment]
Functionally, how does 
```json
  "dimension": {    
    "outputName": "place",
    "type": "multi",
    "fn": "sprintf",
    "string": "%s->%s",
    "args": [
      "country",
      "city"
    ]
  },
```
Differ from a groupBy? (other than adding a sprintf on top of the results?)

**Comment by gianm** [comment]
One difference is that if Druid can treat that as a single column then we can do topNs on it.

Another difference is that we can filter on it. Even for simple stuff like "concat" it's annoying to write a filter without this functionality. You have to translate `WHERE CONCAT(a, b) = "foo"` to `WHERE (a = "" AND b = "foo") OR (a = "f" AND b = "oo") OR (a = "fo" AND b = "o") OR (a = "foo" AND b = "")`. For more complex functions it's not in general feasible to translate them to boolean filters.

IMO this feature is not super useful if it doesn't work with stuff like topNs and filters, but it really should.

**Comment by vogievetsky** [comment]
@drcrallen I actually started implementing this in Plywood where plywood would issue a groupBy and then do the post processing it became hard to make all the possible queries that should work function with that workaround.

for example let's say the user sorts lexicographically on the derived dimension

Also I know I just named CONCAT() but another interesting function to implement would be [coalesce](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#function_coalesce) so you could do a group by on `COALESCE(`city`, `region`, `country`) AS "location"`

**Comment by vogievetsky** [comment]
Obviously (you know me) I would love to have a JS function that I can prototype / gap fill with that takes multiple inputs:

```
"dimension": {    
  "outputName": "place",
  "type": "multi-javasctipt",  
  "args": [
    "city",
    "region",
    "country"    
  ],
  "fn": "function(a,b,c) { return a || b || c; }"
}
```

in fact the JS functionality alone would make me happier than a pup with two tails.

**Comment by drcrallen** [comment]
So right now we have the following capabilities regarding dimensionality of the data:

1. Project a single dimension onto another dimension basis (single-dimension lookups which are many-to-one or one-to-one).
2. Use combinations of dimension values. (group-by)

This ask, if I'm reading the discussion correctly, is to allow more flexibility along the lines of 1 by allowing a lookup (or some other dimension-function kind of feature) function's domain to have more than one dimension as input.

What this is NOT asking is to contain multiple values (one-to-many or many-to-many) in the range.

Is that accurate?

If so I think that's a reasonable ask so long as the use cases are reducing (or maintaining) overall datasource dimension value cardinality (ex: you can't get more rows out than are in the datasource)

**Comment by navis** [comment]
we are using combination of string-math-expr(
https://github.com/druid-io/druid/pull/2836) and virtual column (
https://github.com/druid-io/druid/pull/2511) to address this kind of issue.
It looks something like "virtualColumns": [{"type": "expr", "expression":
"datediff(start, end)", "output": "time_diff"}], for example.


2016년 5월 20일 금요일, Charles Allen<notifications@github.com>님이 작성한 메시지:

**Comment by vogievetsky** [comment]
This is possible now via http://druid.io/docs/latest/misc/math-expr.html
