### ISSUE TITLE
[Proposal] Skip writing value lengths in the indexes

### ISSUE THREAD

**Issue by pjain1** [apache/incubator-druid#3070]
Druid uses [format](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/data/GenericIndexed.java#L36) described in GenericIndexed class to serialize indexes. While writing index values, Druid writes the length of values in bytes before each value. 

However, this may be skipped as end offsets of each serialized value is already written before the values are stored. This can lead to savings of (4 bytes \* number of values in the index) for each index in the final segment. Some examples of GenericIndexed index are for writing Dictionary values, corresponding bitmaps etc. 

Corresponding PR for discussion - https://github.com/druid-io/druid/pull/3069

**Comment by navis** [comment]
I've also did this once but found the difference was not big enough (~5%) to justify format inconsistency. I'm good on this change because we don't have any product cluster yet but it seemed hard to accepted for others.
