### ISSUE TITLE
Add better checksumming information

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3150]
Right now there isn't any real consideration within druid regarding data integrity. If segments are corrupted it can go undetected for an indefinite amount of time.

This ask is to have checksum information propagated with segments so that the data integrity can be evaluated.

**Comment by xvrl** [comment]
@drcrallen what kind of corruptions are you trying to prevent with checksums? Currently segment files are packaged in a zip archive that will carry some checksum protection against corruption when reading from deep storage.

**Comment by drcrallen** [comment]
Being able to do #3151 would likely require checksumming of some kind.
