### ISSUE TITLE
Expose coordinator loadstatus by datasource as an emitted metric

### ISSUE THREAD

**Issue by michaelschiff** [apache/incubator-druid#3173]
Right now loadstatus (the number of segments left to load until segments that should be loaded in the cluster are available for queries.) is only exposed via the Coordinators HTTP api. Emitting these values as standard coordinator metrics will make them easier to integrate with existing cluster monitoring, instead of having to collect them separately.

**Comment by glasser** [comment]
This should be closed (was fixed years ago by #3176).

**Comment by michaelschiff** [comment]
@glasser yup - closing.
