### ISSUE TITLE
Multi-valued dimensions stored as list of Strings are not ingested properly during batch Ingestion with avro_hadoop

### ISSUE THREAD

**Issue by Digma** [apache/incubator-druid#3210]
Hi,

I am trying to ingest a multi-valued dimension stored as an array of string using the Avro Hadoop Parser.

Here are some of my parser config:

`
"parser" : {
        "type" : "avro_hadoop",
        "parseSpec" : {
          "format": "timeAndDims",
  ...
}
`

 The job finishes successfully but the array is not ingested properly. Empty arrays and arrays of size 1 return correct values however it seems arrays of size larger than 1 produce entries such as "Ljava.lang.String;@550b9e33"

The issue may be fixed by this PR https://github.com/druid-io/druid/pull/2414, although it is not very clear to me at first glance if this will fix the issue.

**Comment by himanshug** [comment]
i think its broken, will give a fix soon.

**Comment by himanshug** [comment]
actually, it seems to be working fine... can you give you provide your avro schema, full druid task indexer json and possibly some sample avro data to reproduce the problem?

**Comment by Digma** [comment]
I cannot unfortunately share the sample I used as it contains user information. I will try to replicate the problem with another datasource and provide you a sample later this week.

However, in the meantime, I can give you a bit more information about the data. The schema of the dimension I am trying to ingest is the following:

```
"type":"record",
"name":"XXXX",
"namespace":"XXXX",
"fields":[
      ....
      {
         "name":"session_status",
         "type":
            {
               "type":"array",
               "items":"string"
            },
         "doc":"Status of the session record"
      },
      ...
```

I tried verifying I could indeed read the field properly from Scala. Using the following code works (rec: GenericRecord) for me:
```
rec.get("session_status").asInstanceOf[GenericData.Array[String]].toList
```
And it returns me the correct values regardless of the number of entries in the array.

**Comment by petit-pois** [comment]
Hi @himanshug, I've managed to reproduce @Digma problem. Basically it seems that druid gives value like `[Ljava.lang.String;@46004d9c` when the data contains at least twice the same list.
```
{"timestamp":1468887263818,"cause_codes":{"array":["A","B"]}}
{"timestamp":1468887299486,"cause_codes":{"array":["A","B"]}}
```
I've attached the sample data and batch job config to reproduce the bug.

[debug_batch_ingest.zip](https://github.com/druid-io/druid/files/374023/debug_batch_ingest.zip)

**Comment by imcecil** [comment]
Could this actually be related to #3344? The above test ingestion is also has useCombiner set to true.

**Comment by gianm** [comment]
It looks like this is the same as #3344.
