### ISSUE TITLE
logging properties should not be printing password

### ISSUE THREAD

**Issue by cywjackson** [apache/incubator-druid#3230]
https://github.com/druid-io/druid/blob/master/services/src/main/java/io/druid/cli/GuiceRunnable.java#L86 should have some masking of password/sensitive properties' values

**Comment by drcrallen** [comment]
Agreed

**Comment by drcrallen** [comment]
Part of this is why `startupLoggingConfig.isLogProperties` exists. You can turn it off to prevent it here.

but it will STILL print it out as part of running an indexing task.

**Comment by drcrallen** [comment]
See https://github.com/druid-io/druid/pull/2464 and https://github.com/druid-io/druid/pull/2452 for related items

**Comment by cywjackson** [comment]
hah, didn't realize there's already a long discussion on this like #2452 . I'd very much like and want logging properties on start, but for sensitive data (url, name, passwd , etc), they should either be masked or don't print it at all. thx @drcrallen
