### ISSUE TITLE
Ability to put historical nodes into maintenance modes - Do not count towards replication

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3247]
This ask is that historical nodes are able to be put into a maintenance mode such that their nodes do not count towards the replication threshold. This allows for scaling tiers down in a more controlled manner.

We occasionally have capacity issues as we scale our cluster such that a lower tier fills up, and upper tiers need to be expanded to accommodate the handoff of realtime indexing tasks while the lower tiers expand. Once this is completed and segments are flowing as expected through the tiers, the "more recent data" tiers need to be shrunk back to normal operating size.

Being able to put a historical node into a state where it doesn't count towards replication would help in this.

**Comment by egor-ryashin** [comment]
Changes:
1. `LoadRule` should ignore such nodes during assignment.
2. `BalancerStrategy` should prioritize moving segments from such nodes. Priority can be specified by a number from 1 to 10. IE `maitenanceModeSegmentsPriority=7` means 70% of `maxSegmentsToMove` segments will be balanced from nodes in maintenance mode, only 30% of segments will be balanced from general nodes.
3. HTTP endpoint `/druid/coordinator/v1/maintenance` will provide json array of `host:port` elements, which can be created/modified using POST request.

If nobody is working on it, I'm gonna take it.

**Comment by egor-ryashin** [comment]
Also, parameters can be changed using Coordinator console:
![image](https://user-images.githubusercontent.com/14215045/45718663-8713ff00-bba6-11e8-88c0-13dd19b39cbf.png)

**Comment by gianm** [comment]
This was fixed by #6349, I believe.
