### ISSUE TITLE
About autoscaling of middle manager

### ISSUE THREAD

**Issue by billbargens** [apache/incubator-druid#3261]
In official doc(http://druid.io/docs/0.9.1/design/indexing-service.html), you mentioned:

> The Autoscaling mechanisms currently in place are tightly coupled with our deployment infrastructure but the framework should be in place for other implementations. We are highly open to new implementations or extensions of the existing mechanisms. In our own deployments, middle manager nodes are Amazon AWS EC2 nodes and they are provisioned to register themselves in a galaxy environment.

So if I want to enable the autoscaling mechanism, should ”the Amazon AWS EC2“ and ”galaxy registration“ be two requirements?

**Comment by gianm** [comment]
Hey @billbargens, the current autoscaling implementation is EC2-based, but you don't need to use galaxy. You can set any userData you want and your AMI can interpret that however it wants.

fwiw "galaxy" refers to: https://github.com/ning/galaxy

**Comment by billbargens** [comment]
So that still means I must deploy druid on Amazon EC2 nodes?

**Comment by billbargens** [comment]
@gianm So that still means I must deploy druid on Amazon EC2 nodes?
