### ISSUE TITLE
`DataSegment`'s `equals` implementation should do a proper object equals

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3287]
See https://github.com/druid-io/druid/pull/3286 for more information.

The equals method should be correct for object equivalence, and things which need to check equivalence of some sub-portion of the object should do so explicitly.

The `Comparable` interface should be removed from `DataSegment` in favor of explicit comparators/orderings for sub-portions of the object that need comparing.

The `equals` should perform a proper java equals of the fields of the object to allow complete substitution of one object for another if `equals` is true.

**Comment by leventov** [comment]
This issue is not relevant / is already implemented; the current view on how `equals()` should look in `DataSegment` is expressed here: https://github.com/apache/incubator-druid/issues/6358#issuecomment-489102183.
