### ISSUE TITLE
On select performance (with multiple partitions)

### ISSUE THREAD

**Issue by KenjiTakahashi** [apache/incubator-druid#3297]
We've been investigating Druid `select` query performance for some cases where we need to pull a large (hundreds of thousands) number of items from a pretty coarse data (more details can be found at https://groups.google.com/forum/#!topic/druid-user/o_Ex2ygmjAs).

We are ingesting data into DAY segments with 50 partitions each and we can't really reduce the number of partitions much. This will be important :-).

In some tests, we've noticed that filtered queries are significantly faster than unfiltered ones, even though they were constructed to both return exactly the same data.
This felt very odd, so we've decided to go down and do some profiling on Druid's historical server. We've used two different profilers, both yielding very similar results.
The profiles led, unsurprisingly, to the `select` code and the first suspicious thing was that the `lookupName` method at https://github.com/druid-io/druid/blob/druid-0.9.1.1/processing/src/main/java/io/druid/query/select/SelectQueryEngine.java#L135 was called... exactly 50 times the `threshold` set for the query.
Further profiling and debugging has proven that Druid is indeed retrieving `threshold` items from _each_ of the 50 partitions, then merging them together and throwing away the rest. And "the rest" in our case was 98% of the retrieved data.

As I understand, it was done this way, because there seem to be no constraints as to how data in partitions within segment relate to each other. Theoretically, one could, e.g. put a whole day of some metrics into one partition, then put each hour of the rest into separate partitions, all within one DAY segment. Or maybe set partition numbers out of order. Might not make sense, but seems possible, so I guess it should "work as expected".
I guess that different partitions might also reside on different historical instances?

In our case, we've been able to do a quick hack that works for some tests and that moved the query times down from >2 minutes to sub-second, so we see a lot to be gained here.

With all that, I gotta say that I do not have enough expretise in Druid (and on top, I've not programmed Java for years) to think of a good, generic solution to this. That's why I'm writing it down here, hoping for you to be able to point us into right direction.

Tests and profiles were first done on `0.9.1-rc4`. I have re-run the tests later on `0.9.1.1` and no significant changes were observed, so I assume that the conditions above have not changed.

Let me know if I can provide any further information. Thanks in advance for any ideas on how to improve the situation.

**Comment by gianm** [comment]
@KenjiTakahashi, thanks for posting your experience.

From my perspective the problems you pointed out mostly come from the fan out to the processing pool on historicals. Most Druid queries work this way because it works well for aggregations that can be parallelized and then merge. Select doesn't really work well with the parallelize-then-merge strategy due to the ordering restriction. It really begs for something more like "continuous merge". Maybe it would be better for select to run single threaded.

**Comment by navis** [comment]
It's exactly what we want to do with #3292 but not in-progress currently.

**Comment by KenjiTakahashi** [comment]
@navis Care to elaborate a bit? I might be missing something, but looking at the description, I'm not sure how this is relevant. Thanks!

@gianm But even if we run it in single thread, we still don't know from which partitions to get what items, right? E.g. we might get `threshold` items from partition `1`, but then it turns out some of the items we want (are in order) are in partition `3` and some in `7` and we don't know that beforehand. Or do we?

**Comment by navis** [comment]
@KenjiTakahashi #3292 retrieves row count for each segments targeted by a select query, something like
```
"result" : {
   "segmentCounts" : {
     "array_2016-04-09T09:00:00.000+09:00_2016-04-10T09:00:00.000+09:00_2016-05-10T02:31:21.509Z" : 3,
     "array_2016-01-18T00:00:00.000+09:00_2016-01-19T00:00:00.000+09:00_2016-07-05T10:50:43.457+09:00" : 1,
     "array_2016-01-04T00:00:00.000+09:00_2016-01-05T00:00:00.000+09:00_2016-07-05T10:50:43.381+09:00" : 1,
     "array_2016-03-09T09:00:00.000+09:00_2016-03-10T09:00:00.000+09:00_2016-03-24T06:08:49.668Z" : 3,
     "array_2016-01-11T00:00:00.000+09:00_2016-01-12T00:00:00.000+09:00_2016-07-05T10:50:43.436+09:00" : 1
   },
   "totalCount" : 9
```

So if we should acquire 3 rows, we can set just the first segment id, not using whole interval. Currently it's not accepting paging spec but we can support that with some more works, I believe. This process even can be automated in druid broker, that we are testing on select query with union datasource.

**Comment by gianm** [comment]
@KenjiTakahashi Honestly I'm thinking more about the case where you don't care about ordering or necessarily want a threshold – when you're trying to pull out some (or even all) data matching a filter in whatever order you get it. In that case you can read from partitions one at a time, just going to the next one when you exhaust an earlier one.

If you do care about the ordering, probably what makes sense there is reading the time columns from all applicable partitions first – to figure out which rows you're going to include – and then once you've picked the rows, read all the other columns.

**Comment by KenjiTakahashi** [comment]
@navis I see. Would that work per partition (i.e. within segment) as well? Theoretically, it could, as select code does not seem to differentiate between segments and partitions at all.

@gianm Oh, OK. If we don't care about ordering then it would indeed work. Maybe in specific cases it would be possible to store data in a way that comes out as "pre-sorted", given that we know in what order partitions will be read. Or, if the data is partitioned on dimension, maybe use the method @navis proposed to "cut" `threshold/num_of_partitions` items from each partition and merge client-side.

I'm afraid that reading time from everything would still take significant amount of time. It would be some improvement, but we're looking for as much as possible here :-).
