### ISSUE TITLE
Support Min/Max of timestamp

### ISSUE THREAD

**Issue by sirpkt** [apache/incubator-druid#3298]
I have a need to know when the source input row of the given aggregated value starts and ends.

For example with following data consisted of timestamp, dimension, and metric value, 

```
2015-07-28T01:00:00.000Z  A  1
2015-07-28T02:00:00.000Z  A  1
2015-07-28T03:00:00.000Z  A  1
2015-07-28T04:00:00.000Z  B  1
2015-07-28T05:00:00.000Z  A  1
2015-07-28T06:00:00.000Z  B  1
2015-07-28T07:00:00.000Z  C  1
2015-07-28T08:00:00.000Z  C  1
2015-07-28T09:00:00.000Z  A  1
2015-07-28T10:00:00.000Z  A  1
```

What I want to know is aggregation(e.g. sum) of metric value and start/end time of corresponding input data like followings 

```
2015-07-28T00:00:00.000Z A 5 2015-07-28T01:00:00.000Z 2015-07-28T10:00:00.000Z
2015-07-28T00:00:00.000Z B 2 2015-07-28T04:00:00.000Z 2015-07-28T06:00:00.000Z
2015-07-28T00:00:00.000Z C 2 2015-07-28T07:00:00.000Z 2015-07-28T08:00:00.000Z
```

Because existing `__time` column has only the same granularity as query granularity,
I think It need to add min/max aggregator for timestamp column.
It targets not just for timestamp column, but also for any columns whose type are Timestamp, DateTime, or string representation of Timestamp.

I made an extension to support this and I'm going to PR soon.
Any comments, please.

**Comment by gianm** [comment]
@sirpkt, use case makes sense, thanks for the explanation.

I wonder if being able to apply extractionFns at ingestion time (and, I guess, extractionFns being able to return longs) would remove the need for time-specific aggregators. Something like InputRow transformers. Then you could use a timestamp-parsing extractionFn to generate a long and feed that into a regular longMax/longMin aggregator.

**Comment by sirpkt** [comment]
@gianm Thank you for the comment.
You're right. I can get the same value with your suggestion.
But, someones do not like to see long value as a result and feel inconvenient to convert that long to timestamp.
I don't think what I did is the best solution because it shows timestamp value only with group by query as internal data type is still long, 
and it would be best if timestamp data type is supported.
