### ISSUE TITLE
druid.historical.cache.numBackgroundThreads documentation

### ISSUE THREAD

**Issue by benwck** [apache/incubator-druid#3313]
See:
https://github.com/druid-io/druid/pull/936
and https://groups.google.com/forum/#!topic/druid-user/WC8Vo0a3UK0

druid.historical.cache.numBackgroundThreads need some documentation considering it is really useful !

Thanks,
Ben

**Comment by drcrallen** [comment]
This feature actually needs more testing. We encountered some buffer clobbering when we tested it out under certain configurations.
