### ISSUE TITLE
Add "pailer" type functionality to overlord console

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3334]
[Mesos](http://mesos.apache.org/) has a really cool [pailer](https://github.com/apache/mesos/blob/1.0.0/src/webui/master/static/js/jquery.pailer.js) used to handle their task logs from the master console. It would be awesome if we could borrow that functionality for the druid overlord console. 

The general idea being that the task's logs can be "streamed" to an observer operating in the overlord console.

**Comment by vogievetsky** [comment]
I believe that https://github.com/apache/incubator-druid/pull/7703 addresses this
