### ISSUE TITLE
statsd-emitter - add support for metrics with decimal digits

### ISSUE THREAD

**Issue by sascha-coenen** [apache/incubator-druid#3350]
The statsd documentation states that metric values must be integers (https://github.com/etsy/statsd#concepts  "in general values should be integer")

A few metrics that Druid emits have decimal digits:
- segment/usedPercent
- query/cache/total/hitRate
- query/cache/delta/hitRate

These metrics end up empty in our dashboards (graphite-based and datadog) although Druid emits them correctly (metric values are present when using LoggingEmitter). 

Don't know what the best way to fix this would be. Perhaps one could extend the statsd-config that the statsd-emitter extension uses (via druid.emitter.statsd.dimensionMapPath property) to contain an optional conversion instruction for each metric. For the abovementioned metrics one could multiply by 100 and round to the nearest integer.

**Comment by michaelschiff** [comment]
Hey thanks for pointing this out, these metrics are missing from our dashboards as well.

Right now the StatsDEmitter converts everything to long
```
switch (metricType) {
          case count:
            statsd.count(fullName, value.longValue());
            break;
          case timer:
            statsd.time(fullName, value.longValue());
            break;
          case gauge:
            statsd.gauge(fullName, value.longValue());
            break;
        }
```

where value is a Number.  If 0 <= value < 1 then this will round down to 0, producing the empty metrics we've observed.  I think your suggestion makes the most sense: for metrics whose value is between 0 and 1 we need to convert to a 0-100 range, and then round to nearest integer.

**Comment by knepperjm** [comment]
What protocol is druid statsd emitter attempting to send metrics over?  udp/tcp?

**Comment by michaelschiff** [comment]
It uses the java statsd client implementation NonBlockingStatsDClient, which sends over UDP (source for this can be found here https://github.com/tim-group/java-statsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java)

**Comment by knepperjm** [comment]
Thanks @michaelschiff for the quick response. I can see my measurements in influxdb, but no data is populated this is my telegraf config.  Any suggestions?  I'm wondering if "clustering only" for the write consistency implies that it's only for clustered influxdb clusters.  I have a monolithic /standalone influxdb node?

**Comment by michaelschiff** [comment]
@knepperjm sorry, I'm not following.  I take it you are using the statsd-emitter to send metrics through a StatsD server into InfluxDB (via telegraf)? Not sure what you mean that you can see measurements in InfluxDB but don't see data populated.  I don't have any first-hand experience with InfluxDB, so I apologize if this isn't super helpful.
