### ISSUE TITLE
segment-balancer - infinite cycle

### ISSUE THREAD

**Issue by sascha-coenen** [apache/incubator-druid#3354]
Druid 0.9.1.1 seems to have an issue balancing segments. 
We have two separate clusters setup, one with four nodes and a single tier and one with 3 nodes in a hot tier and 2 nodes in a cold tier. Both clusters do NOT have any data flowing into them and are also not dropping any segments. So without any data-movement and without any dropRules to come into effect, the segment-distribution should eventually converge to a steady-state but instead segments are continuously moved from one node to another and then back again.

I attached a coordinator log and also two "timeseries" of coordinator snapshots that show how the cluster oscilates between a perfectly balanced state and a slightly unbalanced one. 

It seems to us that this behaviour might be a threshold issue, meaning that the balancer is too sensitive about segment-imbalances and advises re-distributions even when this would only lead to another imbalance according to its sensitivity. Might be that the sensitivity for triggering rebalancing also needs to take cluster size into account.

![druid-test-segment-distribution-snapshot-11](https://cloud.githubusercontent.com/assets/1635350/17597235/387ba88e-5ff5-11e6-9114-5dd8cfb72b85.png)
![druid-test-segment-distribution-snapshot-10](https://cloud.githubusercontent.com/assets/1635350/17597234/387b8eda-5ff5-11e6-9209-e2db90d34248.png)
![druid-test-segment-distribution-snapshot-9](https://cloud.githubusercontent.com/assets/1635350/17597237/387c0d56-5ff5-11e6-8386-7cfbcdb2beba.png)
![druid-test-segment-distribution-snapshot-8](https://cloud.githubusercontent.com/assets/1635350/17597236/387bcbb6-5ff5-11e6-80e3-8878dc9b5970.png)
![druid-test-segment-distribution-snapshot-7](https://cloud.githubusercontent.com/assets/1635350/17597232/387879d4-5ff5-11e6-8dda-7b61adc1e0f6.png)
![druid-test-segment-distribution-snapshot-6](https://cloud.githubusercontent.com/assets/1635350/17597233/387b8962-5ff5-11e6-8627-77ed69259ad4.png)
![druid-test-segment-distribution-snapshot-5](https://cloud.githubusercontent.com/assets/1635350/17597238/389166ba-5ff5-11e6-8fdb-08af2d7646b5.png)
![druid-test-segment-distribution-snapshot-4](https://cloud.githubusercontent.com/assets/1635350/17597243/38987766-5ff5-11e6-8262-96a0748923e0.png)
![druid-test-segment-distribution-snapshot-3](https://cloud.githubusercontent.com/assets/1635350/17597240/3893fa56-5ff5-11e6-95a4-63910ae3e23e.png)
![druid-test-segment-distribution-snapshot-2](https://cloud.githubusercontent.com/assets/1635350/17597242/3896dc44-5ff5-11e6-9a3a-51d1742a1282.png)
![druid-test-segment-distribution-snapshot-1](https://cloud.githubusercontent.com/assets/1635350/17597241/38942288-5ff5-11e6-8ef6-5b3c95632c9f.png)
![druid-stage-segment-distribution-snapshot-11](https://cloud.githubusercontent.com/assets/1635350/17597239/3893a236-5ff5-11e6-9bfd-3354535583d9.png)
![druid-stage-segment-distribution-snapshot-10](https://cloud.githubusercontent.com/assets/1635350/17597244/38a9950a-5ff5-11e6-9209-d5145269a368.png)
![druid-stage-segment-distribution-snapshot-9](https://cloud.githubusercontent.com/assets/1635350/17597245/38aab62e-5ff5-11e6-8f4e-4d79d7c4c9bf.png)
![druid-stage-segment-distribution-snapshot-8](https://cloud.githubusercontent.com/assets/1635350/17597249/38b35eb4-5ff5-11e6-9319-3bc17e7287fd.png)
![druid-stage-segment-distribution-snapshot-7](https://cloud.githubusercontent.com/assets/1635350/17597248/38b21e28-5ff5-11e6-87f7-84a0bdfb5a77.png)
![druid-stage-segment-distribution-snapshot-6](https://cloud.githubusercontent.com/assets/1635350/17597247/38b07a0a-5ff5-11e6-9bd6-f3bc5d3db53b.png)
![druid-stage-segment-distribution-snapshot-5](https://cloud.githubusercontent.com/assets/1635350/17597246/38b0357c-5ff5-11e6-980a-7d27c70f1b12.png)
![druid-stage-segment-distribution-snapshot-4](https://cloud.githubusercontent.com/assets/1635350/17597250/38c2af4a-5ff5-11e6-8d20-e5468532ae79.png)
![druid-stage-segment-distribution-snapshot-3](https://cloud.githubusercontent.com/assets/1635350/17597251/38c3332a-5ff5-11e6-9740-c8b0750d2780.png)
![druid-stage-segment-distribution-snapshot-2](https://cloud.githubusercontent.com/assets/1635350/17597253/38c8a74c-5ff5-11e6-8b0a-0a6d4555878e.png)
![druid-stage-segment-distribution-snapshot-1](https://cloud.githubusercontent.com/assets/1635350/17597252/38c83dde-5ff5-11e6-9d56-f06117347e6f.png)
[druid-segment-loading-cycle-issue-coordinator-logs.txt](https://github.com/druid-io/druid/files/413757/druid-segment-loading-cycle-issue-coordinator-logs.txt)

**Comment by fjy** [comment]
This is a known day-1 issue

**Comment by sascha-coenen** [comment]
what is a "day-1 issue" ?

**Comment by nishantmonu51** [comment]
there has been some related work to add a steady state here - https://github.com/druid-io/druid/pull/2806

**Comment by nishantmonu51** [comment]
as a workaround, you can throttle the segment movement across nodes by setting maxSegmentsToMove to a very low value.

**Comment by sascha-coenen** [comment]
Thanks Nishant for your suggestion. 
I looked at #2806 and read that people are concerned about the asymptotic complexity of the algorithm proposed there.
Looking at the metamarkets blog post about the new cost function, I liked how mathematical these guys were about defining the cost function, but I think it might be missing a piece.

In the context of machine learning, the common paradim is:

optimization objective = cost function + regularization term

Could it be that the current balancer is missing the regularization term?
Usually, the cost function complexity grows linearly with the problem size but the regularization term has a constant complexity as it penalizes the parameters used in the cost function and is therefore independent of the number of datapoints a cost function iterates over.

In the concrete case of the balancer the regularization term could quantify the cost of executing the segment movements to counterbalance the benefit of moving them which is modeled by the cost function.
