### ISSUE TITLE
[QTL] Return key as well as value

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3367]
A common request is the ability to return both the lookup key as well as the lookup value for injective lookups. This feature request is to have a way to do this natively without resorting to a group-by query.

**Comment by drcrallen** [comment]
See https://groups.google.com/d/msg/druid-user/PDYW2TjOaAc/Q29y1Z7JAwAJ for related discussion

**Comment by gianm** [comment]
One possible solution: https://github.com/druid-io/druid/issues/3414#issuecomment-243818758
