### ISSUE TITLE
Better handle misbehaving query nodes

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3449]
If one historical node is misbehaving due to bad hardware, or a rare bug in software which renders on a single node, then the entire query pipeline can get shutdown.

This ask is that the query pipeline in general be improved to be better aware of bad nodes it is trying to communicate to.

**Comment by maxl0rd** [comment]
👍

**Comment by fjy** [comment]
I've spoken about this before: https://www.infoq.com/presentations/data-integrity-distributed-systems

The real solution is that at some point we need tied requests in Druid

**Comment by maxl0rd** [comment]
I looked into this a little bit today. It seems like if a DruidClient were to meter and publish its error rate, then it would unlock end user-written balancer strategies that take error rate into account.

**Comment by drcrallen** [comment]
@fjy changed title a bit
