### ISSUE TITLE
Force shutdown Kafka supervisor

### ISSUE THREAD

**Issue by pjain1** [apache/incubator-druid#3496]
I think it will be good to have an HTTP endpoint to force shutdown supervisor which will force kill all the running tasks. Can be helpful while experimenting with new Kafka indexing service and during initial set up.

**Comment by dclim** [comment]
@pjain1 if #3484 is approved, you should be able to use the /reset endpoint followed immediately by a /shutdown to accomplish the force kill of running tasks and shutting down of the supervisor (if you're okay with the metadata being cleared out also)
