### ISSUE TITLE
Don't copy twice when moving bytes from InputStream to ByteBuffer/Channel

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#3561]
This question is raised here: https://github.com/metamx/java-util/pull/46#r77991157

Occurrence in java-util: https://github.com/metamx/java-util/blob/3c7b49c91ae178825965694111ab846d459c0d7c/src/main/java/com/metamx/common/io/smoosh/FileSmoosher.java#L301

There are some occurrences of this pattern in Druid: https://github.com/druid-io/druid/search?utf8=%E2%9C%93&q=ByteStreams.copy%28Channels.newChannel

This task is blocked until java-util is merged into Druid.

/cc @cheddar

**Comment by Shimi** [comment]
@leventov maybe this one is not relevant anymore?
I see 0 occurrences here
https://github.com/apache/incubator-druid/search?utf8=%E2%9C%93&q=ByteStreams.copy%28Channels.newChannel
