### ISSUE TITLE
can not select data in second segment

### ISSUE THREAD

**Issue by chencunyang1** [apache/incubator-druid#3618]
there are many segment in a day like 
segmentid[0]:"ywgz_2016-10-14T00:00:00.000+08:00_2016-10-15T00:00:00.000+08:00_2016-10-17T12:44:15.445+08:00"
segmentid[1]:"ywgz_2016-10-14T00:00:00.000+08:00_2016-10-15T00:00:00.000+08:00_2016-10-17T12:44:15.445+08:00_1"
segmentid[2]:"ywgz_2016-10-14T00:00:00.000+08:00_2016-10-15T00:00:00.000+08:00_2016-10-17T12:44:15.445+08:00_2"
when i select in second segment:
entry query--{"queryType":"select","dataSource":"ywgz","metrics":[],"pagingSpec":{"pagingIdentifiers":{"**ywgz_2016-10-14T00:00:00.000+08:00_2016-10-15T00:00:00.000+08:00_2016-10-17T12:44:15.445+08:00_1**":0},"threshold":10},"granularity":"all","dimensions":[],"intervals":["2016-10-14T00:00:00.000+08:00/2016-10-15T00:00:00.000+08:00"],"descending":"false"}

**the result is still in the first segment:**
  "result" : {
    "pagingIdentifiers" : {
      **"ywgz_2016-10-14T00:00:00.000+08:00_2016-10-15T00:00:00.000+08:00_2016-10-17T12:44:15.445+08:00**" : 9
    },...

**Comment by navis** [comment]
I also felt strange on this doing #2480 because LogicalSegment does not provide any partition related information to investigate. Looks critical bug (possibly blocker?).
