### ISSUE TITLE
BUG: MapReduce job is not killed when cancelled a hadoop-index job from overlord api

### ISSUE THREAD

**Issue by hamlet-lee** [apache/incubator-druid#3622]
As I supposed, when we kill a task with:
```
curl --connect-timeout 10 -m 20 -X 'POST' -H 'Content-Type:application/json' -d a=b ${OVERLORD}/druid/indexer/v1/task/${taskid}/shutdown
```
both the running `overlord task` and related `hadoop mapreduce task` should be killed.

But the actual result is:
1. the task on overlord is killed
1. the Yarn Job `is still running`

I think this is a defect.  Because when we intend to kill a ingest task, we want to kill all related running jobs.

Do you agree?
If agreed, maybe I can try to make a fix by registering on JVM Shudown Hook to kill related yarn job.

**Comment by cheddar** [comment]
That seems reasonable to me.

**Comment by niketh** [comment]
@hamlet-lee The thing you might have to keep in mind is to make sure that when the MM shuts down (in the case of a restart/deploy) , you don't want to kill the Yarn Job.

**Comment by hamlet-lee** [comment]
@niketh when the MM shuts down, is the lock for a ingesting datasource released? Although I do not know much, but there seems a lock mechanism. If the MM shuts down and the yarn job still need to keep running, there should be a mechanism to make sure the lock mechanism works and another MM take over the running yarn job related ingest task? If there is not such mechanism I suggest we just kill the related yarn job when MM shutdown. And provide a configuration to disable this mechanism if desired.
