### ISSUE TITLE
QueryableIndexIndexableAdapter.getRows() should return Sequence rather than Iterable

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#3637]
For better or worse currently `Sequence` interface is used in Druid in situations when we need to "iterate, then close something when done". `QueryableIndexIndexableAdapter.getRows()` returns `Iterable` which closes it's resources when `hasNext()` failed, that is unreliable (somebody might just not try to iterate to the end of the iterable).

**Comment by gianm** [comment]
Alternate view: Currently we use Sequence mainly (only?) on the query side of things, and QueryableIndexIndexableAdapter is an indexing side thing. Maybe it makes sense to use Sequences there too but currently we largely don't.

**Comment by leventov** [comment]
Also Sequence is quite heavy-weight and seems to be supposed to be used to iterate/map/filter large objects like segments, subqueries, etc. For Rows maybe another simpler abstraction could be used, something like `CloseableIterable extends Iterable, Closeable`.

**Comment by navis** [comment]
I also thought of removing Sequence several times(even made a patch) but in some micro test comparing MergeSequence and MergeIterable, I've seen the former outperformed the latter. So I just let it go.
