### ISSUE TITLE
Ambari integration ?

### ISSUE THREAD

**Issue by ebuildy** [apache/incubator-druid#3662]
Hi guys,

Just to know if there is an integration with Ambari available? (make installation, configuration and monitoring easier).

Cheers,

**Comment by nishantmonu51** [comment]
@ebuildy, yes, we recently added druid specs for Ambari as part of -  
https://issues.apache.org/jira/browse/AMBARI-17981
will be available in next ambari release.

**Comment by ebuildy** [comment]
Woa fantastic! How can I test it right now? Thanks you
