### ISSUE TITLE
[Proposal] Remove throttling while dropping segments

### ISSUE THREAD

**Issue by niketh** [apache/incubator-druid#3725]
I ran into an issue where we had segments being replicated 5-6 times even though the replication factor was set to 2. This was happening because the "drop" method in LoadRule.java is throttled and some segments could never get deleted. 

I believe this is a bug, the fix for this is fairly straight forward: Do not throttle the "drop" method in LoadRule.

**Comment by cheddar** [comment]
👍  the whole intent of throttling was to limit the amount of network traffic happening in the background to ensure a stable system.  Dropping segments doesn't induce network traffic so shouldn't be throttled.

Really, I don't think there's ever a case where dropping should be throttled.
