### ISSUE TITLE
mysql metadata 0.9.1.1 insert error in pendingSegments table

### ISSUE THREAD

**Issue by fphilippon** [apache/incubator-druid#3739]
Hello,

Druid version : 0.9.1.1
Metadata DB: mysqld (mysqld 10.2.2-MariaDB)

I found weird errors in the overlord logs about an incorrect SQL query for the mysql jdbc driver:
### 
`Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"end", sequence_name, sequence_prev_id, sequence_name_prev_id_sha1, payload) VAL' at line 1 [statement:"INSERT INTO druid_pendingSegments (id, dataSource, created_date, start, "end", sequence_name, sequence_prev_id, sequence_name_prev_id_sha1, payload) VALUES (:id, :dataSource, :created_date, :start, :end, :sequence_name, :sequence_prev_id, :sequence_name_prev_id_sha1, :payload)", located:"INSERT INTO druid_pendingSegments (id, dataSource, created_date, start, "end", sequence_name, sequence_prev_id, sequence_name_prev_id_sha1, payload) VALUES (:id, :dataSource, :created_date, :start, :end, :sequence_name, :sequence_prev_id, :sequence_name_prev_id_sha1, :payload)", rewritten:"INSERT INTO druid_pendingSegments (id, dataSource, created_date, start, "end", sequence_name, sequence_prev_id, sequence_name_prev_id_sha1, payload) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", arguments:{ positional:{}, named:{sequence_prev_id:'',payload:[123, 34, 100, 97, 116, 97, 83, 111, 117, 114, 99, 101, 34, 58, 34, 97, 100, 95, 97, 112, 34, 44, 34, 105, 110, 116, 101, 114, 118, 97, 108, 34, 58, 34, 50, 48, 49, 54, 45, 49, 50, 45, 48, 53, 84, 49, 48, 58, 48, 48, 58, 48, 48, 46, 48, 48, 48, 90, 47, 50, 48, 49, 54, 45, 49, 50, 45, 48, 53, 84, 49, 49, 58, 48, 48, 58, 48, 48, 46, 48, 48, 48, 90, 34, 44, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 34, 50, 48, 49, 54, 45, 49, 50, 45, 48, 53, 84, 49, 48, 58, 48, 48, 58, 48, 52, 46, 54, 54, 50, 90, 34, 44, 34, 115, 104, 97, 114, 100, 83, 112, 101, 99, 34, 58, 123, 34, 116, 121, 112, 101, 34, 58, 34, 110, 117, 109, 98, 101, 114, 101, 100, 34, 44, 34, 112, 97, 114, 116, 105, 116, 105, 111, 110, 78, 117, 109, 34, 58, 52, 44, 34, 112, 97, 114, 116, 105, 116, 105, 111, 110, 115, 34, 58, 48, 125, 125],start:'2016-12-05T10:00:00.000Z',end:'2016-12-05T11:00:00.000Z',id:'ad_ap_2016-12-05T10:00:00.000Z_2016-12-05T11:00:00.000Z_2016-12-05T10:00:04.662Z_4',created_date:'2016-12-05T10:13:42.085Z',dataSource:'ad_ap',sequence_name:'index_kafka_ad_ap_5abe22c71b3aebc_1',sequence_name_prev_id_sha1:'2EECECAB2BBA7974D9E47FCA6C2E8A61E51EC4AC'}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1334) ~[jdbi-2.63.1.jar:2.63.1]
	at org.skife.jdbi.v2.Update.execute(Update.java:56) ~[jdbi-2.63.1.jar:2.63.1]
	at io.druid.metadata.IndexerSQLMetadataStorageCoordinator$3.inTransaction(IndexerSQLMetadataStorageCoordinator.java:555) ~[druid-server-0.9.1.1.jar:0.9.1.1]
	at io.druid.metadata.IndexerSQLMetadataStorageCoordinator$3.inTransaction(IndexerSQLMetadataStorageCoordinator.java:376) ~[druid-server-0.9.1.1.jar:0.9.1.1]`

We have tons of segments on our druid cluster, running since months without any problems and this error appeared 2 times in last 2 days.

Thanks for your help guys!

**Comment by kosii** [comment]
Hi,

I'm @fphilippon's colleague. The error occurred again this morning. Any idea why is this happening?
