### ISSUE TITLE
Allow approximate groupBys by following your inner topN

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#3749]
TopNs are fast because they push down `limit: 1000` to all the compute nodes and then merge the partial results, resort, and apply the requested limit. This produces approximate but mostly good results on 'real-world' data.

I think the same exact idea can be applied to groupBys also. There already is a limit pushdown optimization that needs to happen with GroupBy (https://github.com/druid-io/druid/issues/1872) once that work is done this should be straightforward.

The API would add a flag to the groupBy query (or its context). Maybe also allow the user to configure the pushed down expanded-limit.

Advantages:
- Unify query API - now users need not learn topNs as they would be unnecessary. This makes it easier for people writing tools that made druid queries and for new users.
- Facilitates multi-dimensional topNs
- Not much work on top of https://github.com/druid-io/druid/issues/1872 (if I understand correctly)

**Comment by gianm** [comment]
Maybe a context flag like `"limitApproximate":"true"`. On top of #1872 this should be doable by enabling the limit push down always when that flag is set, rather than only when pushdown is lossless.
