### ISSUE TITLE
Allow handling of multiple data sources with single Kafka Indexing Service task

### ISSUE THREAD

**Issue by jasoncheow** [apache/incubator-druid#3752]
Currently, each Kafka Indexing Service task can only handle data from 1 Kafka topic and index it to 1 data source. This requires multiple workers, one for each data source, that will continually be running.

If the volume of data is not large, it'll be advantageous if there are options for a task to map N topics to N data sources. This way, 1 worker can be used for multiple data sources.

**Comment by gianm** [comment]
Right now Tasks are fundamentally single-datasource beasts, so making a change like this would mean addressing that first. #3482 is going in that direction so that should help with this one too.
