### ISSUE TITLE
Race condition in KafkaLookupExtractorFactory

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#3772]
https://github.com/druid-io/druid/pull/3403#discussion_r88312768

FYI @gvsmirnov: just creating an issue in order not to forget about it

**Comment by karthikbhat13** [comment]
Hey @leventov, Is this issue for rolling back to `!future.isDone() && !future.cancel(true) && !future.isDone()`? or find a more permanent solution?
Thanks.

**Comment by leventov** [comment]
I would say - just remove `if` and simply cancel the future. See the linked thread.
