### ISSUE TITLE
Search query slow with filter

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#3775]
If the following are true then a search query on a QueryableIndex can be slower than expected.

- There is a filter
- The search dimension is high cardinality
- Many values of the search dimension match the query

This is because for QueryableIndex, the search query uses an index-based algorithm that does a bitmap intersection op for every value of the search dimension that matches the query _before_ applying the filter. This can be more expensive than the cursor-based algorithm that applies the filter first, especially if the filter is very selective or if the search dimension is high cardinality.

Ideally the search query should use some heuristics to choose between the index-only vs. cursor-based algorithms, or at least provide a context flag to let you choose which one.

See also https://groups.google.com/d/topic/druid-user/gjhh3rfdrUw/discussion.

**Comment by jihoonson** [comment]
Sounds interesting! I'm working on it.

**Comment by b-slim** [comment]
@gian not sure why we need some heuristics, i think if the query contains a filter we should apply the filters first.

**Comment by gianm** [comment]
We always use the filter bitmap, the only question is do we intersect it with the bitmaps in the indexes of the search dimension (index-based algorithm), or do we use it to scan through the rows of the search dimension (cursor-based algorithm). Which one is faster would depend on the number of rows that match the filter and on the cardinality of the search dimensions.
