### ISSUE TITLE
Coordinator rules console visually overflows with > 4 tiers

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#3875]
Screenshot, note the glitch after "+ d replicant":

![image](https://cloud.githubusercontent.com/assets/1214075/22191710/74fff30a-e0e2-11e6-9693-3d41c9d1844e.png)

**Comment by vogievetsky** [comment]
Love the milestone game!

New console to the rescue.

![image](https://user-images.githubusercontent.com/177816/65644982-b1af4980-dfaa-11e9-8498-da19b3c5696e.png)

Solved :-D
