### ISSUE TITLE
[Proposal] define a RPC  protocol for querying data, support apache Arrow as data exchange interface

### ISSUE THREAD

**Issue by weijietong** [apache/incubator-druid#3891]
In our scenario , a query of one Druid segment  matched 400million rows from 900 million rows took 79ms to query out the matched data ,but took 19s to serialize all the data into json format, also with a high cpu load.Though json has a better readability, it's unacceptable for large data query.

I also mentioned that some other ones expected a binary transfer protocol ,as http is not good at high speed data transfer.

I will try to define a RPC protocol to substitute the http protocol . Also substitute the json output data format with apache ``` Arrow ``` ,as the output data to be expressed as ```ValueVector``` ,it doesn't need to be serialized or deserialized. Most of other systems like``` Kudu, Spark,Drill ``` are collaborating to support ```Arrow```  as system exchange data standard.

I think a RPC and ```Arrow``` combination should be a candidate or a new interactive standard for the ```broker ,history ,realtime  ```  nodes to exchange data.

**Comment by b-slim** [comment]
@weijietong have you tried using the Smile format ?

**Comment by fjy** [comment]
@jihoonson agree. I think we've known for awhile that for larger result sets, serde time can be the bottleneck. It'd be nice if we had a binary format, especially given recent changes to support larger result sets, but we have to look more into Arrow.

**Comment by drcrallen** [comment]
Note that druid does support [SMILE](https://en.wikipedia.org/wiki/Smile_(data_interchange_format\)) for most http endpoints.

**Comment by drcrallen** [comment]
Another large bottleneck is serialization for cache. (just FYI)

**Comment by himanshug** [comment]
I don't think yet that HTTP is a problem and RPC is necessary. With HTTP you can totally transfer binary data , connections are persistent and there is great tooling available to work with HTTP. 
More interestingly with HTTP 2.0 , it is gonna be even better and would allow parallel requests on same connection.

I can understand the sentiment around Json though and if Smile is also not good enough then adding another format is OK.

**Comment by weijietong** [comment]
Except avoiding the serde bottleneck,Arrow stores data as off heap DirectByteBuffer. By leveraging NIO RPC , we can achieve sending data with zero copy memory performance , that is what Servelet does not support .  

btw I want to know how to enable Smile binary json format at current Druid version.

I agree that http and json is still useful for most common case. Substituting seems rash.
