### ISSUE TITLE
TimeBoundary problems with incomplete segments

### ISSUE THREAD

**Issue by fjy** [apache/incubator-druid#391]
Let's say we have segments from 12-02T00 to 12-02T01, 12-02T01 to 12-02T02 ... 12-02T11 to 12-02T12 on version 1
and a segment , 12-02T00 to 12-03T00 on version 0

Issuing a time boundary query will cause the VIT to look up and correctly return segments:
12-02T00 to 12-02T01, 12-02T01 to 12-02T02 ... 12-02T11 to 12-02T12, 12-02T12 to 12-03T00

After time boundary filtering, we are left to check two segments:  12-02T00 to 12-02T01 and 12-02T12 to 12-03T00

Timeboundary query will pull and merge the first and last timestamps from the timestamp column from each of these segments.

Now if the segment from 12-02T00 to 12-03T00 actually only has data with timestamps 12-02T00, an incorrect max time will be returned.

**Comment by nishantmonu51** [comment]
looks like this is already fixed ? 
TimeBoundaryQueryQueryToolChestTest.testFilterSegments() tests this scenario when there are multiple segments with hourly granularity overlapping segment with a day granularity.
