### ISSUE TITLE
`statsd-emitter` - add option to disable logging errors when mapping is missing

### ISSUE THREAD

**Issue by eyalzek** [apache/incubator-druid#3960]
I enabled `statsd-emitter` which works great, the only problem I have with it is that it pollutes our logs with many errors for missing statsd mapping, coming from here:
https://github.com/druid-io/druid/blob/master/extensions-contrib/statsd-emitter/src/main/java/io/druid/emitter/statsd/StatsDEmitter.java#L123

e.g:

```
February 22nd 2017, 17:41:10.000	2017-02-22T16:41:10,731 ERROR [Coordinator-Exec--0] io.druid.emitter.statsd.StatsDEmitter - Metric=[segment/count] has no StatsD type mapping
February 22nd 2017, 17:41:00.000	2017-02-22T16:41:00,390 ERROR [MonitorScheduler-0] io.druid.emitter.statsd.StatsDEmitter - Metric=[jetty/numOpenConnections] has no StatsD type mapping
February 22nd 2017, 17:40:49.000	2017-02-22T16:40:49,507 ERROR [MonitorScheduler-0] io.druid.emitter.statsd.StatsDEmitter - Metric=[jetty/numOpenConnections] has no StatsD type mapping
February 22nd 2017, 17:40:40.000	2017-02-22T16:40:40,730 ERROR [Coordinator-Exec--0] io.druid.emitter.statsd.StatsDEmitter - Metric=[segment/underReplicated/count] has no StatsD type 
```

about 220 log lines in 15 mins (running 1 node of each druid role). Would be nice to have an option to turn these off.

**Comment by Gkhere** [comment]
Yes, I faced the same problem for graphite too... could you please provide the option of disabling.

**Comment by knepperjm** [comment]
What protocol is druid statsd emitter using?

**Comment by Gkhere** [comment]
I haven't used statsd I have used graphite emitter..

With regards,
Gopi kiran
