### ISSUE TITLE
a problem of post large quantities of data to lookups

### ISSUE THREAD

**Issue by mjaow** [apache/incubator-druid#3996]
hi,when i post large quantities of data to /druid/coordinator/v1/lookups,i found it would serialize the data and insert it into druid_config (my metastorage table).while inserting so many data will cause mysql connection reset error.

how can i handle the situation?i don't know the usage of druid_config,can i just delete the code of inserting data into druid_config?

Expect quick reply,Thx

**Comment by gianm** [comment]
@mjaow, what's the reason that you're posting a large amount of data to the lookup config endpoint? It's not really meant to store a lot of data; it does support in-line lookups but that's meant for small ones. If you have a big lookup file it would work better to put it on s3 or http and reference that file from your lookup definition.

**Comment by mjaow** [comment]
@gianm  my teamates use hdfs for storage not s3,so can i just use hdfs and reference the file from my lookup?

**Comment by gianm** [comment]
I think HDFS should work for lookup files if you have the
druid-hdfs-storage extension loaded.

**Comment by nlokare** [comment]
@gianm I've had success using lookups in the past, but as I've added more to the system both in count and lookup types, I am getting `Unknown error updating configuration` errors when attempting to POST lookups to my coordinator node.

You mentioned storing lookups in S3 and then referencing these from the lookup definition. I can't seem to find any documentation for doing so? I am storing our lookups in GCS (along with our segments for deep storage, etc.) and was hoping you could help.

Thanks.

**Comment by nlokare** [comment]
@gianm What would you recommened is the max size of a lookup map? My largest lookup is about 10MB.

**Comment by mjaow** [comment]
@nlokare i use hdfs and reference these path from lookup.It indeed work.S3 can surely work

**Comment by gianm** [comment]
@nlokare you mean the "inline" maps? I would probably avoid them for anything larger than 100KB or so, but it should work higher than that (as you say you have 10MB maps). Certainly, storing them in files is more scalable than specifying them inline.

Yes http://druid.io/docs/latest/development/extensions-core/lookups-cached-global.html is the right place to look. I'm not sure if GCS lookups are supported though. I know S3 and HDFS are. You might be able to get GCS to work if you also include `google-extensions` which is a new community extension for Druid 0.10.

**Comment by nlokare** [comment]
@gianm Not inline, I've been posting various lookups to the coordinator but they are not starting to fail with the error message I shared above.

When configuring the `cachedNamespace` lookup, do I still send as the body in a request to the coordinator? I can see that lookup but when I query for them, it doesn't seem to be working. I have some sample code below.

I send this to coordinator (will be using GCS in production):
```
{
	"account_lookup": {
		"type": "cachedNamespace",
		"extractionNamespace": {
			"uri": "file:/Users/neil/Documents/accounts_lookup.txt",
	    	         "namespaceParseSpec": {
	        	      "format": "simpleJson"
			}	
		},
		"pollPeriod": "PT1M"
	}
}
```

which is a file that looks like
```
{"1475837": "{\"id\": \"1475837\", \"name\": \"Test Account 1\"}"}
{"1475836": "{\"id\": \"1475836\", \"name\": \"Test Account 2\"}"}
```

My lookup on the query is specified like this:
```
{
            'type': 'registeredLookup',
            'lookup': 'account_lookup',
            'retainMissingValue': True,
            'dimension': 'account_id',
            'outputName': 'account'
}
```
Unfortunately, it doesn't appear to be returning the value from the lookup.

**Comment by nlokare** [comment]
@gianm I was able to get working lookups on query with a `cachedNamespace` with a file saved locally. No luck using GCS.
