### ISSUE TITLE
MiddleManager fails to remove a task entry from Zookeeper, that leads to a stuck task entry

### ISSUE THREAD

**Issue by egor-ryashin** [apache/incubator-druid#4008]
If MiddleManager fails to remove a task entry from Zookeeper (ZK is unavailable, for example) here:
_io/druid/indexing/worker/WorkerTaskMonitor.java:400_
then it doesn't try afterwards.
That leads to a invalid task entry. The task doesn't exist nor it can't be killed manually which is a waste of resources and impedes AutoScaler operations.

There should be a retry until the ZK entry removal is successful.

Here is a log shows we got an exception during the removal request:
> 11	
> <142>1 2017-02-28T21:27:34.351Z [c="io.druid.indexing.overlord.TaskRunnerUtils" t="forking-task-runner-5"] Task [index_2017-02-27T11:00:00.000Z_2017-02-27T12:00:00.000Z_2017-02-28T17:37:13.361Z] status changed to [FAILED].
> 12	
> <142>1 2017-02-28T21:27:34.352Z [c="io.druid.indexing.overlord.ForkingTaskRunner" t="forking-task-runner-5"] Removing task directory: /mnt/persistent/task/index_2017-02-27T11:00:00.000Z_2017-02-27T12:00:00.000Z_2017-02-28T17:37:13.361Z
> 13	
> <139>1 2017-02-28T21:51:58.420Z [c="io.druid.indexing.worker.WorkerTaskMonitor" t="WorkerTaskMonitor"] Failed to update task announcement: {class=io.druid.indexing.worker.WorkerTaskMonitor, exceptionType=class org.apache.curator.CuratorConnectionLossException, exceptionMessage=KeeperErrorCode = ConnectionLoss, task=index_2017-02-27T11:00:00.000Z_2017-02-27T12:00:00.000Z_2017-02-28T17:37:13.361Z}

Afterwards the task entry is stuck forever.

**Comment by niketh** [comment]
@egor-ryashin In which version of Druid are you seeing this error?
