### ISSUE TITLE
[Proposal] support join query without the data shuffle

### ISSUE THREAD

**Issue by weijietong** [apache/incubator-druid#4040]
## motivation
--- 
Most of the open source projects do not support join query as joining data from different tables needs to shuffle data across the cluster . As shuffling is a heavy work for the projects to do so , most of the supporting join feature projects utilize the distributed memory calculating technology to shuffle the data ,has a low reading latency, let the project be more complex and less stable.

To reduce the shuffle work, Google's Spanner has a idea to let joint data stay together , and the open source project CockroachDB following that idea has a join query support but so far not stable to use.  Another fact that support this proposal is that OLAP often follows the star schema :  one fact table and more dimension tables. so a OLAP join query often has a common join condition field from different tables.  According to the Druid's bitmap inverted index feature ,I designed this join query called```LocalJoin``` query.

My work was inspired by two papers: [JoinIndices](http://www.diku.dk/hjemmesider/ansatte/henglein/papers/valduriez1987.pdf) and [Efficient joins with compressed Bitmap indexes](https://www.osti.gov/scitech/biblio/982896). I have implemented  and extended the last paper for ```LocalJoin```query.The query has the following features.

## query feature
---
* without the heavy data shuffle work
* high query response time
* low memory requirement
* streaming  output of query result
* lazy to materialize the join query result
* push down join query to scan step
* support querying segments from different tables and across different time intervals
* support tables from history and realtime nodes

## implementation design
---
First ,for example , I  define three tables :  table 1: ``` user_shop_detail( user_id,shop_item)```  table 2: ```user(user_id, user_name,user_address)``` , table 3: ```user_security(user_id,security_level)```
these three tables follow the OLAP star schema .  

Second , assume a join query to find the shop item coming from the one who has a high security level :  ``` select a.shop_item from user_shop_detail a join user b  join user_security c on a.user_id=b.user_id  , a.user_id=c.user_id where a.user_id='001' and b.user_name='jack' and c.security_level='high'  ```

The given query example sql will be translated to a new Druid query:

```
 {
    "queryType": "localJoin",
    "batchSize": 10,
    "context": null,
    "subSelectQueries": [
        {
            "dataSource": {
                "type": "table",
                "name": "user_shop_detail"
            },
            "granularity": {
                "type": "all"
            },
            "dimensions": [
                {
                    "type": "default",
                    "dimension": "shop_item",
                    "outputName": "shop_item"
                }
            ],
            "metrics": null,
            "jointDimension": "user_id",
            "dimFilter": {
                "type": "selector",
                "dimension": "user_id",
                "value": "001",
                "extractionFn": null
            },
            "querySegmentSpec": {
                "type": "LegacySegmentSpec",
                "intervals": [
                    "2011-01-12T00:00:00.000Z/2011-01-14T00:00:00.000Z"
                ]
            }
        },
        {
            "dataSource": {
                "type": "table",
                "name": "user"
            },
            "granularity": {
                "type": "all"
            },
            "metrics": null,
            "jointDimension": "user_id",
            "dimFilter": {
                "type": "selector",
                "dimension": "user_name",
                "value": "jack",
                "extractionFn": null
            },
            "querySegmentSpec": {
                "type": "LegacySegmentSpec",
                "intervals": [
                    "2011-01-12T00:00:00.000Z/2011-01-14T00:00:00.000Z"
                ]
            }
        },
        {
            "dataSource": {
                "type": "table",
                "name": "user_security"
            },
            "granularity": {
                "type": "all"
            },
            "metrics": null,
            "jointDimension": "user_id",
            "dimFilter": {
                "type": "selector",
                "dimension": "user_security",
                "value": "high",
                "extractionFn": null
            },
            "querySegmentSpec": {
                "type": "LegacySegmentSpec",
                "intervals": [
                    "2011-01-12T00:00:00.000Z/2011-01-14T00:00:00.000Z"
                ]
            }
        }
    ]
}
```

To implement the local join query  ,I defined four metadata tables :
*  ```table_group(group_name,joint_table_name, joint_table_field,total_bucket_number )``` 
   To the given example ,the table_group will have three items: ```('g1','user_shop_detail','user_id',1024) ('g1','user','user_id',1024) ('g1','user_security','user_id',1024)```  
*   ```bucket_segment(bucket_number,segment_id,assignment_version)```
   The tables from the same TableGroup will have the group name , bucket number. The data from the same table group will be partitioned on joint key according to the total bucket number ,and have a partition rule i.e. ``` bucket_number= hash(joint_field)% total_bucket_number ```  .  Through this process ,we will have the bucket and DataSegment relationship.

*   ```bucket_assignment(bucket_number,machine_host,assignment_verion)```
   By implement an assignment algorithm, we can let the bucket go to a physical machine. The algorithm will give the bucket_assignment table data. 
   A  tip : a bucket is a DataSegment group which has equal joint field data

*  ```assignment_version(version_number,effect)```
    We may have different assignment according to the cluster changes ,so we should give an assignment a version number and a effect tag. The assignment with the largest version number and true effect tag will take place to generate a segment assignment.

The implementation can be broken into 4 parts:
>
* rewrite the query plan to push down the join query to the scan 
* partition the table's data according to the same partition rule
  The  history and realtime model will be treated differently.
*  let DataSegment from the same partition number to stay together at the  same physical machine
   By implementing a new  ``` DruidCoordinatorHelper ``` to do the assignment algorithm  , It writes the metadata table ```bucket_assignment  ,assignment_version ```  
   By implementing a new ```BalanceStrategy```  ,It assigns the unload segment to a dedicated machine  through the queried assignment metadata.
* implement a new join query called LocalJoin to query the DataSegments of the local machine which conform to the query condition.
    Here ,I have implemented a new join query mechanism called BitmapMatrix which is a [paper](https://www.osti.gov/scitech/biblio/982896) implementation. 

## working plan
---
Now ,I have implemented the 2~4 parts of the history model , the 1st part is WIP . I plan to  take two PRs to complete this proposal , one for history model, another is for realtime model ,to reduce the code review work.  I will give the history model implementation PR as soon as possible.

**Comment by jihoonson** [comment]
@weijietong thanks for your nice proposal! I have a couple of questions.

- The json spec for join query seems not extensible to support other query types as well. Is the ```LocalJoin``` query designed to support only inner equi join? I think this idea can be used for other types like outer joins or partially theta joins as well.
- Currently Druid supports [limited hash and range partition features](http://druid.io/docs/0.9.2/ingestion/batch-ingestion.html). It means, hash partitioning is allowed with only all dimensions and range partitioning is allowed with only a single dimension. Both partitioning schemes are not enough to cover various join cases. What is your plan for this problem?
- How do you extend Druid's partitioning feature to realtimes?

**Comment by weijietong** [comment]
@jihoonson  
* To 1st question , the ```LocalJoin ``` query json spec was initially designed to support inner equal join. I agree that it has limited expression ability to express join direction like ```left , right outer join```  though left or right outer join query can also be implemented later by ```LocalJoin``` technology , and  this is the aspect that we can discuss upon that. 

* To 2st question, I have a little change to the hash batch ingestion to let it support one dimension partition. I have no plan to support the range partition ,as I have not thought about that.

* To 3st question, We now do realtime ingestion through the push model.To push model, I plan to let the Overlord to generate a total shard number size workers .Each one of the workers will service a dedicated input data with specified bucket number , e.g. worker 1 will service data belongs to bucket 1,worker n will service data belongs to bucket n.  The input data will also have a bucket number calculation ``` bucketNumber=hash(jointField)%totalBucketSize ``` and transfers to the correspond worker . 

Then history  and realtime data can both stay together at the same physical machine ,as they share the same bucketNumber <---> machineHost relationship assignment.

To pull model, I have not thought about that yet. Any advice will be appreciated .

**Comment by jihoonson** [comment]
Thanks for your reply. For the second question, I'd like to ask you further how you decide the location of segments of different data sources partitioned by the same dimension. I think only the segments of the associated data sources should be co-located together because, otherwise, a skewed data distribution can be caused. I wrote some idea about this issue [here](https://github.com/druid-io/druid/issues/4032#issuecomment-286724163).

**Comment by weijietong** [comment]
@jihoonson I have read the proposed idea by @gianm. I think DistributedRule is a good concept to express the data distribution to the users. As mentioned above,to distribute the partitioned data, I defined four relevant metadata tables which is similar to implement the DistributeRule. A bucket is a group of segments which have partitioned by the same dimension key. When ingesting the data,we have the bucket number and the relevant segment relationship. This metadata stores in the bucket_segment metadata table.I define another common distribution interface called IPartition which do the work to distribute the bucket number to a server that also means find the sever to load the relevant segments. I have implemented several consistent hash implications of that interface. Also that interface has the responsibility to do the replication work. I use the double ring with replicator factor to guarantee replicated segments stored at different servers. The distribution result of this interface will be stored in the metadata table bucket_assignment . I reuse the LoadRule to do the real work to load segments according to the distribution result of last step. Another reason to store bucket_assignment is to compare the old,new distribution results to choose the segments to be moved due to the cluster has changed and the users decide to do so.I think this a implementation of the DistributionRule concept . To broadcast table,the bucket equals to the small table and another IPartition implementation to assign this small table to all the servers which service the biggest table. Any advice or objections please.

**Comment by jihoonson** [comment]
You mean the locations of segments (including replicas) are decided by ```IPartition``` which is based on the consistent hashing, and the actual storing and replicating segments are done by load rules? Sounds good, but I have one more question about that.
Druid is currently using ```BalancerStrategy``` to decide which server will hold a segment. ```IPartition``` seems to do the same work, so do you have any reason why you added a new interface? 
And, this new interface can be integrated well with the existing one? I wonder what happens if ```BalancerStrategy``` and ```IPartition``` doesn't return the same location for the same replica.

And, I think the work relating to the consistent hashing will be large because it should contain codes handling cluster changes. It would be better to make a separate PR for it.

**Comment by weijietong** [comment]
To be concrete ,`IPartition` does the real distribution logic work ,which we can have different distribution algorithms like the `HRW consistent hash`,`Jump consistent hash`,the traditional ring consistent has ,or just assign to all the corresponding servers like broadcasting. I implementation another `BalancerStrategy ` called `ClusteringBalancerStrategy` which use the distribution result (i.e. the saved metadata of `bucket_assigment`)calculated by the `IPartition` .  More concretely, there's a new Helper implementation which run periodically to run the `IParition` method , watch the cluster status, collect the distribution result from the metadata table , pack the distribution result as runtime parameters for the next Helper i.e. the `ClusteringBalancerStrategy` to use. 

As Druid now only use the `CostBalancerStrategy` by writing the hacker code ,that's a restriction that we maybe need to do a change ,My indirect solution is to let `CostBalancerStrategy` to nest have a `ClusteringBalancerStrategy`.

`BalancerStrategy` has methods to solve the rebalance question , that's where consistent hash was designed to solve. As we ever discussed offline , whether to rebalance the segments as the cluster changes ,the decision belongs to the users through change the `assignment_version` metadata effective tag. I don't think we need another PR for it.

**Comment by jihoonson** [comment]
Ah, I got it. Thanks for your detailed description. It's ok if the size of PR is not large. Please go ahead.
