### ISSUE TITLE
Mark interfaces which are Druid extension points in code

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#4044]
Following https://github.com/druid-io/druid/pull/3889#issuecomment-285783193 it would be nice to have APIs which are sensitive to changes being designated in code e. g. with `@DruidExtensionPoint` annotation.

cc @himanshug

**Comment by drcrallen** [comment]
I thought that's what druid-api is for. Or more specifically, if you are writing extensions and using classes that are NOT in druid-api, then they might change from release to release.

**Comment by leventov** [comment]
`BufferAggregator` is not in druid-api, but @himanshug pointed out that many people extend it

**Comment by himanshug** [comment]
@drcrallen @leventov i don't think there is an exhaustive list of interfaces that are considered the extension points. however, things mentioned in http://druid.io/docs/0.9.2/development/modules.html are considered public extension points.

**Comment by leventov** [comment]
Fixed in https://github.com/apache/incubator-druid/pull/4433
