### ISSUE TITLE
SqlResource: Metrics, request logs, cancellation

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#4047]
SqlResource should be up to the standards of QueryResource:

- Emit metrics for SQL queries. This could be `query/sql/time` to differentiate it from `query/time`.
- ~Emit metrics like `query/time` for the Druid native queries that underlie a SQL query. There might be more than one of these per SQL query.~ Fixed in #4561
- ~Emit request logs for the Druid native queries that underlie a SQL query.~ Fixed in #4561
- ~Emit friendly errors for QueryInterruptedException and any other cases that QueryResource emits friendly errors. This can be tested by setting a really low timeout and confirming you get a friendly JSON error rather than unfriendly HTML.~ Fixed in #4053
- Implement query cancellation, maybe by giving an "umbrella query ID" to all Druid native queries that underlie a SQL query, and returning that in the header of SqlResource's response, or maybe by assigning the same Druid query ID to all native queries (I think this would technically work although it would be a little strange).
- Return query IDs on SQL queries so users can correlate it to metrics stores.

I think a lot of this could be accomplished by sharing code between QueryResource and SqlResource. Some of it (like a `query/sql/time` metric) would be unique to SqlResource.

**Comment by drcrallen** [comment]
Why would metrics need to be different?

**Comment by gianm** [comment]
Because one SQL query can lead to multiple native Druid queries, there's an extra layer that QueryResource doesn't have to deal with.

**Comment by drcrallen** [comment]
Would it make sense to have an extra dimension for those metrics instead?

**Comment by gianm** [comment]
I dunno, it depends on whether you think `query/time` means "the time it takes for an http call to return" or "the time it takes a native druid query to execute". Either one should be fine as long as the information is there.

With other things, we give different "layers" of a request different names, like `query/time`, `query/node/time`, `query/segment/time`, etc.
