### ISSUE TITLE
Task to complete even if the logs haven't completed uploading

### ISSUE THREAD

**Issue by akashdw** [apache/incubator-druid#4048]
One of our realtime task got stuck in running state even it got marked as `"status" : "SUCCESS"`,
>2017-03-13T21:59:33,023 INFO [task-runner-0-priority-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "abcd",
  "status" : "SUCCESS",
  "duration" : 713
}

We found it was due to mm got stuck while uploading the logs into hdfs (this was b/c of regular grid maintenance) but peon completed successfully.
Now real issue is that mm was available to take new tasks but overlord did not assign any tasks to it b/c of the running state.
This a question of correctness versus availability and in this case availability might be more nicer?

**Comment by cheddar** [comment]
From the discussion during the dev chat.  It sounds like we can resolve this with one of two options

1. We can introduce a timeout to pushing up the logs and have it give up and just clean up the logs at some point
2. We can hand the log upload off to another thread that does it in the background.  If we go with this option, this background thread should have a well-defined retry mechanism as well as a well-defined "giving up" point where it decides that it has too much of a backlog and just starts throwing things on the floor (where throwing things on the floor means deleting the local log files).
