### ISSUE TITLE
Make extensions load definition easier for multiple extensions collections

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#4068]
As it currently stands, it is possible to have extensions which are applicable only to certain microservices within druid. For example: a broker does not need to load in a deep storage extension, coordinator does not need a cache extension, historicals don't need to load the spark batch indexer.

MOST of the time this is harmless, but if there is a reason to have an extension loaded only on certain nodes, it becomes very cumbersome to keep track of the load list.

Since we have a `common.runtime.properties` and a `runtime.properties` I suggest moving the extension list to something that can work with a definition in both properties files.

Potential solutions include, but are not limited to:

1. A common extension load list and a load list for `runtime.properties`
1. A special property prefix which can be grep'd to find the extensions. ex: `druid.extension.list.foo`, `druid.extension.list.bar` --> `extensionList=["foo", "bar"]`

**Comment by kaijianding** [comment]
Option 2 sounds better.
I currently face the same problem. I have an extension which requires `QuerySegmentWalker`, but overlord doesn't have one and overlord failed to start, I have to override extension list in runtime.properties to fix it.
