### ISSUE TITLE
task shutdown should be available via overlord console

### ISSUE THREAD

**Issue by textractor** [apache/incubator-druid#410]
Right now you've got to post 

  <overlord>:<port>/druid/indexer/v1/task/<id_of_task>/shutdown

to shut down a task.

It would be great if, in the overlord console, there was a shutdown button for each task. Or maybe one shutdown button and a checkbox for each task, to be able to shut down multiple tasks.

**Comment by comchangs** [comment]
Hi, @fjy.

I have some codes resolving like this issue for my own system so if I could take this issue, I want to make a PR for this.
Could I take this issue?

Thanks.

**Comment by vogievetsky** [comment]
This has been addressed in all consoles (old and new #6832) @fjy this can be closed
