### ISSUE TITLE
GroupByV2 error message

### ISSUE THREAD

**Issue by akashdw** [apache/incubator-druid#4129]
We are seeing some of the GroupByV2 queries fails with `ResourceLimitExceededException` but error message does not say exactly what was the cause, that makes tuning difficult.
It would be nice if we can log message which says where error happens.

**Comment by arpankhagram** [comment]
Hi @akashdw  We have been facing similar issues with groupBy V2 where tuning is becoming difficult with similar message for most of the issues - i have replied @gianm about our problems - https://github.com/druid-io/druid/issues/3833.
