### ISSUE TITLE
Possibility of having String Metrics

### ISSUE THREAD

**Issue by arpankhagram** [apache/incubator-druid#4132]
Similar to the new feature we have in 0.10 to allow dimension with non-string values - we have requirement of specifying few of the metrics as String and perform  last/first operations on them.

Kindly let me know.

**Comment by fjy** [comment]
@arpankhagram Where we are going is for Druid just to have columns with types. if you disable rollup in Druid, you can you list all your columns as dimensions, and you can perform filters/aggregations/other functions over those columns. What you are asking for might already be possible, I just have to double check.

**Comment by arpankhagram** [comment]
Hi Fajing, Did you get anything around this ? The requirement i have is to run lastValue aggregation on specific dimension (which in our case is String metric)
