### ISSUE TITLE
how to decompress segment to Raw data

### ISSUE THREAD

**Issue by mjaow** [apache/incubator-druid#4158]
i had a need on moving data from druid to another app which don't know the format of druid segment.I have to decompress the segment from druid hdfs.Is there any function exists to get it done?Or is there a better way?

**Comment by mjaow** [comment]
i find a dump-segment tool in the version of 0.9.2.But i'm using 0.9.1.It seems i have to implement it with help of latest version

**Comment by knoguchi** [comment]
I don't think you can extract raw data from 0.9.1.  The 0.9.2 introduced `rollup` option in the [granularity spec](http://druid.io/docs/0.9.2/ingestion/).  Unless the option is explicitly turned off the  raw data is aggregated and rolled up before saved into disk.

**Comment by mjaow** [comment]
@knoguchi you are right.Anyway i can still get the aggregated data.Maybe that is just enough
