### ISSUE TITLE
Overlord Logs : Warning

### ISSUE THREAD

**Issue by arpankhagram** [apache/incubator-druid#4167]
Hi Team, I can see below warning continuously in my overlord logs for our Kafka supervisor. PFB the sample :

WARN[KafkaSupervisor-DSLAM] io.druid.segment.indexing.DataSchema - No metricsSpec has been specified. Are you sure this is what you want ?

This is in spite of the metrics specified in Kafka supervisor. 

Is this something known and should be ignored ? Do not see impact of this anywhere except this continuous logging for all our supervisor.

Regards,
Arpan

**Comment by pjain1** [comment]
If you have non empty `metricsSpec` in the Supervisor specification then this shouldn't printed.

**Comment by arpankhagram** [comment]
@pjain1 I have uploaded logs and attached specifications at below

https://groups.google.com/forum/#!topic/druid-user/SmL7MCNUxQI

Can you please have a look if you see any issues with specifications. Thanks in advance.

**Comment by arpankhagram** [comment]
@pjain1  Although it's not causing any issues but im still unable to figure out what exactly is wrong with my specifications.

**Comment by toughrogrammer** [comment]
I'm getting same warning logs
