### ISSUE TITLE
Problem about restoring task at dead middlemanager

### ISSUE THREAD

**Issue by mjaow** [apache/incubator-druid#4187]
my middlemanager is dead while it is running some tasks.After many hours,I start it.The restored task（druid.indexer.task.restoreTasksOnRestart=true is set）wil run.Wil it run and succeed as normal task?Or it will fail because of data overdue.

**Comment by gianm** [comment]
It will probably fail since it's been timed out. Tasks are only allowed a certain amount of time to restore after disappearing before the overlord gives up.
