### ISSUE TITLE
How can you get top X records, sorted by time, grouped on a set of dimensions?

### ISSUE THREAD

**Issue by donpinkus** [apache/incubator-druid#4204]
I've been combing the docs for the past few hours and trying to get a query to accomplish this - but no luck.

Is it possible to get the top X records, sorted by time, grouped on a set of dimensions?

## Example:
This is a fictional example, that's meant to simply illustrate the problem.

Given a data source in the following format, how can I get the most recent 10 people to make a purchase, and their most recent purchase amount & product name?

So the result is 10 unique people, and their most recent purchase amount & product name.

**Data:**

```
purchases
----------------------------------------------------------------------
timestamp   first_name    last_name   customer_id  product_name  purchase_amount
```

**Result:**
```
 James, Jackson, 1234, 'foo', 432.123
 Tim, McTimothy, 321, 'bar', 5124.11
 Bob, Bobbertson, 55, 'foo', 432.123
 Claire, Rando, 191, 'tv', 700.00
 Jimbo, Manman, 631, 'ps4', 450.00
```
### Select query

This doesn't do any grouping, but does order the 10 most recent records by time.  Issue is the 10 rows returned are not unique people.

```
{
  "context": {
  	"timeout": 8000
  },
  "queryType": "select",
  "dataSource": "purchases",
  "granularity": "all",
  "intervals": [ "2017-04-01T00:00:00.000Z/2017-04-23T00:00:00.000Z" ],
  "descending": "true",
  "pagingSpec": { "pageIdentifiers": {}, "threshold": 10 }
}
```

### groupBy query
This groups by all dimensions and metrics, instead of just grouping on first_name, last_name, customer_id - and then taking the most recent product_name and purchase_amount.

So you will have 10 records, but they will not be 10 unique people. Just 10 unique combinations of the metrics & dimensions listed.

Also it's not ordered by time.

```
{
  "queryType": "groupBy",
  "dataSource": "purchases",
  "granularity": "all",
  "intervals": [ "2017-04-01T00:00:00.000Z/2017-04-23T00:00:00.000Z" ],
  "dimensions": [
    "first_name",
    "last_name",
    "customer_id",
    "product_name"
  ],
  "metrics": [
    "purchase_amount"
  ],
  "limitSpec": { 
    "type": "default", 
    "limit": 10
  }
}
```

**Comment by jihoonson** [comment]
I think you need to use window functions which is not supported by druid yet unfortunately.

**Comment by gianm** [comment]
You should be able to get the customers and the timestamps with:

```sql
select customer_id, max(__time)
from tbl
group by customer_id
order by max(__time) desc
limit 10
```

Or the equivalent topN or groupBy native query.

Then you'd want to find the records that have those `customer_id` and `__time` pairs. You could do it with a select query filtering on an OR of ANDs (each AND on a customer_id and a timestamp). But you might get more than 10 rows back if the same customer_id did more than one purchase in the same millisecond. If your app can handle that, you should be fine.

Btw, you should have been able to do that entire thing with Druid SQL, although there's a planner bug that prevents the most natural query from working: #4208, which would have been:

```sql
select * from tbl where (customer_id, __time) in (
  select customer_id, max(__time)
  from tbl
  group by customer_id
  order by max(__time) desc
  limit 10
)
```
