### ISSUE TITLE
How to do update dataSource set metric1 = xxx, metric2 = yyy where dimension1 = d1 and dimension2 = d2

### ISSUE THREAD

**Issue by javcly** [apache/incubator-druid#4209]
I am evaluating Druid for our new OLAP system. We have 100+ dimensions, and dimensions are mutable, can be added , renamed, removed, historical data need to be updated once dimensions are changed. 
Also historical data are mutable too. 
So I need to perform sql like update queries on existing data set, like below:  

1. update dataSource set metric1 = xxx, metric2 = yyy where dimension1 = d1 and dimension2 = d2

2. update dataSource set dimension1 = new_d1, dimension2 = new_d2 where dimension1 = d1 and dimension2 = d2

Does Druid support such function?

**Comment by kaijianding** [comment]
I don't think druid can handle this. Druid treat data as immutable.
But you can use new schema in new segment, you can check kafka indexing service

**Comment by javcly** [comment]
thanks, I've asked another question in a separate post, stating my requirement and see if Druid fits.
