### ISSUE TITLE
The default value of "druid.server.http.numThreads"

### ISSUE THREAD

**Issue by licl2014** [apache/incubator-druid#4216]
the default value of  `druid.server.http.numThreads` in official doc is `10` , but the value  in druid release code is `Math.max(10, (Runtime.getRuntime().availableProcessors() * 17) / 16 + 2) + 30`, am i wrong with this value？

**Comment by nishantmonu51** [comment]
good catch, @licl2014 : the docs are outdated, would you be able to create a PR for the fix in docs ?
