### ISSUE TITLE
Namespace Lookups not Propagating Through to Outer Query For Nested Queries

### ISSUE THREAD

**Issue by cbulacan9** [apache/incubator-druid#4219]
Version: 0.9.2
GroupByStrategy: v1

When using namespace lookups via JDBC or URI, the extraction seems to be inconsistently handled, it only propagates the transformed version for some dimension lookups some of the time. For example, if I have do a Lookup dimensionSpec on the inner query and then query for that same inner dimension on the outer query, I get the default non-extracted dimension value. However, I have tried running the inner query independently and do indeed receive the transformed lookup value. I've had some success by changing some of the JDBC lookups to JSON lookupParseSpec's, but I'm not sure if it makes sense to change all of my lookups to use this. 

I've also had some more luck using the registeredLookup extraction dimension spec vs the lookup dimension spec.

https://groups.google.com/forum/#!topic/druid-user/8gNaN0_2Vsw

**Comment by cesure** [comment]
I just had the same issue:
- Druid 0.9.2
- Lookup DimensionSpec in nested GroupBy
- GroupByStrategy V2
- Lookup was configured with `lookups-cached-global` and is read from CSV from HDFS

I noticed that this was my only Lookup which had `injective: true`. As soon as I changed it to `false` everything was fine again.

**Comment by cesure** [comment]
If you run [this](https://gist.github.com/gianm/97c08f7910cae1a08bec4e1cbae509a3) test from @gianm it will succeed. If you then change  the parameter for `MapLookupExtractor.isOneToOne` to `true` (which means injective afaik) then the test fails. It should succeed in both cases in my opinion.

I had no chance to test this in newer Druid versions yet.
