### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by thibaultmeyer** [apache/incubator-druid#4234]
Hello,

I'm just reading your documentation. Honestly, I have no idea how to begin with your software. No sample, no clear installation process (just tar -xvf is not an explication, what are all possible configuration keys ?), no client based sample to explain how to insert data, querying ...

By example, I'm developping an e-store app using Play Framework with Java 8, how I can insert data each time a client buy something ? or logging article views ?

Once data is inserted, how I can query data from a Java 8 application ?

Sincerely

**Comment by pjain1** [comment]
You might want to start with reading Druid concepts/design - http://druid.io/docs/0.10.0/design/ and http://druid.io/docs/0.10.0/design/design.html 

Then use http://druid.io/docs/0.10.0/tutorials/quickstart.html to setup a minimal Druid cluster to try out things. Common runtime properties/configuration and node specific runtime properties for the quickstart resides in `conf-quickstart/druid/_common` and `conf-quickstart/druid/<node_type>` directories. You can read more about them here - http://druid.io/docs/0.10.0/configuration/index.html

There are various ways druid can ingest event data like the one you mentioned - http://druid.io/docs/0.10.0/tutorials/tutorial-streams.html and http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html

For querying you can use any of the already existing libraries/UI - http://druid.io/libraries.html or create your own web service which makes json queries to Druid. I hope this was helpful.
