### ISSUE TITLE
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;

### ISSUE THREAD

**Issue by rahulsingh303** [apache/incubator-druid#4291]
Hi,

I am trying to use druid to analyze parquet data . I think I have done all the necessary steps . Here are the steps I took:

1. Created json metadata file for source . Attached file here named parquet_metadata.txt , renamed it to .txt , originally it is .json.

If you see in file I have used , as suggested , "mapreduce.job.classloader": "true"
[parquet_metadata.txt](https://github.com/druid-io/druid/files/1011861/parquet_metadata.txt)

2. Since I am running my hadoop on cloudera 5.9.0 , I downloaded dependencies using pull-deps : 
java -classpath "/home/druid/druid-0.10.0/lib/*" io.druid.cli.Main tools pull-deps -r https://repository.cloudera.com/content/repositories/releases/ -h org.apache.hadoop:hadoop-client:2.6.0-mr1-cdh5.9.0

3. However when I run druid job am getting this error : 
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;

I have also attached full druid log . 
[druid_log.txt](https://github.com/druid-io/druid/files/1011886/druid_log.txt)

Please let me know if I have missed anything .

-Rahul

**Comment by mentholi** [comment]
@rahulsingh303 Did you figure out what was the issue? I'm facing same problem. :I

**Comment by bendoerr** [comment]
@rahulsingh303 Struggling here as well. What was the issue?

**Comment by b-slim** [comment]
Are you sure you Hadoop version accepts `"mapreduce.job.classloader": "true"`, you can try this one instead `mapreduce.job.user.classpath.first = true`
