### ISSUE TITLE
Higher precision for hyperunique aggregator

### ISSUE THREAD

**Issue by yaochitc** [apache/incubator-druid#4300]
Hi, we are using hyperunique for the computation of cardinality, and find the default precision is a bit low. Is is possible to add some parameters to control the memory consumption for better precision(such as control the bucket size)?

**Comment by gianm** [comment]
Hey @yaochitc, currently no config parameters are exposed. You could edit the code, but watch out for incompatibilities in the serialized form as a result. If you're interested in contributing something here, HyperLogLogCollector and HLLCV1 are good places to start.

**Comment by yaochitc** [comment]
In fact, I tried to alter the code. It seems that there are two places that needed to be changed:
BITS_FOR_BUCKETS 
bucketMask;
Both of them are in HyperLogLogCollector.java.
