### ISSUE TITLE
problem about how data goes from overlord to middlemanager

### ISSUE THREAD

**Issue by mjaow** [apache/incubator-druid#4311]
i wonder how realtime data goes from overlord to middlemanager.Is it first sent to zookeeper by overlord then get from zookeeper  by middlemanager?If it is so,can zookeeper hold so many realtime data?

**Comment by gianm** [comment]
The overlord doesn't touch the data stream at all. It sets up ingestion tasks on the middlemanagers and then those tasks process the data stream directly from the source.

**Comment by mjaow** [comment]
@gianm where is the source?now in my system kafka+tranquility play the realtime role. middlemanager process data from tranquility?
