### ISSUE TITLE
Broker double-counting HA rt-segments

### ISSUE THREAD

**Issue by sixtus** [apache/incubator-druid#443]
Hi,

I got a mixed setup of RTs with linear sharding. Not all shards are created equal, i.e. some I keep double, e.g.

rt1:
1
100
rt2:
2
100

In this case, brokers will ask both rts for segment 100 and thus double count. Once the segment hits historical nodes, all is good.

**Comment by vogievetsky** [comment]
I believe this is no longer an issue with the [Kafka indexing service](http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html)
