### ISSUE TITLE
LDAP Authentication for Druid

### ISSUE THREAD

**Issue by kusumakarb** [apache/incubator-druid#4454]
Can we use LDAP authentication with Druid? I would like know if there are any known implementations of LDAP authentication for druid. If not, are there any roadblocks to develop some sort of an extension?

**Comment by drcrallen** [comment]
Great question. Can you explain some more on what your needs for authentication and access rights are?

**Comment by kusumakarb** [comment]
We need something similar to what Kylin provides. [Kylin Enable Security with LDAP.](http://kylin.apache.org/docs/howto/howto_ldap_and_sso.html)
