### ISSUE TITLE
Possible bug in StringDimensionIndexer

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#4493]
https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/segment/StringDimensionIndexer.java#L215

Should probably be `encodedDimensionValues = new int[]{dimLookup.add(null)};`

@jon-wei what do you think?

**Comment by vogievetsky** [comment]
@leventov is this still an issue in 0.16.0? the link does not work prob because of apache migration

**Comment by leventov** [comment]
[This link](https://github.com/apache/incubator-druid/blob/HEAD@%7B2017-06-30T21:58:22Z%7D/processing/src/main/java/io/druid/segment/StringDimensionIndexer.java#L215) works for me. No, that was fixed in #5278.
