### ISSUE TITLE
how to terms first，then topn

### ISSUE THREAD

**Issue by zhxiaom5** [apache/incubator-druid#4575]
I used to use elasticsearch to query topn，like below
```
s.aggs.bucket('channel_top_ip_status', 'terms', field='hostname')\
    .bucket('top_ip_static', 'terms', field='xforward',size='20')\
    .metric('ip_sum_bytes', 'sum', field='send_byte')
```
i can first terms hostname by hostname,then terms by xforward,fininal get sum。so how to achieve that use druid？
thanks

**Comment by zhxiaom5** [comment]
any help?

**Comment by zhxiaom5** [comment]
any one ? thanks

**Comment by zhxiaom5** [comment]
i cant find any help

**Comment by GaryHuangBD** [comment]
pls see http://druid.io/docs/0.10.1/querying/groupbyquery.html. if u feel confused, u can try using [sql](http://druid.io/docs/latest/querying/sql.html).

**Comment by zhxiaom5** [comment]
that not what I want,
I want to first groupby,then topN every groupby ,not just group by,then topN all groupby

**Comment by zhxiaom5** [comment]
well，foreach topN works too，not cost too many time

**Comment by zhxiaom5** [comment]
Just check out，we still use foreach topN ，any help would be greate

**Comment by zhxiaom5** [comment]
Yes，thats what i am doing now
