### ISSUE TITLE
Metric sort on timeseries query

### ISSUE THREAD

**Issue by sundaramprasad** [apache/incubator-druid#4610]
Is there any way to sort my query results on the basis of my aggregation which i choose. suppose I am querying api-count for each minute in one hour. I want to sort my results count wise. I couldn't find anyway to do that in the docs for timeseries query. Is there a way to do this? 
Sundaram

**Comment by satishbhor** [comment]
Here is sample query that group by field_1(Dimension) and order by Count(Metrics) and limits 10 results
Refer : [Druid limitSpec](http://druid.io/docs/latest/querying/limitspec.html ) more details,

`{"intervals":["start_date/end_date"],"granularity":"all","context":{"timeout":60000},"queryType":"groupBy","dataSource":"myDataSource","aggregations":[{"type":"count","name":"Count"}],"dimensions":["field_1","count"],"limitSpec":{"columns":[{"dimension":"count","direction":"ascending"},{"dimension":"field_1","direction":"ascending"}],"type":"default","limit":10}}`

**Comment by gianm** [comment]
Timeseries can only sort by time (hence the name). groupBy can group by time and sort by something else, which sounds like what you want.
