### ISSUE TITLE
Druid timezone problem

### ISSUE THREAD

**Issue by JLLNANA** [apache/incubator-druid#4616]
When start druid, I set timezone
java -Xmx256m -Duser.timezone=UTC+08:00 -Dfile.encoding=UTF-8 `cat conf-quickstart/druid/broker/jvm.config 
or
java -Xmx256m -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8
on all nodes(broker,  coordinator, historical, middleManager, overlord)
Neither of these two method takes effect.
Druid time is still later 8 hours than linux system time.

How to set timezoen of druid?

**Comment by JLLNANA** [comment]
In the file of linux
/etc/sysconfig/clock
ZONE="Asia/Shanghai"
Maybe, there is no relation with jvm timezone setting

**Comment by b-slim** [comment]
Druid does support running on UTC only.

**Comment by b-slim** [comment]
@JLLNANA http://druid.io/docs/latest/operations/recommendations.html

**Comment by leventov** [comment]
@b-slim system timezone is widely used yet though, see #4611

**Comment by b-slim** [comment]
@leventov am not sure am getting your comments, currently as per https://github.com/druid-io/druid/issues/2619 we still highly recommend to run the JVM on UTC timezone otherwise bad things will happen, haven't looked at your PR yet but hope it fixes 2619

**Comment by fanwu72** [comment]
@b-slim 
Think about this: 
I want to aggregate the data into a one-day granularity at ingestion time. Obviously it is related to the timezone. The definition of one day is different at different timezone. In this situation, forcing user to use UTC makes things weird.

Best regards,
Ryan
