### ISSUE TITLE
SQL: Multi-value column support

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#4638]
Druid SQL doesn't support multi-value columns right now. They kind of work sometimes but not always.

- They are reported as VARCHAR which does not give the user a hint that they are multi-value.
- ~If you select one without aggregation then you get an error (#4637) as the runtime tries to cast them to string but cannot.~ Fixed by #6462.
- If you group on one you get the standard Druid multi-value grouping behavior, which is surprising in the context of SQL.
- Since Druid SQL thinks they're VARCHARs, you write filters on them as if you were filtering on a string column. But the planner may do some inappropriate optimizations (like optimize `a = 'x' AND a = 'y'` to `FALSE` even though a multi-value column could have both values).
- I'm not sure what happens when a multi-value column is involved in a semi-join but I'm sure it's not anything good.

I'm not sure how to best express multi-value columns in SQL. Ideas are welcome. See also a calcite dev thread: https://www.mail-archive.com/dev@calcite.apache.org/msg02846.html

**Comment by clintropolis** [comment]
resolved by the additions from proposal #7525
