### ISSUE TITLE
Endpoint to dump runtime properties

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#4645]
Maybe `/properties` or `/status/properties`. Would be useful for debugging "does this server actually have the configs I want"?

For security considerations, this should require admin privileges, since properties are often sensitive.

**Comment by b-slim** [comment]
Sounds good idea and yes this need to be protected if security is on.

**Comment by vishnu93** [comment]
Hi!
I'm interested in creating this endpoint. I'd like to know that if this end point is an HTTP one then how would the protection be implemented, is there already an authentication service or does that have to be created too?
Thanks.

**Comment by gianm** [comment]
@vvc11 thanks for your interest in contributing!

It would be an HTTP endpoint (in general Druid speaks HTTP). Probably the right place to add it would be StatusResource. It's already protected by the StateResourceFilter (see the `@ResourceFilters(StateResourceFilter.class)` at the top) meaning that a user would need to have "read state" permissions to be able to access it.

So what needs to be done is to inject the Properties into the resource (check out other Resource classes for examples of injection), add a new `@GET` method for getting the properties, and add some unit tests.

**Comment by vvc11** [comment]
Hi @gianm !
 Apologies for the delay. Here is the pull request : [https://github.com/druid-io/druid/pull/5276](url)
My test checks if the properties returned by the StatusResource class is the same that's used in the project (by comparing values). Also, when I was trying to run tests for the druid-server module I was getting a Forbidden Method Invokation in LookupExprMacro.java . Did not touch that file, is this normal?

Thanks

**Comment by b-slim** [comment]
@gianm  and @vvc11 can we add a list of exclusion that by defaults includes the sensible information like metadata passwords and AWS key if any. This should be straightforward.
