### ISSUE TITLE
kafka supervisor kill dont remove offsets from metadata db

### ISSUE THREAD

**Issue by mazorigal** [apache/incubator-druid#4714]
Hi,

we were trying to delete a data source which is created via the kafka supervisor.
We stopped the supervisor, then disabled the datasource and finally submitted kill task for that datasource, however we noticed that the kafka offsets for that data source were not cleaned from the mysql metadata (druid_dataSource), also we noticed that in druid_pendingSegments pending segments records were not removed .
We also tried first to rest the supervisor, then to shut it down, disable the datasource and submit kill task, but we noticed that once we shutdown the supervisor, he will first save kafka offset in mysql, so that would not help either.

Thanks,

**Comment by pantaoran** [comment]
I have a similar problem just now. I tried to change the Kafka topic of a datasource by resubmitting the changed supervisor to overlord. Now all tasks fail, in the logs I see it complaining about the Kafka offsets not matching.
I'm not sure how I can achieve this, looking into manually removing the datasource entry from the mysql DB now.

**Comment by sderosiaux** [comment]
@pantaoran Did you tried to reset the offsets ? `POST /druid/indexer/v1/supervisor/<supervisorId>/reset`

**Comment by pantaoran** [comment]
I totally forgot that this API existed! It actually seems perfectly suited to solve my problem.
I have another datasource with the same problem, and after this call its tasks now succeed again.
Thanks!

**Comment by suhassumukhv** [comment]
Exactly, the reset is an excellent way to change the offsets. 
But, @sderosiaux, is there a way to completely remove the supervisor metadata from Druid?
