### ISSUE TITLE
Add configuration to control size of segments loading into the memory

### ISSUE THREAD

**Issue by Ken-LiuL** [apache/incubator-druid#4723]
As time goes by, the size of segments in historical node will become larger and larger, I think it is important that we can configure the maximum size of segments that a historical node can put in memory, thought, this will cause slowness of the query, it is better than  server crashed since out of memory

**Comment by GaryHuangBD** [comment]
Try using load rule and drop rule,  and maybe u should have a look at historical node tire, it's useful for  separating hot and cold data.

**Comment by Charles-Lau-** [comment]
The drop and load rule will not be applicable in this case , in which you will not be able to get result from those segments configured as dropped

**Comment by GaryHuangBD** [comment]
I don't think it's a good idea. Actually, a dynamic loading strategy can implement this, but loading segments is expensive, and u will find that druid have to load and drop segment from ram frequently due to queries of different time periods. I think u can improve the specified queries performance by using  historical node tire.

**Comment by Charles-Lau-** [comment]
Even if building up a historical node tire, I still need more machines and more memories, which is not my intention. Here, the restriction is that I do not have lots of memories available and slight slowness of queries is tolerable.  As for the expensiveness of loading segments into memory, we can build a cache layer in front of broker to alleviate the overhead brought by queries involved with cold data, thus, hot data queries can be served by broker, most of cold data queries can be served by a cache layer, only a small portion of cold data queries will cause loading segments from hard drive
