### ISSUE TITLE
Overlord IndexService shutdown request does not kill corresponding Batch Ingestion Hadoop job

### ISSUE THREAD

**Issue by jason166** [apache/incubator-druid#4753]
I've noticed that requesting a shutdown on an indexing task results in the hadoop job being left orphaned consuming resources on the cluster.  I would expect that once a task has been shutdown that a hook will fire to kill the running hadoop job.  

http://<OVERLORD_IP>:<port>/druid/indexer/v1/task/{taskId}/shutdown
See http://druid.io/docs/latest/design/indexing-service.html

**Comment by gianm** [comment]
@jason166, you're right, hadoop tasks don't clean up.

If you wanted to take a stab at this, maybe you could do it by adding a `stop()` method to the Task interface, and having the ThreadPoolTaskRunner call that method if it's _not_ in restore mode (in which case it would call stopGracefully instead). I guess in that case, when `stop()` exits, then the ThreadPoolTaskRunner would still go ahead and interrupt the main thread.
