### ISSUE TITLE
Is there any way to filter message in kafka indexing task?

### ISSUE THREAD

**Issue by kinghw** [apache/incubator-druid#4765]
e.g. Considering dimension: version, which might have values: v1, v2, v3 I would like to have only v2 loaded.

or can i write code on druid ?

**Comment by knoguchi** [comment]
I think you need a stream processor (Storm for example) that filters out unwanted events in front of Druid for the time being.

If we want such feature in Druid, It's somewhat related to [this discussion.](https://groups.google.com/forum/#!topic/druid-development/qzqWjxShGII).    Theoretically the dimensions spec in parseSpec can be extended with "optional" or "required" flag, and filters.   At my work, we've developed custom parsers (fairy easy), and ingested events with specific values.
