### ISSUE TITLE
Coordinator endpoint /druid/coordinator/v1/metadata/datasources does not report datasources without physical segments

### ISSUE THREAD

**Issue by nishantmonu51** [apache/incubator-druid#4819]
Coordinator endpoint /druid/coordinator/v1/metadata/datasources does not report datasources from realtime tasks which are not handed off yet. 
Fwiw, other endpoint - /druid/coordinator/v1/datasources lists those datasources also.

**Comment by himanshug** [comment]
my understanding is that `/druid/coordinator/v1/metadata/*` reflects information about segments stored inside metadata store, so ` /druid/coordinator/v1/metadata/datasources` wouldn't show datasources that don't exist in metadata store yet.
`/druid/coordinator/v1/datasources` should probably list everything.

**Comment by niketh** [comment]
The behaviour is consistent with the paradigm of "Datasource existing only when there are segments" and segments really only exist once we have them in deep storage.
