### ISSUE TITLE
[Proposal] maxQueryTimeout property in runtime properties.

### ISSUE THREAD

**Issue by akashdw** [apache/incubator-druid#4821]
`druid.server.http.defaultQueryTimeout` property can be overridden by clients via query context. It would be nice to have `druid.server.http.maxQueryTimeout` setting  similar to `druid.server.http.maxScatterGatherBytes` where actual value used should be default or math.min(context.timeout, maxQueryTimeout).

@himanshug @gianm

**Comment by gianm** [comment]
Sure, it sounds like it could be useful. I would say the default should be -1, meaning no max.

**Comment by himanshug** [comment]
as discussed, :+1: ... yeah agree with @gianm about about making enforced max to be infinity (implemented with special value -1 if needed )
