### ISSUE TITLE
Druid Coordinator doesn't respond to HTTP Requests

### ISSUE THREAD

**Issue by sasounda** [apache/incubator-druid#4830]
Ran into a nasty bug where Druid coordinator wouldn't respond to HTTP requests. Not even the `/status` endpoint.

Some Observations
1. I am running all Druid processes as separate containers on a `CentOS7` machine with `Mesosphere's DC/OS` installed. Runs `Java 8 Build 131`
2. None of the other Druid nodes (realtime, historical, broker, overlord) has this problem. 
3. I confirmed that it is not a networking issue or a Docker issue because I am able to request fine from other nodes and running a coordinator process standalone on the host also doesn't help. Also, a `tcpdump` suggests that the initial handshake went through fine, but the Druid server didn't respond with the data back.
4. I added some logs to Druid code, built and confirmed that the GET method for the `/status` handler is not being called in this case.
5. This doesn't reproduce on a CoreOS machine.
6. This is not something which broke in recent Druid version because I ran into this problem even on older Druid binaries (~ 0.9.2).

It is problematic for Druid functioning because realtime nodes are not able to get rid of the handed-off segments since coordinator wouldn't respond to HTTP requests.

**Comment by gianm** [comment]
Do you know what happened to get Druid into this state? Is it reproducible?

Could you try running `jstack -l <coordinator pid>` and see what the http handler threads are doing? (They should start with the string `qtp`)

**Comment by sasounda** [comment]
Yes. It is consistently reproducible on my machine right from when Druid coordinator starts up. 

Here is the output from `jstack`: 
[jstack_coordinator.txt](https://github.com/druid-io/druid/files/1320019/jstack_coordinator.txt)

**Comment by sasounda** [comment]
Found that this problem with coordinator occurs only on high spec systems like `32vCPU/120GB RAM` and not on lower end systems like `8vCPU/32GB RAM`.

Increasing the num of http threads in the coordinator from `20` to `40` fixed the problem. What's surprising is that I was running `20` threads on all the other Druid processes and it was running fine. Also, having `20` threads on the coordinator on a lowed spec machine didn't cause any issues.

You might want to look into what makes coordinator process behave differently on a higher spec machine.
