### ISSUE TITLE
Select Query - Recursive pagingIdentifiers

### ISSUE THREAD

**Issue by fmarelli** [apache/incubator-druid#4849]
Hi, I have a select query with following format, I have 11 records for the given id

`{
  "queryType" : "select",
  "dataSource" : "dsource",
  "descending" : "false",
  "dimensions" : [ "id", "ndg_id", "A", "B", "C", "D", "E", "F", "G" ],
  "metrics" : [ "ee", "qq" ],
  "granularity" : "all",
  "intervals" : [ "2000-01-01/2000-01-02" ],
  "filter" : {
    "type" : "and",
    "fields" : [ {
      "type" : "in",
      "dimension" : "ref_date",
      "values" : [ "2017.03" ]
    }, {
      "type" : "in",
      "dimension" : "ndg_id",
      "values" : [ "0000000000000239" ]
    } ]
  },
  "pagingSpec" : {
    "pagingIdentifiers" : {
    },
    "threshold" : 5
  }
}
`
After the 1st submission I have 5 events and the following pagingIdentifier

`    "pagingIdentifiers" : {
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z" : 1,
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_1" : 0,
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_2" : 1
    }`

Which I feed back in the next query which in turn gives me back the pi

`    "pagingIdentifiers" : {
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_3" : 1,
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_5" : 1,
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_6" : 0
    }`

Which I feed back again to get what I think should be the one remaining event, but I get back 5 more events with the following pi

`    "pagingIdentifiers" : {
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z" : 1,
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_1" : 0,
      "damneat_2000-01-01T00:00:00.000Z_2000-01-02T00:00:00.000Z_2017-09-05T06:40:03.754Z_2" : 1
    }
`

which is exactly the same as the first and puts me in an endless loop as the result is never empty.

Any idea as to why this is happening? Is there a way to execute a select query without pagination?

Thanks!

**Comment by bhrgv-bolla** [comment]
first request => you get paging identifiers in response.
Use the first response paging identifiers for second request => you get new paging identifiers in second response.
Now merge the first response paging identifiers with the second response paging identifiers for the third request.
Essentially, you are overwriting the entries in first with the entries in 2 for the merged paging identifiers.

SUGGESTION: Hope druid does that internally in the next versions!
