### ISSUE TITLE
API changes report for Druid

### ISSUE THREAD

**Issue by lvc** [apache/incubator-druid#4896]
The review of API changes for the Druid library since 0.3.3 version: https://abi-laboratory.pro/java/tracker/timeline/io.druid.druid-api/

Hope it will be helpful for users and maintainers of the library.

The report is generated for jars found at http://central.maven.org/maven2/io/druid/druid-api/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![io druid druid-api-2](https://user-images.githubusercontent.com/1517837/31114599-92edd8de-a827-11e7-84aa-e2d430e096bc.png)
![io druid druid-api-1](https://user-images.githubusercontent.com/1517837/31114600-92f036ce-a827-11e7-88ff-67f7c152529d.png)

**Comment by leventov** [comment]
Thank you. How the publicness of the API is determined? In Druid we have `@PublicApi` and `@ExtensionPoint` annotations for that.

**Comment by lvc** [comment]
In this report, Public API=="Methods, classes and interfaces with public or protected access level". In the next release of Druid I'll filter out private symbols from the report with the help of annotations.

Thank you.
