### ISSUE TITLE
Backpressure for broker-to-historical communication

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#4933]
If the result set size is very large and the client making the query is not pulling the results out fast enough, brokers can go OOM. This is because the broker lacks backpressure for large result sets, and they can "pile up" in memory. I believe that the specific part lacking backpressure is the collection and merging of results from individual historical (and realtime) nodes.

This is mostly an issue with scan queries and groupBy queries, which can generate large result sets.

When implementing backpressure it would be important to consider the effect this may have on the historical nodes. Backpressure would presumably extend all the way down to them, and in that case, would block threads their http server pools.

Related: #4229, which introduced `maxScatterGatherBytes` as a kind of workaround to prevent broker crashes (although it will fail queries).

Also related: #4865, a symptom.

**Comment by gianm** [comment]
Also related: #6014, an attempt to solve this.

**Comment by gianm** [comment]
#6014 was closed but still has relevant discussion: https://github.com/apache/incubator-druid/pull/6014#issuecomment-409518597

**Comment by coolboi567** [comment]
This issue is still present.
Broker process gets killed by kernel due to OOM.
