### ISSUE TITLE
Overlord Exception While Announcing Segments

### ISSUE THREAD

**Issue by praveshg** [apache/incubator-druid#5025]
Hi,
We are facing an exception in overlord in a production environment while announcing the Historical Segment. 

It looks to me some sort of multi-threading issue (if thats possible ) as the segment is already present in the MetaData and still the "segmentExists"  method (IndexerSQLMetadataStorageCoordinator.java+581) is returning "FALSE" on some of the times .
We are using druid-0.9.1 in our production.

Following is the Logs :

2017-08-08 06:15:02.534+0000 *INFO*  io.druid.metadata.IndexerSQLMetadataStorageCoordinator Found [prod_report_ds_2017-08-08T05:00:00.000Z_2017-08-08T06:00:00.000Z_2017-08-08T05:00:04.589Z_5] in DB, not updating DB

2017-08-08 06:15:01.692+0000 *ERROR* io.druid.metadata.IndexerSQLMetadataStorageCoordinator Exception inserting segment[prod_report_ds_2017-08-08T05:00:00.000Z_2017-08-08T06:00:00.000Z_2017-08-08T05:00:04.589Z_5] into DB
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "druid_segments_pkey"
  ...
  Detail: Key (id)=(prod_report_ds_2017-08-08T05:00:00.000Z_2017-08-08T06:00:00.000Z_2017-08-08T05:00:04.589Z_5) already exists.
Show all 89 lines

2017-08-08 06:15:01.690+0000 *INFO* [qtp1997290658-83] io.druid.metadata.IndexerSQLMetadataStorageCoordinator Published segment [prod_report_ds_2017-08-08T05:00:00.000Z_2017-08-08T06:00:00.000Z_2017-08-08T05:00:04.589Z_5] to DB

In above logs it is clear the the segment [prod_report_ds_2017-08-08T05:00:00.000Z_2017-08-08T06:00:00.000Z_2017-08-08T05:00:04.589Z_5] has already been inserted in the postgres (metadata) but still overlord throws an exception. Also the very first line (after around 1 minute difference), "segmentExists"  would have returned true.

Note the time between last two logger lines , hardly in milliseconds.  Is it possible that two thread would have come at this method (announceHistoricalSegment) and executed segmentExists without knowing about each other (Race Condition)

More Details : https://groups.google.com/forum/#!topic/druid-user/8hFWfsD6THk

**Comment by gianm** [comment]
@praveshg, do you know if this is still an issue in the latest version?

**Comment by david-benes** [comment]
Hi, I'm experiencing the same issue except that I use mysql.
Race conditions seems as reasonable explanation due to random nature of the error occurrence.
In my case, this started happening after I increased task.replicants in tranquility from 1 to 2.

Now we have two worker tasks for each hour.

Druid version: druid-0.9.1.1

Anyone else experiencing this or have a solution?
