### ISSUE TITLE
Link to Zookeeper cluster

### ISSUE THREAD

**Issue by QubitPi** [apache/incubator-druid#5041]
In [doc](http://druid.io/docs/0.10.1/tutorials/cluster.html):

![screen shot 2017-11-03 at 11 03 01 am](https://user-images.githubusercontent.com/16126939/32388983-9b09864a-c086-11e7-9ee8-8e58562ded69.png)

If I have a Zookeeper cluster of, for example, 5 machines(each runs a Zookeeper instance), how should I specify them in `druid.zk.service.host`? Comma separated?

**Comment by drcrallen** [comment]
Good question. The value for `druid.zk.service.host` is passed directly into the [Curator](https://curator.apache.org/) Ensemble connect string. So whatever kind of string is valid for [FixedEnsembleProvider](https://curator.apache.org/apidocs/org/apache/curator/ensemble/fixed/FixedEnsembleProvider.html) is valid for use in this property. I don't have a great link to docs that explain the connection string handy at the moment.

**Comment by gianm** [comment]
It's the same format described on https://zookeeper.apache.org/doc/trunk/zookeeperProgrammers.html.

> To create a client session the application code must provide a connection string containing a comma separated list of host:port pairs, each corresponding to a ZooKeeper server (e.g. "127.0.0.1:4545" or "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002"). The ZooKeeper client library will pick an arbitrary server and try to connect to it. If this connection fails, or if the client becomes disconnected from the server for any reason, the client will automatically try the next server in the list, until a connection is (re-)established.

**Comment by drcrallen** [comment]
I suggest leaving this issue open until the docs are patched to link to the ZK connection string information.

**Comment by skyrocknroll** [comment]
```
# Zookeeper
#

druid.zk.service.host=zk-node-1.bm.infra:2181,zk-node-2.bm.infra:2181,zk-node-3.bm.infra:2181
druid.zk.paths.base=/druid
```

**Comment by skyrocknroll** [comment]
`druid.zk.service.host=host1:2181,host2:2181,host3:2181`

**Comment by vogievetsky** [comment]
This has been fixed.
