### ISSUE TITLE
Unable to remove metric from realtime node

### ISSUE THREAD

**Issue by erikdubbelboer** [apache/incubator-druid#5090]
I just removed a metric from the config of our realtime nodes and restarted them. Now they fail to persist the segments around the time the node was restarted:
```
Failed to persist merged index[foo]: {class=io.druid.segment.realtime.plumber.RealtimePlumber, exceptionType=class io.druid.java.util.common.IAE, exceptionMessage=Indices to merge contained metric[bar], but requested metrics did not, interval=2017-11-14T04:00:00.000Z/2017-11-14T05:00:00.000Z}
```
Which is from here:
https://github.com/druid-io/druid/blob/3541b7544b90f4991673fb6f052615dfd825d721/processing/src/main/java/io/druid/segment/IndexMergerV9.java#L798
Shouldn't it just drop this metric during the merge instead?

How can this be fixed for these segments and what is the proper procedure to remove a metric?

**Comment by erikdubbelboer** [comment]
I'm guessing this is only possible using Tranquility and not using the standalone realtime nodes?

**Comment by gianm** [comment]
I seem to recall seeing this issue before with realtime nodes. I think it shouldn't happen with tranquility or with the kafka indexing service. If you're interested in fixing it then a patch would be welcome. You're probably right that it should be a little more forgiving.
