### ISSUE TITLE
Configurations like "fetchTimeout" is getting stripped off from the Druid task and payload

### ISSUE THREAD

**Issue by mohanrajnaidu** [apache/incubator-druid#5164]
I am ingesting a S3 file with following configurations
    "ioConfig" : {
      "type" : "index",
      "firehose" : {
        "type" : "static-s3",
        "uris" : [ "s3://dp-cdp-druid/freewheer_sor_data/year=2017/month=12/day=10/1512882000-1512885600/part-00000-fc315240-8d51-4d2a-ba11-a6be41dd9cf9.csv" ],
        "prefixes" : [ ],
        "maxCacheCapacityBytes" : 3073741824,
        "maxFetchCapacityBytes" : 3073741824,
        "prefetchTriggerBytes" : 536870912,
        "fetchTimeout" : 120000,
        "maxFetchRetry" : 7
      },
      "appendToExisting" : true
    }

Most of the configurations are getting stripped off and Druid is taking default. The payload from coordinator look like below
      "ioConfig": {
        "type": "index",
        "firehose": {
          "type": "static-s3",
          "uris": [
            "s3://dp-cdp-druid/freewheer_sor_data/year=2017/month=12/day=10/1512882000-1512885600/part-00000-fc315240-8d51-4d2a-ba11-a6be41dd9cf9.csv"
          ],
          "prefixes": [
            
          ]
        },
        "appendToExisting": true
      },

When I look into the log druid is picking up the default values like below
   "ioConfig" : {
      "type" : "index",
      "firehose" : {
        "type" : "static-s3",
        "uris" : [ "s3://dp-cdp-druid/freewheer_sor_data/year=2017/month=12/day=10/1512882000-1512885600/part-00000-fc315240-8d51-4d2a-ba11-a6be41dd9cf9.csv" ],
        "prefixes" : [ ],
        "maxCacheCapacityBytes" : 1073741824,
        "maxFetchCapacityBytes" : 1073741824,
        "prefetchTriggerBytes" : 536870912,
        "fetchTimeout" : 60000,
        "maxFetchRetry" : 3
      },
      "appendToExisting" : true
    }

I want to increase the timeout

I am using druid druid-0.10.1

**Comment by jihoonson** [comment]
Hi @mohanrajnaidu, thank you for the report. It's a bug in 0.10.1 and will be fixed in 0.11.0. Please see https://github.com/druid-io/druid/pull/4948.
