### ISSUE TITLE
Wrong libs Path reference in JDK9

### ISSUE THREAD

**Issue by yaodwwy** [apache/incubator-druid#5168]
Errors occurred while build effective model from C:\Users\Adam\.gradle\caches\modules-2\files-2.1\com.alibaba\druid\1.1.5\89c05586e0d4e28a543d0239cbc63df28fda202\druid-1.1.5.pom:
    'dependencies.dependency.systemPath' for com.alibaba:jconsole:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar in com.alibaba:druid:1.1.5
    'dependencies.dependency.systemPath' for com.alibaba:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar in com.alibaba:druid:1.1.5

**Comment by leventov** [comment]
This issue belongs to https://github.com/alibaba/druid
