### ISSUE TITLE
Error: com.google.inject.util.Types.collectionOf(Ljava/lang/reflect/Type;)Ljava/lang/reflect/ParameterizedType;

### ISSUE THREAD

**Issue by ighack** [apache/incubator-druid#5202]
cp $DRUID_HOME/lib/*guice* $HADOOP_HOME/share/hadoop/yarn/lib/
cp $DRUID_HOME/lib/*guice* $HADOOP_HOME/share/hadoop/mapreduce/lib/
It's still fail.

**Comment by ighack** [comment]
you need restart druid

**Comment by xiaoxixi0314** [comment]
It's useful to me, thank you very much.

**Comment by successok** [comment]
add 
"jobProperties": {
  "mapreduce.job.classloader": "true"
}
