### ISSUE TITLE
-XX:OnOutOfMemoryError="kill -9 %p"

### ISSUE THREAD

**Issue by leanken** [apache/incubator-druid#5205]
I was trying to set the -XX:OnOutOfMemoryError="kill -9 %p" inside jvm.config, and try to start. But it turn out that node.sh start service using following:

java `cat jvm.config | xargs` to specific jvm parameters. xargs will cut the whole string to several one because xargs will use \n, space, tab as delimeter. so for -XX:OnOutOfMemoryError="kill -9 %p" parameter it's not working at all.

i think we can add this parameter into the node.sh like following:

java '-XX:OnOutOfMemoryError="kill -9 %p"' `cat jvm.config | xargs` <the rest of args>

**Comment by leanken** [comment]
if agreed, i can do a pull request to fix it.

**Comment by Himadri1800** [comment]
Use `-XX:OnOutOfMemoryError="/bin/kill -9 %p"` instead
