### ISSUE TITLE
Realtime ingestion stop after some time

### ISSUE THREAD

**Issue by amoussoubaruch** [apache/incubator-druid#5219]
Hi, 

I was using Druid since few month and try a realtime ingestion with tranquility spark scala API.
I used a kafka topic to take messages in real time (300 messages per second). 
I start my spark jar with hour Granularity. Ingestion start well and take something like 10 min for ingestion and nothing after. I don't have any data. I am using 2 hours for window period so i can explain why i have no data ingest in druid. 
I have druid cluster with 6 nodes : 2 overlord and 2 coordinator in same machine; middlemanager, brocker and historical are start on all of them. 

Whats is the best way to find if realtime ingestion work fine? 
How can i verify that if 200 messages come in window period i have the same message in druid in this period. 

Thanks

**Comment by dragonls** [comment]
Maybe you can try the [Stream Pull Ingestion](http://druid.io/docs/0.11.0/ingestion/stream-pull.html).

AFAIK, you can query the result in a realtime using Stream Pull Ingestion once druid ingest data from Kafka.
But by using Stream Push Ingestion, you will have to wait a window period.
