### ISSUE TITLE
Implement custom Druid Aggregator

### ISSUE THREAD

**Issue by QubitPi** [apache/incubator-druid#5231]
I'm implementing a custom [BufferAggregator](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/aggregation/BufferAggregator.java). The doc in the code level is pretty good! I just have extra questions that, as a dev user, could ask:

* ~~What does [buf](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/aggregation/BufferAggregator.java#L54) actually hold? Are they bytes of metrics or bytes of aggregators?~~

* When we say ["Implementations must not change the position, limit or mark of the given buffer"](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/aggregation/BufferAggregator.java#L45), do we always want to use `buf.duplicate();` or `buf.slice()` as the first statement in implementation? Why does the position of the given buffer could possibly be non-zero? Is it because the same byteBuffer has been used in initialization of other kinds of aggregators? If so, when did the init happen?

* What's the difference between `Aggregator` and `BuffereAggregator`? Is `Aggregator` post agg and `BufferAggregator` non-post agg?

**Comment by QubitPi** [comment]
Is `BufferAggregator` for off-heap aggregation and `Aggregator` on-heap(slower) ?

**Comment by jihoonson** [comment]
Hi @QubitPi, here are my answers.

- ```BufferAggregator``` is supposed to simply put/update/get some value at the given position of the given buffer. It isn't supposed to duplicate or slice the given buffer because it doesn't have to keep the intermediate status. See ```LongSumBufferAggregator``` as an example.
- Yes, ```BufferAggregator``` and ```Aggregator``` are for off-heap and on-heap, respectively.
