### ISSUE TITLE
TopN query error seems incorrect - "Must have an AggregatorFactory"

### ISSUE THREAD

**Issue by donpinkus** [apache/incubator-druid#5234]
When I run a TopN query, I get an error that I must give an "AggregatorFactory" for a particular metric. 

I'm using the standard "longMax" aggregation in my query. (see query below)

Why am I getting this error? 

**Error:**
```
{"error": "Instantiation of [simple type, class io.druid.query.topn.TopNQuery] value failed: Must have an AggregatorFactory or PostAggregator for metric[purchase_amount], gave[[LongSumAggregatorFactory{fieldName='purchase_amount', expression='null', name='max_purchase_amount'}]] and [[]]"}
```

**Query:**
```
{
  "queryType": "topN",
  "dataSource": "my_records",
  "dimension": "my_unique_id",
  "threshold": 1,
  "metric": "purchase_amount",
  "aggregations": [
    { "type": "longMax", "name": "max_purchase_amount", "fieldName": "purchase_amount" }
  ],
  "intervals": ["2018-01-06T03:07:48.482Z/2018-01-06T03:08:21.523Z"],
  "granularity": {
    "type": "duration",
    "duration": 330.41,
    "origin": "2018-01-06T03:07:48.482Z"
  },
  "filter": {
    "type": "and",
    "fields": [
      { "type": "selector", "dimension": "first_name", "value": "Don" },
      { "type": "selector", "dimension": "last_name", "value": "Pinkus" }
    ]
  }
}
```

**Comment by jihoonson** [comment]
Hi @donpinkus, did you see the error message when executing the above query? Looks weird because the metric name of the error (```e2e_latency```) is different from that in the query (```purchase_amount```).

**Comment by donpinkus** [comment]
@jihoonson - ah yes, sorry had to change some of the query fields to make it more legible / less proprietary ;)

**Comment by jihoonson** [comment]
Still weird.

> {"error": "Instantiation of [simple type, class io.druid.query.topn.TopNQuery] value failed: Must have an AggregatorFactory or PostAggregator for metric[e2e_latency], gave[[LongSumAggregatorFactory{fieldName='purchase_amount', expression='null', name='max_purchase_amount'}]] and [[]]"}

This means, you specified a longSum aggregator for ```purchase_amount```, but the metric in the query is ```e2e_latency```. This is different from the above query in two ways: the aggregator type and the metric name.

**Comment by donpinkus** [comment]
@jihoonson sorry, forgot to change that `e2e_latency` to be `purchase_amount`!

Edited in the original post.

**Comment by manujose0** [comment]
Had the same issue. Seems like in the aggregations the name and fieldName should be the actual metric_name ... weird and seems like a bug. 

"aggregations": [
    { "type": "longMax", "name": "max_purchase_amount", "fieldName": "purchase_amount" }
  ],

Should be : 

"aggregations": [
    { "type": "longMax", "name": "purchase_amount", "fieldName": "purchase_amount" }
  ],
