### ISSUE TITLE
Using namespace lookup extraction in a quert filter not possible anymore

### ISSUE THREAD

**Issue by erikdubbelboer** [apache/incubator-druid#5243]
[The documentation](http://druid.io/docs/latest/querying/dimensionspecs.html#lookup-extraction-function) show the example where a `namespace` lookup extraction function is being used. But when trying this in `0.11.0` I always get the error `Could not resolve type id 'namespace' into a subtype of [simple type, class io.druid.query.lookup.LookupExtractor]`.

Judging by [the code](https://github.com/druid-io/druid/blob/7b8b0a96d63e99b5990760cf91b51f03ea49fac0/processing/src/main/java/io/druid/query/lookup/LookupExtractor.java#L36) `namespace` lookup extraction function doesn't exist anymore.

Am I right and should the documentation be updated or did I miss something?

I could only find one other person who tried this [on the druid-user mailing list](https://groups.google.com/forum/#!searchin/druid-user/namespace|sort:date/druid-user/vjYfFfZtzMU/B6BcGtJwBwAJ) but didn't get it to work either.

**Comment by himanshug** [comment]
I think the docs are wrong ( PR to fix it would be great) and its probably called `cachedNamespace` now and part of extension http://druid.io/docs/0.11.0/development/extensions-core/lookups-cached-global.html .

this happened in 0.9.2 release and noted in those release notes at https://github.com/druid-io/druid/releases?after=druid-0.10.0-rc1 .

so, I'm assuming you upgraded from 0.9.1 to 0.11.0 or else what I said above does not make sense.

also, while not ideal and some might disagree, but I think its better to create your own extension for doing lookups by creating implementations of LookupExtractorFactory . Code in current lookup extensions could be used for reference. that is usually simpler and what I recommend to my customers.

**Comment by erikdubbelboer** [comment]
@himanshug That doesn't work either. That just gives me `Could not resolve type id 'cachedNamespace' into a subtype of [simple type, class io.druid.query.lookup.LookupExtractor]`.

The lookups-cached-global documentation only describes how to create the lookups, not how to actually use them. 

In the source the only classes that implement the `LookupExtractor` interface are [MapLookupExtractor](https://github.com/druid-io/druid/blob/aa7e4ae5e46a13a9db8d0ee29885249fd0afd02e/processing/src/main/java/io/druid/query/extraction/MapLookupExtractor.java#L43) and the [LoadingLookup](https://github.com/druid-io/druid/blob/c0beb78ffdb5807ceea8a340838eab01d6a18d1d/extensions-core/lookups-cached-single/src/main/java/io/druid/server/lookup/LoadingLookup.java#L42) and [PollingLookup](https://github.com/druid-io/druid/blob/8d9902831ef344b9c4c29f5d9d07e69e37edd706/extensions-core/lookups-cached-single/src/main/java/io/druid/server/lookup/PollingLookup.java#L44) classes from the `lookups-cached-single` extension. So I'm guessing `lookups-cached-global` is just not fully implemented and nobody is using it.

Next I'm going to try the `lookups-cached-single` extension and see if that actually works.

**Comment by himanshug** [comment]
@drcrallen would know more about `lookups-cached-global` but your investigation sounds accurate to me. Feel free to use `lookups-cached-single` if that works for you.
that said, I think documentation needs fixing at the very least and let us keep this ticket open till docs are fixed.

**Comment by erikdubbelboer** [comment]
I tried using `lookups-cached-single` but it appears you have to specify your jdbc connection options in your query instead of in some global place which seems weird and won't work for us. I had to read the code again to figure this out as the documentation was severely lacking.

**Comment by cyrillay** [comment]
Same issue here on 0.11.0 as well `Could not resolve type id 'cachedNamespace' into a subtype of [simple type, class io.druid.query.lookup.LookupExtractorFactory]`

Did you eventually manage to get it working ?
