### ISSUE TITLE
Long running travis job

### ISSUE THREAD

**Issue by akashdw** [apache/incubator-druid#5263]
https://travis-ci.org/druid-io/druid/builds/329583957 is running for last ~6 hours.
Some of the build have completed but containers are still running, e.g https://travis-ci.org/druid-io/druid/jobs/329583960 .

Looks like other Travis jobs are stuck because of this.

@nishantmonu51 @gianm

**Comment by jihoonson** [comment]
Just canceled and restarted that build.

**Comment by akashdw** [comment]
Thanks @jihoonson.
Looks like build backlogs are related to https://www.traviscistatus.com/incidents/c1s4dlyxd4lf
