### ISSUE TITLE
Deep storage migration from s3 to hdfs

### ISSUE THREAD

**Issue by akashdw** [apache/incubator-druid#5273]
I'm running hadoop distcp to copy existing segments from s3 to hdfs but druid segments in s3 have `:` in the paths which is a bad uri for hadoop.
I see https://github.com/druid-io/druid/blob/master/api/src/main/java/io/druid/segment/loading/DataSegmentPusher.java#L96 and https://github.com/druid-io/druid/blob/master/extensions-core/hdfs-storage/src/main/java/io/druid/storage/hdfs/HdfsDataSegmentPusher.java#L221 are different as hdfs one replaces `:` with `_`. 
Any suggestions how to distcp segments from s3 to hdfs?
@himanshug @gianm @b-slim what do you think of using a common safe path format for s3, hdfs and if possible for other deep storage to avoid similar problems?

**Comment by b-slim** [comment]
@akashdw I have not done this TBH. Please share with us your tricks once you accomplish this.

**Comment by himanshug** [comment]
had a quick discussion with @akashdw offline. it appears that Druid is always writing the correct URIs as expected by S3 and HDFS naming conventions.
Problem is Distcp not supporting functionality to rename URIs as it writes to HDFS which doesn't support ':' . 

Its a one time activity and my suggestion is to do following.
1. copy relevant segments to another temp location on same S3 region.
2. rename segment files to replace ':' with '_'  as S3 can support '_' .
3. copy renamed file from temp location on S3 to HDFS.

then use insert-segment-to-db tool to update the metadata store correctly on the target Druid cluster.

**Comment by dragonls** [comment]
I faced the same problem while migrating segments from local storage to HDFS storage.
And I did extracly as @himanshug suggested. That works fine.
