### ISSUE TITLE
[Proposal] Coordinator Auto Kill feature config to ignore segments marked unused in last x days/weeks etc

### ISSUE THREAD

**Issue by himanshug** [apache/incubator-druid#5305]
Currently users can configure auto kill of unused segments to completely wipe them out (from metadata store as well as deep storage) automatically. However, it is not considered safe for production because sometimes segments get marked unused accidentally when load/drop rules are changed or someone accidentally clicks "disable" button for a dataSource on the coordinator console ( On one of our clusters , we have had this happen and then auto-kill deleting all the data)

To make "auto kill" safer against above concerns, proposal here is to add another configuration at coordinator that tells auto-kill code to not touch any segments which were marked unused in last x days/weeks. For example, user can setup that config to be 1 week and have some alerting mechanism  on missing data. Whenever segments are marked unused accidentally, they will notice it before 1 week passes and auto-kill wouldn't delete them.

Now, for the implementation, **we would need to add another column "marked_unused_date" in "druid_segments" table which will be updated whenever a segment is marked unused**. Auto-kill code would use timestamp stored in that column.

**Comment by zhangxinyu1** [comment]
Auto kill feature is very useful for us!
Maybe we can set the time or the frequency to decide when deleting the unused data, like 'crontab' in linux.

**Comment by jihoonson** [comment]
I wonder if a similar goal can be achieved by checking segment intervals rather than adding a new column in the metastore. It means, the coordinator can check the segment interval is old enough and make sure that the segment interval is not overlapped with the configured "safe" period (like dropRules). I guess usually old segments are marked as unused, and will be killed at some point. In this use case, checking segment intervals looks enough. So, I think it might be better because we can avoid adding a new column which is not compatible with old versions. What do you think?

**Comment by himanshug** [comment]
@jihoonson I don't really want to couple rules with auto-kill and have the feeling that implementation would become unnecessarily complex that way... also there are many different ways a segment can get disabled, having a column that clearly tells when the segment was disabled allows very simple semantics without worrying about all the different ways user could've disabled the segment.
In #5315 only thing is that users need to run the ALTER TABLE statement **anytime** before upgrade and everything else is taken care of. it could be run without taking the cluster down or upgrading any of the nodes etc.
I'll see if it makes sense to auto-execute `ALTER TABLE` on coordinator/overlord startup so that there are no manual steps in the upgrade. However, considering the simplicity , I was thinking of not automating it, but we'll see.

**Comment by jihoonson** [comment]
I didn’t mean to couple rules and auto-kill feature. I meant, auto-kill feature can be implemented with segment intervals like dropRule. 

> there are many different ways a segment can get disabled, having a column that clearly tells when the segment was disabled allows very simple semantics without worrying about all the different ways user could've disabled the segment.

I understand what you mean and it sounds making sense. I’ll look into the PR as well.

**Comment by himanshug** [comment]
> Auto kill feature is very useful for us!
Maybe we can set the time or the frequency to decide when deleting the unused data, like 'crontab' in linux.

@zhangxinyu1 that wouldn't solve the problem for most of our users whose "frequency" would be in hours and not in weeks. Also, it is always possible that auto-kill executes immediately after you accidentally disabled segments.
