### ISSUE TITLE
Calcite causes segment metadata request logs as soon as it starts up

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#5320]
`io.druid.sql.calcite.schema.DruidSchema#refreshSegmentsForDataSource` calls a bunch of `SegmentMetadataQuery` requests on startup on the brokers, which causes crazy entries in the logs. There also is not any sort of tracer associated with these queries (like a special query id) which makes them hard to track through the system.

They also have a crazy rendering for their intervals, causing giant request logs as soon as the node starts up.

This is a mild annoyance but it would be nice to be able to separate out the auto-generated query traffic from calcite from the external user traffic.

**Comment by gianm** [comment]
Are you talking about request logs (the ones that can go to files and such) or some other kind of logs? The `identity` field might be a good way to separate the logs, if you are using a cluster that has authentication enabled. The auto-generated queries use the escalator so they should be using the system identity.

**Comment by drcrallen** [comment]
Request logs :)
