### ISSUE TITLE
Get the maximum value along with timestamp in group by query.

### ISSUE THREAD

**Issue by fanwu72** [apache/incubator-druid#5341]
Hi there, 

I am facing a query scenario based on a business requirement. I would like to get the max value along with its timestamp. Say I have below data in druid:

**timestamp domain isp val
1517731200 a.com dx 10
1517731260 a.com dx 11
1517731320 a.com dx 9
1517731200 b.com dx 3
1517731260 b.com dx 2
1517731320 b.com dx 1
1517731200 c.com yd 123**
...
other records
...

The  dimension is domain, the interval is [1517731200, 1517731320], the granularity is ALL, the filter is like (domain in('a.com', 'b.com') and isp = 'dx') and the aggregator is (val, max).

It works well if I run the druid query, which works like below sql:
select domain, max(val) from tbl where domain in ('a.com', 'b.com') and __time >= 1517731200 and __time <= 1517731200 and isp = 'dx' group by domain;
The result is 
a.com 11
b.com 3

p.s. I don't use druid sql. The above sql is just an example.

However, the result I want is:

a.com 11 1517731260 
b.com 3 1517731200 

It seems that a sub query or a window function is required for a standard sql. Now the question is: how to do the same in druid? I checked the druid document but didn't find the solution. 
Please help me with this scenario. Any solution or workaround would be very helpful. 
Thank you.

Best regards,
Ryan

**Comment by Suman21** [comment]
I'm also facing the same kind of problem!!!

**Comment by rajarshibemech** [comment]
I am facing the same issue. Anybody can help please??

**Comment by ciukstar** [comment]
Same issue with [Feature scaling](https://en.wikipedia.org/wiki/Feature_scaling). Maybe as `druid-stats` extension.

**Comment by gianm** [comment]
This does sound like a good candidate for an aggregator extension.

**Comment by kaijianding** [comment]
@fanwu72 it sounds like :  select domain, max(val),max(__time) from tbl where domain in ('a.com', 'b.com') and __time >= 1517731200 and __time <= 1517731200 and isp = 'dx' group by domain;

**Comment by mahendrasingh07** [comment]
i am also facing same issue.
For resolve issue i am executing following query which too much slow

select __time, value from temp where value in ( select max(value) from temp group by time_foor(__time,'PT14S'))
