### ISSUE TITLE
Failed to create tmp directory error

### ISSUE THREAD

**Issue by Llinjing** [apache/incubator-druid#5373]
When the "**tmp**" directory is not created, submit the task, will be reported "**Failed to create directory within 10000 attempts (tried 1470845895301-0 to 1470845895301-9999)**" error. Found to be using Guava's createTempDir method has a problem.
```
public static File createTempDir() {
    File baseDir = new File(System.getProperty("java.io.tmpdir"));
    String baseName = System.currentTimeMillis() + "-";

    for (int counter = 0; counter < TEMP_DIR_ATTEMPTS; counter++) {
      File tempDir = new File(baseDir, baseName + counter);
      if (tempDir.mkdirs()) {
        return tempDir;
      }
    }
    throw new IllegalStateException("Failed to create directory within "
            + TEMP_DIR_ATTEMPTS + " attempts (tried "
            + baseName + "0 to " + baseName + (TEMP_DIR_ATTEMPTS - 1) + ')');
  }
```
Use mkdirs () instead of mkdir (), you can solve the error.

 At the same time, init script can be removed, because after the change, all the directories are automatically created.

**Comment by zhztheplayer** [comment]
In my own experience, you can check the following:

1. Whether the tmp dir exists or not (The dir should be created manually)
2. Ensure The number of tmp files has not reached the file system limit.

**Comment by drcrallen** [comment]
is the problem here that `java.io.tmpdir` does not exist, so the `mkdir` fails?

**Comment by Llinjing** [comment]
The problem can be resolved by create tmp dir. But i should to run init.sh file before i start the cluster for first time.I think is not a good way to maintain a cluster.I hope this path can be created automatically when it is used.

**Comment by kiran-jagtap** [comment]
Hi Team,
I'm using druid 0.12.3 in cluster mode with three node cluster, I'm getting same error of 
"Version:0.9 StartHTML:0000000212 EndHTML:0000000819 StartFragment:0000000248 EndFragment:0000000783 SourceURL:http://10.101.26.62:8090/druid/indexer/v1/task/index_wikipedia_2018-11-02T13%3A25%3A08.523Z/log
java.lang.IllegalStateException: Failed to create directory within 10000 attempts (tried 1541165112739-0 to 1541165112739-9999)
"

I have setup "-Djava.io.tmpdir=tmp" and given 777 permissions still error present no luck to get data ingestion working ...

Any help would be great;y appreciated..

Thanks,
Kiran
