### ISSUE TITLE
Upgrade druid-0.11.0 from 0.10.0 timezone faild?

### ISSUE THREAD

**Issue by panqingcui** [apache/incubator-druid#5424]
Upgrade Druid 0.11.0 by Druid 0.10.0, Duser.timezone = UTC + 0800 does not take effect
[

![image](https://user-images.githubusercontent.com/10126345/36656001-08e87f8e-1b01-11e8-9fcd-0ff07791e13c.png)

**Comment by nishantmonu51** [comment]
The start an end are now represented in UTC instead of user.timezone and this is as expected. 
IMO, your queries should still be getting correct results.
