### ISSUE TITLE
must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar

### ISSUE THREAD

**Issue by yaodwwy** [apache/incubator-druid#5447]
Errors occurred while build effective model from C:\Users\Adam\.gradle\caches\modules-2\files-2.1\com.alibaba\druid\1.1.6\55ff28bd66de65a644a922ad8bca123d5e1826c3\druid-1.1.6.pom:
    'dependencies.dependency.systemPath' for com.alibaba:jconsole:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/jconsole.jar in com.alibaba:druid:1.1.6
    'dependencies.dependency.systemPath' for com.alibaba:tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar in com.alibaba:druid:1.1.6

build in gradle ,JAVA 1.9 Errors occurred

**Comment by nishantmonu51** [comment]
seems like you are building some alibaba specific druid fork. 
Please raise an issue on alibaba repo.

**Comment by leventov** [comment]
@nishantmonu51 it's an entirely different project.

@yaodwwy this issue belongs to https://github.com/alibaba/druid
