### ISSUE TITLE
Make AggregatorFactory an interface

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#5475]
It was made an abstract class to add some methods (pre Java 8 default methods in interfaces). For stable API it's better to switch back.

**Comment by himanshug** [comment]
curious... would there be any practical advantage/reason for doing that ?

**Comment by leventov** [comment]
I think it's better to focus on this issue: #7287 for "Stable API" instead of cosmetically make `AggregatorFactory` an interface. The two other interfaces which will be the result of #7287 can be interfaces (rather than abstract classes) because there are just no reasons to make them abstract classes.
