### ISSUE TITLE
Override value of count aggregator

### ISSUE THREAD

**Issue by erankor** [apache/incubator-druid#5497]
Hi all,

We're using a count aggregator in most of our data sources, once in a while we get a request to migrate a set of events from some external system. We get these events aggregated, so that a single row represents multiple events. 
In order to get the correct count metric, I was thinking about one of -
1. Generate duplicate input rows according to the aggregated count - naturally this would be a huge overhead for large number of events
2. Avoid using count aggregator in general - always use longSum instead, and make sure to send "count": 1 in all our regular/non-migrated events
3. I think it would be great (maybe there already is such a feature? :) ) to have the ability to configure `fieldName` on the `count` aggregator - so that -
  a. If fieldName exists in the event JSON, its value will be used
  b. Otherwise, the value will be assumed to be 1 (as count normally behaves)

Thanks!

Eran

**Comment by gianm** [comment]
Hi @erankor, the usual way to do this is (2): using longSum and adding a `"count": 1` to the regular events.

**Comment by erankor** [comment]
Thanks @gianm

**Comment by erankor** [comment]
@gianm, a follow up question - if I change my schema now from count to longSum, so that new segments will be indexed with longSum while old segments were indexed with count, is it expected to cause any issue? (e.g. will a query that spans across the two types return the correct result)
My guess is that count gets translated internally to longSum, and if that is the case, a segment created with count should be equivalent to one created with with longSum. But just wanted to make sure...

Thanks!

Eran

**Comment by erankor** [comment]
@dragonls, it's the other way around, the old segments use count aggregation, so it doesn't matter that the events don't have the `count` field (it will only be problematic if I will reindex them with the new schema). 
For new segments, I will make sure to add the `count` field to the JSONs before I update the schema to longSum. 
The question was whether segments that were ingested with longSum are equivalent to segments that were ingested with count (my guess is that they are, but would be great to get a confirmation on this)

**Comment by dragonls** [comment]
@erankor The results are not the same.
The result using count may be smaller than that using longSum. The records with the same dimensions in one segment will be count just as 1.
