### ISSUE TITLE
Document quantile sketches

### ISSUE THREAD

**Issue by will-lauer** [apache/incubator-druid#5499]
Druid 0.12 added support for quantile sketches, but they don't appear to be documented in the datasketches extensions page. The only way to understand how to use them is to read the API doc and the source.

**Comment by b-slim** [comment]
yeah, it is sad! I have been asking Sketch devs to add some basic docs examples but nothing is happening, I guess writing docs is not glorious...
https://github.com/druid-io/druid/pull/5148#issuecomment-361965095

**Comment by AlexanderSaydakov** [comment]
https://github.com/druid-io/druid/pull/5513
