### ISSUE TITLE
add time range param to /datasources/[DATASOURCE]/intervals?simple

### ISSUE THREAD

**Issue by tarekrached** [apache/incubator-druid#550]
so that we don't have to hammer the coordinator by asking for every interval any time we want to check recent data sizes, it would be great to be able to do the following to get just a subset of the intervals:

```
/datasources/[DATASOURCE/intervals?simple&start=2013-02-03&end=2013-02-14
```

or

```
/datasources/[DATASOURCE/intervals?simple&interval=2013-02-03/2013-02-14
```

to be clear, the output should be exactly the same as /intervals?simple, just a filtered result.

**Comment by drcrallen** [comment]
I'm torn here because it would be very cool if the service accepted Range headers
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35

**Comment by tarekrached** [comment]
I'm not clear from reading the rfc - does the range header support non
byte-based ranges?

**Comment by drcrallen** [comment]
@tarekrached at one time I had read a part that did, but I may have linked to the wrong part.

**Comment by tarekrached** [comment]
other folks looking at the same issues: "I think it is up to the developer
whether to use it this way, but to me the hole is a bit too round for this
square peg! Pass the values in the query string."

https://stackoverflow.com/questions/11009107/can-i-specify-custom-range-types-in-the-accept-ranges-header

**Comment by vogievetsky** [comment]
I believe the [Druid system tables](http://druid.io/docs/latest/querying/sql#retrieving-metadata) effectively solve this issue.

**Comment by tarekrached** [comment]
fantastic
