### ISSUE TITLE
[Proposal] A new HTTP endpoint to check completed queries.

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-druid#5503]
The proposal is to discuss the possibility of intruducing a new http endpoint representing completed query details.

Current query metrics emitting system is very good for query monitoring, but still not enough when users would like to check the details of completed queryies.

Maybe adding a new HTTP path '/druid/v2/history/' to broker node is worth to be considered. To provide this feature, query profiles could be stored in metadata storage (in a new 'queryHistory' table) after executed.

The endpoint could be used in following way:

request:
```
GET {host:port}/druid/v2/history
```
response (listing in time descending):
```
[
  "44349763-b3c1-4a8d-a9f1-5013420b46d0",
  "51e5ddbe-2e4f-403b-bae2-d9331b459dad",
  "7ef67973-2c59-4c7f-ba68-b0d3486c6ba0",
  "1f3b1369-d32e-4e81-bac9-c2331399ed95",
  "304428ad-733d-463e-a9fa-6fc1e9771d61",
  "850f3df5-0fda-4982-848f-44613fc3d50b",
  "2570a8ed-cdbc-49c6-bbe6-06cc28e5f596",
  "23ebd1b6-c212-4025-a286-69808d3cafb5",
  "0634fb43-f14a-47d3-8116-45410d074801"
]
```

request:
```
GET {host:port}/druid/v2/history/44349763-b3c1-4a8d-a9f1-5013420b46d0
```

response:
```
{
  "queryID": "44349763-b3c1-4a8d-a9f1-5013420b46d0",
  "profile": {
    "broker": 45,	// "broker time". The value is equal to metric "query time"
    "druid-middlemanager-1:8102": 3    // "node time". The value is equal to metric "ttfb"
    "druid-historical-1:8102": 40
  },
  "createDate": "2018-03-19T03:11:08.795Z",
  "status": "FINISHED",    // could be either "finished" or "running"
  "datasources": ["table-1"],    // queried datasources. Got from Query.getDataSource().getNames()
  "sql": "SELECT * FROM table-1 LIMIT 10" // sql text. Could be empty if query is a native query.
}
```

**Comment by drcrallen** [comment]
Commented in https://github.com/druid-io/druid/pull/5514#issuecomment-375727112 : Can this be accomplished by a https://github.com/druid-io/druid/blob/druid-0.12.0/server/src/main/java/io/druid/server/log/RequestLogger.java ?
