### ISSUE TITLE
Add getters for AlertEvent

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#5505]
Specific getter methods (getService() and getDataMap()) for AlertEvent were removed as part of #5461 
https://github.com/druid-io/druid/blob/master/java-util/src/main/java/io/druid/java/util/emitter/service/AlertEvent.java
Our internal alerting extension makes use of these methods and consequently they have started failing. If the only reason for the removal was their non-usage, can we get them added back please.
Unfortunately, I missed the PR before it was merged, else I could have raised a concern there. Thoughts @leventov ?

**Comment by leventov** [comment]
`AlertEvent` is not marked as `@PublicApi`. It could be, but other committers should agree on that.

**Comment by gianm** [comment]
I could see a good argument for making AlertEvent, ServiceMetricEvent, and RequestLogEvent public APIs. It's useful to poke at them in emitter extensions.
