### ISSUE TITLE
discrepancy between documentation and example code in 0.12.0

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#5560]
the documentation for all the node configuration mentions the property `druid.plaintextPort` however, the download for 0.12.0  contains configuration that uses propery `druid.port`.

I cant find any documentation for when `druid.port` became `druid.plaintextPort` or which version is preferable. This needs to be clarified somewhere.

**Comment by pdeva** [comment]
in similar vein, config for middle manager should use `druid.indexer.runner.javaOptsArray` instead of deprecated `druid.indexer.runner.javaOpts`

**Comment by pantaoran** [comment]
I can see that the documentation switched from `druid.port` to `druid.plaintextPort` with 0.11.0, but it doesn't say anything about how to transition. Is the previous field now deprecated? We don't know.

On our cluster we have been running 0.12.0 with `druid.port` and that has worked well so far, but now we want to switch to TLS and I'm confused by this change.
