### ISSUE TITLE
Applying doubleSum over doubleFirst aggregations in nested groupBy fails

### ISSUE THREAD

**Issue by kskalski** [apache/incubator-druid#5566]
The query 
`{
      "queryType": "groupBy",
      "dataSource": {
        "type": "query", "query": {
          "queryType": "groupBy",
          "dataSource": "data",
          "aggregations":[{ "type": "doubleFirst", "name": "value_num", "fieldName": "value_num" }],
          "dimensions": ["object_id"],
          "intervals": "2017-06-30T00:00:00/2020-10-02T16:46:40",
          "granularity": "day"
        }
      },
      "intervals": "2017-06-30T00:00:00/2020-10-02T16:46:40", "granularity": "day",
      "aggregations":[{ "type": "doubleSum", "name": "value_num", "fieldName": "value_num"}],
      "dimensions": []
    }`

fails with error:
  `"errorMessage" : "Unknown type[class io.druid.collections.SerializablePair] for field",`
  `"errorClass" : "io.druid.java.util.common.parsers.ParseException",`

**Comment by kskalski** [comment]
Log with stack trace
[log.txt](https://github.com/druid-io/druid/files/1871126/log.txt)

**Comment by mx781** [comment]
It seems that this error is caused by the fact that first/last post-aggregations return a tuple of format
```json
...
             "postAggregatorName": {
                "lhs": 1516581790000,
                "rhs": 1
            },
...
```
where lhs is timestamp and rhs is the value you actually want. Since `finalizingFieldAccess` doesn't work with this (which I think should!), the only option I saw was using a Javascript post-aggregator (if you have it enabled), e.g.

```json
  "type": "javascript",
      "name": "extractedLastCount",
      "fieldNames": ["lastCount"],
      "function": "function(lastCount){ return lastCount.lhs; }"
    }
```

**Comment by lianglingbo** [comment]
how can i use nested groupBy ?

**Comment by kskalski** [comment]
FYI, I got a fix here https://github.com/druid-io/druid/pull/5699 though it is a bit symptomatic, there might be a better way to address it, since this incompatibility of values returned by first/last aggregators might be hitting other places too.

**Comment by jihoonson** [comment]
Hi all,

`DoubleFirstAggregator` returns `SerializedPair`s  which is the intermediate format to merging doubleFirst values from multiple historicals. So, to compute some aggregations like `sum` over `doubleFirst`, you first need to _finalize_ the intermediate result to be the final format which contains only the double value. You can use `expression` postAggregator to do this. Here is an example.

```json
{
  "queryType": "groupBy",
  "dataSource": {
    "type": "query",
    "query": {
      "queryType": "groupBy",
      "dataSource": "twitter",
      "aggregations": [
        {
          "type": "doubleFirst",
          "name": "tweets",
          "fieldName": "tweets"
        }
      ],
      "postAggregations": [
        { "type" : "expression", "name": "tweets_first", "expression" : "tweets" }
      ],
      "dimensions": [
        "lang"
      ],
      "intervals": "2018-07-27/2018-07-28",
      "granularity": "hour"
    }
  },
  "intervals": "2018-07-27/2018-07-28",
  "granularity": "hour",
  "aggregations": [
    {
      "type": "doubleSum",
      "name": "value_num",
      "fieldName": "tweets_first"
    }
  ],
  "dimensions": []
}
```

**Comment by kskalski** [comment]
@jihoonson thanks for the tip, indeed this makes the query work fine. I'm wondering though, if this use-case shouldn't be possible to handle automatically. In fact Druid has the concept of "finalized" and not-finalized values from aggregators and it can apply it correctly to first/last aggregators, which implement that pattern, e.g.:

```
{
    "queryType": "groupBy",
    "dataSource": "pm_data",
    "aggregations":[{ "type": "doubleFirst", "name": "value_num", "fieldName": "value_num" }],
    "dimensions": ["counter_id"],
    "intervals": "2017-06-30T00:00:00/2017-07-02T16:46:40",
    "filters": {"type": "selector", "dimension": "version", "value": "43:48501"},
    "granularity": "day"
}
```

works fine returning just value num without using expression postaggregator. Shouldn't it also apply the same logic in nested query? I suppose outer query will always treat its input as finalized, so in essence the nested query should finalize its results.

Actually, I would like to know how the mechanizm of finalizing results works, since I also had similar problem using Java client classes (_com.simplaex.clients.druid.DruidClient_, which I know is not supported approach, but still might shed some light on the issue here) when executing above (non-nested) group_by query - the client was not able to parse the results correctly, so I suppose there is some trick / special postprocessing / flag forcing finalization of results.

**Comment by jihoonson** [comment]
> I'm wondering though, if this use-case shouldn't be possible to handle automatically.

@kskalski good point. We can do unless there's some use cases to get the non-finalized values from the inner query. Probably someone wants to compute a sort of custom aggregator on the pairs of <timestamp, first/last value>.

> so I suppose there is some trick / special postprocessing / flag forcing finalization of results.

Yes, there is a query context flag, called `finalize`, to get finalized results. `FinalizeResultsQueryRunner` is the query runner which automatically checks this flag and do some necessary work. In `GroupByStrategyV2.mergeResults()`, the broker sets `finalize` to false to get non-finalized results from historicals. Once it merges all results from historicals, it finalizes the merged results. Please check `ClientQuerySegmentWalker.makeRunner()` and `FluentQueryRunnerBuilder.applyPostMergeDecoration()`.

**Comment by sirianni** [comment]
@jihoonson is it safe to explicitly set `"finalized": true` in the inner query `context` as an alternative to using an `expression` `postAggregator`?

I assume the broker will reset `finalized` to `false` so that it gets the unfinalized results from the historicals.  I've tested in a single machine setup, but wanted to confirm that this is expected to work properly in a fully distributed environment with multiple historicals.

```json
{
  "queryType": "groupBy",
  "dataSource": {
    "type": "query",
    "query": {
      "queryType": "groupBy",
      "dataSource": "twitter",
      "aggregations": [
        {
          "type": "doubleFirst",
          "name": "tweets",
          "fieldName": "tweets"
        }
      ],
      "context": {
        "finalize": true
      }
      "dimensions": [
        "lang"
      ],
      "intervals": "2018-07-27/2018-07-28",
      "granularity": "hour"
    }
  },
  "intervals": "2018-07-27/2018-07-28",
  "granularity": "hour",
  "aggregations": [
    {
      "type": "doubleSum",
      "name": "value_num",
      "fieldName": "tweets"
    }
  ],
  "dimensions": []
}
```
