### ISSUE TITLE
More coordinator automated testing

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#5623]
We've had quite a few coordinator bug fixes recently, e.g.:
https://github.com/druid-io/druid/pull/5554
https://github.com/druid-io/druid/pull/5532
https://github.com/druid-io/druid/pull/5529
https://github.com/druid-io/druid/pull/5528

Based on this, I think It's probably good idea for us to develop some more tests around coordinator behavior, at least for the following areas:
- Coordinator leadership changes (to help catch bugs like the one fixed by #5554)
- Segment balancing behavior

**Comment by EungsopYoo** [comment]
I think it would be better to add some performance regression tests.
We got a performance regression of coordinator in 0.12.0.
It will be reported soon.

**Comment by jihoonson** [comment]
@EungsopYoo I believe this issue is about adding a test environment for testing coodinator functionalities. But, performance regression test also sounds good. Would you raise a new issue for it?

**Comment by EungsopYoo** [comment]
@jihoonson 
My colleague will do. It is caused by use of Collection.contains() and is revealed a problem when we have above 200k segments.
