### ISSUE TITLE
Is ZK ACLs allowed and honoured by druid

### ISSUE THREAD

**Issue by varaga** [apache/incubator-druid#5641]
I'm trying to deploy druid cluster in our staging environment in AWS for evaluation of druid. Our ZK ensemble uses role based authorizations. Essentially I don't see a way to provide the ZK credentials to Druid for it's client to authenticate/authorize. I only see zk.base paths and zk host.

I originally raised this question in the users group. Since there wasn't response I presume this is an issue.

**Comment by gianm** [comment]
Hi @varaga, I'm not familiar with what is needed client-side for ZK applications to use role based authorization. Do you have a pointer to the ZK docs or to another project that does what you want? It's possible Druid already supports it, or if not, that it's easy to add.

**Comment by varaga** [comment]
```
builder.authorization("digest", authenticationString.getBytes())
                    .aclProvider(new ACLProvider() {
                        @Override
                        public List<ACL> getDefaultAcl() {
                            return ZooDefs.Ids.CREATOR_ALL_ACL;
                        }

                        @Override
                        public List<ACL> getAclForPath(String path) {
                            return ZooDefs.Ids.CREATOR_ALL_ACL;
                        }
});
```
where builder is a CuratorFramework builder ?

**Comment by gianm** [comment]
@varaga We already have a way to set up the aclProvider: you can set `druid.zk.service.acl=true`. However I think we don't have a way to set up the authorization.

Would you be interested in contributing something here? It should probably be a relatively straightforward addition. The place to start would be in `io.druid.curator.CuratorModule`, which is what creates our CuratorFramework.

**Comment by varaga** [comment]
Hi @gianm  - Apologies for getting back to you late. I had to check in the company to confirm contribution.
So, sure I will contribute this.

**Comment by jihoonson** [comment]
Hi @varaga, you may have done this, but http://druid.io/community/#contributing is a good starting point. We don't currently use JIRA yet, so you can just fork the Druid repository, make a branch for your patch, and make a pull request.

**Comment by varaga** [comment]
@gianm  & @jihoonson  - PR Submitted here: https://github.com/druid-io/druid/pull/5701

**Comment by jon-wei** [comment]
@varaga I reviewed the PR you submitted, also wondering if you've tried adding a JAAS configuration file as a JVM argument described in the "Client Configuration" here: https://cwiki.apache.org/confluence/display/ZOOKEEPER/Client-Server+mutual+authentication#Client-Configuration

I haven't tried that myself though.

**Comment by varaga** [comment]
@jon-wei - I haven't tried adding a JaaS conf file. I believe the mechanism is comparable to read the file vs read through the properties.
