### ISSUE TITLE
SQL: Push down filters from aggregators

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#5643]
We can optimize queries with filtered aggregators but with no GROUP BY columns by pushing down any filters that they all share. For example,

```sql
SELECT
  COUNT(*) FILTER(WHERE col1 = 'abc' AND col2 = 'def'),
  COUNT(*) FILTER(WHERE col1 = 'abc')
FROM tbl
```

Becomes,

```sql
SELECT
  COUNT(*) FILTER(WHERE col2 = 'def'),
  COUNT(*)
FROM tbl
WHERE col1 = 'abc'
```

This allows indexes to be used, and is especially powerful when the pulled-out filter is a time filter.

Note that this optimization cannot be done when there are GROUP BY columns, because then it may affect the results (in this example, it would improperly eliminate groups from the result that originated from table rows where `col1 != 'abc'`).

**Comment by xueyumusic** [comment]
Hi, @gianm , Do you think whether it makes sense if having only one filter aggregation, such as:
```
SELECT
  COUNT(*) FILTER(WHERE col1 = 'abc' AND col2 = 'def')
FROM tbl
```
=>
```
SELECT
  COUNT(*)
FROM tbl
WHERE col1 = 'abc' AND col2 = 'def'
```

**Comment by gianm** [comment]
@xueyumusic, that does make sense too.
