### ISSUE TITLE
Add "taskType" dimension to task metrics

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#5651]
It would be useful for analyzing behavior of specific types of tasks.

This should be doable by looking for places where `DruidMetrics.TASK_ID` is set in metrics today, and adding `DruidMetrics.TASK_TYPE` too. We may want to extract that to a helper method, since it looks like very similar code is written in a few places.

**Comment by kamaci** [comment]
Is this issue closed due to #5664 is merged?

**Comment by gianm** [comment]
Definitely looks like it!
