### ISSUE TITLE
Kafka Emitter does not support RequestLogEvent

### ISSUE THREAD

**Issue by mkuthan** [apache/incubator-druid#5700]
When request logging subsystem is configured to use EmittingRequestLogger and Kafka Emitter extension is configured as a provider, request logs are not emitted at all.

There is no explicit support for Event types other than ServiceMetricEvent and AlertEvent:
https://github.com/druid-io/druid/blob/master/extensions-contrib/kafka-emitter/src/main/java/io/druid/emitter/kafka/KafkaEmitter.java#L171-L181

It should be quite easy to add third topic dedicated for request logs and enhance KafkaEmitter class. 
Finally due to complex Query object in RequestLogEvent, JSON flatten spec could be used during ingestion from Kafka to Druid. Or I missed something?

**Comment by dkhwangbo** [comment]
@mkuthan @jihoonson Hi. It's late comment. I missed mention. @mkuthan 's idea and an outline described is good. Please go ahead If you want to progress.
