### ISSUE TITLE
Is the "Segment Availability" section in coordinator docs still accurate?

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#5713]
The "Segment Availablity" section in the coordinator docs (http://druid.io/docs/latest/design/coordinator.html#segment-availability) suggests that when a historical node goes down, there is a sort of grace period before the segments on that historical node are reassigned.

Is this still the case? I didn't see any configs related to this, and I'm not sure where in the code (if this is still accurate) this is handled.

This topic came up on the druid-user mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/-hfjg0_JM7E/TxExhH_fAQAJ

**Comment by gianm** [comment]
I didn't think there was any grace period beyond the one implied by `replicationThrottleLimit`.
