### ISSUE TITLE
segmentMetadata query: add flag to indicate dimension or metric

### ISSUE THREAD

**Issue by realfun** [apache/incubator-druid#572]
Talked with @fjy over IRC and open an issue below:

Currently segmentMetadata query returns all dimension and metrics at the same time, it would be good to able to distinguish which is dimension and which is metric, adding a flag would help. Adding the flag to the query parameter is even better.

Like:

```
"signin": { "type" : "STRING", "size" : 100000, "cardinality" : 1944, flag: "dimension"},
"count": { "type" : "STRING", "size" : 100000, "cardinality" : 1944, flag: "metric"}
```

It does not have to be named "flag".

**Comment by akshaygoyal** [comment]
Not necessarily. Sometime fields like size, length etc are treated as dimensions, depending on the use case.  
@fjy I am starting up with druid. I would like to take this up as my first piece.

**Comment by fjy** [comment]
@akshaygoyal Cool! Did you already have some ideas about how it could be done or did you want some guidance?

**Comment by akshaygoyal** [comment]
Following is what i am planning to do
1: Enum ColumnType {
    DIMENSION,
    METRIC
}
parallel to enum ValueType.
2: Identifying column type using availableDimensions and availableMetrics collections in storageAdaptor.
3: getColumnType() as new capability in ColumnCapabilities 
4: Required changes around ColumnAnalysis, SegmentAnalyzer and SegmentMetadataQueryRunnerFactory

The final response json would look like 

"signin": { "type" : "STRING", "size" : 100000, "cardinality" : 1944, columnType: "dimension"},
"count": { "type" : "STRING", "size" : 100000, "cardinality" : 1944, columnType: "metric"}

@fjy let me know if this seems right or if I missed something or if there is a better way of doing it.
Thanks in advance for your guidance.

**Comment by akshaygoyal** [comment]
StorageAdapter already has an api with name getColumnTypeName() for the 'type' field.
Need to think of some other name for it instead of ColumnType. 'FieldType' or 'ColumnCategory' maybe.
