### ISSUE TITLE
error wirh quickstart

### ISSUE THREAD

**Issue by thuylevn** [apache/incubator-druid#5798]
hi,
 I am trying to run druid following the guid in http://druid.io/docs/latest/tutorials/quickstart.html

https://user-images.githubusercontent.com/24593553/40419539-f09911dc-5e85-11e8-8816-bf72e43956ab.png

but when I run bin/init it has an error
 [ec2-user@ip-172-30-0-123 druid-0.12.0]$ bin/init
 mkdir: cannot create directory ‘log’: File exists
 [ec2-user@ip-172-30-0-123 druid-0.12.0]$

https://user-images.githubusercontent.com/24593553/40419614-28196102-5e86-11e8-85b6-09ff29482970.png

java cat conf-quickstart/druid/historical/jvm.config | xargs -cp "conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/*" io.druid.cli.Main server historical

https://user-images.githubusercontent.com/24593553/40419689-6178afa2-5e86-11e8-83e9-2965ac4fac16.png

please guid to me how to solved it

**Comment by Dylan1312** [comment]
Hey @ThuyLeVn what version of Java do you have installed? I think AMI comes with Java7 out of the box whereas you need Java8

**Comment by ThuyLeVn** [comment]
I am using java8
![1](https://user-images.githubusercontent.com/24593553/40427258-b3dbef4c-5e8c-11e8-8f56-a9c756e470fb.JPG)

and another question is if I use druid image in docker, how I can run new tasks???

Thanks you so much

**Comment by Dylan1312** [comment]
Could you run `java -version` to check? The screenshot shows a docker image running java8 but your original screenshot shows a bash prompt indicating that the java command wasn't run inside that container.

If you mean ingestion tasks, submitting new tasks should be much the same as normal. POSTing the JSON spec at the overlord running on port 8090.

**Comment by ThuyLeVn** [comment]
hii, this is version 1.8.0_171
May you remind me the way to  submitting new tasks


thanks you so much
ThuyLe

**Comment by ThuyLeVn** [comment]
I meet some problem when work with druid-docker

https://github.com/druid-io/docker-druid

docker pull druidio/example-cluster
docker run --rm -i -p 8082:8082 -p 8081:8081 druidio/example-cluster



when I run task it has an error


do you know how to solved it?

**Comment by vogievetsky** [comment]
In Druid 0.15.0 the startup scripts were redone and in Druid 0.16.0 more Java versions are supported. I believe this can now be closed as solved. Please reopen if there are still issues.
