### ISSUE TITLE
Ask infrastructure to set up issue tracker (JIRA, Bugzilla).

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#5830]
http://incubator.apache.org/projects/druid.html

**Comment by leventov** [comment]
I think this issue should be closed, as well as many others in https://github.com/apache/incubator-druid/projects/3 as either not relevant anymore or done.

**Comment by gianm** [comment]
True, we are using GH issues for this, so I think it's not needed. They are already set up (we are in them right now!!)
