### ISSUE TITLE
SegmentListerResource.getSegments() must return non-void type

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#5853]
When an error occurs in integration tests, the below message is shown instead of the real error.

```
WARNING: The following warnings have been detected with resource and/or provider classes:
  WARNING: A HTTP GET method, public void io.druid.server.http.SegmentListerResource.getSegments(long,long,long,javax.servlet.http.HttpServletRequest) throws java.io.IOException, MUST return a non-void type.
```

**Comment by chillinger** [comment]
I have encountered the exact same issue - this warning occured in my logs as well and the respective real time indexing Jobs lead to missing segments.

How can we fix this?
What is the source of this problem? 
- Connection with the coordinator? 
- The indexer?

Thanks a lot!

**Comment by bryan-dlvr** [comment]
Our indexing tasks is reproducing this as well followed by failure to publish segments.
[log.txt](https://github.com/apache/incubator-druid/files/3404135/log.txt)

**Comment by himanshug** [comment]
@chillinger  and @bryan-dlvr that warning is harmless , please ignore that for now and it will disappear in 0.16.0 release.

**Comment by bryan-dlvr** [comment]
If I'm understanding @jihoonson comment above, he says the warning is logged instead of the real error.  Is that assessment correct?  Or with this fix should we not expect something useful to be logged since you say it is not related to issues we saw?

**Comment by jihoonson** [comment]
Hi @bryan-dlvr, I was testing something when I opened this issue and some error was thrown in `SegmentListerResource.getSegments()` method. But I couldn't see the exact error message or stack trace because of this issue. 

```ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Could not load Logmanager "io.druid.logging.log4j.jul.LogManager"
java.lang.ClassNotFoundException: io.druid.logging.log4j.jul.LogManager
```

From the log file you attached, it looks there is an issue with your logging configuration. Would you please set it properly and then try again? More details messages will be printed.
