### ISSUE TITLE
sql query

### ISSUE THREAD

**Issue by thuylevn** [apache/incubator-druid#5867]
I meet some errors in SQL query in Druid,
 curl -XPOST -H'Content-Type: application/json' http://localhost:8082/druid/v2/sql/ -d '{"query":"SELECT column1, position(\"-\" in column1) as posi, length(column1) as len FROM s3_bigdata_test_sample limit 2"}'

{"error":"Unknown exception","errorMessage":"org.apache.calcite.runtime.CalciteContextException: From line 1, column 39 to line 1, column 41: Column '-' not found in any table","errorClass":"org.apache.calcite.tools.ValidationException","host":null}

Do you know why?

**Comment by vogievetsky** [comment]
Hi you used double quotes `"` to escape your `-`, you need to use single quotes `'` instead.

Try:

```
{"query":"SELECT column1, position('-' in column1) as posi, length(column1) as len FROM s3_bigdata_test_sample limit 2"}
```

**Comment by vogievetsky** [comment]
I believe I solved this issue above. Please reopen if not.
