### ISSUE TITLE
Support limit for timeseries (native and SQL)

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#5894]
The timeseries query should support a `limit` parameter. The main motivation for this is for Druid SQL: people sometimes write a query with a `limit X` that really _should_ be a timeseries, but we can't plan it as one, since timeseries doesn't support limits.

**Comment by gianm** [comment]
A good test case for this would be a SQL query like:

```
select floor(__time to day), count(*) from foo limit 2
```

Which should plan into a timeseries query with a `limit: 2` parameter. But today, it plans into, I think, a topN.

**Comment by fjy** [comment]
Fixed by https://github.com/apache/incubator-druid/pull/5931
