### ISSUE TITLE
clean up loadstatus endpoints

### ISSUE THREAD

**Issue by tarekrached** [apache/incubator-druid#591]
right now, we have:
/loadstatus : getLoadStatus() percent of data available
/loadstatus?simple : getSegmentAvailability()  number of missing segments
/loadstatus?full : getReplicationStatus() per-tier replication status

There are a couple issues with this:  first, the names (simple, full, default) have no indication as to their result.  Second, replication is calculated within each tier, which isn't what we're really looking for.  Third, until a segment is loaded, it shouldn't show up in the availability or replication counts.

I think we could fix it by changing /loadstatus?full to show the (cross-tier) replication and availability as a proportion of total data size for each datasource, like so:  (where 1 is 100 percent)

```
{
  datasource_a: {
    replication: 0.95,
    availability: 1
  },
  datasource_b: {
    replication: 1,
    availability: 1
  },
  ...

```

**Comment by vogievetsky** [comment]
I think the [system tables](http://druid.io/docs/latest/querying/sql#retrieving-metadata) effectively solve this, that is what the web console uses.

**Comment by tarekrached** [comment]
miss u vad ;)
