### ISSUE TITLE
Binding Annotation does not work in Druid extensions

### ISSUE THREAD

**Issue by QubitPi** [apache/incubator-druid#5920]
Our team instantiates [LookupExtractorFactory](https://github.com/druid-io/druid/blob/master/processing/src/main/java/io/druid/query/lookup/LookupExtractorFactory.java) via a constructor that takes an injected parameter. The injected parameter has a [binding annotation](https://github.com/google/guice/wiki/BindingAnnotations#binding-annotations). This annotations causes runtime errors during Druid start. The errors says no implementations for the annotated parameter class is found.

**Comment by jihoonson** [comment]
I'm closing this PR. We can open this again if we have an actual issue.
