### ISSUE TITLE
The annotation handler 'io.druid.annotations.SubclassesMustBePublicAnnotationProcessor' could not be found

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-druid#5955]
When i built the latest druid project locally, i received the error message that `
Error:java: The annotation handler 'io.druid.annotations.SubclassesMustBePublicAnnotationProcessor' could not be found`. Seems that the version of `maven-compiler-plugin` is `3.2`, and cause the plugin could not support [annotation processing](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths) feature. Maybe we should upgrade the version into `3.5.1`?

**Comment by leventov** [comment]
@asdf2014 make sure to read the discussion at https://github.com/druid-io/druid/issues/5849

**Comment by asdf2014** [comment]
I see. Thanks.

**Comment by asdf2014** [comment]
I confirm that after upgrading Intellij's idea to v2018.2, it no longer happens.
