### ISSUE TITLE
Adjust HadoopDruidIndexer to allow for pulling credentials out of something other than the config

### ISSUE THREAD

**Issue by cheddar** [apache/incubator-druid#60]
The HadoopDruidIndexer currently requires various credentials (namely the DB) to exist in the config, it would be easier to share those configs around if we didn't require that and instead took them from a runtime.properties file like all the other processes do.

**Comment by gianm** [comment]
Looks no longer relevant, since these days the `index_hadoop` task takes configs from runtime properties.
