### ISSUE TITLE
Missing exception handling as part of `io.druid.java.util.http.client.netty.HttpClientPipelineFactory`

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#6024]
The `io.druid.java.util.http.client.netty.HttpClientPipelineFactory` class constructs the netty pipeline for handling request channels. But whenever an exception happens in reading (for example a historical shuts down during a query) The following log line is printed in the logs:

```
EXCEPTION, please implement org.jboss.netty.handler.codec.http.HttpContentDecompressor.exceptionCaught() for proper handling.
```

As can be seen in `org.jboss.netty.channel.SimpleChannelUpstreamHandler#exceptionCaught`

This ask is that "proper" exception handling be implemented in the http client workflow such that the logs do not have such an error when there are exceptions in the netty channel.

**Comment by asdf2014** [comment]
Hi, @drcrallen . Perhaps this issues should be closed.

**Comment by jihoonson** [comment]
@asdf2014 thanks for checking. I think we can close this issue now.
