### ISSUE TITLE
"Build from Source" page states an outdated JDK version 7

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6030]
[Copied from [website issue #470](https://github.com/druid-io/druid-io.github.io/issues/470)]

Problem:
The documentation page [Build from Source](http://druid.io/docs/latest/development/build.html) states the following:

`Building Druid requires the following: - JDK 7 or JDK 8`

While in fact Druid mandates JDK 8 since version 0.10.0 (as evident in Druid pr #3914 by @gianm).

Solution:
Remove the text "JDK 7 or ".

**Comment by jihoonson** [comment]
@yurmix thanks. Do you want to make a PR for this issue?

**Comment by yurmix** [comment]
Oh, actually I have made one already: https://github.com/apache/incubator-druid/pull/6031
(I have mentioned the issue there, but not vice versa.)
