### ISSUE TITLE
Duplicate DataSegmentTest

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#6064]
Seems that `io.druid.timeline.DataSegmentTest` is duplicated in druid-api and druid-server modules.

**Comment by asdf2014** [comment]
BTW, in addition to this place, there are a lot of `duplicate code` problems, about 349. :sweat_smile:

![image](https://user-images.githubusercontent.com/8108788/43435338-2b35b4e6-94b2-11e8-8bd2-9e3921c2b56b.png)
