### ISSUE TITLE
SQL bug of avg function

### ISSUE THREAD

**Issue by hellobabygogo** [apache/incubator-druid#6085]
`{
	"query":"explain plan for select  AVG(queryTime) from druid_request_log where __time >= timestamp '2018-08-01 16:19:09' group by dataSource ",
	"context":{"sqlTimeZone":"Asia/Shanghai"}
}`

`[
    {
        "PLAN": "DruidQueryRel(dataSource=[druid_request_log], intervals=[[2018-08-01T08:19:09.000Z/146140482-04-24T15:36:27.903Z]], dimensions=[[DefaultDimensionSpec{dimension='dataSource', outputName='d0', outputType='STRING'}]], aggregations=[[Aggregation{aggregatorFactories=[LongSumAggregatorFactory{fieldName='queryTime', expression='null', name='A0:sum'}, CountAggregatorFactory{name='A0:count'}], postAggregator=ArithmeticPostAggregator{name='a0', fnName='quotient', fields=[FieldAccessPostAggregator{name='null', fieldName='A0:sum'}, FieldAccessPostAggregator{name='null', fieldName='A0:count'}], op=QUOTIENT}, finalizingPostAggregatorFactory=null}]])\n"
    }
]`

the avg fucntion defined in calcite avg(x) = sum(x) / count(X). but if the metric x is longSum aggregator
the avg(x) = sum(x) / sum('"count").

**Comment by gianm** [comment]
Hi @hellobabygogo, currently, Druid SQL is not rollup-aware. So for average on a rolled up datasource you should instead write: `select sum(queryTime) / sum("count")`.

**Comment by hellobabygogo** [comment]
@gianm hi, thanks for reply.    I agree with your suggestion that used sum(queryTime) / sum("count") to instead of avg(queryTime) , but  its users Unfriendly!  May be we need forbid avg function.
