### ISSUE TITLE
DOCS:  ingestion spec documentation should be expanded

### ISSUE THREAD

**Issue by dyanarose** [apache/incubator-druid#6100]
- The dataSchema would be much clearer if an example of the raw data was included.
- The importance of the metric spec would be clearer if there was a dedicated section explaining how it's used when querying along with example queries that are made possible by the example metrics spec (some information is spread out in the design document and the schema-design document, but the metricSpec should have it's own dedicated and complete documentation)

https://github.com/apache/incubator-druid/blob/master/docs/content/ingestion/index.md

**Comment by gianm** [comment]
@jon-wei has been working on some new docs; @jon-wei do you know if your work is related to these points?

**Comment by jon-wei** [comment]
we have a new tutorial that gives more information on the ingestion spec: http://druid.io/docs/latest/tutorials/tutorial-ingestion-spec.html

**Comment by vogievetsky** [comment]
The ingestion docs have been completely rewritten for 0.16.0: https://druid.apache.org/docs/latest/ingestion/index.html

Closing as solved
