### ISSUE TITLE
Ability to specify list of task ports

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#6154]
In some environments (like containerized environments without isolated network stacks) it is desirable to decide ahead of time exactly what ports your services are going to use. In Druid the main thing stopping this from being easy is the fact that peons have a startPort that you can set, but then they'll use ports potentially above that, and you don't have a ton of control over how high they'll go.

It would be nice to be able to provide a `druid.indexer.runner.ports = [8100, 8101, 8102]` config as an alternative to `druid.indexer.runner.startPort`.

**Comment by KenjiTakahashi** [comment]
+1.
We have a use case where Druid and all its' deps are on Linux, in Docker containers. But the ingestion service is on Windows (don't ask) and using EventReceiver, so we have to expose peons to the outside. Right now, we're just exposing ports `8100-8200` right away and it's usually enough, but it is not ideal, ofc.

Maybe it is good idea to (also?) give option to supply range, like above, to avoid having to set a possibly quite long config array? Just a thought.

**Comment by QiuMM** [comment]
+1.
We have met port conflicts because of running middle manger on Docker containers. If more than two middle manger instance run on a same machine, It may lead to conflict.  The way we solve this problem is similar to your suggestion.
