### ISSUE TITLE
extensions not updated for 0.12.2

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#6164]
example, io.druid.extensions.contrib:druid-redis-cache the latest version remains 0.12.1

**Comment by gianm** [comment]
It seems to be an oversight, we didn't publish extensions for 0.12.2 yet. Will check into it.

**Comment by gianm** [comment]
I just published these to the Central Repository. Usually, it takes a few hours for caches and whatnot to reflect that.
