### ISSUE TITLE
TimeBoundary, DataSourceMetadata filterSegments flawed with overlapping segments

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#6177]
The "interval" on a LogicalSegment corresponds to the timeline object holder interval, meaning that with overlapping segments, it is only the queryable part. This means that the code in filterSegments of both timeBoundary and dataSourceMetadata is flawed. It looks like this in both of them:

```java
    final T min = query.isMaxTime() ? null : segments.get(0);
    final T max = query.isMinTime() ? null : segments.get(segments.size() - 1);

    return Lists.newArrayList(
        Iterables.filter(
            segments,
            input -> (min != null && input.getInterval().overlaps(min.getInterval())) ||
                   (max != null && input.getInterval().overlaps(max.getInterval()))
        )
    );
```

But because of how "interval" works on the LogicalSegments, `input.getInterval()` for two different LogicalSegments will never overlap. This causes erroneous results in cases like this:

- Segment A is 2017/2018 (YEAR granularity) and has data up through May 2017.
- Segment B is 2017-08-01/2017-08-02 (DAY granularity) and has data for August 1 2017.

In this case, three LogicalSegments are returned:

- 2017/2017-08-01
- 2017-08-01/2017-08-02
- 2017-08-02/2018

And the filterSegments methods on these two query types will only inspect the last LogicalSegment, meaning they'll miss the _actual_ max time, which is in the 2017-08-01/2017-08-02 holder.

**Comment by himanshug** [comment]
Problem could be with expectation as well. Segment-A's interval doesn't reflect the actual data it contains. If indexing was done with data being available until May-2017, segment granularity should've been chosen to be monthly.
"fixing" it would probably mean doing no filtering at broker because we don't peek inside the segment at that point.

**Comment by gianm** [comment]
I think we could filter at the broker, we just want to check any segment that overlaps with the one that has the latest chunk. So in the example above we should have checked any segment that overlaps with 2017/2018. We could still safely ignore anything from prior to 2017.
