### ISSUE TITLE
Docker based environment for developers

### ISSUE THREAD

**Issue by amitabak** [apache/incubator-druid#6183]
We need a small scale docker based environment for development purposes that will fit a developers laptop. Nothing fancy. Minimal set of replications that will conform to Druid basic minimal configuration and at the same time will run all the examples without a single failure as startpopint.

**Comment by b-slim** [comment]
is this one https://github.com/druid-io/docker-druid not good enough ? i can run it on my work station.

**Comment by vogievetsky** [comment]
This is part of 0.16.0 yo: https://github.com/apache/incubator-druid/issues/8369#docker

Solved :-D
