### ISSUE TITLE
select query slow beyond believe

### ISSUE THREAD

**Issue by sixtus** [apache/incubator-druid#619]
reading a data source with 49 dimensions and 33 aggregations, I get:

threshold => request time
10 => 1.4s
100 => 6.7s
1000 => 77s

Based on these numbers, I'd take ~16 years to read a single day of data.

On IRC, other people could verify the slowness.

**Comment by vogievetsky** [comment]
I think the new scan query fixes this! 🎆 
@fjy I think this can be closed.
