### ISSUE TITLE
How can i load data without timestamp? please provide any solution if it is there.

### ISSUE THREAD

**Issue by ranjan321** [apache/incubator-druid#6196]
Loading json which is not having any timestamp field.but not able to load as it is throwing exception timestampSpec is not available.

**Comment by QiuMM** [comment]
Data load to Druid must have a timestamp field, you can preprocess your data to add one.

**Comment by ghulands** [comment]
@QiuMM that is not accurate. If you have data that is partitioned and are ingesting it based on that partitioning you don't have to have a column in that data to contain an actual timestamp. You can specify the timestamp spec as follows

"timestampSpec": {
              "format": "yyyy-MM-dd",
              "column": "ts",
              "missingValue": "2018-08-20"
          }

ts does not need to exist.

Hope that helps @ranjan321

**Comment by QiuMM** [comment]
@ghulands Got it, thanks for your reminder.

**Comment by ranjan321** [comment]
@ghulands Thanks for your input..it is perfectly working fine
