### ISSUE TITLE
[Documentation] About Direct Memory

### ISSUE THREAD

**Issue by QiuMM** [apache/incubator-druid#6198]
In current doc, it says the amount of direct memory needed by Druid is at least 

`druid.processing.buffer.sizeBytes * (druid.processing.numMergeBuffers + druid.processing.numThreads + 1)`. 

But for realtime and historical nodes they need direct memory for mmap, so the java `MaxDirectMemorySize` should set to more larger than this value. Am I right? Or the memory needed for mmap is already covered by this value?

**Comment by josephglanville** [comment]
mmaped files are not considered direct memory AFAICT but yes, realtime nodes, peons and historicals all need memory in reserve for the Linux page cache which is responsible for paging files the have been mmaped in and out of memory.

**Comment by QiuMM** [comment]
I have figured it out. Thanks.
