### ISSUE TITLE
Coordinator console should make use of druid.segmentCache.locations:maxSize for historical nodes

### ISSUE THREAD

**Issue by ethanocentricity** [apache/incubator-druid#622]
The rules for determining available space on a historical node for a segment seem to include both druid.server.maxSize and druid.segmentCache.locations:maxSize.

However, the Coordinator Console shows the Max Size and Percent Used based only on druid.server.maxSize.

It would be useful if the console showed both values to help diagnose "segment too large" errors thrown by the OmniSegmentLoader (when people accidentally set them to different values).

See https://groups.google.com/forum/#!searchin/druid-development/segment$20too$20large/druid-development/w8Q65ZRusi4/kN0JybUtUfAJ

**Comment by jkukul** [comment]
These two configurations seem redundant to me and have always caused a lot of confusion. Could we get rid of one of them? 

I found two other issues suggesting to do so (https://github.com/apache/incubator-druid/issues/373 and https://github.com/apache/incubator-druid/issues/798), unfortunately both were closed without much explanation.

**Comment by vogievetsky** [comment]
This is handled much better by the new console

![image](https://user-images.githubusercontent.com/177816/65644463-22edfd00-dfa9-11e9-8c2a-14dd41e8dd7c.png)

Closing as effectively solved. Please reopen if needed.
