### ISSUE TITLE
opentsdb emitter occupy 100% core

### ISSUE THREAD

**Issue by hefei1986** [apache/incubator-druid#6247]
We use opentsdb emitter to transfer metrics to opentsdb. But we found that the OpentsdbSender occupied 100% of one core. 

![image](https://user-images.githubusercontent.com/1287334/44651691-a347d480-aa1c-11e8-8179-1f2db2970767.png)

![image](https://user-images.githubusercontent.com/1287334/44651648-84e1d900-aa1c-11e8-9f29-a77c18931b14.png)
 
![image](https://user-images.githubusercontent.com/1287334/44651878-0cc7e300-aa1d-11e8-8691-c9c0849b85e1.png)

when the eventQueue is empty, a loop will happen.

**Comment by hefei1986** [comment]
add Thead.sleep(INTERVAL) logic may fix the prob.

**Comment by QiuMM** [comment]
Thanks for your report, I will fix this problem in a few days.
