### ISSUE TITLE
Securing truststore passwords used for SSL connections to Kafka

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#6265]
Presently for Kafka indexing service, connecting to Kafka via SSL would require the user to add the keystore and truststore passwords as plaintext data in the `consumerProperties` section. This information is visible from the supervisor spec in the overlord console as well as the task logs. This could probably be fixed by plugging in a PasswordProvider implementation for these properties or maybe reuse the keystore info from the `druid.server.https.keyStorePassword` property. Any thoughts?

**Comment by jon-wei** [comment]
> This could probably be fixed by plugging in a PasswordProvider implementation

I think that would work, you could adjust the consumerProperties and resolve the PasswordProviders in `getKafkaConsumer()`.

> or maybe reuse the keystore info from the druid.server.https.keyStorePassword property

I think the PasswordProvider or another mechanism would be better, there's no guarantee that the truststore needed for connecting to kafka would have the same password as the truststore/keystore used by Druid.

**Comment by a2l007** [comment]
Makes sense. I'll work on getting a PR out for this.
