### ISSUE TITLE
Segment Metadata Queries

### ISSUE THREAD

**Issue by Oscer2016** [apache/incubator-druid#6280]
### post json:
{
  "queryType":"segmentMetadata",
  "dataSource":"sample_datasource",
  "merge":"true",
  "intervals":["2018-08-30/2018-08-31"]
}
### return info:
[ {
  "id" : "some_id",
  "intervals" : [ "2018-08-30T00:00:00.000Z/2018-08-31T00:00:00.000Z" ],
  "columns" : {
    "__time" : { "type" : "LONG", "hasMultipleValues" : false, "size" : 0, "cardinality" : null, "errorMessage" : null },
    "dim1" : { "type" : "STRING", "hasMultipleValues" : false, "size" : 0, "cardinality" : 1944, "errorMessage" : null },
    "dim2" : { "type" : "STRING", "hasMultipleValues" : true, "size" : 0, "cardinality" : 1504, "errorMessage" : null },
    "metric1" : { "type" : "FLOAT", "hasMultipleValues" : false, "size" : 0, "cardinality" : null, "errorMessage" : null }
  },
  "aggregators" : {
    "metric1" : { "type" : "longSum", "name" : "metric1", "fieldName" : "metric1" }
  },
  "queryGranularity" : {
    "type": "none"
  },
  "size" : 0,
  "numRows" : 5000000
} ]
## when I use segment metadata queries, it return per-segment information, but size field always is 0. How should I solve this problem?thanks~

**Comment by Oscer2016** [comment]
@agile @trotter @mcroydon @StFS @housejester

**Comment by doctording** [comment]
druid 0.12.3
+1
I'm sure that segment data is not none and `numRows=113`, but `size=0` returned

**Comment by gianm** [comment]
You need to enable some extra analysisTypes -- check the Druid docs for what they do.

**Comment by doctording** [comment]
thanks, such `size` can be got in the other way.  Is there some losses by setting `druid.query.segmentMetadata.defaultAnalysisTypes`, eg. query efficiency or resource consumption

**Comment by vogievetsky** [comment]
@doctording the more `analysisTypes` you have the slower the query will be so it is better to be conservative. Closing as solved.
