### ISSUE TITLE
Does not work with Java 10

### ISSUE THREAD

**Issue by swapneeldatta** [apache/incubator-druid#6282]
On starting, it throws exceptions regarding not finding javax.xml.bind, which was removed from Java 10. I fixed this by adding --add-modules java.xml.bind. Then it fails because of this error `java.lang.NoClassDefFoundError: sun/misc/Perf`.
Some of the features of this project require unsafe or deprecated APIs of Java 8 and need to be fixed.

OS: debian 9
JVM: Oracle JDK 10

**Comment by RestfulBlue** [comment]
#5589
