### ISSUE TITLE
[DRAFT] Druid 0.12.3 release notes

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#6288]
# DRAFT

Druid 0.12.3 contains stability improvements and bug fixes from 6 contributors. Major improvements include:

- More stable Kafka indexing service
- Several query bug fixes

The full list of changes is here: https://github.com/apache/incubator-druid/pulls?q=is%3Apr+milestone%3A0.12.3+is%3Aclosed

Documentation for this release is at: http://druid.io/docs/0.12.3

### More stable Kafka indexing service

0.12.3 fixes a serious issue where the Kafka indexing service would incorrectly delete published segments in certain situations. Please see #6155, contributed by @gianm, for details.

Other stability improvements include:
* Fix NPE in KafkaSupervisor.checkpointTaskGroup: #6206, added by @jihoonson 
* Fix NPE for taskGroupId when rolling update: #6168, added by @jihoonson 

### Query bug fixes

0.12.3 includes a memory allocation adjustment for the GroupBy query that should reduce heap usage. Added by @gaodayue in #6256.

This release also contains several fixes for the TopN and GroupBy queries when numeric dimension output types are used. Added by @gianm in #6220.

#### SQL fixes

Additionally, 0.12.3 includes the following Druid SQL bug fixes:

* Fix post-aggregator naming logic for sort-project: https://github.com/apache/incubator-druid/pull/6250
* Fix precision of TIMESTAMP types: https://github.com/apache/incubator-druid/pull/5464
* Fix assumption that AND, OR have two arguments: https://github.com/apache/incubator-druid/pull/5470
* Remove useless boolean CASTs in filters: https://github.com/apache/incubator-druid/pull/5619
* Fix selecting BOOLEAN type in JDBC: https://github.com/apache/incubator-druid/pull/5401
* Support projection after sorting in SQL: #5788
* Fix missing postAggregations for Timeseries and TopN: #5912 
* Finalize aggregations for inner queries when necessary #6221

### Other

0.12.3 fixes an issue with the `druid-basic-security` extension where non-coordinator nodes would sometimes fail when updating their cached views of the authentication and/or authorization tables from the coordinator. Fixed by @gaodayue in #6270.

### Full change list

The full change list can be found here: https://github.com/apache/incubator-druid/pulls?q=is%3Apr+milestone%3A0.12.3+is%3Aclosed

## Updating from 0.12.2 and earlier
0.12.3 is a minor release and compatible with 0.12.2. If you're updating from an earlier version than 0.12.2, please see release notes of the relevant intermediate versions for additional notes.

## Credits
Thanks to everyone who contributed to this release!

@gaodayue
@gianm
@jihoonson
@jon-wei
@QiuMM
@vogievetsky
@wpcnjupt

**Comment by quenlang** [comment]
Do you have any plan to release this version ?

**Comment by jon-wei** [comment]
@quenlang Yes, 0.12.3 will be the next release, and the first release candidate 0.12.3-rc1 is available now.
