### ISSUE TITLE
OpentsdbEmitter fails sending tags whose value contains ":"

### ISSUE THREAD

**Issue by hefei1986** [apache/incubator-druid#6292]
some metric contains  "host => hostname:port",  bug ":" is not a valid name in opentsdb. 

![image](https://user-images.githubusercontent.com/1287334/44974797-45bf0500-af93-11e8-8a16-4020b3946c3b.png)
http://opentsdb.net/docs/build/html/user_guide/writing/index.html#metrics-and-tags

**Comment by hefei1986** [comment]
I use opentsdb2.3.0~ which version do u use? @QiuMM

**Comment by QiuMM** [comment]
I'm not clear, sorry. It's a service provided by other departments of our company. Maybe there are some difference between the open-source. Can you provide your log about this fail.

**Comment by QiuMM** [comment]
Anyway, I fixed this in #6251.
