### ISSUE TITLE
Moving Average query type

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6320]
# [Feature] Moving Average query type
## A new query type, wrapping groupBy/timeseries, optimized for performing moving-average calculations.
Notes: 
* While this feature can be relevant when discussing Druid and [Window Functions](https://en.wikibooks.org/wiki/Structured_Query_Language/Window_functions), it is a very scoped and limited implementation of the subject.
* The concept of moving average is also known as rolling average or running average.

## Background:
In general terms, a Moving Average is a calculation performed on top of a time series, in order to smooth out fluctuations. 

Below is an example of the smoothing effect of a moving average function:
![An example of two moving average curves](https://upload.wikimedia.org/wikipedia/commons/d/d9/MovingAverage.GIF "An example of two moving average curves")

A simple example would be a trailing seven-day average for page views. The value of each day in the result would be the average page views of the last 7 days for that day:

![](https://latex.codecogs.com/gif.latex?trailingPageViews=\frac{\sum_{i=day-6}^{day}pageViews_i}{7})

An additional theoretical background can be found on the subject’s Wikipedia page (titled [Moving Average](https://en.wikipedia.org/wiki/Moving_average)).

## Problem:
Currently, In order to compute a moving average with Druid, one would need to union multiple Timeseries/GroupBy queries, one per day of the result.
In addition to being a cumbersome solution, that approach is also less efficient, as it requires multiple passes per row.

## Solution:
We propose a new query type, **movingAverage**, which wraps [groupBy query](http://druid.io/docs/latest/querying/groupbyquery.html) (Or [timeseries query](http://druid.io/docs/latest/querying/timeseriesquery.html) when there are no dimensions). 

At high level, the movingAverage is doing the following:
1. Run an inner query (of type groupBy or timeseries) to get initial daily aggregations.
2. Computes the moving-average function based on inner query results. This phase is done in the broker only and not re-reading segment data.
3. Return combined records with both the simple aggregation and the moving average.

This allows the query to avoid multiple segment passes and aggregations per granularity period.

In order to allow a flexible definition of the moving average function, movingAverage query introduces a new interface called **Averager**. The averager is somewhat similar to the **Aggregator**, but while the Aggregator's input is a metric from the datasource, the Averager's input as an Aggregator from the query.

## Example:
This example is based on the `wikipedia` datasource available via the [tutorial examples package](http://druid.io/docs/latest/tutorials/tutorial-examples.tar.gz).

The supplied datasource has only a single-day worth of data, so we will use 30-minute periods instead of the usual daily period.
_Note: I have chosen a granularity period of 30 minutes in order to have enough data points. In reality, the current implementation doesn't fully support sub-daily granularity, but should require only minor changes to accommodate such an enhancement._

Let's use the `delta` metric in the `wikipedia` datasource.
Say we want to compute the 7-period mean average over 30-minute periods of `delta`.
We will define both an aggregator and an averager for this task using the movingAverage query syntax:

```json
{
  "queryType": "movingAverage",
  "dataSource": "wikipedia",
  "granularity": {
    "type": "period",
    "period": "PT30M"
  },
  "intervals": [
    "2015-09-12T00:00:00Z/2015-09-13T00:00:00Z"
  ],
  "aggregations": [
    {
      "name": "delta30Min",
      "fieldName": "delta",
      "type": "longSum"
    }
  ],
  "averagers": [
    {
      "name": "trailing30MinChanges",
      "fieldName": "delta30Min",
      "type": "longMean",
      "buckets": 7
    }
  ]
}
```

Note that this syntax is derived from groupBy, with adding the **averages** JSON Object:

**name**: Output name.
**fieldName**: Input (aggregator) name.
**type**: Formula type (longMean/doubleMean/doubleMax/etc. Full list will be included in the documentation).
**bucket**: Number of buckets to look back.

The result is inherited from the groupBy format:
```json
[ {
  "version" : "v1",
  "timestamp" : "2015-09-12T00:30:00.000Z",
  "event" : {
    "delta30Min" : 30490,
    "trailing30MinChanges" : 4355.714285714285
  }
}, {
  "version" : "v1",
  "timestamp" : "2015-09-12T01:00:00.000Z",
  "event" : {
    "delta30Min" : 96526,
    "trailing30MinChanges" : 18145.14285714286
  }
}, {
  "version" : "v1",
  "timestamp" : "2015-09-12T01:30:00.000Z",
  "event" : {
    "delta30Min" : 87887,
    "trailing30MinChanges" : 30700.428571428572
  }
}, {
  "version" : "v1",
  "timestamp" : "2015-09-12T02:00:00.000Z",
  "event" : {
    "delta30Min" : 254632,
    "trailing30MinChanges" : 67076.42857142857
  }
} ]
```

A graph of the result will show a smoothing effect:
![](https://docs.google.com/spreadsheets/d/e/2PACX-1vRBMWvSs2IFuEHfCqWWdLgXQng512RnyenX9aeST7mG-haqcAZrXDCm_m2HT25adbKf6Op-e33npJTm/pubchart?oid=685921408&format=image)

There are a few more advanced aspects to the implementation and usage of movingAverage. Those will be available in the pull request (via the code and the documentation).

## Future work

Phase 1: Add more existing features which are already implemented
- [ ] Datasketches.
- [ ] Median averagers.
- [ ] Sum averagers.

Phase 2:  Integrate with SQL
- [ ] Support SQL-compatible null-handling.
- [ ] Druid SQL.

Phase 3: Refactoring
- [ ] Reimplement averagers as part of the query engine (Benefits: cleaner iteration and aggregation implementation, seamless integration with other features).

**Comment by like1008** [comment]
I am very interested in the Moving Average query type, when will you commit your codes?

**Comment by yurmix** [comment]
@like1008, please check back next week, I hope to have it available for review by then.

**Comment by yurmix** [comment]
@like1008 please see the attached pr.

**Comment by like1008** [comment]
thanks, it helps me a lot!

**Comment by b-slim** [comment]
Very High level questions:

- When collecting the results of the inner query to compute the moving AVG, is it done in a streaming fashion or you are materializing/buffering the entire result set to run the bucket based trailing aggregate?
-  In your example i see `"type": "longMean"` and the result is a floating point number, that seems odd to me.

**Comment by b-slim** [comment]
One more question:
In your example i see that the first data point has 
```json
"event" : {
    "delta30Min" : 30490,
    "trailing30MinChanges" : 4355.714285714285
  }
```
not sure what am missing here but isn't for the first data point `delta30Min` should be equal to `trailing30MinChanges`

**Comment by b-slim** [comment]
And Another question:
In general Druid users use a column called count in conjunction with the XXXSum column to derive AVG when Rolling up of rows occurs, does your feature take that into consideration?

**Comment by yurmix** [comment]
Thanks @b-slim, sorry for the very late response, here are my answers:

> When collecting the results of the inner query to compute the moving AVG, is it done in a streaming fashion or you are materializing/buffering the entire result set to run the bucket based trailing aggregate?

The query uses `Sequence` all the way, but effectively I've seen that all groupBy iteration finishes before movingAverage iteration starts.
Please see [`MovingAverageQueryRunner@run()`](https://github.com/apache/incubator-druid/pull/6430/files#diff-41837c2a60693bdeee35530e5dcfc6d5R91).

> In your example i see `"type": "longMean"` and the result is a floating point number, that seems odd to me.

`longMean` consumes `Long` Aggregator but returns `Double`. I can see how this is confusing and I'll look into changing that.

**Comment by yurmix** [comment]
@b-slim :

> In your example i see that the first data point has <...> not sure what am missing here but isn't for the first data point `delta30Min` should be equal to `trailing30MinChanges`

The formula for the `longMean` averager is roughtly `sum(range(n))/n`, where `n` is the number of buckets. 
Here's the computation for the first record:
`trailing30MinChange = sum(delta30Min[i-6..i0])/7 = sum(delta30Min[i0..i0])/7 = sum(delta30Min[i0])/7 = 30490/7 = 4355.714285714285`.

There are two happening regarding to `intervals` which I should clarify:

* movingAverage takes the `intervals` defined by the user and expands with an offset it when running groupBy query. This allows the averager to iterate over all N buckets contributing to a record, even for periods not part of the original `intervals`. The additional time range will not be displayed but its data will contribute to the aggregator result. This is done [here](https://github.com/apache/incubator-druid/pull/6430/files#diff-41837c2a60693bdeee35530e5dcfc6d5R109)).

* When querying the datasource's "beginning of time", there will be a noticable drop of value for the first few rows, as you noticed in your comment. This is because the prior buckets for these records are empty.

To clarify, here's an example of a datasource and a result:

Datasource:

date       | metric
-----------|-------
12/23/2017 | 3     
12/24/2017 | 3     
12/25/2017 | 3     
12/26/2017 | 3     
12/27/2017 | 3     
12/28/2017 | 3     
12/29/2017 | 3     
12/30/2017 | 3     
12/31/2017 | 3     
01/01/2018 | 9     
01/02/2018 | 9     
01/03/2018 | 9     
01/04/2018 | 9     
01/05/2018 | 9     
01/06/2018 | 9     
01/07/2018 | 9     
01/08/2018 | 9     
01/09/2018 | 9     

Query #1 - Last 7 days averager, Interval Jan-2018:
`{"queryType": "movingAverage", "granularity" :{"period":"P1D"}, "intervals": ["2018-01-01/2018-01-09"], "averagers": {"buckets":7}}`
(I skipped a few parameters here).

Result #1:

date       | metric | averager 
-----------|--------|----------
01/01/2018 | 9      | 3.9      
01/02/2018 | 9      | 4.7      
01/03/2018 | 9      | 5.6      
01/04/2018 | 9      | 6.4      
01/05/2018 | 9      | 7.3      
01/06/2018 | 9      | 8.1      
01/07/2018 | 9      | 9.0      
01/08/2018 | 9      | 9.0      
01/09/2018 | 9      | 9.0      

Query #2 - Last 7 days averager, All time:
`{"queryType": "movingAverage", "granularity" :{"period":"P1D"}, "intervals": ["2017-01-23/2018-01-09"], "averagers": {"buckets":7}}`

Result #2:

date       | metric | averager 
-----------|--------|----------
12/23/2017 | 3      | 0.4      
12/24/2017 | 3      | 0.9      
12/25/2017 | 3      | 1.3      
12/26/2017 | 3      | 1.7      
12/27/2017 | 3      | 2.1      
12/28/2017 | 3      | 2.6      
12/29/2017 | 3      | 3.0      
12/30/2017 | 3      | 3.0      
12/31/2017 | 3      | 3.0      
01/01/2018 | 9      | 3.9      
01/02/2018 | 9      | 4.7      
01/03/2018 | 9      | 5.6      
01/04/2018 | 9      | 6.4      
01/05/2018 | 9      | 7.3      
01/06/2018 | 9      | 8.1      
01/07/2018 | 9      | 9.0      
01/08/2018 | 9      | 9.0      
01/09/2018 | 9      | 9.0

**Comment by yurmix** [comment]
@b-slim 

> In general Druid users use a column called count in conjunction with the XXXSum column to derive AVG when Rolling up of rows occurs, does your feature take that into consideration?

I'm not sure if I understand correctly, I'll try to answer though.
With Aggregators and Post-Aggregators, one could count and sum values using two aggregators, then combine them in a post aggregator to get the average. (Not a moving average but a simple arithmetic average).

Averager calculation is done completly separately from Aggregators code (although aggregator is an input to the averager computation). An example for an Averager calculation: [`DoubleMeanAverager@computeResult()`](https://github.com/apache/incubator-druid/pull/6430/files#diff-08f4829cb1dcb4ea5ebee703daa17189R32).

**Comment by yurmix** [comment]
Also worth noting is the written documentation: 
https://github.com/apache/incubator-druid/blob/1d9884792cb162433fc2d3b9c6728e132d9b5853/docs/content/development/extensions-contrib/moving-average-query.md

**Comment by jon-wei** [comment]
@yurmix Sorry, I've been meaning to review this, but I have been pretty busy handling 0.14.0-incubating release items recently, I'll have more time after that settles down

**Comment by jihoonson** [comment]
@yurmix thanks for the proposal. Would you please explain what is the different between Averager and PostAggregator?

**Comment by yurmix** [comment]
@jihoonson The similarity between `PostAggregator` and `Averager` is that they both run post the query aggregation. They run in the Broker on the aggregated resultset. But while `PostAggregator` works on a single `Row` in the post-aggregation result set, `Averager` aggregated data over multiple Rows.

How? Averagers collects previous records into a buffer (called `BaseAverager.buckets`) and uses that to compute a moving-average result for each Row. In the code, there is a collaberation between `Averager` and `MovingAverageIterable` to iterate over GroupBy's result-set while keeping a buffer and while returning the averager's result per each record.

You can take a look at MovingAverageIterable and how `MovingAverageIterable#computeMovingAverage()` is calling `Averager#getResult()` -> `BaseAverager#computeResults()`.
https://github.com/apache/incubator-druid/pull/6430/files#diff-0cbedd32f92fe9f41d7c47a628a2974fR270

**Comment by jihoonson** [comment]
@yurmix great! I'll take a look!

**Comment by yurmix** [comment]
Fixed with #6430

**Comment by shrutigs** [comment]
Do we have support for Sum averagers? Checked documentation  didn't find any "type" to get longSum

**Comment by yurmix** [comment]
@shrutigs the community version doesn't support it yet. I have it working internally though and I'll make sure to add it in a later version (probably 0.17.0 as 0.16.0 is in code freeze).

**Comment by birTiwana** [comment]
I noticed that `moving-average-query` has a **having** property. But can the having property be used only on aggregations or it can be used after averages as well?

We have a use case where want to calculate a metric value based on a rolling window of 5 minutes and then return the values only where the value exceeds some threshold, so will the following parameters work?

`
granularity=1 minute, 
averaging buckets=5, 
having averaging_output_field > threshold
`
