### ISSUE TITLE
Druid-Kafka-Indexing-Service Running Time

### ISSUE THREAD

**Issue by bahadircolak44** [apache/incubator-druid#6345]
Hello I want to ask you a quick question about druid-kafka. I am using kafka-indexing-service and I think it works too slow. I am always sending data to kafka(using logstash) but druid takes that data every 10-12 minutes. It doesn't matter how big data is. For example, I sent a 1.5 mb file to kafka and it took 11 mins. Then I shut it down and started using logstash and sent data continuously to kafka. After 10-12 mins, druid took all data. After 10-12 mins, it took new data. I mean every 10-12 mins, it is looking for new data. I am not sure if I explained it clearly. So I am wondering:

- Is it normal?
- How can I make it faster?
- Is it possible to make it real-time? (If there is a data in Kafka, take it immediately)*******
I look forward to hearing from you. Thank you for your time.

**Comment by RestfulBlue** [comment]
you doing something completely wrong.
Do you send queries to broker or historical? 
Is there something in the logs? 
Which version of druid do you use?

**Comment by bahadircolak44** [comment]
Neither. I am using coordinator. Like:

**Comment by xbaran** [comment]
What are u looking for is there http://druid.io/docs/latest/development/extensions-core/kafka-ingestion


intermediatePersistPeriod | ISO8601 Period | The period that determines the rate at which intermediate persists occur. | no (default == PT10M)

Change it to PT10S and u will see ur date updated more often. Every 10 sec ;-)
