### ISSUE TITLE
Remove ConvertSegmentTask, HadoopConverterTask, and ConvertSegmentBackwardsCompatibleTask

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#6350]
We have been using the segment format v9 for a long time. AFAIK, there's no use case where still needs these tasks.

**Comment by kevinconaway** [comment]
Does this need to be a blocker for 0.13?

**Comment by jihoonson** [comment]
I want to add this to 0.13. if possible because this is an incompatible change which is allowed only in major releases. But, I think it's not necessarily a blocker. We can move this to another major release if it takes too long time to fix.
