### ISSUE TITLE
Maven artifacts for druid-0.12.3 missing

### ISSUE THREAD

**Issue by brunodebus** [apache/incubator-druid#6398]
I can find the maven artifacts for druid 0.12.2 in maven central, but cannot locate the ones from 0.12.3. Is it possible to release them?

**Comment by fjy** [comment]
@jon-wei can you take a look?

**Comment by fjy** [comment]
@gianm I think folks don't have permissions to upload to Maven

**Comment by leventov** [comment]
@fjy https://search.maven.org/search?q=g:io.druid%20AND%20a:druid&core=gav

**Comment by gianm** [comment]
I just uploaded the 0.12.3 artifacts. They should start showing up on mirrors soon. Sorry for the delay on this one!
