### ISSUE TITLE
Licenses  of some files are not updated

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#6413]
https://github.com/apache/incubator-druid/search?q=%22Metamarkets+Group+Inc%22&unscoped_q=%22Metamarkets+Group+Inc%22

**Comment by jihoonson** [comment]
@leventov thanks for finding this. I think tex files listed above should be fine because they just mean what company they worked at that time.

**Comment by dclim** [comment]
Fixed by #6449
