### ISSUE TITLE
Does druid support cumulative sum aggregation? 

### ISSUE THREAD

**Issue by yy1** [apache/incubator-druid#6434]
Does druid support cumulative sum aggregation? Like this，ElasticSearch，https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-cumulative-sum-aggregation.html.
Especially hyperUnique.

**Comment by gianm** [comment]
Not in core (yet) but the moving average extension could in principle be extended to support it: https://druid.apache.org/docs/latest/development/extensions-contrib/moving-average-query.html

I'd definitely be excited to see this functionality in core at some point.
