### ISSUE TITLE
Supply numeric index

### ISSUE THREAD

**Issue by weijietong** [apache/incubator-druid#6458]
This issue is to supply a index (a binary tree with leaf nodes which have a value chain  ) to numeric data type column which may be numeric dimension or metric ones.  The index can be configurable to a numeric column. And this is also a start point to support date time type. The PRs will be split into several small parts . Please wait.

**Comment by himanshug** [comment]
Is this about creating indexes for numerical columns for faster filtering?

I couldn't really understand the design/plan from the description given. It would be nice if you could elaborate some more or maybe your PR would have that.
