### ISSUE TITLE
Lookup: JdbcCacheGenerator fails if keyColumn is reserved keyword

### ISSUE THREAD

**Issue by sachinkaleuipath** [apache/incubator-druid#6463]
Hi,

I am using following config to create Lookup.
```
{
  "__default": {
    "job_state": {
      "version": "v0",
      "lookupExtractorFactory": {
        "type": "cachedNamespace",
        "extractionNamespace": {
          "type": "jdbc",
          "namespace": "queue_status_lookup",
          "connectorConfig": {
            "connectURI": "jdbc:sqlserver://myserver:1433;Database=mydb;Trusted_Connection=True",
            "user": "myuser",
            "password": "mypasswd"
          },
          "table": "Queues",
          "keyColumn": "Key",
          "valueColumn": "Status",
          "tsColumn": "EndTime",
          "pollPeriod": 600000
        },
        "firstCacheTimeout": 120000,
        "injective": true
      }
    }
  }
}
```

But getting following error in historical:
`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'Key'.`

As **Key** is reserved keyword in SQL. 

I tried using **[Key]** which work while executing the query but as we are using the same while extracting the results, the code will look for **[Key]** in the result whereas result will contain only **Key**. So, we will get following error:

`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The column name [Key] is not valid.`

I think, this will be solved if we take _keyColumnAlias_ and _valueColumnAlias_ in the input.

I will be able to submit patch for the same. Just wanted to check that there is no solution to this problem (Generally, we avoid naming table fields with keywords but this is a third party table and don't have any control over it).

**Comment by anthonyguyot-msq** [comment]
Hello, same issue for MySQL.

The generated SQL query looks like:
```
SELECT myKeyColumn AS key, myValueColumn AS value FROM myTable
```
this generates the following error:
```
SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, myValueColumn AS value FROM myTable'
```
It should encapsulate aliases with backquote:
```
SELECT myKeyColumn AS `key`, myValueColumn AS `value` FROM myTable
```
Is there a way to achive protected keyword encapsulation/protection, or any alias configuration?
