### ISSUE TITLE
query/cpu/time is much higher than query/time in historical

### ISSUE THREAD

**Issue by QiuMM** [apache/incubator-druid#6465]
![lark20181014-160152](https://user-images.githubusercontent.com/15156517/46914044-98480400-cfca-11e8-8c48-e891c608ee00.png)
Is this normal?

**Comment by Dylan1312** [comment]
Have you got units configured correctly? Cpu/time is nanoseconds while
query/time is millisecond

**Comment by QiuMM** [comment]
Yes, of course. And in fact, query/time is [millisecond](https://github.com/apache/incubator-druid/blob/e3397ba00ff6c439b3fb97a8da1e5e27f1cf301a/processing/src/main/java/org/apache/druid/query/DefaultQueryMetrics.java#L201) while query/cpu/time is [microsecond](https://github.com/apache/incubator-druid/blob/e3397ba00ff6c439b3fb97a8da1e5e27f1cf301a/processing/src/main/java/org/apache/druid/query/DefaultQueryMetrics.java#L237).

**Comment by himanshug** [comment]
Possibly because query/cpu/time is cumulative of multiple cores and multiple segments for same query do get processed in parallel on multiple cores.

**Comment by QiuMM** [comment]
@himanshug after look into the code, I think you are right, thanks.
