### ISSUE TITLE
Binary artifacts in Druid source code

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6476]
There was a potential issue raised in the Dev sync today regarding binary artifacts. It was mentioned that in order to comply with the ASF release standards, the release package should not contain binary artifacts.

I did a quick scan of the master branch and found the following files:

``` bash
$ find . -type f ! -name "*.jpg" ! -name "*.png" ! -name "*.pdf" | perl -lne 'print if -B' | grep -v "./.git/"
./core/src/test/resources/keystore.jks
./processing/src/test/resources/v8SegmentPersistDir/00000.smoosh
./processing/src/test/resources/v8SegmentPersistDir/version.bin
./publications/whitepaper/modii658-yang.zip
./server/src/main/resources/static/old-console/images/favicon.ico
./docs/_graphics/druid.graffle
./examples/quickstart/tutorial/wikiticker-2015-09-12-sampled.json.gz
./indexing-hadoop/src/test/resources/test-segment/index.zip
./extensions-contrib/parquet-extensions/example/wikipedia_list.parquet
./extensions-contrib/parquet-extensions/example/284a0e001476716b-56d5676f53bd6e85_115466471_data.0.parq
./extensions-contrib/parquet-extensions/example/test_date_data.snappy.parquet
./extensions-contrib/time-min-max/src/test/resources/druid.sample.tsv.zip
```

However, I'm not sure how much of an issue this is:
1. I also scanned Apache's GitHub organization for such file extensions and found many existing examples (i.e. .jks):
```
https://github.com/search?utf8=%E2%9C%93&q=org%3Aapache+extension%3Ajks&type=Code&ref=advsearch&l=&l=
```
2. I couldn't find any written ASF guidelines on the matter which makes sense. The closest thing I found is [RELEASE CREATION PROCESS: WHAT IS A VALID RELEASE PACKAGE?](http://www.apache.org/dev/release-publishing.html#valid).

Once we figure out which the audit rules we can add this into the CheckStyle or to the integration tests.

**Comment by jon-wei** [comment]
@yurmix thanks for looking into this!

> Once we figure out which the audit rules we can add this into the CheckStyle or to the integration tests.

Hm, deciding whether a non-code binary artifact should be allowed seems pretty subjective and context dependent to me, seems like a Checkstyle rule would be too blunt (My impression is that this really requires a manual case-by-case review).

e.g., would we forbid "zip" files? I think it's reasonable to include sample data for tests in a zip file.

**Comment by yurmix** [comment]
I believe all of these files fall into the following categories:
1. Test data (either binary or packaged textual).
2. Binary content (Image files, PDFs).

I couldn't find any document which states that these types of files are not allowed in a source release (and I found multiple cases where such files exists in the GitHub Apache organization).

Therefore I believe we can close this issue. 

Please review the list and see if you reach the same conclusion:

| File name      | Category |
| :---        |    :----:   |
|./core/src/test/resources/keystore.jks|Test data|
|./processing/src/test/resources/v8SegmentPersistDir/00000.smoosh|Test data|
|./processing/src/test/resources/v8SegmentPersistDir/version.bin|Test data|
|./publications/whitepaper/modii658-yang.zip|Binary content|
|./server/src/main/resources/static/old-console/images/favicon.ico|Binary content|
|./docs/_graphics/druid.graffle|Binary content|
|./examples/quickstart/tutorial/wikiticker-2015-09-12-sampled.json.gz|Test data|
|./indexing-hadoop/src/test/resources/test-segment/index.zip|Test data|
|./extensions-contrib/parquet-extensions/example/wikipedia_list.parquet|Test data|
|./extensions-contrib/parquet-extensions/example/284a0e001476716b-56d5676f53bd6e85_115466471_data.0.parq|Test data|
|./extensions-contrib/parquet-extensions/example/test_date_data.snappy.parquet|Test data|
|./extensions-contrib/time-min-max/src/test/resources/druid.sample.tsv.zip|Test data|

**Comment by dclim** [comment]
Thank you @yurmix for looking into this. I agree with your conclusion, and think that it makes sense to go ahead with the RC including these files. If our mentors or the incubator PMC expresses any concerns, we can address them at that time. Thanks again!

**Comment by yurmix** [comment]
Resolved (As per the feedback in comments).
