### ISSUE TITLE
HavingSpecMetricComparator ignores comparison for custom Aggregator types

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#6486]
Currently the comparison within `HavingSpecMetricComparator` is restricted to Long, Integer, Float, Double and String. For custom aggregators having a custom type, this comparison would fail with an exception as per:
https://github.com/apache/incubator-druid/blob/master/processing/src/main/java/org/apache/druid/query/groupby/having/HavingSpecMetricComparator.java#L77
Instead of throwing an exception, I'd like to replace it with a default comparison using Double.compare. Any thoughts/objections  @gianm @leventov  ?

**Comment by jihoonson** [comment]
Hi @a2l007, would you elaborate more on the default behavior? Is this issue to add an assumption that all custom type metrics should be able to be converted to double?

**Comment by a2l007** [comment]
@jihoonson The basic requirement is that for custom types, the compare method should not to throw an exception and handle it in a default way. The reasoning behind using the Double comparison as default is that most of the existing type classes(Integer,Long etc) provide a doubleValue() method and therefore I feel it would be reasonable to assume that custom metric types also should be able to override this method. Does it make sense?

**Comment by jihoonson** [comment]
> The basic requirement is that for custom types, the compare method should not to throw an exception and handle it in a default way. 

Hmm, I think it would be best if the default behavior can handle most of types. But, in this case, I'm not sure there's a reasonable default behavior. So, I still think it makes more sense to throw an exception if the metric column is an unknown type. With #6505, it will throw the ClassCastException anyway if it can't be casted to Number. 

I wonder if you can explicitly cast the column in the having clause to double in your query. Does it make sense?

**Comment by a2l007** [comment]
I think another way to handle this would be to have an explicit instanceof check for the Number type and in this case, do `Double.compare(d, value.doubleValue());` If it does not fall under this check as well, we could throw the exception. Would this be reasonable?

**Comment by jihoonson** [comment]
Hmm, that may involve some accuracy loss which can cause inexact result. For example, if `metricValueObj` is a `BigDecimal` containing some value which can't be represented with double, `metricValueObj.doubleValue()` returns a different value. Would you tell me more about your use case? What custom metric type are you using?

**Comment by jihoonson** [comment]
Thanks. That makes sense to me.
