### ISSUE TITLE
Documentation link down!

### ISSUE THREAD

**Issue by bhrgv-bolla** [apache/incubator-druid#6489]
http://druid.io/docs/latest/design/

**Comment by fjy** [comment]
@bhrgv-bolla seems to work for me? Can you try again?

**Comment by bhrgv-bolla** [comment]
I am seeing this on my work network inside chrome 

![image](https://user-images.githubusercontent.com/24613688/47235508-1a9b4400-d38e-11e8-8436-78e9d5b7e565.png)
