### ISSUE TITLE
Tasks got stuck when upload log files to hdfs

### ISSUE THREAD

**Issue by QiuMM** [apache/incubator-druid#6517]
Due to the hadoop cluster have broken, tasks got stuck when upload log files to hdfs.

**Comment by jihoonson** [comment]
I think this is the expected behavior of the current implementation. What is the improvement you think?

**Comment by QiuMM** [comment]
Add a timeout property to control it just like the `handoffConditionTimeout`.

**Comment by jihoonson** [comment]
Thanks. Do you know where the task is stuck in the codes? 

I think it also makes sense to do retrying with your timeout.

**Comment by jihoonson** [comment]
Hmm, maybe timeout isn't necessary for hdfs.

**Comment by QiuMM** [comment]
I added timeout logic in `ForkingTaskRunner` like this:
```java
final ListenableFuture<Void> uploadLogFuture = MoreExecutors
                                  .sameThreadExecutor()
                                  .submit(() -> {
                                            taskLogPusher.pushTaskLog(task.getId(), logFile);
                                            if (reportsFile.exists()) {
                                              taskLogPusher.pushTaskReports(task.getId(), reportsFile);
                                            }
                                            return null;
                                          }
                                  );
                              if (taskConfig.getUploadLogTimeout() == 0) {
                                uploadLogFuture.get();
                              } else {
                                try {
                                  uploadLogFuture.get(taskConfig.getUploadLogTimeout(), TimeUnit.MILLISECONDS);
                                }
                                catch (TimeoutException e) {
                                  log.makeAlert("Timed out after [%d] millis waiting for upload log file", taskConfig.getUploadLogTimeout())
                                     .addData("TaskId", task.getId())
                                     .emit();
                                }
                              }
```

**Comment by jihoonson** [comment]
Ah sorry, my bad. Timeout is necessary, but retrying might not.

> In ForkingTaskRunner call taskLogPusher.pushTaskLog(task.getId(), logFile), then stuck here :

I mean, what code in `pushTaskLog`? I guess it's `ByteStreams.copy(in, out)`, but do you know why it happens? In `ByteStreams.copy(in, out)`, there's an infinite loop but it's expected to return if there's any exception. Is `FSDataOutputStream.write()` blocking on errors without throwing exceptions?

**Comment by QiuMM** [comment]
> Is FSDataOutputStream.write() blocking on errors without throwing exceptions

Might be, but I'm not very sure and it's not convenient to reproduce. The hadoop cluster maintained by other team in my company, they adopt exponential back-off algorithm to retry when there are errors.

**Comment by jihoonson** [comment]
Hmm, I think timeout should be added to inside of `HdfsTaskLogs` if needed because other taskLogPusher implementations can have their own error handling mechanism which can cause blocking for a while. For example, `S3TaskLogs` retries on errors to avoid transient S3 errors. Timeout in `ForkingTaskRunner` can interrupt it before exhausting all retries.

But before that, I think we need to check that other HDFS distributions have the similar issue. If it's common in various distributions, it's worth to handle it. Do you have any idea about this?

**Comment by QiuMM** [comment]
Hmm, agree. I'll check it when I'm not busy.

**Comment by jihoonson** [comment]
Thanks. I'll check it too.
