### ISSUE TITLE
Lookups should be able to return list of values

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6519]
Hi,

This is an early discussion before I proceed with a clear proposal.

**The requirement:**
We have a requirement in which a Registered lookup extraction function (`registeredLookup`) will return multi-value list instead of String. A common example would be tag heirarchy, in which the lookup input is the heirarchy root and the output is a flattened list for the heirarchy.
Since this is not a slowly changing dimension (Which is handled at ingestion time), it requires hadeling via query time lookups.

@sandeep217 described the requirement pretty well in the below issue from 2.5 years ago. Thought it would be better to open a fresh one:
**[Support for lookup into a multi-value dimension #2374](https://github.com/apache/incubator-druid/issues/2374)**
Lookups currently support a 1x1 and Nx1 mapping. Often there's a need to do a lookup against 1xN mapping. A common example is a lookup that maps userid to user-groups where a user may belong to more than one user groups. Denormalizing at ETL may not be desirable if user to user-group mapping changes over time.

**Implementation**
I'm looking for a bit of help with the design. I'm aware that this will require support in both 
the filtering part of the query as well as the grouping part. 
I was looking into adding a companion method to `LookupExtractor#apply()` that returns `Map<String, Object>` and add a call to it in the places that call `apply()` is called today. (I thought it would be better not to change apply() itself for the sake of existing written lookup extensions).

@b-slim @drcrallen I saw that both of you worked on releated items in the past, perhaps you care to comment?

**Comment by yurmix** [comment]
@will-lauer ^

**Comment by will-lauer** [comment]
Instead of `LookupExtractor@apply()` returning a `String` (which it does now) or a `Map<String, Object>`, I think the correct contract is for a new method that returns a `List<String>` with a default implementation that simply invokes `return Collections.singletonList(apply())`, creating a list from the standard single value return, thus allowing any existing lookups to continue to work without any changes. 

One of the tricky issues here is that `LookupExtractor.unapply()` makes less sense for mutlivalued values. We would need to understand what that API would do for this case.

**Comment by yurmix** [comment]
I've done some initial initial investigation. In addition to extending `apply()`, it will also require a change to `MapLookupExtractor` and `MapLookupExtractorFactory` and places where these classes are being used (such as `NamespaceLookupExtractorFactory`):
```java
public class MapLookupExtractor extends LookupExtractor
{
  private final Map<String, String> map;
//
//
  public Map<String, String> getMap()
  {
    return ImmutableMap.copyOf(map);
//
//
```

**Comment by yurmix** [comment]
Another question I'm trying to answer is how does GroupBy determines that a dimension is of multi-value capability.
So far I've seen that `GroupByQueryEngineV2` checks `columnCapabilities.hasMultipleValues()` in order to decide wether to route through `aggregateMultiValueDims` or `aggregateSingleValueDims`, but I haven't found where is that property being decided for Lookups.

**Comment by yurmix** [comment]
#7009
