### ISSUE TITLE
TransformSpec doesn't work with KafkaIndexTask

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#6534]
The original discussion is [here](https://groups.google.com/forum/#!topic/druid-user/3lWm80NLrmQ).

It looks that transformSpec works with indexTask, but not with KafkaIndexTask.

**Comment by gianm** [comment]
Hmm, really? There is a "testRunWithTransformSpec()" in KafkaIndexTaskTest.

**Comment by jihoonson** [comment]
Hmm, yeah. I've verified it by testing a transformSpec with `cast`.
