### ISSUE TITLE
"Unable to rename" exceptions on standalone Indexing Hadoop jobs

### ISSUE THREAD

**Issue by quode** [apache/incubator-druid#6537]
My current Druid setup does batch ingestion of data, which uses "indexing-hadoop" tasks for ingestion. So I observe "Unable to rename ******" exception and subsequent job failure of indexing tasks and frequency increases when I run data back-filling/correction tasks for some interval of say 1 month. I ingest data at DAY granularity.

**Comment by eranbranovate** [comment]
i see the same problem with version 0.12.3 and i see it everyday and i ingest data hourly so i see it more frequently, i described my problem here https://groups.google.com/forum/#!topic/druid-user/GAYgulwblIs
