### ISSUE TITLE
compaction tasks run for much time

### ISSUE THREAD

**Issue by QiuMM** [apache/incubator-druid#6541]
I have tried using compaction task to compact my segments,  then I found it work slowly, It has been running for over 6 hours and I have no idea when it will finish up. The compaction interval is `2018-10-25T03:00:00+00:00/2018-10-25T04:00:00+00:00` and corresponding segment granularity is `HOUR`. There are 2700 segment files between this interval and  these files' total size is almost 50GB. These segments are produced by kafka index service with 50 tasks. But there are only one task I can use to compact these segments. It would be better to make compaction tasks can run parallel, use hadoop MR job to do compaction?

**Comment by jihoonson** [comment]
Hi @QiuMM, yeah that should be the next step for compactionTask. The compactionTask should be able to support various indexing task types like native parallel index task or hadoop index task. But you can still do compaction in parallel by running multiple compactionTasks per segment granularity.

**Comment by QiuMM** [comment]
In my use case, the interval `2018-10-25T03:00:00+00:00/2018-10-25T04:00:00+00:00` overlaps one hour which equals to the segment granularity, so I can use only one compactionTasks, no way to run in parallel. Is there any plan to support hadoop compaction task?

**Comment by jihoonson** [comment]
Oh, got it. Yes, I have a plan to support the hadoop task. 

In your case, I think it's better to use hadoopTask with `dataSource` inputSpec for reindexing (http://druid.io/docs/latest/ingestion/update-existing-data.html).

**Comment by QiuMM** [comment]
Hmm, I have changed to use hadoop batch task to reindex the data.
