### ISSUE TITLE
Shared metric vs. specific metrics

### ISSUE THREAD

**Issue by erankor** [apache/incubator-druid#6557]
Hi all,

Got a question related to data modelling... in our system we have several metrics that measure time. For example, we measure the time it takes to load a video player and we also measure the time it takes for the video to start playing. The former exists only in 'player load' events, while the later exists only in 'play started' events (=we never have both metrics together).
One way to model it is to create two metrics, one for each, and another approach is to have a single metric that changes its meaning according to the event type.
I'm wondering whether there are performance implications to this decision, will a shared metric take less space/be more efficient than multiple metrics?

Thanks,

Eran

**Comment by kaijianding** [comment]
@erankor it sounds either approach produces same number of rows if i understand correctly. less rows, better performance.

**Comment by erankor** [comment]
Thanks @kaijianding, yes, the number of rows will be the same.
