### ISSUE TITLE
Coordinator console doesn't show the port of the historical node

### ISSUE THREAD

**Issue by egor-ryashin** [apache/incubator-druid#6574]
Historical nodes can share the same host, that way having a single IP, while the different ports aren't visible in a tier nodes usage summary layout.
![image](https://user-images.githubusercontent.com/14215045/47956575-a2e92e00-dfb7-11e8-84f3-ac4bff8e3c67.png)
As well as it's not present in a segment description layout.
![image](https://user-images.githubusercontent.com/14215045/47956581-b4cad100-dfb7-11e8-820b-a4ce4e8fac99.png)
That've complicated operators work during production issues a bunch of times.

**Comment by dragonls** [comment]
Usually, if the historical nodes share the same host, why not just start one historical node with higher memory and more threads? I just wonder that.

**Comment by egor-ryashin** [comment]
@dragonls cost reduction 😉

**Comment by drcrallen** [comment]
I suspect this has the greatest likelihood of showing up in a containerized environment where you may or may not have guarantees over isolation at the network level. In the world of "make one config you know *works* and stamp it out with only superficial care for what the underlying hardware looks like" (aka: the promise of containers), a scenario can easily arise where you have multiple JVMs on the same network interface, but different ports.

**Comment by vogievetsky** [comment]
The new console as of Druid 0.16.0

![image](https://user-images.githubusercontent.com/177816/65644688-cb03c600-dfa9-11e9-9b43-17020f273b7b.png)

Shows all the ports for all the nodes and even tells you is they are TLS or plaintext.

Closing as solved.
