### ISSUE TITLE
tasks tables in metadata storage are not cleared

### ISSUE THREAD

**Issue by RestfulBlue** [apache/incubator-druid#6579]
we have separate cluster for stress testing with following kill configuration:
coordinator: 
```
druid.coordinator.kill.on=true
druid.coordinator.kill.period=PT1H
druid.coordinator.kill.durationToRetain=PT1H
druid.coordinator.kill.maxSegments=100000
druid.coordinator.kill.pendingSegments.on=true
```
service-wide : 
```
druid.indexer.logs.kill.enabled=true
druid.indexer.logs.kill.durationToRetain=1000
```
default rules is set to load last 12hours, drop forever

After some time we notice what now metadata storage is growing, even if total size of data in cluster stay the same( new data is coming, old data is killed). After we stop feed data, segments and datasources was cleaned. But when we look into [database](https://prnt.sc/lf37p9) - tasks tables is not cleared. 

Is there a bug or we have misconfiguration somewhere?

druid version is 12.3
metadata storage is postgres
data in hdfs (logs/segments) is properly cleared

**Comment by QiuMM** [comment]
You mean the  *druid_tasks* and *druid_tasklogs* tables' data size keep growing? It seems current kill functions do not clean up old data in tasks table and tasklogs table.

**Comment by QiuMM** [comment]
I have checked the code and found the automatic log file deletion function does not clean up old entries in metadata store.
