### ISSUE TITLE
run query dynamically in post aggregator

### ISSUE THREAD

**Issue by qweed00** [apache/incubator-druid#6582]
Hi
Is there a way to run a query dynamically in a post aggregator?

**Comment by Dylan1312** [comment]
Hey @qweed00 can you give an example of what you'd like to achieve?

**Comment by qweed00** [comment]
Thanks for looking into this @Dylan1312, I am currently investigating to see if I can migrate an existing OLAP project to druid. Just trying to do a like for like port as much as possible at this stage.  

There are a few instances in the original code where it execute another query in the post aggregator based on dimension values
e.g. Measure 2 in the below executes another query to grab Measure 1 for DIM A :( (no idea why it was implemented this way)
```
 DIM1 | Measure 1 | Measure 2
---------------------------
 A    | 1         | Measure 1 + a bunch of other measures
 B    | 2         | Measure 1 + a bunch of other measures
 C    | 3         | Measure 1 (from DIM A) + a bunch of other measures
```

**Comment by kaijianding** [comment]
@qweed00 sounds the lookup feature can meet your need.

**Comment by qweed00** [comment]
@kaijianding i dont think lookup will work, as i need the aggregated result of another row. what i need is a self left join i think. will have to wait until some one implements join support
