### ISSUE TITLE
Due to the unbalanced distribution of segments, query will cost more time.

### ISSUE THREAD

**Issue by licl2014** [apache/incubator-druid#6586]
We have a datasource with many segments and use `CostBalancerStrategy`  in our cluster, but we find this datasource's segments has follows distribution:
![qq 20181107175240](https://user-images.githubusercontent.com/6941514/48124275-da592280-e2b6-11e8-9218-c798edc216f8.png)
Then the query request to `druid04` will has a long tail.

**Comment by nishantmonu51** [comment]
Please add more info - 
1) Version of Druid 
2) Were there new nodes that were added ? Did you waited enough time for the coordinator to rebalance the segments ? 
3) Coordinator balancing related configs, if using non-default 
4) provide distribution snapshot over time, e.g at t, t+6, t+12, t+24 hrs
5) Coordinator logs after masking any sensitive info.
