### ISSUE TITLE
Maven build fails immediately after clone

### ISSUE THREAD

**Issue by janvanoort** [apache/incubator-druid#6589]
I issued this command: 

mvn -U -T 24 clean install -Dmaven.test.skip -Dmaven.javadoc.skip=true

and got this: 

ERROR] Failed to execute goal on project druid-processing: Could not resolve dependencies for project org.apache.druid:druid-processing:jar:0.13.0-incubating-SNAPSHOT: Could not find artifact org.apache.druid:druid-core:jar:tests:0.13.0-incubating-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]

Am using Maven 3.5.0 with Java 8 on Linux Mint 18

**Comment by janvanoort** [comment]
BTW both 

mvn validate

and 

mvn compile

fail

**Comment by janvanoort** [comment]
This happens on master and on branch druid-0.9.2, although "mvn validate" does fail on the former, not on the latter. 
Didn't check any other branches.

**Comment by janvanoort** [comment]
Doesn't happen on branch druid-0.9.1

**Comment by Dylan1312** [comment]
use -DskipTests instead of -Dmaven.test.skip 

I'm not sure why but the latter causes the unit test jars not to be built but the application still depends on them.

**Comment by janvanoort** [comment]
Correct: with -DskipTests this doesn't happen, and the build completes. 
However, this does not provide an explanation for the build to successfully execute on  branch druid-0.9.1 with -Dmaven.test.skip. 
Strange.

**Comment by janvanoort** [comment]
Closing, as nobody seems to have a better solution than @Dylan1312 (which is an actual, working solution) and investigating maven itself is out of scope.
