### ISSUE TITLE
Dependency Injection in DruidModule extension

### ISSUE THREAD

**Issue by QubitPi** [apache/incubator-druid#6634]
We are writing a custom registered lookup module. We have an object to be injected like this

```java
public class Foo {

    @Inject // Guice inject
    Foo(@PayPal CreditCardProcessor processor) {
        ...
    }
}
```

We are using binding annotation to bind `CreditCardProcessor` type to `PayPalCreditCardProcessor` implementation. `PayPalCreditCardProcessor` is created via Jackson binding on `runtime.properties`

```java
public class PayPalCreditCardProcessor implements CreditCardProcessor {

    @JsonCreator
    PayPalCreditCardProcessor(@JsonProperty("cardNumber") String cardNumber) {
        ... // cardNumber is a config in runtime.properties
    }
}
```

This gave us "cannot find a bound CreditCardProcessor impl" error.

Looks like for Guice to traverse dependency graph down to `PayPalCreditCardProcessor`, I had to bind it using Guice annotation like this

```java
    @Inject // Guice inject
    @JsonCreator
    PayPalCreditCardProcessor(@JsonProperty("cardNumber") String cardNumber) {
        ...
    }
```

But when I did that, it asked for a Guice instance binding for `cardNumber` which seems to be impossible via Jackson binding. Am I wrong? How do I make dependency injection start with Guice binding and have a terminal injection via Jackson?

**Comment by nishantmonu51** [comment]
mapping runtime.properties to a Config class can be done by using JsonConfigProvider. 
e.g Refer to how LookupConfig is binded in LookupModule. 
```
    JsonConfigProvider.bind(binder, PROPERTY_BASE, LookupConfig.class);
```
Configs can then be specified in runtime.properties like <PROPERTY_BASE>.<PROPERTY_NAME> e.g. 
`druid.lookupsnapshotWorkingDir` for this example.

**Comment by QubitPi** [comment]
Thank you very much, @nishantmonu51 !

So we just added 

```java
JsonConfigProvider.bind(binder, CONFIG_BASE, PayPalCreditCardProcessor.class, PayPal.class);

binder.bind(CreditCardProcessor.class)
                .annotatedWith(PayPal.class)
                .to(PayPalCreditCardProcessor.class);
```

This gives us a runtime error on historical:

```
Could not find a suitable constructor in java.lang.String. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
```

**Comment by QubitPi** [comment]
Update:

If we remove

```java
binder.bind(CreditCardProcessor.class)
                .annotatedWith(PayPal.class)
                .to(PayPalCreditCardProcessor.class);
```

The error becomes

```
No implementation for CreditCardProcessor annotated with @PayPal() was bound.
  while locating CreditCardProcessor annotated with @Sql()
```

**Comment by gianm** [comment]
Does your "Foo" class need to be injected somewhere by Guice (usually this means it's going to be created at startup)?

If so, then Guice doesn't understand Jackson annotations. You could either modify PayPalCreditCardProcessor to use Guice annotations (`@Inject`, etc) and add bindings for it, or, keep the Jackson annotations but use @nishantmonu51's suggestion of the JsonConfigProvider bridge. However, that bridge has some specific requirements.

- The constructor must be empty, or something Guice can understand (i.e. uses Guice-bound inputs, not Jackson style inputs).
- Stuff that you want Jackson to set should be class fields annotated with `@JsonProperty`.

Check out the other examples of JsonConfigProvider for some examples of how to set up the classes.
