### ISSUE TITLE
Case when cannot work on nested sql

### ISSUE THREAD

**Issue by zhaojiandong** [apache/incubator-druid#6651]
My SQL is as follows, I use case..when in outer sql, but  cannot get "value"
```
SELECT 
t, 
sum(CASE host WHEN 'druid-host1' then value ELSE 0 END) as "tps_host1",
sum(CASE host WHEN 'druid-host2' then value ELSE 0 END) as "tps_host2"
FROM(
SELECT
    TIME_FLOOR(__time, 'PT1M') as t,
    host,
    sum(sum_value) as v
FROM druid_metric_default
WHERE "__time" >= '2018-11-21 16:30:00+0800'
AND metric='ingest/events/processed'
GROUP BY TIME_FLOOR(__time, 'PT1M'),host
)
GROUP by t
```

**Comment by gianm** [comment]
Hey @zhaojiandong,

What result _do_ you get when you run this query? And what do you get if you add "EXPLAIN PLAN FOR" to the front of it?

**Comment by zhaojiandong** [comment]
> Hey @zhaojiandong,
> 
> What result _do_ you get when you run this query? And what do you get if you add "EXPLAIN PLAN FOR" to the front of it?

For example, the inner SQL
```
SELECT
    TIME_FLOOR(__time, 'PT1M') as t,
    host,
    sum(sum_value) as v
FROM druid_metric_default
```

We got:
```
t                           host          v
2018-11-22T10:00:00.000Z    druid-host1   100
2018-11-22T10:00:00.000Z    druid-host2   10
2018-11-22T10:01:00.000Z    druid-host1   150
2018-11-22T10:01:00.000Z    druid-host2   12
```

We expect to  get when run the whole sql
```
t                                                tps_host1    tps_host2   
2018-11-22T10:00:00.000Z    100            10          
2018-11-22T10:01:00.000Z    150             12                
```

Actually We get:
```
t                                                tps_host1    tps_host2   
2018-11-22T10:00:00.000Z    0                 0         
2018-11-22T10:01:00.000Z     0                 0                
```
@gianm

**Comment by gianm** [comment]
Hi @zhaojiandong,

I tried a similar query on master and got a correct result. It is possible something has been fixed here since the version you're using. Could you tell if this query works in master (or even in the latest 0.13.0 RC, available at https://dist.apache.org/repos/dist/dev/incubator/druid/0.13.0-incubating-rc3/)?

If you still find issues in master, could you please write a unit test that shows the problem, in CalciteQueryTest?

Thanks!

**Comment by gianm** [comment]
Hi @zhaojiandong,

I'm going to close this since it seems to be working in master.

**Comment by zhaojiandong** [comment]
> Hi @zhaojiandong,
> 
> I tried a similar query on master and got a correct result. It is possible something has been fixed here since the version you're using. Could you tell if this query works in master (or even in the latest 0.13.0 RC, available at https://dist.apache.org/repos/dist/dev/incubator/druid/0.13.0-incubating-rc3/)?
> 
> If you still find issues in master, could you please write a unit test that shows the problem, in CalciteQueryTest?
> 
> Thanks!

Thanks Gianm
It works in 0.13.0, we use 0.12.0
