### ISSUE TITLE
zk.chroot

### ISSUE THREAD

**Issue by Tagar** [apache/incubator-druid#6660]
I am very new to Druid.

We will use a ZK cluster that's shared with other services.

Is there is a way to specify Druid "chroot" for zk so all Druid related zk paths will be related to that "chroot" zk path? 

Thanks.

**Comment by dragonls** [comment]
I think the `druid.zk.paths.base` in common configuration is what you need.
http://druid.io/docs/latest/configuration/index.html#zookeper

**Comment by Tagar** [comment]
Thank you. Yep, that's the one I was looking for.
