### ISSUE TITLE
Slow timeBoundary queries

### ISSUE THREAD

**Issue by erankor** [apache/incubator-druid#6661]
Hi all,

I'm occasionally seeing timeBoundary queries (issued by Swiv) that run for a very long time.
For example, this query was running for 30 sec - 
```
{
	"queryType": "timeBoundary",
	"dataSource": {
		"type": "table",
		"name": "reach-usage"
	},
	"intervals": {
		"type": "intervals",
		"intervals": ["0000-01-01T00:00:00.000Z/3000-01-01T00:00:00.000Z"]
	},
	"bound": "maxTime",
	"filter": null,
	"context": {
		"queryId": "515cd6b7-f7a4-46ee-84b3-7c63a78ceaf8",
		"timeout": 40000
	},
	"descending": false
}
```
What can be the cause of this? can it be related to the MySQL? is Druid performing any SQL queries to answer this?
(I'm using version 0.10.0)

Thank you,

Eran

**Comment by kaijianding** [comment]
This is not related to mysql.

@erankor do you have large number of segments in this datasource? I guess the second time to issue this TimeBoundary query would be faster due to the cache. But if you have large number of segments, the segmentMetadata can be always slow, the bottleneck is the broker merging.

**Comment by erankor** [comment]
Thanks @kaijianding!
The data source in the first example (timeBoundary) is tiny, the one from the second example (segmentMetadata) is larger -
```
mysql> select count(1) from druid_segments where used and dataSource = 'reach-usage';
+----------+
| count(1) |
+----------+
|       22 |
+----------+

mysql> select count(1) from druid_segments where used and dataSource = 'player-events-historical';
+----------+
| count(1) |
+----------+
|    14740 |
+----------+
```
To make sure I understand what you wrote - in order to answer the second query, the broker has to perform it for all segments and merge the results?
If so, maybe I'll hack it so that it only performs it for the last week or so, the latest schema is probably what I want anyway...

**Comment by kaijianding** [comment]
@erankor yes, for segmentMetadata, the broker will do the merge, and it is slow if you have plenty of segments. A workaround solution is that you can use a smaller interval.

**Comment by glasser** [comment]
I suspect there's some missing logic in TimeBoundaryQueryRunnerFactory.  For example, I'm not an expert on the query execution code but it seems like (if you specify `filter`) it touches every segment.  Also even if you're only requesting `maxTime` or `minTime` via `bound`, it looks up both if you specify `filter`.
