### ISSUE TITLE
Compilation issue due to checkstyle error

### ISSUE THREAD

**Issue by anuprk** [apache/incubator-druid#6668]
I just pull latest repo and trying to compile "mvn clean install". Getting below error. There is no directory called src incubator-druid. Do I need to create it. I am using maven 3.1.1 and jdk8. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project druid: Unable to parse configuration of mojo org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check for parameter sourceDirectories: Cannot assign configuration entry 'sourceDirectories' with value '~/github/incubator-druid/src/main/java' of type java.lang.String to property of type java.util.List -> [Help 1]

**Comment by jihoonson** [comment]
Hi @anuprk, thank you for reporting this. It seems that recent versions of maven can handle this properly (https://github.com/kongchen/swagger-maven-plugin/issues/441#issuecomment-283072599). I tried 3.6.0 and it works. Would you try again with the latest version of maven?

**Comment by anuprk** [comment]
Thanks @jihoonson. Maven 3.6.0 seems to be working. But I am getting below compilation error with JDK8. 

src/main/java/org/apache/druid/segment/StringDimensionMergerV9.java:[141,50] incompatible types: inferred type does not conform to upper bound(s)
[ERROR]     inferred: org.apache.druid.segment.data.CloseableIndexed<T>
[ERROR]     upper bound(s): org.apache.druid.segment.data.Indexed<java.lang.String>,java.io.Closeable
[ERROR]

**Comment by anuprk** [comment]
Yes with latest patch update of jdk1.8 its working fine. I was using 1.8.0_25, x86_64 and now with 1.8.0_202, x86_64 worked fine. Thanks a lot.
