### ISSUE TITLE
fail fast hadoop indexer

### ISSUE THREAD

**Issue by Tagar** [apache/incubator-druid#6681]
After 4.5 hours of work 1897 reducers failed, **0** completed, 2225 to go.. 

![image](https://user-images.githubusercontent.com/3013418/49200951-24846f80-f35c-11e8-992a-d9b7c8a761c2.png)

Obviously it's not going to complete..

Is there is a druid/ hadoop setting to make it fail fast?

**Comment by b-slim** [comment]
If you are running on Yarn you can kill the job with `yarn kill application_id`

**Comment by gianm** [comment]
I'm not sure, there might be a hadoop setting that kills a map/reduce job if it has more than X% of map or reduce tasks fail. If there isn't then it would be a good setting for hadoop to add :)
