### ISSUE TITLE
WARN [main] org.apache.hadoop.ipc.Client - Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(com.google.protobuf.InvalidProtocolBufferException): Protocol message contained an invalid tag (zero)

### ISSUE THREAD

**Issue by Tagar** [apache/incubator-druid#6682]
While running hadoop indexer, my console is filled with warnings like

> 2018-11-29T05:33:31,507 WARN [main] org.apache.hadoop.ipc.Client - **Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(com.google.protobuf.InvalidProtocolBufferException): Protocol message contained an invalid tag (zero)**.
> 2018-11-29T05:33:31,610 WARN [main] org.apache.hadoop.ipc.Client - Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(com.google.protobuf.InvalidProtocolBufferException): Protocol message contained an invalid tag (zero).
> 2018-11-29T05:33:31,713 WARN [main] org.apache.hadoop.ipc.Client - Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(com.google.protobuf.InvalidProtocolBufferException): Protocol message contained an invalid tag (zero).

What could be the root cause for this?

Thanks.

**Comment by egor-ryashin** [comment]
@Tagar could you post the task spec, Indexer and MiddleManager configuration, Druid and Hadoop versions?
