### ISSUE TITLE
Druid-redis does not provide a historical buffer interface?

### ISSUE THREAD

**Issue by love1693294577** [apache/incubator-druid#6723]
When I configure redis in historical

Druid.cache.type=redis
druid.historical.cache.useCache=true
druid.historical.cache.populateCache=true
Druid.historical.cache.unCacheable=[]
druid.cache.sizeInBytes=104857600

Redis does not buffer data

**Comment by love1693294577** [comment]
Yes
I just want to turn on the buffer of the historic
I configured it in all common.runtime.properties
Druid.cache.host=xx.xxx.xxx.13
Druid.cache.port=6379

And configured in all historical nodes
druid.historical.cache.useCache=true
druid.historical.cache.populateCache=true
Druid.historical.cache.unCacheable=[]
Druid.cache.type=redis

But there is still no buffered data in redis


I tried to configure the broker's buffer, but there is no configuration in the historical, this has buffered data in redis, and there is buffer information for the segment.

**Comment by love1693294577** [comment]
Yes
I just want to turn on the buffer of the historic
I configured it in all common.runtime.properties
Druid.cache.host=xx.xxx.xxx.13
Druid.cache.port=6379

And configured in all historical nodes
druid.historical.cache.useCache=true
druid.historical.cache.populateCache=true
Druid.historical.cache.unCacheable=[]
Druid.cache.type=redis

But there is still no buffered data in redis

I tried to configure the broker's buffer, but there is no configuration in the historical, this has buffered data in redis, and there is buffer information for the segment.

**Comment by love1693294577** [comment]
> 请检查[redis缓存文档](https://github.com/apache/incubator-druid/blob/master/docs/content/development/extensions-contrib/redis-cache.md)以了解如何使用它。以下是一个例子：
> 
> ```
> # Use cache
> druid.historical.cache.useCache=true
> druid.historical.cache.populateCache=true
> druid.historical.cache.unCacheable=["select", "scan"]
> 
> druid.cache.type=redis
> druid.cache.host=127.0.0.1
> druid.cache.port=8080
> ```

是的
我只想打开历史悠久的缓冲区
我在所有common.runtime.properties中配置它
Druid.cache.host = xx.xxx.xxx.13 
Druid.cache.port = 6379

并在所有历史节点中配置
druid.historical.cache.useCache = true 
druid.historical.cache.populateCache = true 
Druid.historical.cache.unCacheable = [] 
Druid.cache.type = redis

但redis中仍然没有缓冲数据

我尝试配置代理的缓冲区，但历史记录中没有配置，这已经用redis缓冲数据，并且该段有缓冲区信息。

**Comment by love1693294577** [comment]
> Please check the [redis cache doc](https://github.com/apache/incubator-druid/blob/master/docs/content/development/extensions-contrib/redis-cache.md) to learn how to use it. Below is a example:
> 
> ```
> # Use cache
> druid.historical.cache.useCache=true
> druid.historical.cache.populateCache=true
> druid.historical.cache.unCacheable=["select", "scan"]
> 
> druid.cache.type=redis
> druid.cache.host=127.0.0.1
> druid.cache.port=8080
> ```

Yes

I just want to turn on the buffer of the historic
I configured it in all common.runtime.properties
Druid.cache.host=xx.xxx.xxx.13
Druid.cache.port=6379
And configured in all historical nodes
druid.historical.cache.useCache=true
druid.historical.cache.populateCache=true
Druid.historical.cache.unCacheable=[]
Druid.cache.type=redis
But there is still no buffered data in redis
I tried to configure the broker's buffer, but there is no configuration in the historical, this has buffered data in redis, and there is buffer information for the segment.

**Comment by QiuMM** [comment]
> I tried to configure the broker's buffer, but there is no configuration in the historical, this has buffered data in redis, and there is buffer information for the segment.

Sorry, I don't understand you. Did you mean the cache work on broker but not on historical? Besides, can you provide your historical node's startup logs ?

**Comment by love1693294577** [comment]
> > I tried to configure the broker's buffer, but there is no configuration in the historical, this has buffered data in redis, and there is buffer information for the segment.
> 
> Sorry, I didn't understand you. Did you mean the cache work on broker but not work on historical? Besides, can you provide your historical node's startup logs ?

Ok I solved this problem because I didn't configure the historical druid-redis-cache to have a historical intermediate result set.
But I still have a place I don't understand. After configuring the broker redis buffer, in addition to querying the intermediate result set information, the broker also has segment buffer information.

**Comment by QiuMM** [comment]
> the broker also has segment buffer information.

I think you may talk about segment metadata information. If you enabled sql on your broker, it will do [segment metadata queries](http://druid.io/docs/latest/querying/segmentmetadataquery.html) to obtain information about segment schema. These queries' result would be cached if you enabled the cache.

**Comment by love1693294577** [comment]
Ok, I understand, thank you. Have the opportunity to exchange and learn together. I'm in Beijing

**Comment by love1693294577** [comment]
> > the broker also has segment buffer information.
> 
> I think you may talk about segment metadata information. If you enabled sql on your broker, it will do [segment metadata queries](http://druid.io/docs/latest/querying/segmentmetadataquery.html) to obtain information about segment schema. These queries' result would be cached if you enabled the cache.

Ok, I understand, thank you. Have the opportunity to exchange and learn together. I'm in Beijing

**Comment by QiuMM** [comment]
Sounds good, welcome! You can contact me via email csurjqmm@gmail.com.
