### ISSUE TITLE
Ability to move leader to another node

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-druid#6725]
Hi,
I have following problem.
I'm trying to fix Druid helm chart and one of the problems I found needs ability to move coordinator and overlord leadership to different node.
Is there any option for that ?

**Comment by QiuMM** [comment]
Starting a new coordinator/overlord in a different node, then kill the old ones. The new ones will work as leader.

**Comment by maver1ck** [comment]
I now about this.
But if it's possible to move leader before killing it ?
