### ISSUE TITLE
Calcite column resolution bug

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#6751]
The following query fails:

```sql
SELECT channel
FROM "wikipedia"
WHERE "user" IN (
    select "user" FROM (
        SELECT "user", count(*) AS "cnt"
        FROM "wikipedia"
        WHERE __time >= '2018-10-01' AND __time < '2018-11-01'
        GROUP BY 1
        HAVING "cnt" > 100
    )
)
GROUP BY 1
```

With error: `Unknown exception: org.apache.calcite.runtime.CalciteContextException: From line 9, column 16 to line 9, column 20: Column 'cnt' not found in any table`

This is incorrect, the "cnt" in the HAVING clause refers to the agg.
This Query should work.

Note that these queries work fine:

Just the inner query:

```sql
select "user" FROM (
    SELECT "user", count(*) AS "cnt"
    FROM "wikipedia"
    WHERE __time >= '2018-10-01' AND __time < '2018-11-01'
    GROUP BY 1
    HAVING "cnt" > 100
)
```

and the same query but with an agg in the HAVING

```sql
SELECT channel
FROM "wikipedia"
WHERE "user" IN (
    select "user" FROM (
        SELECT "user", count(*) AS "cnt"
        FROM "wikipedia"
        WHERE __time >= '2018-10-01' AND __time < '2018-11-01'
        GROUP BY 1
        HAVING count(*) > 100
    )
)
GROUP BY 1
```

This is tested on 0.13.0

**Comment by egor-ryashin** [comment]
@vogievetsky I wonder if it still persists? couldn't reproduce it straight away.
