### ISSUE TITLE
Unknown provider[mysql] of Key[type=org.apache.druid.metadata.MetadataStorageProvider,

### ISSUE THREAD

**Issue by mprior10** [apache/incubator-druid#6759]
I'm testing apache-druid-0.13.0-incubating, and using the Quickstart tutorial

 ./supervise -c ../quickstart/tutorial/conf/tutorial-cluster.conf

In "quickstart/tutorial/conf/druid/_common/common.runtime.properties" I set druid.extensions.loadList=["mysql-metadata-storage", "druid-hdfs-storage", "druid-kafka-indexing-service"]
and configure the mysql settings, server, port etc. The mysql jar files exist in druid/extensions/mysql-metadata-storage and in druid/lib. I can see in the error log that the jar files are in the classpath. This is the error on startup (full log attached)

2018-12-19T18:16:03,439 ERROR [main] org.apache.druid.cli.CliCoordinator - Error when starting up.  Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Unknown provider[mysql] of Key[type=org.apache.druid.metadata.MetadataStorageProvider, annotation=[none]], known options[[derby]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:108) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
  while locating org.apache.druid.metadata.MetadataStorageProvider
  while locating org.apache.druid.metadata.MetadataStorage

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
        at com.google.inject.internal.Inje

[druid_cordinator_ERROR.txt](https://github.com/apache/incubator-druid/files/2696117/druid_cordinator_ERROR.txt)

**Comment by ggjjl1** [comment]
http://druid.io/docs/latest/development/extensions-core/mysql.html

**Comment by egor-ryashin** [comment]
> known options[[derby]]

it says it didn't load the `mysql` extension, only `derby` capability is available.
@mprior10 I believe you've already resolved the issue, right?

**Comment by mprior10** [comment]
Hi Egor,

I didn’t get back to this, after I got the error.

Thanks

Mike
