### ISSUE TITLE
How to migrate druid cluster?

### ISSUE THREAD

**Issue by hey-jude** [apache/incubator-druid#6776]
I'm trying to migrate some part (deep storage, segment, metadata) from running druid cluster to new one.
Deep storage, segment, metadata are changed new hardware & network address and whole data are so big, I have to migrate some cubes only.

Is there a guide or cheatsheet?
In addition, is it possible to migrate deep storage from hdfs to aws s3?

**Comment by egor-ryashin** [comment]
Related https://github.com/apache/incubator-druid/issues/5273
