### ISSUE TITLE
apache-druid-0.13.0-incubating router /druid/router/v1/brokers

### ISSUE THREAD

**Issue by panqingcui** [apache/incubator-druid#6786]
ERROR PreResponseAuthorizationCheckFilter:106 - Request did not have an authorization check performed.: {class=org.apache.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/druid/router/v1/brokers, method=GET, remoteAddr=172.19.104.129, remoteHost=172.19.104.129}

**Comment by srggrs** [comment]
I have a similar error when introspec a global caches lookup:

`2019-03-13T02:05:12,997 ERROR [qtp1043822951-119] org.apache.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=org.apache.druid.server.se$
urity.PreResponseAuthorizationCheckFilter, uri=/druid/v1/lookups/introspect/portfolio_uuid, method=GET, remoteAddr=127.0.0.1, remoteHost=127.0.0.1}                                                                
2019-03-13T02:05:12,998 WARN [qtp1043822951-119] org.eclipse.jetty.server.HttpChannel - /druid/v1/lookups/introspect/portfolio_uuid                                                                                
org.apache.druid.java.util.common.ISE: Request did not have an authorization check performed.`

funny thing if I issue the request with:

`curl -X GET http://localhost:8082/druid/v1/lookups/introspect/mylookup`
curl is able to retrieve part of the lookup map, but when I use the same endpoint in a Python requests, it failed.

**Comment by egor-ryashin** [comment]
@panqingcui could you post here Druid version and router configuration?
