### ISSUE TITLE
getFailedSendingTimeCounter method in HttpPostEmitter is incorrect

### ISSUE THREAD

**Issue by licl2014** [apache/incubator-druid#6788]
` public ConcurrentTimeCounter getSuccessfulSendingTimeCounter() 
  {
    return emittingThread.successfulSendingTimeCounter;
  }`

and

`public ConcurrentTimeCounter getFailedSendingTimeCounter()
  {
    return emittingThread.successfulSendingTimeCounter;
  }`

**Comment by licl2014** [comment]
it shoud be
`public ConcurrentTimeCounter getFailedSendingTimeCounter()
  {
    return emittingThread.failedSendingTimeCounter;
  }`

**Comment by asdf2014** [comment]
Thanks for reporting this, which has been fixed in #6793.
