### ISSUE TITLE
chooseBestServer bug in CostBalancerStrategy

### ISSUE THREAD

**Issue by licl2014** [apache/incubator-druid#6790]
Related code as follows:

>     try {
>      for (Pair<Double, ServerHolder> server : resultsFuture.get()) {
>        if (server.lhs <= bestServers.get(0).lhs) {
>          if (server.lhs < bestServers.get(0).lhs) {
>           bestServers.clear();
>          }
>          bestServers.add(server);
>        }
>      }
>      // Randomly choose a server from the best servers
>      bestServer = bestServers.get(ThreadLocalRandom.current().nextInt(bestServers.size()));
>    }

Here， we're not considering if `resultsFuture.get()` has `one` element and if `bestServers` has all `Double.POSITIVE_INFINITY ` elements , i have a simple fix.

>     try {
>      List<Pair<Double, ServerHolder>> servers = resultsFuture.get();
>      if (servers.size() == 1) {
>        if (servers.get(0).lhs < bestServers.get(0).lhs) {
>          bestServers.clear();
>          bestServers.add(servers.get(0));
>        }
>      } else {
>        for (Pair<Double, ServerHolder> server : servers) {
>          if (server.lhs <= bestServers.get(0).lhs) {
>            if (server.lhs < bestServers.get(0).lhs) {
>              bestServers.clear();
>            }
>            bestServers.add(server);
>          }
>        }
>      }
>     if (bestServers.stream().allMatch(server -> server.lhs != Double.POSITIVE_INFINITY)) {
>        // Randomly choose a server from the best servers
>        bestServer = bestServers.get(ThreadLocalRandom.current().nextInt(bestServers.size()));
>     }
>    }

**Comment by QiuMM** [comment]
@licl2014 why we have to consider if `resultsFuture.get()` has only one element, I didn't see any difference. Would you elaborate more?

**Comment by asdf2014** [comment]
Hi, @licl2014 . In fact, there should be no problem here. As long as there is a normal server, those servers with cost value of `Double.POSITIVE_INFINITY` will be cleared from `bestServers` collection.

**Comment by QiuMM** [comment]
@licl2014 I know, but you have add below code, so there is no need to do anymore.
```java
if (bestServers.stream().allMatch(server -> server.lhs != Double.POSITIVE_INFINITY)) {
   // Randomly choose a server from the best servers
   bestServer = bestServers.get(ThreadLocalRandom.current().nextInt(bestServers.size()));
}
```

**Comment by licl2014** [comment]
@QiuMM yep!!!
after  `if (bestServers.stream().allMatch(server -> server.lhs != Double.POSITIVE_INFINITY))`, we couldn't consider if `resultsFuture.get()` has only one element.

**Comment by licl2014** [comment]
@asdf2014  yes, but  we should consider if all servers have  `Double.POSITIVE_INFINITY`
