### ISSUE TITLE
Different groupBy strategies for ThetaSketch and HyperUnique? 

### ISSUE THREAD

**Issue by csimplestring** [apache/incubator-druid#6795]
Hello, recently we start using ThetaSketch aggregator for groupBy query. Since we learned that ThetaSketch library is more feature-rich which supports INTERSECT|UNION|NOT operations, we believe soon we will use it.

Right now our requirement is pretty simple: get the approximate cardinality of a column UUID, so the ingestion metricsSpec looks like:
`
"metricsSpec": [
        {
          "name": "count",
          "type": "count"
        },
        {
          "type": "thetaSketch",
          "name": "uuid_sketch",
          "fieldName": "uuid"
        }
      ],
`

The groupBy query is:
`
{
	"queryType": "groupBy",
	"dataSource": "xxx",
	"dimensions": [
		"column-A"
	],
	"intervals": [
		"2018-11-01T00:00:00/2018-12-03T23:59:59"
	],
	"context": {
		"timeout": 60000,
		"useCache": false,
		"populateCache": false,
		"groupByStrategy": "v2"
	},
	"granularity": "all",
	"aggregations": [
		{
			"type": "count",
			"name": "loads"
		},
		{
			"type": "thetaSketch",
			"name": "unique_loads",
			"fieldName": "uuid_sketch"
		}
	]
}
`

The groupBy query is pretty slow, which takes almost 40 seconds. Then I did some tests: firstly, I set the 'dimensions' to be empty(because in the official document, all the examples for thetaSketch leave 'dimensions' empty), then response is very fast: only 1 second. Secondly, I re-ingest the data by using HyperUnique aggregator and use the same above groupBy query, the response is also very fast. 

Therefore based on those tests, I am wondering is it because there are different groupBy strategies for HyperUnique(which is the core-module) and ThetaSketch(which is the contrib-module)?

The Druid version is 0.11.
Thanks!

**Comment by gianm** [comment]
Hi @csimplestring,

This is possibly related to #6743 and may come from the same underlying problem: the theta sketch has a relatively large maximum size, even though it's not typically going to use it all. This causes IncrementalIndex to overestimate its size and it also causes groupBy to reserve a lot more space for it than truly necessary. In turn- this can cause inefficiency and potentially slow down the query.

Could you try running the query with `"groupByStrategy": "v1"`? That one uses on-heap aggregators and so it doesn't suffer from the same problem. If it's faster, it probably means my guess above is correct about wha's happening.

This is one of the only situations where groupBy v1 is better than v2 (when using an aggregation type that has a large maximum size but a small typical size). Possibly the only situation at all.

**Comment by csimplestring** [comment]
Hi, @gianm,

I tried the 'v1' and 'v2' groupbyStrategy respectively, there is NO significant difference at all. I plan to switch to HyperUnique aggregator later in order to achieve faster speed.

As mentioned in #6743, the Druid HLL implementation is some years ago and might be deprecated, using the theta sketch library is the preferred option. But the performance is still a small hurdle to me.

But thanks for your help.

**Comment by leerho** [comment]
@csimplestring 

> But the performance is still a small hurdle to me.

Which sketch are you referring to and what aspect of "performance" are you referring to?  Update speed, merge speed, space utilization ??  And can you provide some data examples?

Thanks.

**Comment by csimplestring** [comment]
Hi, @leerho ，

Thanks! I'll try that as well soon. 

Right now in Druid, there are 3 sketch options to get the approximate distinct count:
- the old Druid built-in HLL, aka, HyperUnique
- the DataSketch's ThetaSketch aggregator
- the DataSketch's HLL Sketch aggregator

I'll test them and hopefully give you a small summary.

**Comment by leerho** [comment]
@csimplestring @gianm 
What is the status of this?
