### ISSUE TITLE
[kafka index service] execute peon successfully,but no segment was generated.

### ISSUE THREAD

**Issue by helianthuslulu** [apache/incubator-druid#6806]
my supervisor spec as follow: 

> {
>   "type": "kafka",
>   "dataSchema": {
>     "dataSource": "metrics-kafka",
>     "parser": {
>       "type": "string",
>       "parseSpec": {
>         "format": "json",
>         "timestampSpec": {
>           "column": "time",
>           "format": "auto"
>         },
>         "dimensionsSpec": {
>           "dimensions": [
>              "url", "user"
>           ]
>         }
>       }
>     },
>     "metricsSpec": [
>       {
>         "name": "views",
>         "type": "count"
>       }    ],
>     "granularitySpec": {
>       "type": "uniform",
>       "segmentGranularity": "HOUR",
>       "queryGranularity": "NONE",
>       "rollup": true
>     }
>   },
>   "tuningConfig": {
>     "type": "kafka",
>     "maxRowsPerSegment": 5000000
>   },
>   "ioConfig": {
>     "topic": "metrics",
>     "consumerProperties": {
>       "bootstrap.servers": "101.8.101.20:9092"
>     },
>     "taskCount": 1,
>     "replicas": 1,
>     "taskDuration": "PT1H",
>     "completionTimeout": "PT1H"
>   }
> }

and after I submitted this supervisor by DRUID API "HttpClient.go()",ann then producer data by this way:

> druid@druid01 kafka]$ ./bin/kafka-console-producer.sh --broker-list localhost:9092 --topic metrics
> {"time": "2019-01-04T06:47:17Z", "url": "/ftp/druid", "user": "alice"}

overload.log like this:

> 2019-01-04T15:24:53,763 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.overlord.MetadataTaskStorage - Inserting task index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko with status: TaskStatus{id=index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko, status=RUNNING, duration=-1}
> 2019-01-04T15:24:53,786 INFO [KafkaSupervisor-metrics-kafka] **io.druid.indexing.overlord.TaskLockbox - Adding task[index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] to activeTasks**
> **2019-01-04T15:24:53,788 INFO [TaskQueue-Manager] io.druid.indexing.overlord.TaskQueue - Asking taskRunner to run: index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko**
> 2019-01-04T15:24:53,788 INFO [TaskQueue-Manager] io.druid.indexing.overlord.RemoteTaskRunner - Added pending task index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko
> 2019-01-04T15:24:53,799 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - {id='metrics-kafka', generationTime=2019-01-04T07:24:53.798Z, payload={dataSource='metrics-kafka', topic='metrics', partitions=1, replicas=1, durationSeconds=3600, active=[], publishing=[]}}
> 2019-01-04T15:24:53,809 INFO [rtr-pending-tasks-runner-0] io.druid.indexing.overlord.RemoteTaskRunner - Coordinator asking Worker[101.8.101.22:8091] to add task[index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko]
> 2019-01-04T15:24:53,812 INFO [rtr-pending-tasks-runner-0] io.druid.indexing.overlord.RemoteTaskRunner - Task index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko switched from pending to running (on [101.8.101.22:8091])
> 2019-01-04T15:24:53,813 INFO [rtr-pending-tasks-runner-0] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] status changed to [RUNNING].
> 2019-01-04T15:24:53,819 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Worker[101.8.101.22:8091] wrote RUNNING status for task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] on [TaskLocation{host='null', port=-1, tlsPort=-1}]
> 2019-01-04T15:24:53,821 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Worker[101.8.101.22:8091] wrote RUNNING status for task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] on [TaskLocation{host='101.8.101.22', port=8100, tlsPort=-1}]
> 2019-01-04T15:24:53,821 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] location changed to [TaskLocation{host='101.8.101.22', port=8100, tlsPort=-1}].
> 2019-01-04T15:25:00,804 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,844 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,845 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,845 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,845 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,846 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,846 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,847 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,847 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,848 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,848 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,849 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,849 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,851 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,851 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,852 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,852 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,853 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,853 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:00,853 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.java.util.http.client.pool.ChannelResourceFactory - Generating: http://101.8.101.22:8100
> 2019-01-04T15:25:01,011 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - Setting taskGroup sequences to [{0={0=30}}] for group [0]
> 2019-01-04T15:25:01,028 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - {id='metrics-kafka', generationTime=2019-01-04T07:25:01.027Z, payload={dataSource='metrics-kafka', topic='metrics', partitions=1, replicas=1, durationSeconds=3600, active=[{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', startTime=2019-01-04T07:24:59.662Z, remainingSeconds=3598}], publishing=[]}}
> 2019-01-04T15:25:15,653 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
> 2019-01-04T15:25:23,691 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - {id='metrics-kafka', generationTime=2019-01-04T07:25:23.691Z, payload={dataSource='metrics-kafka', topic='metrics', partitions=1, replicas=1, durationSeconds=3600, active=[{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', startTime=2019-01-04T07:24:59.662Z, remainingSeconds=3575}], publishing=[]}}
> 2019-01-04T15:25:53,690 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - {id='metrics-kafka', generationTime=2019-01-04T07:25:53.690Z, payload={dataSource='metrics-kafka', topic='metrics', partitions=1, replicas=1, durationSeconds=3600, active=[{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', startTime=2019-01-04T07:24:59.662Z, remainingSeconds=3545}], publishing=[]}}
> 2019-01-04T15:26:15,653 INFO [TaskQueue-StorageSync] io.druid.indexing.overlord.TaskQueue - Synced 1 tasks from storage (0 tasks added, 0 tasks removed).
> 2019-01-04T15:26:23,692 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - {id='metrics-kafka', generationTime=2019-01-04T07:26:23.692Z, payload={dataSource='metrics-kafka', topic='metrics', partitions=1, replicas=1, durationSeconds=3600, active=[{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', startTime=2019-01-04T07:24:59.662Z, remainingSeconds=3515}], publishing=[]}}
> 2019-01-04T15:26:53,691 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - {id='metrics-kafka', generationTime=2019-01-04T07:26:53.691Z, payload={dataSource='metrics-kafka', topic='metrics', partitions=1, replicas=1, durationSeconds=3600, active=[{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', startTime=2019-01-04T07:24:59.662Z, remainingSeconds=3485}], publishing=[]}}

and after I shutdown this supervisor,overload.log like this:

> 2019-01-04T15:27:05,729 INFO [qtp1735854903-73] io.druid.indexing.kafka.supervisor.KafkaSupervisor - Beginning shutdown of KafkaSupervisor[metrics-kafka]
> 2019-01-04T15:27:05,729 INFO [qtp1735854903-73] io.druid.indexing.overlord.RemoteTaskRunner - Unregistered listener [KafkaSupervisor-metrics-kafka]
> 2019-01-04T15:27:05,729 INFO [qtp1735854903-73] **io.druid.indexing.kafka.supervisor.KafkaSupervisor - Posting GracefulShutdownNotice, signalling managed tasks to complete and publish**
> 2019-01-04T15:27:05,729 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - Task group [0] has run for [PT3600S]
> 2019-01-04T15:27:05,775 INFO [KafkaIndexTaskClient-metrics-kafka-0] io.druid.indexing.kafka.KafkaIndexTaskClient - Task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] paused successfully
> 2019-01-04T15:27:05,776 WARN [KafkaSupervisor-metrics-kafka-Worker-0] io.druid.indexing.kafka.supervisor.KafkaSupervisor - Checkpoint [{0=30}] is same as the start offsets [{0=30}] of latest sequence for the task group [0]
> 2019-01-04T15:27:05,776 INFO [KafkaSupervisor-metrics-kafka-Worker-0] io.druid.indexing.kafka.supervisor.KafkaSupervisor - Setting endOffsets for tasks in taskGroup [0] to {0=30} and resuming
> 2019-01-04T15:27:05,810 INFO [qtp1735854903-73] io.druid.indexing.kafka.supervisor.KafkaSupervisor - Shutdown notice handled
> 2019-01-04T15:27:05,810 INFO [qtp1735854903-73] io.druid.indexing.kafka.supervisor.KafkaSupervisor - KafkaSupervisor[metrics-kafka] has stopped
> 2019-01-04T15:27:05,810 INFO [KafkaSupervisor-metrics-kafka] io.druid.indexing.kafka.supervisor.KafkaSupervisor - KafkaSupervisor[metrics-kafka] interrupted, exiting
> 2019-01-04T15:27:06,311 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Worker[101.8.101.22:8091] wrote SUCCESS status for task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] on [TaskLocation{host='101.8.101.22', port=8100, tlsPort=-1}]
> 2019-01-04T15:27:06,312 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Worker[101.8.101.22:8091] completed task[index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] with status[SUCCESS]
> 2019-01-04T15:27:06,312 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.TaskQueue - Received SUCCESS status for task: index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko
> 2019-01-04T15:27:06,312 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Cleaning up task[index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] on worker[101.8.101.22:8091]
> 2019-01-04T15:27:06,318 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.TaskLockbox - Removing task[index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] from activeTasks
> 2019-01-04T15:27:06,319 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.MetadataTaskStorage - Updating task index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko to status: TaskStatus{id=index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko, status=SUCCESS, duration=132493}
> 2019-01-04T15:27:06,322 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.TaskQueue - Task done: AbstractTask{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', groupId='index_kafka_metrics-kafka', taskResource=TaskResource{availabilityGroup='index_kafka_metrics-kafka_b3619332353cfa6', requiredCapacity=1}, dataSource='metrics-kafka', context={checkpoints={"0":{"0":30}}, IS_INCREMENTAL_HANDOFF_SUPPORTED=true}}
> 2019-01-04T15:27:06,322 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.TaskQueue - Task SUCCESS: AbstractTask{id='index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko', groupId='index_kafka_metrics-kafka', taskResource=TaskResource{availabilityGroup='index_kafka_metrics-kafka_b3619332353cfa6', requiredCapacity=1}, dataSource='metrics-kafka', context={checkpoints={"0":{"0":30}}, IS_INCREMENTAL_HANDOFF_SUPPORTED=true}} (132493 run duration)
> 2019-01-04T15:27:06,322 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.TaskRunnerUtils - Task [index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] status changed to [SUCCESS].
> 2019-01-04T15:27:06,322 INFO [Curator-PathChildrenCache-1] io.druid.indexing.overlord.RemoteTaskRunner - Task[index_kafka_metrics-kafka_b3619332353cfa6_ojfldgko] went bye bye.

but NO segment was generated. and from **http://${coordinator_ip}:8081/#/** I cannot see this datasource. I am very confused and need your help. Any response would be appreciated...
==============================================================

**Comment by licl2014** [comment]
if this kafka index task has segment meta data in mysql or has segment data in HDFS?

**Comment by helianthuslulu** [comment]
There is no metadata information, and no sink in hdfs.

**Comment by helianthuslulu** [comment]
in $DRUID_HOME/conf/druid/_common/common.runtime.properties, segment dir config:
**druid.storage.storageDirectory=/druid/segments**
but there is no segment about this datasource "metrics-kafka"

**Comment by helianthuslulu** [comment]
my env:
druid-0.12.3 release
openjdk-8
hadoop-2.7.1
kafka_2.11-0.10.2.2

**Comment by helianthuslulu** [comment]
data is manually send by kafka-console-producer.sh：
**{"time": "2019-01-04T06:47:17Z", "url": "/ftp/druid", "user": "alice"}**
data should be correct.

**Comment by helianthuslulu** [comment]
The problem is that peon task cannot connect

**Comment by chenyuan9028** [comment]
hello，has your problem resolved?
I meet the same problem these days. Through the logs,I can see the indexing task works well，but after it's done，it is always be publishing and no segments generate.

**Comment by helianthuslulu** [comment]
@chenyuan9028 hello,Did your problem has been solved ?my solution is here： https://github.com/apache/incubator-druid/issues/6809
