### ISSUE TITLE
【kafka-index-service  Druid-0.12.3】Nothing to publish, skipping publish step

### ISSUE THREAD

**Issue by helianthuslulu** [apache/incubator-druid#6809]
Hi， team. I am a druid new user, when ingesting data from kafka to druid by kafka-indexing-service,I met a confused question: 
after task executed successfully, task log shows:
"io.druid.segment.realtime.appenderator.BaseAppenderatorDriver - Nothing to publish, skipping publish step."

I cannot recognize what's wrong with it.....

**Comment by helianthuslulu** [comment]
Does someone had the same problem？

**Comment by nishantmonu51** [comment]
either there is no events to be ingested in the topic or all the events are unparseable.

**Comment by helianthuslulu** [comment]
@nishantmonu51 Thanks for your reply and prompt. I will check again(*￣︶￣)

**Comment by helianthuslulu** [comment]
I find it. The problem is "org.apache.kafka.common.network.Selector - Connection with localhost/127.0.0.1 disconnected", it means connecting to kafka broker failed. it was solved by modify $KAFKA_HOME/config/server.proerties:
**advertised.listeners=PLAINTEXT://xxx.xxx.xxx.xxx:9092**,
then restart kafka service

**Comment by shubhamgupta9597** [comment]
"org.apache.kafka.common.network.Selector - Connection with localhost/127.0.0.1 disconnected"
@helianthuslulu Where did u see this error? 
and what did u modify in "$KAFKA_HOME/config/server.proerties" to resolve this?
