### ISSUE TITLE
Does apache-druid-0.13.0-incubating-bin.tar.gz package has something incorrect?

### ISSUE THREAD

**Issue by helianthuslulu** [apache/incubator-druid#6818]
![image](https://user-images.githubusercontent.com/4606832/50825615-6c8fac80-1374-11e9-9be8-84ccf6f220c2.png)

I download it twice ensure download full，is there something wrong ?I'm not sure.... I cannot understand...

**Comment by gianm** [comment]
It might be an error with your extraction of the tarball. Or try checking the sha512 and gpg signature to make sure you got the right tarball.

**Comment by dragonls** [comment]
The same situation as in https://github.com/apache/incubator-druid/issues/6442#issuecomment-449295061
