### ISSUE TITLE
[Proposal] Consolidated segment metadata management

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#6849]
## Motivation
Druid currently stores segment metadata in two places, i.e., metadata store and deep storage. In metadata store, segment metadata is stored in `segments` table. In deep storage, it's stored in `descriptor.json` file.

Druid core retrieves segment metadata only from the metadata store, and only `insert-segment-to-db` tool uses `descriptor.json` file to find segment files in deep storage.

However, storing metadata in two different places has several drawbacks.

1. An additional effort is required to make sure that the same segment metadata is stored in metadata store and deep storage (https://github.com/apache/incubator-druid/issues/4170). 
2. Deep storage migration is complex because it needs to update metadata in both metadata store and deep storage.

`insert-segment-to-db` tool seems to be introduced for recovery when the metadata store is broken (https://github.com/apache/incubator-druid/pull/1861), but another approach should be employed to handle that kind of error, e.g., replicating metadata store.

## Public Interfaces
`DataSegmentFinder` will be removed.

## Proposed Changes
The segment metadata is stored only in the metadata store.

## Compatibility, Deprecation, and Migration Plan
This is not a backward compatible change. `descriptor.json` file is no longer stored in deep storage. `insert-segment-to-db` tool will be removed.

Deep storage migration would become simpler since segment metadata needs to be updated in only metadata store.

## Test Plan
N/A

## Rejected Alternatives
N/A

**Comment by josephglanville** [comment]
I think this is a big simplicity win. Most people are already using replicated metadata databases with PITR (or managed options like RDS/Google Cloud SQL).

**Comment by jihoonson** [comment]
It's quite limited. Only `dataSource`, `interval`, `version`, `loadspec`, `binaryVersion`, and `size` are fully restorable. It looks hard to determine what is `dimensions` or `metrics` from `meta.smoosh`. `shardSpec` cannot be restored since we don't know its type. This gets even worse after https://github.com/apache/incubator-druid/issues/6319. `overshadowedSegments` and `atomicUpdateGroup` cannot be restored from the segment path and index.zip, which means the overshadowing relation cannot be restored.

As I noted in the proposal, I think replicating metadata store is a better solution for disaster recovery. I would imagine that deep storage is likely broken if the metadata store is broken by some sort of disaster and they are in the same data center.

**Comment by nishantmonu51** [comment]
I have seen people in past using insert-segment-to-db tool to recover metadata storage db segments. 
Having said that, I think its ok to remove it and the descriptor file as well from deep storage, but at the same time we need to update docs to have more emphasis on recommending the increased importance of metadata storage in the docs and add recommendations for setting up recovery and backup policies for the metadata storage.

**Comment by capistrant** [comment]
@jihoonson This was a cool change. I have a question regarding the existing descriptor.json files after the upgrade. Do they need to be manually removed? We use HDFS as a deep store so it would be nice to reduce the file count from Druid after upgrade validation. Thanks!

**Comment by gianm** [comment]
They don't _need_ to be manually removed, but you can if you want to.

**Comment by jihoonson** [comment]
@capistrant as @gianm said, you don't have to. `KillTask` will remove them automatically. Also please note that `KillTask` will fail in 0.14.0 or earlier if `descriptor.json` file is missing. It means, once you remove those files, it might be hard for you to roll back to an earlier version.
