### ISSUE TITLE
druid-0.13.0-incubating | Druid broker and Druid History is failing to start in Docker 

### ISSUE THREAD

**Issue by havannavar** [apache/incubator-druid#6872]
Hi,
I'm trying to run **druid-0.13.0-incubating** using docker under 64GB RAM and 4Core CPU machine.
Zookeeper is a different image and a container
Broker is a different image and 3 containers
History is in different machine
coordinator, overload, Middlemanager are in different containers but same machine as broker and zookeeper (Still not went to production, so keeping all processes in same machine except History)

Though  coordinator, overload and Middlemanager  are working
Tested by creating datasource and cross verified the creation of datasource with API's.

But, Broker and History have not started at all and this is the error I get. And in logs I don't see any error or fail messages. Can someone help me ? Thanks in advance

```
[Wed Jan 16 15:17:30 2019] Command[broker] failed, see logfile for more details: /opt/druid/druid/var/sv/broker.log
[Wed Jan 16 15:17:32 2019] Running command[broker], logging to[/opt/druid/druid/var/sv/broker.log]: bin/run-druid broker quickstart/tutorial/conf
[Wed Jan 16 15:19:04 2019] Command[historical] exited (pid = 24, signal = 9)
[Wed Jan 16 15:19:04 2019] Command[historical] failed, see logfile for more details: /opt/druid/druid/var/sv/historical.log
[Wed Jan 16 15:19:06 2019] Running command[historical], logging to[/opt/druid/druid/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Jan 16 15:19:38 2019] Command[broker] exited (pid = 310, signal = 9)
[Wed Jan 16 15:19:38 2019] Command[broker] failed, see logfile for more details: /opt/druid/druid/var/sv/broker.log
[Wed Jan 16 15:19:44 2019] Running command[broker], logging to[/opt/druid/druid/var/sv/broker.log]: bin/run-druid broker quickstart/tutorial/conf
[Wed Jan 16 15:19:44 2019] Command[historical] exited (pid = 340, signal = 9)
[Wed Jan 16 15:19:44 2019] Command[historical] failed, see logfile for more details: /opt/druid/druid/var/sv/historical.log
[Wed Jan 16 15:19:47 2019] Running command[historical], logging to[/opt/druid/druid/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
```

**Comment by havannavar** [comment]
I'm able to fix the issue, as this was network issue and fixed zookeeper in common.properties fiel too

**Comment by TicklesTheBrain** [comment]
I'm running into the same issue. Would you mind telling how you fixed this issue? What did you change in common.runtime.properties? Did you need to touch any other configs? Thanks.

**Comment by havannavar** [comment]
my main issues was  `druid.zk.service.host`, I fixed that by adding IP address of the zookeeper

```
druid.zk.service.host=<ip-address of running zookeeper>
druid.zk.paths.base=<base folder of the druid inside the docker container eg. /druid>
```
And for paths.base, it should be the location of the /druid inside the container.

**Comment by tonytjo** [comment]
Dear @havannavar 
Sorry for my ignorance.
How could I update the druid.zk.service.host config?

I'm using helm to deploy druid in kubernetes cluster:
https://hub.helm.sh/charts/incubator/druid

Regards,
Tony
