### ISSUE TITLE
Kill Segment Grace Period

### ISSUE THREAD

**Issue by capistrant** [apache/incubator-druid#6873]
I wanted to propose a potential feature addition to coordinator kill task automation and see what the community thinks about it. It is an enhancement that came up in some discussions at my current org and we thought it would be worthwhile to see what the community thinks. 

As I will indicate below, this would likely require a schema change to druid_segments table and I am not sure if the project is open to entertaining schema changes to this table. Therefore, this proposal could very well be dead on arrival, but nevertheless I wanted to bring it up and see what others think.

Use case:

We want to turn coordinator kill on in production, but we also want to guard against accidental permanent deletes of data in the deepstore if possible. To accomplish this, we thought there could be some value in having a "grace period" starting when a segment goes from used=1 to used=0 in the metastore. The coordinator kill logic would then never create a kill task for a segment who became unused within the grace period.

Accomplishing this today:

I don't believe there is a way to accomplish this with the current state of configuration available. But someone please correct me if I am wrong so I can close this issue as non-actionable!

What this may require at a very high level:

I expect that this would require a schema change in the druid_segments table because the kill logic would need to identify if a segment became disabled within the grace period. I'm not sure what the general consensus is on altering metastore schema, but if it is acceptable to do so, I could potentially foresee something like this:

`disabled_date` could be a date field in druid_segments that serves as a timestamp of when a segment became unused by the cluster.

`druid.coordinator.kill.gracePeriod` would be a potential coordinator config that specifies an iso 8601 period. The default of `PT0S` would indicate to the coordinator kill logic to ignore filtering on `disabled_date` and perform its kill how it would today. However, if the period was any other valid value the coordinator would filter on `disabled_date` and only kill segments whose `disabled_date` falls outside of the grace period.

**Comment by jihoonson** [comment]
Hi @capistrant, thank you for the proposal.

It sounds useful, but I'm wondering how different it is from `druid.coordinator.kill.durationToRetain`. The coordinator currently doesn't kill segments if their intervals overlap with (`now - durationToRetain`, `now`). The proposed solution sounds like counting time per segment since each of them has been disabled. Do you know a particular use case that the current behavior doesn't make sense and the proposed solution is needed?

**Comment by capistrant** [comment]
@jihoonson 

`druid.coordinator.kill.durationToRetain` is useful for us in some cases. We currently use it so protect the last N days from being killed (usually 7 or 14 days for us).

The use case I am referring to is more of a `soft kill` for a set period fo time followed by an actual kill if no action was taken to re-enable the segments. This opposed to a permanent retain rule like the `durationToRetain` config does. Our initial idea was to only have the kill task runner run once per day, but that only gives us a good grace period for segments that wen't to unused shortly after the previous execution of the kill task process. Our main problem has been disabling datasources that were still needed and having them be killed before we were alerted to the problem.

Now that I am thinking about this more, it may just be an administrative issue that my org needs to sort out on our own instead of adding this guard. We run a multi-tenant cluster in production with a large number of end users so the lines on what data is useful and what is stale can get blurred for us. Long story short, maybe this proposal isn't the best solution to the problem we face.

**Comment by jihoonson** [comment]
Thank you for the details. I have a follow-up question. Kill tasks can delete only unpublished segments (segments with `used = false` in metadata store) and this is also same when `durationToRetain` is set. If you have published segments older than `now - durationToRetain`, they won't be deleted. So, I guess the difference is a sort of soft-kill-period is reset once an unpublished segment is published again. Is this correct? It sounds good to me, but it would be nice if it can be implemented without changing the data schema of metadata store. 

> Long story short, maybe this proposal isn't the best solution to the problem we face.

Welcome any idea if you have a better one!
