### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by maver1ck** [apache/incubator-druid#6874]
Creating Helm Chart for Druid brings the question about official Druid image. https://github.com/helm/charts/pull/9314
Unfortunately the only druid image is "example-cluster" which cannot be used in Kubernetes.

Do we have any plans to support it ?

The work can be based on my repo: https://github.com/maver1ck/druid-docker

**Comment by gianm** [comment]
There isn't any official Druid docker image -- currently, the only Druid-project-approved releases are the ones you see here: http://druid.apache.org/downloads (source and binary tarballs). Making an official one would be a good discussion for the Druid dev list (dev@druid.apache.org), as to how to fit it into our release processes, where to serve it from, and how it should work (there's more than one way to build a Docker image!)

**Comment by maver1ck** [comment]
I think it is right now
https://github.com/apache/incubator-druid/tree/master/distribution/docker

**Comment by vogievetsky** [comment]
As of 0.16.0 there is an official Docker image 🎆 https://hub.docker.com/r/apache/incubator-druid

**Comment by averma111** [comment]
While pulling the docker image it gives the error.
Using default tag: latest
Error response from daemon: manifest for apache/incubator-druid:latest not found: manifest unknown: manifest unknown

**Comment by averma111** [comment]
> There isn't any official Druid docker image -- currently, the only Druid-project-approved releases are the ones you see here: http://druid.apache.org/downloads (source and binary tarballs). Making an official one would be a good discussion for the Druid dev list ([dev@druid.apache.org](mailto:dev@druid.apache.org)), as to how to fit it into our release processes, where to serve it from, and how it should work (there's more than one way to build a Docker image!)

Using default tag: latest
Error response from daemon: manifest for apache/incubator-druid:latest not found: manifest unknown: manifest unknown

**Comment by azbarcea** [comment]
I was able to start and play with druid following #8702, by using the composition available in `distribution/docker`
