### ISSUE TITLE
Only single-lined json objects inside input files are parseable

### ISSUE THREAD

**Issue by etlolap** [apache/incubator-druid#6876]
It seems that only single-lined json objects inside input data are parseable. I ran the following command: 
`bin/post-index-task --file ...`
The index json file is per Druid [docs](http://druid.io/docs/latest/tutorials/tutorial-batch.html). 
`{
    "type": "index",
    "spec": {
        "dataSchema": {
            "dataSource": "ingestion-tutorial",
            "parser": {
                "type": "string",
                "parseSpec": {
                    "format": "json",
                    "timestampSpec": {
                        "format": "iso",
                        "column": "ts"
                    },
                    "dimensionsSpec": {
                        "dimensions": [
                            "srcIP",
                            {
                                "name": "srcPort",
                                "type": "long"
                            },
                            {
                                "name": "dstIP",
                                "type": "string"
                            },
                            {
                                "name": "dstPort",
                                "type": "long"
                            },
                            {
                                "name": "protocol",
                                "type": "string"
                            }
                        ]
                    }
                }
            },
            "metricsSpec": [
                {
                    "type": "count",
                    "name": "count"
                },
                {
                    "type": "longSum",
                    "name": "packets",
                    "fieldName": "packets"
                },
                {
                    "type": "longSum",
                    "name": "bytes",
                    "fieldName": "bytes"
                },
                {
                    "type": "doubleSum",
                    "name": "cost",
                    "fieldName": "cost"
                }
            ],
            "granularitySpec": {
                "type": "uniform",
                "segmentGranularity": "HOUR",
                "queryGranularity": "MINUTE",
                "intervals": [
                    "2018-01-01/2018-01-02"
                ],
                "rollup": true
            }
        },
        "ioConfig": {
            "type": "index",
            "firehose": {
                "type": "local",
                "baseDir": "quickstart/",
                "filter": "ingestion-tutorial-data1.json"
            }
        },
        "tuningConfig": {
            "type": "index",
            "targetPartitionSize": 5000000
        }
    }
}`
This works with single-lined json input data files as below. The actual format is that each json object occupies one line in the file. 
`{"ts":"2018-01-01T01:01:35Z","srcIP":"1.1.1.1", "dstIP":"2.2.2.2", "srcPort":2000, "dstPort":3000, "protocol": 6, "packets":10, "bytes":1000, "cost": 1.4}
{"ts":"2018-01-01T01:01:51Z","srcIP":"1.1.1.1", "dstIP":"2.2.2.2", "srcPort":2000, "dstPort":3000, "protocol": 6, "packets":20, "bytes":2000, "cost": 3.1}
{"ts":"2018-01-01T01:01:59Z","srcIP":"1.1.1.1", "dstIP":"2.2.2.2", "srcPort":2000, "dstPort":3000, "protocol": 6, "packets":30, "bytes":3000, "cost": 0.4}
{"ts":"2018-01-01T01:02:14Z","srcIP":"1.1.1.1", "dstIP":"2.2.2.2", "srcPort":5000, "dstPort":7000, "protocol": 6, "packets":40, "bytes":4000, "cost": 7.9}
{"ts":"2018-01-01T01:02:29Z","srcIP":"1.1.1.1", "dstIP":"2.2.2.2", "srcPort":5000, "dstPort":7000, "protocol": 6, "packets":50, "bytes":5000, "cost": 10.2}
{"ts":"2018-01-01T01:03:29Z","srcIP":"1.1.1.1", "dstIP":"2.2.2.2", "srcPort":5000, "dstPort":7000, "protocol": 6, "packets":60, "bytes":6000, "cost": 4.3}
{"ts":"2018-01-01T02:33:14Z","srcIP":"7.7.7.7", "dstIP":"8.8.8.8", "srcPort":4000, "dstPort":5000, "protocol": 17, "packets":100, "bytes":10000, "cost": 22.4}
{"ts":"2018-01-01T02:33:45Z","srcIP":"7.7.7.7", "dstIP":"8.8.8.8", "srcPort":4000, "dstPort":5000, "protocol": 17, "packets":200, "bytes":20000, "cost": 34.5}
{"ts":"2018-01-01T02:35:45Z","srcIP":"7.7.7.7", "dstIP":"8.8.8.8", "srcPort":4000, "dstPort":5000, "protocol": 17, "packets":300, "bytes":30000, "cost": 46.3}
`
But it doesn't work ("not parseable") with same json content, in a different, multi-lined format. I didn't copy and paste here, as the return line characters are automatically removed by the text editor here. The actual format is that, each json field occupies one line of the file, and each json object spans across multiple lines.

**Comment by gianm** [comment]
Today, line-oriented text files are the only kind of text files we support. It would be nice to support other styles but it is not currently possible.
