### ISSUE TITLE
[Proposal] Support a "Random" function as an expression

### ISSUE THREAD

**Issue by sascha-coenen** [apache/incubator-druid#6880]
The following page documents a set of functions that can be used to form expressions: http://druid.io/docs/latest/misc/math-expr.html

Among other things, these expressions can be used in the context of transformSpecs
(documented here http://druid.io/docs/latest/ingestion/transform-spec.html)

It is possible to filter and transform data during indexing or re-indexing by declaring expressions within the transformSpec of an ingestion spec. In this particular context, it might be handy if there was a random() function that could be used inside of an expression. 

One possible usecase for having a random() function would be to "sample" data during re-indexing in order to reduce the datavolume and the number of records and thus speed up queries.

**Comment by gianm** [comment]
Instead of random, maybe some kind of deterministic sampling? (Based on a hash, for example.) The reason for this suggestion is that it's good for ingestion to be deterministic - mapper retries during Hadoop-based ingest and replicas during Kafka-based ingest both rely on determinism.
