### ISSUE TITLE
Unable to determine column type from INFORMATION_SCHEMA.COLUMNS

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-druid#6887]
Per the [broker](http://druid.io/docs/latest/operations/api-reference.html#broker) API documentation it suggests that the `/druid/v2/datasources/{dataSourceName}/metrics` API endpoint is deprecated, 

> This API is deprecated and will be removed in future releases. Please use [SegmentMetadataQuery](../querying/segmentmetadataquery.html) instead which provides more comprehensive information and supports all dataSource types including streaming dataSources. It's also encouraged to use [INFORMATION_SCHEMA tables](../querying/sql.html#retrieving-metadata) if you're using SQL.

however for the [INFORMATION_SCHEMA.COLUMNS](http://druid.io/docs/latest/querying/sql.html#retrieving-metadata) there doesn't seem to be any way to decipher between a dimension or metric column.

Is there any other way to get the set of dimensions/metrics for a given datasource?

**Comment by gianm** [comment]
That's true, currently the SQL metadata doesn't tell you whether something was ingested as a dimension or a metric. The SegmentMetadataQuery should, though. It tells you column types and aggregator specs if you ask for them via analysisTypes. For data ingested in relatively recent versions of Druid, it's safe to assume that anything with an aggregator spec is a metric (and anything without is a dimension).
