### ISSUE TITLE
Support for optional client authentication on TLS

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#6900]
Enabling Mutual TLS via `druid.server.https.requireClientCertificate` currently enforces client authentication and therefore requests without a client certificate fails to talk to Druid. This doesn't allow Druid to support other forms of client authentication once Mutual TLS is enabled.

I'm looking at adding a `wantClientAuth`configuration for Druid to make client authentication optional so that server will request for a client certificate, but will not fail if the client doesn't provide one.
Does this sound reasonable? @jon-wei

**Comment by jon-wei** [comment]
> I'm looking at adding a wantClientAuthconfiguration for Druid to make client authentication optional so that server will request for a client certificate, but will not fail if the client doesn't provide one.

That seems fine to me, it's a supported option on the SSL socket.

>  This doesn't allow Druid to support other forms of client authentication once Mutual TLS is enabled.

I'm curious though, in your use case, what checks happen when a client does not provide a valid client cert?

**Comment by a2l007** [comment]
In case the client does not provide a certificate, we may authenticate the user against other authentication schemes such as Okta. This usecase is primarily for browser based users who would like to interact with the druid console as well as use the REST endpoints.
