### ISSUE TITLE
Bring GCP functionality to core functionality

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#6910]
We heavily use the Google Cloud extensions internally, and have encountered some pain points with it being in a contrib extension.

Like the AWS module at https://github.com/apache/incubator-druid/tree/druid-0.13.0-incubating/aws-common this ask is that there be a GCP common which supplies a default `com.google.api.client.http.HttpRequestInitializer`, `com.google.api.client.http.HttpTransport`, and `com.google.api.client.json.JsonFactory`. Any extensions which use the client api can then pull from the parent classpath's instance of these or supply their own. And modules are able to then override the default supplied ones if required.

The overall suggestion is to do the following (in no specific order):

1. Move `aws-common` into `cloud/aws-common`
2. Create `gcp-common` at `cloud/gcp-common` which contains a simple module for supplying `com.google.api.client.http.HttpRequestInitializer`, `com.google.api.client.http.HttpTransport`, and `com.google.api.client.json.JsonFactory`
3. Move the google-extension into extensions-core , we are willing to put effort into maintaining this extension as time goes on.
4. Modify google-extension to use the base gcp-common.

**Comment by jihoonson** [comment]
@drcrallen thanks for raising this issue. Moving GCP functionality to extensions-core sounds nice. 

I think some more details would help other people to understand what the problem is and what you want to do here. For example, I wonder what default implementations for `HttpRequestInitializer`, `HttpTransport`, and `JsonFactory` you're considering. 

I think this should be more like a proposal rather than a simple issue. Would you please add some more details?

**Comment by drcrallen** [comment]
Sure, the pain points are that I have extensions that do things like password providers using KMS, and things like the watermark extension. These use GCP clients which require a lot of duplicates of libraries  somewhere in the class loaders. This makes Hadoop style indexing have problems because all of the libs get jumbled together when the hadoop jobs are run.

Here is a rough example of the module I'm hoping can be in stock druid:


```java

public class GcpModule implements DruidModule
{
  @Override
  public List<? extends Module> getJacksonModules()
  {
    return ImmutableList.of();
  }

  @Override
  public void configure(Binder binder)
  {
    // NOOP
  }


  @Provides
  @LazySingleton
  public HttpRequestInitializer getHttpRequestInitializer(
      HttpTransport transport,
      JsonFactory factory
  )
  {
    try {
      return GoogleCredential
          .getApplicationDefault(transport, factory)
          .createScoped(Collections.singleton("https://www.googleapis.com/auth/cloud-platform"));
    }
    catch (IOException e) {
      throw new RuntimeException("Unable to build authentication", e);
    }
  }

  @Provides
  @LazySingleton
  public HttpTransport getHttpTransport()
  {
    return new NetHttpTransport.Builder()
        .build();
  }

  @Provides
  @LazySingleton
  public JsonFactory getJsonFactory()
  {
    return JacksonFactory.getDefaultInstance();
  }
}
```

This would allow the GCP api client, which has transitive guava and jackson dependencies, to be controlled at the master pom level rather than having their lib versions buried down in the extension. That makes guava and jackson version conflicts easier to manage, and allows extensions in house to not have to load the same jars multiple times.

**Comment by drcrallen** [comment]
For a module which uses KMS, it can be injected by something like the following:


```java

class CloudKmsProvider implements Provider<CloudKMS>
{
  private final HttpRequestInitializer requestInitializer;
  private final HttpTransport httpTransport;
  private final JsonFactory jsonFactory;

  @Inject
  public CloudKmsProvider(
      final HttpRequestInitializer requestInitializer,
      final HttpTransport httpTransport,
      final JsonFactory jsonFactory
  )
  {
    this.requestInitializer = requestInitializer;
    this.httpTransport = httpTransport;
    this.jsonFactory = jsonFactory;
  }

  @Override
  public CloudKMS get()
  {
    return new CloudKMS(httpTransport, jsonFactory, requestInitializer);
  }
}

```

**Comment by jon-wei** [comment]
The suggested changes sound reasonable to me.

On a somewhat related note, do you have any experience running Druid using Dataproc for Hadoop + GCS deep storage?

There's a thread on the mailing list recently about how to get that to work, maybe an area for us to flesh out if we move towards greater Google Cloud support.

**Comment by drcrallen** [comment]
I do have experience with those things. You have to include `com.google.cloud.bigdataoss:gcs-connector` as another default hadoop artifact in addition to the hadoop client you are using for dataproc.

Be aware that recent versions of `com.google.cloud.bigdataoss:gcs-connector` have terrible guava dependency problems.

**Comment by drcrallen** [comment]
The *most* useful override I foresee is `HttpRequestInitializer`, where a company may want to have their own custom way of fetching GCP service account credentials, and need a module to fetch such things.

**Comment by gianm** [comment]
@drcrallen,

I am 10000% in favor of AWS and GCP being treated roughly equally, especially given your ability to commit to maintaining the GCP extension.

I am less excited about adding a `gcp-common` module. I don't really love the `aws-common` module and wish it was something you only had to load if you're actually using AWS-y extensions. Your proposal would cement that, IMO, non-ideal design in place further by doing the same thing with GCP. It is unfair that I only bring this up now, but please accept my apologies for that.

Would it work to remove both the `aws-common` and `gcp-common` modules from `distribution`, and switch them from `provided` to `compile` in the extensions that use them, so the extensions bundle the jars rather than it appearing in `lib/` to always be loaded? It would mean some more redundancy in extension jars (more than one extension uses AWS stuff) but it would mean that core is cleaner (no aws jars loaded if you don't need any of those extensions). It seems like a reasonable tradeoff.

**Comment by drcrallen** [comment]
"Dependency of dependency" is a problem in a few areas now. I can't think of a better solution for the time being, though.

At least with a "standard" module that is pulled into extensions can allow us to manage dependencies a bit better, even if the libs are duplicated.

**Comment by drcrallen** [comment]
I'll update my PR to see how that looks

**Comment by drcrallen** [comment]
haha, its a bunch more work that it sounds. A lot of things in the IndexingService are AWS based

**Comment by drcrallen** [comment]
@gianm  I just realized, this makes it where injecting some of the dependencies is nearly impossible.

I'll think some more on it when I get a chance and see if a good solution comes up

**Comment by gianm** [comment]
Ah I forgot about the AWS stuff in indexing-service. I guess you’re talking about the EC2 autoscaler. That should really be an extension.

What issue are you running into with injecting the dependencies?

**Comment by drcrallen** [comment]
https://travis-ci.org/apache/incubator-druid/jobs/486550791 Injection bites a big "no can do"

**Comment by drcrallen** [comment]
I moved the ec2 autoscaler into an extension on its own.

**Comment by gianm** [comment]
Actually, this happened in https://github.com/apache/incubator-druid/pull/6953.
