### ISSUE TITLE
how to load data from s3 if i dont deploy a cluster 

### ISSUE THREAD

**Issue by laspery** [apache/incubator-druid#6919]
l use the imply to deloy a druid but use the cluster .when i load the data froms3 in the imply ui ,i meet a problem . i have been set the druid-extension 

Parsing failed: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 2C08A767B4340054; S3 Extended Request ID: BSIa10V1uBOssGt+lQQ188W8vnSd/O3aGVBCmiFnZpN1aSm4VENs3wb9j0kACm/DZVkK56/qlbI=)

**Comment by egor-ryashin** [comment]
@laspery I wonder if the issue is resolved?

**Comment by BigDataArtist** [comment]
Hi, My ingestion task says success when I import data from S3 to druid but then the druid never makes its data source , I am submitting the spec thru command line.

#Command
bin/post-index-task --file quickstart/tutorial/wikipedia-index-s3.json --url http://localhost:8081

My SPEC

{
  "type" : "index_parallel",
  "spec" : {
    "dataSchema" : {
      "dataSource" : "wikipediaTest",
      "timestampSpec": {
        "column": "time",
        "format": "iso"
      },
      "dimensionsSpec" : {
        "dimensions" : [
          "channel",
          "cityName",
          "comment",
          "countryIsoCode",
          "countryName",
          "isAnonymous",
          "isMinor",
          "isNew",
          "isRobot",
          "isUnpatrolled",
          "metroCode",
          "namespace",
          "page",
          "regionIsoCode",
          "regionName",
          "user",
          { "name": "added", "type": "long" },
          { "name": "deleted", "type": "long" },
          { "name": "delta", "type": "long" }
        ]
      },
      "metricsSpec" : [],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "day",
        "queryGranularity" : "none",
        "intervals" : ["2015-09-12/2015-09-13"],
        "rollup" : false
      }
    },
    "ioConfig" : {
      "type" : "index_parallel",
      "inputSource" : {
        "type" : "s3",
        "prefixes": ["s3://druids3migration/druid/segments/wikiticker-2015-09-12-sampled2.json"]
 },
      "inputFormat" : {
        "type" : "json"
      },
      "appendToExisting" : false
    },
    "tuningConfig" : {
      "type" : "index_parallel",
      "maxRowsPerSegment" : 5000000,
      "maxRowsInMemory" : 25000
    }
  }
}
