### ISSUE TITLE
Class org.apache.hadoop.hive.ql.io.orc.OrcNewSplit not found

### ISSUE THREAD

**Issue by chenhaiyan** [apache/incubator-druid#6925]
when I load orc file to Druid，return the error，`Class org.apache.hadoop.hive.ql.io.orc.OrcNewSplit not found`， I  have hive-exec-2.0.0.jar in my extension. others say it can be solved by `"jobProperties" : {
        "mapreduce.job.classloader" : "true",
        "mapreduce.job.classloader.system.classes": "-javax.validation.,java.,javax.,org.apache.commons.logging.,org.apache.log4j.,org.apache.hadoop."
      }` , but this doesn't work for me . Can anyone give some help?

**Comment by egor-ryashin** [comment]
@chenhaiyan could you post here the task schema, the orc file schema and Druid version?
