### ISSUE TITLE
bin/dsql doesn‘t work

### ISSUE THREAD

**Issue by chenhaiyan** [apache/incubator-druid#6926]
I use imply.io for druid。when I run ./bin/dsql，return error like this `Welcome to dsql, the command-line client for Druid SQL.
Connected to [http://localhost:8082/].

Traceback (most recent call last):
  File "/usr/local/bigdata/imply-2.8.6/bin/dsql-main", line 556, in <module>
    main()
  File "/usr/local/bigdata/imply-2.8.6/bin/dsql-main", line 494, in main
    readline.read_history_file(readline_history_file)
IOError: [Errno 2] No such file or directory`

I just want to know what is wrong?

**Comment by gianm** [comment]
Hi @chenhaiyan, I think this is a question about the Imply distribution of Druid, not about the Apache Druid project. (At Imply we are shipping basically the Apache Druid distro, but with some additional goodies including the script you mentioned.)

The issue you described has been fixed a couple of Imply releases ago; try the latest 2.8.9.
