### ISSUE TITLE
Checkstyle: prohibit method names starting with a capital letter

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#6936]

**Comment by hpandeycodeit** [comment]
@leventov I will take this one.

**Comment by hpandeycodeit** [comment]
@leventov After adding this check, I am getting few methods starting with Capital Letters. Shall I fix those as well?

**Comment by hpandeycodeit** [comment]
@leventov I am seeing some Inspection/Teamcity build failing. I don't see any errors in my local build though. Any idea?

**Comment by leventov** [comment]
@hpandeycodeit it seems fine - two automatic checks passed. Thank you!

**Comment by hpandeycodeit** [comment]
Thank you!
