### ISSUE TITLE
Create a proposal template

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6949]
Hi, it would be nice if any committer could create a [Proposal] issue template.
What do you committers say? :)

I tried it on my own repository, it's pretty easy. It's done over here:
https://github.com/apache/incubator-druid/issues/templates/edit
And documentation is here:
https://help.github.com/articles/creating-issue-templates-for-your-repository/
https://help.github.com/articles/about-issue-and-pull-request-templates/

I could see a couple of good examples when searching for the Proposal tag.

(Off topic, but BTW, we could even add more templates for bug reports in the future to promote structured reporting.)

**Comment by yurmix** [comment]
Nice, I see this KIP template on their Confluence site: https://cwiki.apache.org/confluence/display/KAFKA/KIP-Template
Is this what we meant to use?

**Comment by gianm** [comment]
Could you please also post a link to this in the dev list thread where we've been talking about proposals?

**Comment by jon-wei** [comment]
Sure, good idea

**Comment by yurmix** [comment]
@jon-wei OK, I've just posted the link there.

**Comment by jon-wei** [comment]
Proposal template PR: https://github.com/apache/incubator-druid/pull/7062

**Comment by clintropolis** [comment]
resolved by #7062
