### ISSUE TITLE
Fix Invalid Link for Rollup Tutorial

### ISSUE THREAD

**Issue by kamaci** [apache/incubator-druid#6962]
At this page: http://druid.io/technology

It is explained as:

> Unlike many traditional systems, Druid can optionally pre-aggregate data as it is ingested. This pre-aggregation step is known as rollup, and can lead to dramatic storage savings.

However, rollup links to:

http://druid.io/docs/latest/design/#roll-up

which should be:

http://druid.io/docs/latest/tutorials/tutorial-rollup.html

**Comment by kamaci** [comment]
I can update it if I can access to such page.

**Comment by gianm** [comment]
You can do it with a PR to https://github.com/druid-io/druid-io.github.io.

**Comment by kamaci** [comment]
Thanks for mentioning it! I've created https://github.com/druid-io/druid-io.github.io/pull/560

**Comment by kamaci** [comment]
#560 is merged and we can close this issue!

**Comment by kamaci** [comment]
Closing this issue since https://github.com/druid-io/druid-io.github.io/pull/560 is merged.
