### ISSUE TITLE
Tuning Kafka Indexing Service for real time

### ISSUE THREAD

**Issue by erankor** [apache/incubator-druid#6963]
Hi all,

Sorry if this is already answered somewhere, tried to google for it and didn't find a clear explanation...

One of our data sources is highly real time in nature = most queries include an interval very close to the live edge. 
We are using:
- KIS for ingestion
- Query granularity of 10 sec (1 sec in Druid, rounded to 10 sec outside druid)
- Segment granularity of 1 hour

Most of our 1 hour segments fall in the range 300-900 MB after merging the partitions using Hadoop. This is very close to recommendations, which probably means the 1 hour segment granularity is not a very bad choice. 
However, since most queries touch the live edge, I think it may be beneficial to have KIS generate smaller segments (maybe 5 min), in order to have a larger portion of the query answered by finalized/immutable segments. These segments will later be merged anyway in offline, in order to get them close to the recommended size.

My questions are - 
1. Does this logic make sense?
2. What is the relation between the KIS taskDuration and segmentGranularity? do I need to change both? what happens if segmentGranularity is 5 min while taskDuration is 1 hour?
3. Read in a few places that windowPeriod is not needed for KIS, if I change the segment duration to 5 min and an event arrives 2 min late, what happens with it?

Thank you!

Eran

**Comment by gianm** [comment]
If most of your queries are just the last hour of data and you want to get those segments out to the historicals as fast as possible, then, it could potentially make sense. Instead of adjusting segmentGranularity, you might prefer to keep 'hour' for your segmentGranularity, but shorten the taskDuration. Or even keep taskDuration the same, but shorten the intermediateHandoffPeriod. This is because running with mixed segmentGranularities in the same datasource, while supported, can be a headache. Shortening the other two configs just means handoff happens more often.

> Read in a few places that windowPeriod is not needed for KIS, if I change the segment duration to 5 min and an event arrives 2 min late, what happens with it?

A new segment is created - this is one of the reasons why KIS + compaction = ❤️

**Comment by erankor** [comment]
Thanks @gianm!

**Comment by erankor** [comment]
@gianm, another question on this, just to clarify - if I set either intermediateHandoffPeriod or taskDuration to 5 min, but leave segmentGranularity on 1 hour, it means the same data will be indexed over and over again, right?  To put it differently - the events of the first 5 min of the hour will be indexed 12 times until the full 1 hour segment is finalized. 
If that is indeed the case, maybe there is an advantage to changing the segmentGranularity instead, it will put less load on the KIS tasks. 
If having multiple granularities is not recommended, I can update the script we use for merging segments so that it will only merge on hour boundary.

Thank you!

Eran

**Comment by gianm** [comment]
That won't happen - what will happen is that every 5 min, you'll get a new set of segments added to the time chunk for the hour, containing whatever new messages showed up in the those 5 min.

**Comment by erankor** [comment]
Great, thanks again!
