### ISSUE TITLE
PreResponseAuthorizationCheckFilter error when loading coordinator console

### ISSUE THREAD

**Issue by jon-wei** [apache/incubator-druid#6982]
in 0.13.0, when loading the coordinator console, the following error occurs (although the subsequent redirect works and authorization checks are performed correctly in the actual console).

```
ERROR [qtp2058526846-335] io.druid.server.security.PreResponseAuthorizationCheckFilter - Request did not have an authorization check performed.: {class=io.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/, method=GET, remoteAddr=1.1.1.1 remoteHost=1.1.1.1}
```

**Comment by jihoonson** [comment]
I just built the current 0.14.0-incubating branch and tested this, but couldn't reproduce it. Is anyone still seeing this error?

**Comment by jon-wei** [comment]
Closing, has not been reported to occur in 0.14.0-incubating.
