### ISSUE TITLE
A removed documentation page appears as part of the latest documentation

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6998]
The following documentation page: [Production Cluster Configuration](http://druid.io/docs/latest/configuration/production-cluster.html) was removed in version 0.9.2 (The PR: https://github.com/apache/incubator-druid/pull/3188).

However, this page, which will appear in search results (i.e. ["druid"  + "Production Cluster Configuration"](https://www.google.com/search?q=%22druid%22+%22Production+Cluster+Configuration%22)), is identified as part of the latest documentation.

The bug might lay in not removing deleted pages. If you look at the "Docs" link in the top banner, it points to version 0.9.2, so this page was probably not have been rendered since 2016.

**Comment by yurmix** [comment]
@jon-wei can this go into 0.14.0? If you're running the doc release, perhaps you can take a look meanwhile doing that?

**Comment by yurmix** [comment]
Actually, don't worry, I'll try testing it on my own environment first.

**Comment by jon-wei** [comment]
> The bug might lay in not removing deleted pages.

@yurmix Added this to 0.14.0, I think that's probably the cause, thanks!
