### ISSUE TITLE
Documentation inconsistency between reference and examples (for middleManager)

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#6999]
The documentation reference states that `druid.indexer.runner.javaOpts` is deprecated:
https://github.com/apache/incubator-druid/blob/0e926e865276f892ddc5b62685d331b822104022/docs/content/configuration/index.md#L1116
However, it appears in our configuration examples:
https://github.com/apache/incubator-druid/blob/0e926e865276f892ddc5b62685d331b822104022/examples/conf/druid/middleManager/runtime.properties#L27

**Comment by a2l007** [comment]
I don't see this property being deprecated in the code though: https://github.com/apache/incubator-druid/blob/7e48593b5780c3bc4852d183dc473be283c84d25/indexing-service/src/main/java/org/apache/druid/indexing/overlord/config/ForkingTaskRunnerConfig.java#L50 We could fix it and update the docs.

**Comment by yurmix** [comment]
After reading #2533 [#2533](https://github.com/apache/incubator-druid/pull/2533), it looks like this is not actually a deprecated parameter, but a parameter with issues. I will improve the documentation to make it more clear.
