### ISSUE TITLE
Auto Detection of Field Types

### ISSUE THREAD

**Issue by kamaci** [apache/incubator-druid#7027]
I can define auto type detection for timestamp as follows:

```
"timestampSpec" : {
     "format" : "auto",
     "column" : "ts"
}
```

In similar manner, I cannot detect field type via parseSpec. I mean:

`{"ts":"2018-01-01T03:35:45Z","app_token":"guid1","eventName":"app-x","properties-key1":"123"}
`

`{"ts":"2018-01-01T03:35:45Z","app_token":"guid2","eventName":"app-x","properties-key2":123}
`

Both `properties-key1` and `properties-key2` are indexed as `String`. I expect to index `properties-key2` as `Integer` at Druid.

We should implement auto field type detection into Druid for a newly created field.

**PS:** I've started a conversation about this task at mail list and than created an issue for it: [Druid Auto Field Type Detection](https://lists.apache.org/thread.html/f39b9d8284ab9604bc4dde2ca38c515def730c779f735cb47531506b@<dev.druid.apache.org>)

**Comment by kamaci** [comment]
Currently, all fields are threaten as String when `dimensions` field is empty:

> Schema-less dimensions
> If the dimensions field is left empty in your ingestion spec, Druid will treat every column that is not the timestamp column, a dimension that has been excluded, or a metric column as a dimension. It should be noted that because of #658 these segments will be slightly larger than if the list of dimensions was explicitly specified in lexicographic order. This limitation does not impact query correctness- just storage requirements.
> 
> Note that when using schema-less ingestion, all dimensions will be ingested as String-typed dimensions.

However we should have work similar to that: [Solr Schemaless Mode](https://lucene.apache.org/solr/guide/7_6/schemaless-mode.html).

**Comment by kamaci** [comment]
I've started to work on this issue. I have 3 possible solutions on undefined schema fields:

1) If value can be convertible to `Float` than convert to `Float`, otherwise try with `Long`, otherwise go with `String`.

2) If field name ends with `_l,` and is not defined at scheme, and a config value of `schemeless mode` is enabled then convert to `Long`, so on so forth.

3) Create a regex defined field. Accept a regex value and make transformation on it which is a generic solution of 2. i.e.:

```
{ "pattern": "*_l", "type": "long" },
{ "pattern": "*_f", "type": "float" }
```

@gianm what do you think?

**Comment by jihoonson** [comment]
Hi @kamaci, thank you for raising this issue. 
I’m not sure what solution you are considering to implement. Are you thinking to pick one of them or support all of them?

Also, would you please write a proposal before you start implementation? It would make clear what your idea is and what you want to implement. You can write a proposal by opening a new issue and choosing the proposal template.

**Comment by kamaci** [comment]
Hi @jihoonson 

These are possible solutions. I can go with 3th one but I've wanted to talk about it before doing implementation. I can create a proposal with template.

**Comment by hyogrin** [comment]
+10000 
Awesome!! : ) This feature is exactly what I was waiting for. I think the 3th option will be a good option for users

**Comment by kamaci** [comment]
I've close this issue since I submitted https://github.com/apache/incubator-druid/issues/7255
