### ISSUE TITLE
[ERROR] Issue with Hadoop Indexer and null numeric dimensions

### ISSUE THREAD

**Issue by ferristseng** [apache/incubator-druid#7050]
I'm running into an issue where the Hadoop Indexer is still treating null numeric dimensions as 0 in `0.13.0-incubating`, even when the system property `druid.generic.useDefaultValueForNull` is set to `false`. 

I dug a little bit into the code, and noticed that the Hadoop Indexer was not updated to treat null numeric dimensions in a SQL-compatible way:

https://github.com/apache/incubator-druid/blob/7e48593b5780c3bc4852d183dc473be283c84d25/indexing-hadoop/src/main/java/org/apache/druid/indexer/InputRowSerde.java#L179

I made a fix for the issue here:

https://github.com/apache/incubator-druid/pull/7020

**Comment by ferristseng** [comment]
Any ideas if this is needed in the future?

**Comment by jihoonson** [comment]
It looks a correct fix. @ferristseng are you planning raising a PR to fix this bug?

**Comment by ferristseng** [comment]
@jihoonson I made a PR for it, and it's been merged. I think it might be in the current release or in the next release!

**Comment by jihoonson** [comment]
@ferristseng oh #7020 is the fix for this issue. Thanks!
