### ISSUE TITLE
Use only com.google.errorprone.annotations.concurrent.GuardedBy, not javax.annotations.concurrent.GuardedBy

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7059]
`com.google.errorprone.annotations.concurrent.GuardedBy` is preferable because Error Prone's GuardedBy bug pattern recognizes only Error Prone's own version of `GuardedBy`.

`javax.annotations.concurrent.GuardedBy` (and in other packages, if any) should be prohibited with forbidden-apis.

**Comment by asdf2014** [comment]
> There are a couple more annotations called `@GuardedBy`, including `javax.annotation.concurrent.GuardedBy` and`org.checkerframework.checker.lock.qual.GuardedBy`. The check recognizes those versions of the annotation, but we recommend using `com.google.errorprone.annotations.concurrent.GuardedBy`.

Hi, @leventov. I found the Error Prone's [doc](https://github.com/google/error-prone/blob/master/docs/bugpattern/GuardedBy.md#guardedby), from which we don't know why it's recommended to use `com.google.errorprone.annotations.concurrent.GuardedBy`, but Error Prone does recognize those versions of `GuardedBy`.

**Comment by leventov** [comment]
@asdf2014 right. Then this is a low priority issue. However, it would still be nice to have uniformity in the codebase.

**Comment by asdf2014** [comment]
@leventov Yep, it makes sense to me.
