### ISSUE TITLE
Broker process gets killed by kernel due to OOM

### ISSUE THREAD

**Issue by coolboi567** [apache/incubator-druid#7080]
This issue is still present. No errors or exceptions can be seen in the broker log.
Broker process gets killed by kernel due to OOM.
$ `dmesg` returns the following :
```
[863081.188433] [29541]  1004 29541 13691125  7552481 61505536        0             0 java
[863081.188441] Out of memory: Kill process 29541 (java) score 980 or sacrifice child
[863081.196640] Killed process 29541 (java) total-vm:54764500kB, anon-rss:30209924kB, file-rss:0kB, shmem-rss:0kB
[863082.678027] oom_reaper: reaped process 29541 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by Dylan1312** [comment]
Can you share your Broker runtime.properties and jvm config please?

**Comment by coolboi567** [comment]
System configuration is 8 vCPUs and 30GB memory.

**jvm.config**
```
-server
-Xms24g
-Xmx24g
-XX:MaxDirectMemorySize=28g
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
-Djava.io.tmpdir=/var/tmp
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
```

**Comment by Dylan1312** [comment]
The above gives the JVM 24GB of heap but also allows the process to acquire up to 28gb of memory for offheap structures like direct bytebuffers, exceeding the system;s total memory. You may want to look at the example configuration  https://github.com/apache/incubator-druid/blob/master/examples/conf/druid/broker/runtime.properties

**Comment by coolboi567** [comment]
@Dylan1312 For now, introducing one high configuration instance of broker has resolved the issue.
I think I will choose to replace the low configuration instance with a high configuration one in the later future since the work division between two brokers is equal and not well balanced.

And, any suggestion on what to tune in the `runtime.properties`?
