### ISSUE TITLE
What is the Escalator function?

### ISSUE THREAD

**Issue by pbalaguer19** [apache/incubator-druid#7081]
It is the first time using Druid and I am reading the documentation in order to understand how it works.

I have a doubt about Basic Security section: what is the Escalator function? It is required to be defined? Is the configuration from [Basic Security guide](http://druid.io/docs/latest/development/extensions-core/druid-basic-security.html) is enough? Do I have to define the `createEscalatedClient` methods and so on, as [Authentication and Autorization section](http://druid.io/docs/latest/design/auth.html) describes?

I am a little lost. Can someone explain it better please?

**Comment by jon-wei** [comment]
Hi @pbalaguer19, 

The Escalator controls what authentication scheme will be used by Druid's internal clients when communicating with other Druid processes, it must be defined.

If you're using the Basic Security extension, you can base your configurations off the info in the first link you provided, no code needs to be written.

The info in the second link you provided is targeted at extension developers who are adding their own authentication/authorization implementations.

**Comment by pbalaguer19** [comment]
Thank you so much!
