### ISSUE TITLE
[PROPOSAL] Adding offset to sql

### ISSUE THREAD

**Issue by bputt** [apache/incubator-druid#7090]
# Motivation

We're looking to utilize druid to provide raw records and aggregations. While the aggregation portion is working well, we need the offset to be available within SQL in order to continue offering pagination for the raw records.

# Proposed changes

SQL adding support for OFFSET

Maybe it makes sense to offer OFFSET when pulling back raw data and not offering that as a feature for aggregated data? I assume it makes the implementation that much harder if you have to support aggregations.

**Comment by gianm** [comment]
Hi @bputt, to be a complete proposal this should include details of how you propose implementing the feature. Otherwise this should be a feature request issue instead.

**Comment by bputt** [comment]
I guess this is a new issue, #7095
