### ISSUE TITLE
[PROPOSAL] Sorting by non timestamp fields for non-aggregation queries

### ISSUE THREAD

**Issue by bputt** [apache/incubator-druid#7091]
# Motivation

We're looking to utilize druid to provide raw records and aggregations. While the aggregation portion is working well, we need the offset to be available within SQL in order to continue offering sorting by fields that are not specifically timestamps.

# Proposed changes

Including support for ORDER BY (non-timestamp field) when doing basic select statements (that aren't aggregations)

**Comment by gianm** [comment]
Hi @bputt, to be a complete proposal this should include details of how you propose implementing the feature. Otherwise this should be a feature request issue instead.

**Comment by bputt** [comment]
I guess that means a regular issue, so #7094
