### ISSUE TITLE
Add support for querying by long timestamp for sql

### ISSUE THREAD

**Issue by bputt** [apache/incubator-druid#7097]
When querying via SQL, our timestamps are stored as longs, but when we add ```WHERE timestampfield = LONG``` the query fails, but as soon as we modify it to be ```WHERE timestampfield = 'YYY-MM-DD HH:mm:ss.zzz``` it works

It'd be nice if it supported longs

**Comment by jihoonson** [comment]
Hi @bputt, I think the current way is the SQL standard. You can [cast](http://druid.io/docs/latest/querying/sql#other-functions) timestampfield as long if you want to filter by a long value.
