### ISSUE TITLE
Modify FilteredRequestLogger to suppress segmentMetadata queries

### ISSUE THREAD

**Issue by Caroline1000** [apache/incubator-druid#7115]
# Description

Create the option to keep request logging enabled but not print the actual segmentMetadata queries in the broker log.

# Motivation

segmentMetadata queries can take up a huge part of broker logs in a cluster with lots of segments, especially during frequent cluster restarts. This can overwhelm information that's needed to troubleshoot other issues, and can push out relevant information if logs are rolled over quickly.

**Comment by drcrallen** [comment]
Related: https://github.com/apache/incubator-druid/issues/5320

**Comment by leventov** [comment]
I believe this is addressed by #7562
