### ISSUE TITLE
HTTP Firehose with Basic Authentication

### ISSUE THREAD

**Issue by capistrant** [apache/incubator-druid#7122]
# Description

I'd like to propose adding the ability to use URIs that require a basic authentication header to the existing HTTP Firehose. I envision a Firehose that works for both depending on what is provided in the ingestion spec. 

One potential implementation: If the client adds credentials to the ingestion spec (new json key:value pairs in the ioConfig), then they will be supplied as a header to the specified URIs. If no credentials are in the ingestion spec, then no authentication header is added to the request.

# Motivation

My org would like to leverage the HTTP Firehose to ingest select files with Native ingestion rather than using hadoop batch ingestion and the overhead that comes with that. However, the API to access the files over the network requires basic authentication.

We implemented the change ourselves to an older version of Druid (0.11.0) and it works great with no breaking changes to firehose users connecting to an insecure endpoint. We plan on upgrading our clusters soon and will need this functionality before the upgrade. 

I'm willing to take a crack at it as well, if there is some consensus around it being a feature that committers would accept.

**Comment by jihoonson** [comment]
Great! This feature looks useful to me.

**Comment by jihoonson** [comment]
Fixed in #7145.
