### ISSUE TITLE
Reported classloader issues with hdfs-storage-module

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#713]
The loading and usage of the hdfs-storage-module is supposed to be able to work without actually having hadoop jars on Druid's main classpath. (Since extensions are supposed to be able to use their own ClassLoaders.) But this has been reported to not actually work, leading to class-not-found exceptions.

The workaround for now is to include the hadoop jars you want to run with on Druid's main classpath.

**Comment by vogievetsky** [comment]
Did #1454 fix this? Is this still a showstopper? I was just running Druid with HDP 3.1.0 and it seemed ok.

**Comment by gianm** [comment]
This isn't isn't relevant any longer. Hadoop jars aren't needed on Druid's main classpath.
