### ISSUE TITLE
The term for "maintenance" nodes

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7148]
The "maintenance" mode of historical nodes introduced in #6349 confused me recently so raise this issue with `0.14.0` milestone while it's not too late to change the name relatively easily.

I like @glasser's suggestion "draining", I think it reflects the essence of the mode more clearly than "maintenance".

**Comment by leventov** [comment]
FYI @egor-ryashin @jon-wei @clintropolis

**Comment by gianm** [comment]
It sounds like the feature in #6349 is a way of telling the coordinator to move all data off a particular historical. "Decommission" seems to be the most popular word to use to describe that kind of operation in other systems I checked just now. It also strikes me as pretty intuitive. So I'd suggest that.

- HDFS calls it decommissioning: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/HdfsDataNodeAdminGuide.html
- So does YARN: https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/GracefulDecommission.html
- So does Cassandra: http://cassandra.apache.org/doc/4.0/operating/topo_changes.html#removing-nodes
- So does Kafka (if only to mention that it doesn't have a simple tool to do it): https://kafka.apache.org/documentation/#basic_ops_decommissioning_brokers
- Mesos doesn't; it uses terms like "maintenance" and "draining" (possibly the inspiration for the terminology in #6349): http://mesos.apache.org/documentation/latest/maintenance/

**Comment by leventov** [comment]
@gianm thanks for the analysis and providing the data.

Now I'm in favor of "decommission".

**Comment by jon-wei** [comment]
"Decommission" sounds good to me.

**Comment by clintropolis** [comment]
I don't have strong opinions here, "draining" and "decommission" both do sound a bit more intuitive than "maintenance",  "draining" seems more popular with orchestration things like mesos, kubernetes, docker swarm, etc.

**Comment by clintropolis** [comment]
Actually.. :+1: for "decommission" because it seems more appropriate terminology for this application level function, and we are closer to kafka/cassandra/hadoop than mesos/kubernetes/etc so it seems more consistent.

**Comment by glasser** [comment]
I'd be interested in making/using a layer on top of this feature where you send an API request to the historical itself and it adds itself to the coordinator's decommission list. (See @clintropolis at https://github.com/apache/incubator-druid/pull/6349#issuecomment-461968344.)

I think "decommission" goes well with this potential feature, especially since one could include an "exit when empty" flag on the API. A decommissioning that ends with exiting feels fitting.

**Comment by gianm** [comment]
It sounds like people generally like "decommission". Since this is a 0.14.0 blocker we'd want to make this change soon (so we can keep progressing towards a release candidate). Is anyone interested in implementing this change?

**Comment by clintropolis** [comment]
I can pick this up this afternoon if no one else claims it.
