### ISSUE TITLE
hadoop overwriteFiles parameter doesn't work

### ISSUE THREAD

**Issue by chenhaiyan** [apache/incubator-druid#7150]
I load hdfs json file to Druid,the load json is below
`{
  "type" : "index_hadoop",
  "spec" : {
    "dataSchema" : {
      "dataSource" : "up_stu_tag",
      "parser" : {
        "type" : "hadoopyString",
        "parseSpec" : {
          "format" : "json",
          "dimensionsSpec" : {
            "dimensions" : [
              "row_key","les_study_state",
              "pay_latest_create_date",
              "pay_latest_deal_date",
              "pay_latest_hours",
              "pay_latest_bu",
              "pay_way_prefer","pay_way_prefer_id",
              "is_renew","is_paid","pay_freq",
              "create_td","pay_cum_order_count","pay_first_deal_time",
              "subject_edition_id","stu_prov_code","stu_city_code","stu_area_code",
              "stu_city_level","stu_gender_code","stu_fill_student_files","is_bound_1v1",
              "is_bound_kid","is_bound_pl","is_subscribe_1v1",
              "is_subscribe_kid","is_subscribe_pl","first_les_time",
              "pay_first_money","pay_first_hours","pay_cum_money",
              "pay_cum_hours","les_regu_sub_num","les_deduct_hours"
             ]
          },
          "timestampSpec": {
           "column": "timestamp",
           "format": "auto",
           "missingValue" : "2019-02-24"
          }
        }
      },
      "metricsSpec" : [],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "day",
        "queryGranularity" : "none",
        "intervals" : ["2019-02-24/2019-02-25"],
        "rollup" : false
      }
    },
    "ioConfig" : {
      "type" : "hadoop",
      "inputSpec" : {
        "type" : "static",
        "paths" : "hdfs://10.80.230.158:9000/druid/hbase_data/up_stu_tag_test/"
      }
    },
    "tuningConfig" : {
      "type" : "hadoop",
      "partitionsSpec" : {
        "type" : "hashed",
        "targetPartitionSize" : 4000000
      },
      "maxParseExceptions" : 1000,
      "targetPartitionSize" : 4000000,
      **"overwriteFiles" : false,**
      "forceExtendableShardSpecs" : true,
      "logParseExceptions":true,
      "jobProperties" : {
        "mapreduce.job.maps" : 10,
        "mapreduce.job.reduces" : 2,
        "mapreduce.map.cpu.vcores" : 4,
        "mapreduce.reduce.cpu.vcores":2,
        "mapreduce.map.memory.mb" : 5120,
        "mapreduce.reduce.memory.mb" : 1024
      }
    }
  }
}
`
no matter overwriteFiles is false or true, when I load another hdfs file to the same interval,it will always overwrite the older files. How can I append data like the native batch parameter when I load hdfs file to druid ? Is this a bug or something else that I don't know?

**Comment by jihoonson** [comment]
Hi @chenhaiyan, this is not a bug since Hadoop index task currently supports only overwriting. You may want to consider `multi` input spec. Please check http://druid.io/docs/latest/ingestion/update-existing-data.html for details.
