### ISSUE TITLE
web console segments view unable to search by exact datasource

### ISSUE THREAD

**Issue by clintropolis** [apache/incubator-druid#7155]
# Affected Version

`0.14.0-incubating` and newer.

# Description

The 'segments' view of the new web console is unable to filter to a specific datasource, which is a problem for clusters which have datasource names that are substrings of other datasource names. For example:

<img width="1671" alt="screen shot 2019-02-27 at 4 50 51 pm" src="https://user-images.githubusercontent.com/1577461/53533768-f3c5ea80-3ab0-11e9-91d8-8e14f3bd8fe7.png">

If we click the 'segments' link we are taken to the 'segments' view, which has segments from other datasources:

<img width="1659" alt="screen shot 2019-02-27 at 4 50 24 pm" src="https://user-images.githubusercontent.com/1577461/53533830-35569580-3ab1-11e9-86c4-a88874efae82.png">

This is due to the system tables query it is using issuing a substring search instead of an exact match:
```
"SELECT "segment_id", "datasource", "start", "end", "size", "version", "partition_num", "num_replicas", "num_rows", "is_published", "is_available", "is_realtime", "payload"↵FROM sys.segments↵WHERE "datasource" LIKE '%twitter%'↵ORDER BY "start" DESC↵LIMIT 50
```

I'm not certain the best way to fix from a UI sense, as the substring search probably makes sense as a search box input, but it seems necessary to be able to exactly filter by datasource as well.

**Comment by vogievetsky** [comment]
I was thinking that we would make `twitter` be a prefix search and `"twitter"` be a an exact match search. Thoughts?
