### ISSUE TITLE
Druid SQL filtered aggregate fails with WHERE clause containing three or more conditions 

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-druid#7207]
### Affected Version

0.12.2.1.

### Description

When running a query containing a filtered aggregate where the `WHERE` clause contains three (or more) conditions, i.e., 
```
SELECT SUM(x) FILTER (WHERE a AND b AND c)
```

it fails with the following (sanitized) error, 
```
Unknown exception (java.lang.RuntimeException): Error while applying rule DruidQueryRule:SELECT_PROJECT, args [rel#19421869:LogicalProject.NONE.[](input=rel#19421867:Subset#6.NONE.[],__timestamp=...]
```

Note if you remove any one of the conditions in the `WHERE` clause the query successfully executes.

**Comment by xueyumusic** [comment]
The current master codes seems to could work for this case and doesn't have this problem, maybe specific version bug...

**Comment by gianm** [comment]
I can't reproduce this on the latest code either. @john-bodley could you please check if your example works in 0.13.0?

**Comment by john-bodley** [comment]
@gianm I'll retest when we upgrade to 0.13.0.

**Comment by john-bodley** [comment]
Confirmed that this works correctly on `0.13.0`.
