### ISSUE TITLE
summation calculation, the 2 decimal point becomes 6 or more

### ISSUE THREAD

**Issue by xqwbx163** [apache/incubator-druid#7240]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

Druid v0.13

### Description

Use KIS load  streaming data into druid, Some columns are decimal(16,2)  in mysql database,the value such as: 3.24
push mysql value into druid, I define the data type as float on druid, and when querying each data through dsql, the display is 2 digits.
![image](https://user-images.githubusercontent.com/20455410/54181228-cded0c80-44d8-11e9-954b-a1a09eaf1fa7.png)

 However, sum(total)   summation calculation, you will find that the decimal point becomes 6 or more。
the sum total  is  different from the calculations in relational databases(mysql)

![image](https://user-images.githubusercontent.com/20455410/54181588-fe817600-44d9-11e9-8c46-b728de866321.png)

could you help me to solve it ?

**Comment by gianm** [comment]
How different is it? Floating-point types behave a bit differently from decimal types, and Druid only supports floating point right now. I'm wondering if the behavior you're seeing is expected for floating-point calculations.

**Comment by xqwbx163** [comment]
that is mysql sum result :
![image](https://user-images.githubusercontent.com/20455410/54205129-aade4f00-4510-11e9-8d33-f5ea7af0e5f2.png)
orderday:2019-02-01 the sum total is 17058984.3
But druid sum is 17058984.2967 ,
This value will be a little less every day, 
And as the number of days increases, the difference will big more.

**Comment by shuigen** [comment]
becase sum by float,the sum of float data is precise calculation。
