### ISSUE TITLE
Duplicate data ingestion in Kinesis indexing service

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#7286]
### Affected Version

0.14.0-rc1

### Description

I created two dataSources for the same Kinesis stream, but it returned different results for the same query. Duplicate raw events was found in one dataSource (it was about 110 events). I'm suspecting [this line](https://github.com/apache/incubator-druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2347). Maybe `isExclusive` should be set to true. But, I'm not sure why it happened for only one dataSource.

**Comment by gianm** [comment]
It's possible the other datasource had duplicates at a different point. I think we were just looking at one second's worth of data when debugging this.

**Comment by jihoonson** [comment]
![Screen Shot 2019-03-18 at 1 42 50 PM](https://user-images.githubusercontent.com/2322288/54562226-ccfa2600-4983-11e9-98d2-6f1985584578.png)

Hmm, yeah maybe. Looks that sometimes `flow0` produces more rows than `flow0-b` too.
