### ISSUE TITLE
Prohibit a Map usage pattern replaceable with putIfAbsent()

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7316]
This pattern is specifically described in this tutorial: https://github.com/apache/incubator-druid/blob/a4270da5f3de25f1182cfdf2ac0d9de7781312cf/ci/README_TeamCity.md#creating-a-custom-inspection-from-a-structural-search-pattern

A part of #4034.

**Comment by sashidhar** [comment]
@leventov, Raised https://github.com/apache/incubator-druid/pull/7764. Please review the pull request.
