### ISSUE TITLE
How to understand the broker node to get the segments from the MiddleManager node？

### ISSUE THREAD

**Issue by w3z4y4** [apache/incubator-druid#7342]
Guys，
I am a software engineer at a Chinese bank. I am sorry for my poor English.😄
Our team going to build a druid production cluster recently. 
Broker could get data from MiddleManager.
MiddleManager could generate segments and writes to deep storage.
What is the state of segment ,that is queried through the MiddleManager node?
How to choose the SSD size of the servers which run the MiddleManager process?

**Comment by justinborromeo** [comment]
For the latter question, see the [clustering docs](http://druid.io/docs/latest/tutorials/cluster.html).
