### ISSUE TITLE
Exception with auto compaction

### ISSUE THREAD

**Issue by RestfulBlue** [apache/incubator-druid#7356]
Hi , i am trying to use druid 0.14.0(rc2), but it looks like there is a bug with auto compaction.

I submit compaction config to coordinator: 
```json
{
  "dataSource" : "druid-metrics",
}
```
but there are exceptions in coordinator logs : 
org.apache.druid.java.util.common.ISE : Failed to post task at HttpIndexingServiceClient:135
Looks like there is problem with that : 
1) In DataSourceCompactionConfig, if targetCompactionSizeBytes is null then it get replaced with default value
2) In ClientCompactQueryTuningConfig maxRowsPerSegment is replaced with default value
According to docs : 
```
targetCompactionSizeBytes | Target segment size after comapction. Cannot be used with targetPartitionSize, maxTotalRows, and numShards in tuningConfig.
```
And as a result every submit of compaction is failing because this condition always failing. Am i doing something wrong? Changing tuningConfig will not help, because null vals will be replaced anyway 

Also, throwing exception in HttpIndexingServiceClient:135 does not show error message and only print .toString() method(which is not overriden in CompactionTask) , not logging overlord error at all. understand what is going on is hard (that was a debugger in my case)

**Comment by jihoonson** [comment]
Thanks for raising this issue.. It looks real. I'll fix it soon.
