### ISSUE TITLE
Change SQL endpoint response code from 405 to 404 on non-broker processes

### ISSUE THREAD

**Issue by justinborromeo** [apache/incubator-druid#7369]
### Description

Currently, when the `/druid/v2/sql` endpoint is hit on a non-broker process, a 405 Method Not Allowed status code is returned.  I feel as if a 405 is misleading since it implies that another method will work.  Perhaps a better option would be a 404 Resource Not Found as it shows that the resource doesn't exist on that process.

### Motivation

This change is motivated by [this question](https://groups.google.com/d/msg/druid-user/Trlp6I-1m8w/CSVddZCRBQAJ) on the Druid user group.  For beginners especially, the 405 is confusing if they copy the exact cURL command from the docs and send it to the wrong process.

Changing the response code would likely cause compatibility issues with existing clients.  Due to this messiness, I'm opening this issue as a discussion rather than a proposal.  Do people think this change would have value and would have enough value to justify the compatibility headache?  If not, maybe it's a better idea to include a message in the body of the response?

**Comment by egor-ryashin** [comment]
I'm confused, as 405 stands for another message 

> The HyperText Transfer Protocol (HTTP) 405 Method Not Allowed response status code indicates that the request method is known by the server but is not supported by the target resource.

**Comment by justinborromeo** [comment]
@egor-ryashin what do you mean by "another message"?

**Comment by egor-ryashin** [comment]
I mean `Method Not Allowed` but in your case it's `Method Not Found`

**Comment by justinborromeo** [comment]
Sorry about that, mixed up the two error messages - it's fixed in the description.
