### ISSUE TITLE
how to use  MaterializedView ，I didn't find the relevant submit task command.

### ISSUE THREAD

**Issue by love1693294577** [apache/incubator-druid#7403]
My is curl -XPOST -H'Content-Type: application/json' -d @view.json http://10.244.68.107:8090/druid/indexer/v1/MaterializedViewSupervisor This command task does not respond? 

Is my task command wrong? I didn't find the relevant submit task command.

**Comment by mihai-cazacu-adswizz** [comment]
Hi,

You have to run something like this:

```
curl -X 'POST' -H 'Content-Type:application/json' -d @view.json "http://10.244.68.107:8090/druid/indexer/v1/supervisor"
```

Have a nice day!

**Comment by love1693294577** [comment]
> Hi,
> 
> You have to run something like this:
> 
> ```
> curl -X 'POST' -H 'Content-Type:application/json' -d @view.json "http://10.244.68.107:8090/druid/indexer/v1/supervisor"
> ```
> Have a nice day!


yes 

[groupBy_[xxx_view2]_ad3ca90c-30b0-4be2-9169-739114c583b7]]
org.apache.druid.query.materializedview.DataSourceOptimizer - +++++++derivatives+++++++[]

this is my Configuration
'http://xx.xx.xx.xx:8082/druid/v2/?pretty=' 
{
"type":"derivativeDataSource",
"baseDataSource":"xx_view2",
"dataSource":"xx_view_11",
"dimensionsSpec":{
"dimensions":[
"xx",
"xx"
]
},
"metricsSpec" : [
{ "name": "xx",
"type": "doubleSum",
"fieldName":"xx"}
],
"tuningConfig": {
"type":"hadoop",
"jobProperties" : {
"mapreduce.job.user.classpath.first":"true",
"mapreduce.reduce.speculative" : "false",
"mapreduce.map.speculative": "false"
}
}
}
submit task
curl -XPOST -H'Content-Type: application/json' -d @xx.json http://xx.xx.xx.xx:8090/druid/indexer/v1/supervisor

query
'{"queryType":"view","query":{"queryType":"groupBy","dataSource":"xxx_view2","granularity":"all","descending":"true","limitSpec":{"type":"default","limit":1},"context":{"priority":1,"timeout":10000000,"queryId":"c7156e24-ad74-4a4b-ae24-2df660cd8287","groupByStrategy":"v2"},"dimensions":["xx"],"aggregations":[{"type":"longSum","name":"xx","fieldName":"xx"}],"intervals":["2017-04-26T00:00:00.000+08:00/2017-04-28T00:00:00.000+08:00"]}

I can't get an optimized materialized view

This is my log
2019-04-11T11:54:21,057 INFO [qtp1556201248-110[topN_[xx_view2]_c7156e24-ad74-4a4b-ae24-2df660cd8287]] org.apache.druid.query.materializedview.DataSourceOptimizer - +++++++derivatives+++++++[]

I am wondering why the derivatives are null, as normal, will get derivatives
