### ISSUE TITLE
"useDefaultValueForNull" needs documentation

### ISSUE THREAD

**Issue by egor-ryashin** [apache/incubator-druid#7404]
see `NullValueHandlingConfig`
Found during investigation of https://github.com/apache/incubator-druid/issues/7108

**Comment by gianm** [comment]
@nishantmonu51 @b-slim are y'all using this functionality in production? (Or is anyone else in the committer ranks?)

**Comment by b-slim** [comment]
@gianm which functionality you are asking about ?
 Considering null as null yes that is what it is set to by default.
 DoubleSketches/quantiles am not aware of any usage or actual testing

**Comment by gianm** [comment]
I'm referring to the behavior you get when setting `druid.generic.useDefaultValueForNull=false`, the sql-compatible null handling feature that was contributed earlier. It isn't described in the docs and I was wondering how battle tested it is. (I don't know of anyone that uses it but I figured maybe some of your users/customers might.)

**Comment by b-slim** [comment]
We have been using this feature since its inception and by using i mean testing internally, benchmarks and as default setting for our users.

**Comment by gianm** [comment]
Cool, @b-slim, that is good to hear, it sounds like it's fairly battle tested in that case.

**Comment by applike-ss** [comment]
i still didn't find the docs for this. Can the issue be re-opened?
