### ISSUE TITLE
Add Druid SQL support to JetBrains DataGrip

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#7405]
### Description

[JetBrains DataGrip](https://www.jetbrains.com/datagrip/) is a cross-database IDE which is meant for the current era of teams using multiple databases. It currently supports [around 20 different database systems](https://www.jetbrains.com/help/datagrip/connecting-to-a-database.html).

JetBrains provides guidelines to database vendors on how to help them onboarding a new DBMS: https://www.jetbrains.com/datagrip/new_dbms/

It would be nice if we can gather the required information and work with JetBrains on onboarding.

### Motivation

With the latest improvements to Druid SQL, including metadata access, it would be a good opportunity to promote Druid and reach a broader audience via an existing database IDE.
Also, the product is just great to use, so I hope using it with Druid.

**Comment by vogievetsky** [comment]
I have had success using Druid from DataGrip via the JDBC connector. Have you tried that?

**Comment by sergei3000** [comment]
+1 for this feature
