### ISSUE TITLE
Unused parameter in ParallelIndexTuningConfig

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7423]
`@JsonProperty("chatHandlerTimeout") @Nullable Duration chatHandlerTimeout` is unused.

FYI @jihoonson

**Comment by jihoonson** [comment]
Hmm, isn't it being used in `ParallelIndexSubTask.run()`?

**Comment by leventov** [comment]
The parameter of `ParallelIndexTuningConfig` class is not used. There is a bug in `ParallelIndexTuningConfig` constructor.

**Comment by jihoonson** [comment]
Thanks. Raised https://github.com/apache/incubator-druid/pull/7479.
