### ISSUE TITLE
errors in coordinator web console in 0.14

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#7471]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.14

### Description
Image of console log:

![image](https://user-images.githubusercontent.com/3190176/56086572-765efb00-5e0e-11e9-886d-80e684b38335.png)

**Comment by vogievetsky** [comment]
The coordinator console had some JS errors for a while? Is this a regression in 0.14?

**Comment by pdeva** [comment]
not sure. i saw them this time so i reported them... 🤷🏻‍♂️

**Comment by vogievetsky** [comment]
It should be noted that the old console is essentially in `Wont fix` state (unless someone wants to contribute), but are working hard to replace it with the new console: https://druid.apache.org/docs/latest/operations/druid-console.html
