### ISSUE TITLE
Conflicting documentation on Metadata storage access

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#7473]
### Affected Version

0.14

### Description
The diagram in the documentation [here](http://druid.io/docs/0.14.0-incubating/design/index.html) suggests the Metadata store is only accessed by the Coordinator/Overlord node:

![image](https://user-images.githubusercontent.com/3190176/56098746-86331980-5eb8-11e9-98e8-ad1ec7c681cd.png)

However the documentation [here](http://druid.io/docs/0.14.0-incubating/dependencies/metadata-storage.html) (at the bottom) suggests its accessed by all the realtime processes too. By that I assume MiddleManager/Peon nodes need to have firewall access to metadata storage too.

Which one is correct?

**Comment by gianm** [comment]
Realtime nodes did use metadata storage directly, but they are gone now, since #7915. Tasks do not, so I believe the diagram is correct.
