### ISSUE TITLE
Can Druid use existed datasource and segments

### ISSUE THREAD

**Issue by hueiyuanSu** [apache/incubator-druid#7474]
Hello Everyone.

I have a question when I use druid.
If I have the datasource and segment created by the previous druid, now I have created a new druid and used the original datasource and segment. 
Is this done in the current druid?

Thanks.
Max

**Comment by vogievetsky** [comment]
For the most part yes. Going up one version (say from 0.12 to 0.13) is guaranteed to be safe always.
As it happens it is safe to go up quite a few versions recently. More details can be found in the release notes. What is the version of your old Druid?
