### ISSUE TITLE
Add option to specify cert / key location for kafka

### ISSUE THREAD

**Issue by bputt** [apache/incubator-druid#7483]
### Description

Currently when setting up the kafka indexing service, we're only able to provide the following and would be nice if we can also specify the certificate/key

```
ioConfig: {
    consumerProperties: {
        "ssl.truststore.password": "",
        "ssl.keystore.password": "",
        "ssl.key.password": ""
    }
}
```

### Motivation

The documentation ins't exactly clear how to use kafka indexing service with tls enabled kafka brokers. It would be nice if there was a way to specify the cert & key or if it's already possible, just updating documentation.

**Comment by adilev26** [comment]
any news about that ?

**Comment by Samlinxia** [comment]
@bputt , is there an instruction on how to setup the key/certificate of the kafka indexing service to be able to consume from Kafka via TLS?

**Comment by adilev26** [comment]
hi @Samlinxia , technically you can put any property of Kafka inside that block of config and it will pass on to the Kafka consumer as is.
I just put the following and it worked:
      "security.protocol": "SSL",
      "ssl.truststore.location": "{location of my .jks file}"
