### ISSUE TITLE
0.14 incubating New router unified-console UI shows 0 historical nodes when a cluster has been installed and historicals has no data yet

### ISSUE THREAD

**Issue by adocortes** [apache/incubator-druid#7498]
0.14 incubating New router unified-console UI shows 0 historical nodes when a cluster has been installed and historicals has no data yet. Historicals are running and the list of historicals can be seen in the legacy console but the new console shows 0 historicals in Data servers, and empty list of data servers.  It shows the number of middlemanagers correctly.

Once some data is loaded, the new unified-console shows the number of nodes in the cluster. 

It would show the number of running historical nodes.

/unified-console.html#servers

**Comment by jihoonson** [comment]
Related to https://github.com/apache/incubator-druid/issues/7005.

**Comment by vogievetsky** [comment]
Will be adding a temporary fallback to to the API call until #7005 is resolved. @shuqi7

**Comment by vogievetsky** [comment]
@jihoonson I noticed you added the 0.15.0 tag before my comment. Were you planning on fixing #7005 for 0.15.0 (if so it is not currently tagged), or were you thinking of my client side workaround?

**Comment by jihoonson** [comment]
I added the milestone before I noticed #7005. Now I think this is a sort of bug, but the real fix might not be simple as I thought first. Client-side workaround would be good for a short term solution though.
I think it would be good if we can ship your client-side workaround in 0.15.0. Is it feasible?

**Comment by vogievetsky** [comment]
Client-side workaround coming in 0.15.0 :-)
