### ISSUE TITLE
Nodes in zookeeper should have a type

### ISSUE THREAD

**Issue by sixtus** [apache/incubator-druid#75]
Currently it's not possible to safely tell nodes apart in zookeeper. Either I have to rely on druid.service to be different for each node type (which is a naming convention) or probe the node via http gets. Both not very nice for client libs.

Proposal:

add {"type": "broker|master" } to the entry stored in zk

**Comment by drcrallen** [comment]
Currently the concept of services is very very loose in druid and not as well defined as it could be. As an alternative to this, I believe we should have features defined by various servers, and announce those features independent of what cli was used to launch the node.
