### ISSUE TITLE
New Router UI: No way to enable/disable datasources. confusing 'drop data' option.

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#7506]
### Affected Version

0.14.0-iap3

### Description

I couldn't see any way to enable/disable datasources in the new UI.

I see an option to 'drop data' for a datasource, but its unclear what it does. 
is it equivalent to:

1. deleting all data and metadata for that datasource, to make it such that no trace of it is left
2. 'disabling' the datasource
3. setting 'dropForever' on the datasource but letting it be 'enabled'

**Comment by gianm** [comment]
It's equivalent to the old 'disable' functionality (mark all segments unused). We're trying to harmonize the language & that is a work in progress.

**Comment by vogievetsky** [comment]
`Drop data` = disable

![image](https://user-images.githubusercontent.com/177816/56393323-f4454c80-61e8-11e9-91db-e9898ed4d30e.png)


If you flick the "show disabled" switch:

![image](https://user-images.githubusercontent.com/177816/56393356-0cb56700-61e9-11e9-887b-ba54f42b277a.png)

You will see:

![image](https://user-images.githubusercontent.com/177816/56393398-235bbe00-61e9-11e9-8bbb-f49774cab982.png)

`Enable` (which is enable) and `Permanently delete` which is issue a kill task.

Any suggestions on labeling / microcopy appreciated

**Comment by vogievetsky** [comment]
I believe that with the changes in #7528 this can be considered closed ( @clintropolis )

![image](https://user-images.githubusercontent.com/177816/58305156-e7011c00-7dab-11e9-9b0f-f2e98bf244bc.png)

**Comment by clintropolis** [comment]
Resolved by #7528
