### ISSUE TITLE
Historical node cannot reconnect to zookeeper

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#751]
Try this:
1. take down your zookeeper cluster completely (that means clear all data from the disk too).
2. bring it back up so its brand new (but with some ips)
3. all other nodes will properly connect to the zookeeper and get discovered, except historical nodes.  
   this can be verified by going to the coordinator web console, where u can see the realtime node present but not historical

**Comment by drcrallen** [comment]
Is this related to https://github.com/druid-io/druid/issues/783 ?

**Comment by vogievetsky** [comment]
Is this still an issue?
