### ISSUE TITLE
druid-kerberos module uses internal Java APIs removed in Java 9 and above

### ISSUE THREAD

**Issue by xvrl** [apache/incubator-druid#7527]
The druid-kerberos module relies on internal JDK classes in `sun.security.krb5` and `sun.security.util` packages, which have been removed in Java 9 and above.

To support compiling with JDK11, we should migrate to supported APIs listed in https://bugs.openjdk.java.net/browse/JDK-8062515

relates to #5589

cc @jon-wei

**Comment by jon-wei** [comment]
@xvrl I should have some time in the later part of this week to look into this

**Comment by jon-wei** [comment]
@xvrl I opened a PR to address this: https://github.com/apache/incubator-druid/pull/7685

**Comment by xvrl** [comment]
@jon-wei great, thanks! I'm not very familiar with that part of the code, so I'll let someone else review this PR, but looking forward to have this merged
