### ISSUE TITLE
[rel#10944:Subset#1.DRUID.[0]] could not be implemented; planner state

### ISSUE THREAD

**Issue by DanoOM** [apache/incubator-druid#7543]
### Affected Version
The Druid version where the problem was encountered.
druid 0.0.14
### Description
Running the following query: 
select messageid from sms_messages_detail order by messageid asc
Gives:
` Error: Error -1 (00000) : Error while executing SQL "select messageid from sms_messages_detail order by messageid asc": Remote driver error: CannotPlanException: Node [rel#10944:Subset#1.DRUID.[0]] could not be implemented; planner state:`

Full stack below

Please include as much detailed information about the problem as possible.
- Cluster size: 10 data nodes, 1 master, 1 query node
- Configurations in use, essentially default accross the board.
- Steps to reproduce the problem

`Error: Error -1 (00000) : Error while executing SQL "select messageid from sms_messages_detail order by messageid asc": Remote driver error: CannotPlanException: Node [rel#10944:Subset#1.DRUID.[0]] could not be implemented; planner state:

Root: rel#10944:Subset#1.DRUID.[0]
Original rel:
LogicalSort(subset=[rel#10941:Subset#2.DRUID.[0]], sort0=[$0], dir0=[ASC]): rowcount = 100.0, cumulative cost = {100.0 rows, 1842.0680743952366 cpu, 0.0 io}, id = 10939
  LogicalProject(subset=[rel#10938:Subset#1.NONE.[]], messageid=[$15]): rowcount = 100.0, cumulative cost = {100.0 rows, 100.0 cpu, 0.0 io}, id = 10937
    LogicalTableScan(subset=[rel#10936:Subset#0.NONE.[]], table=[[druid, sms_messages_detail]]): rowcount = 100.0, cumulative cost = {100.0 rows, 101.0 cpu, 0.0 io}, id = 10926

Sets:
Set#0, type: RecordType(TIMESTAMP(3) __time, VARCHAR accepteddate, VARCHAR accountid, VARCHAR accountname, VARCHAR apiversion, VARCHAR carrierid, VARCHAR carriername, VARCHAR companyid, VARCHAR contentencoding, VARCHAR countrycode, VARCHAR countryname, VARCHAR delivereddate, VARCHAR destinationaddress, VARCHAR internalmessageid, VARCHAR liveoperatorlookup, VARCHAR messageid, VARCHAR messageoriginator, VARCHAR messageoriginatorton, VARCHAR messagestatus, VARCHAR messagetype, VARCHAR mtscore, VARCHAR parentmessageid, VARCHAR phonenumber, VARCHAR productid, VARCHAR productiddescription, VARCHAR productname, VARCHAR productsubtype, VARCHAR programid, VARCHAR remoteipaddress, VARCHAR responsecode, VARCHAR responsecodedescription, VARCHAR sourceaddress, VARCHAR subaccount, VARCHAR updateddate, VARCHAR useragent, VARCHAR userdataheader, VARCHAR userdefined1, VARCHAR userdefined2)
	rel#10936:Subset#0.NONE.[], best=null, importance=0.7290000000000001
		rel#10926:LogicalTableScan.NONE.[](table=[druid, sms_messages_detail]), rowcount=100.0, cumulative cost={inf}
		rel#10945:LogicalSort.NONE.[15](input=rel#10936:Subset#0.NONE.[],sort0=$15,dir0=ASC), rowcount=100.0, cumulative cost={inf}
		rel#10949:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"sms_messages_detail"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"filter":null,"columns":["__time","accepteddate","accountid","accountname","apiversion","carrierid","carriername","companyid","contentencoding","countrycode","countryname","delivereddate","destinationaddress","internalmessageid","liveoperatorlookup","messageid","messageoriginator","messageoriginatorton","messagestatus","messagetype","mtscore","parentmessageid","phonenumber","productid","productiddescription","productname","productsubtype","programid","remoteipaddress","responsecode","responsecodedescription","sourceaddress","subaccount","updateddate","useragent","userdataheader","userdefined1","userdefined2"],"legacy":false,"context":{"sqlQueryId":"5c1cdc19-37dd-4be1-b1c5-ab1fbc2651fa"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, accepteddate:STRING, accountid:STRING, accountname:STRING, apiversion:STRING, carrierid:STRING, carriername:STRING, companyid:STRING, contentencoding:STRING, countrycode:STRING, countryname:STRING, delivereddate:STRING, destinationaddress:STRING, internalmessageid:STRING, liveoperatorlookup:STRING, messageid:STRING, messageoriginator:STRING, messageoriginatorton:STRING, messagestatus:STRING, messagetype:STRING, mtscore:STRING, parentmessageid:STRING, phonenumber:STRING, productid:STRING, productiddescription:STRING, productname:STRING, productsubtype:STRING, programid:STRING, remoteipaddress:STRING, responsecode:STRING, responsecodedescription:STRING, sourceaddress:STRING, subaccount:STRING, updateddate:STRING, useragent:STRING, userdataheader:STRING, userdefined1:STRING, userdefined2:STRING}), rowcount=1.0, cumulative cost={inf}
	rel#10947:Subset#0.NONE.[15], best=null, importance=0.7290000000000001
		rel#10945:LogicalSort.NONE.[15](input=rel#10936:Subset#0.NONE.[],sort0=$15,dir0=ASC), rowcount=100.0, cumulative cost={inf}
	rel#10952:Subset#0.DRUID.[], best=rel#10951, importance=0.36450000000000005
		rel#10951:DruidQueryRel.DRUID.[](query={"queryType":"scan","dataSource":{"type":"table","name":"sms_messages_detail"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"filter":null,"columns":["__time","accepteddate","accountid","accountname","apiversion","carrierid","carriername","companyid","contentencoding","countrycode","countryname","delivereddate","destinationaddress","internalmessageid","liveoperatorlookup","messageid","messageoriginator","messageoriginatorton","messagestatus","messagetype","mtscore","parentmessageid","phonenumber","productid","productiddescription","productname","productsubtype","programid","remoteipaddress","responsecode","responsecodedescription","sourceaddress","subaccount","updateddate","useragent","userdataheader","userdefined1","userdefined2"],"legacy":false,"context":{"sqlQueryId":"5c1cdc19-37dd-4be1-b1c5-ab1fbc2651fa"},"descending":false,"granularity":{"type":"all"}},signature={__time:LONG, accepteddate:STRING, accountid:STRING, accountname:STRING, apiversion:STRING, carrierid:STRING, carriername:STRING, companyid:STRING, contentencoding:STRING, countrycode:STRING, countryname:STRING, delivereddate:STRING, destinationaddress:STRING, internalmessageid:STRING, liveoperatorlookup:STRING, messageid:STRING, messageoriginator:STRING, messageoriginatorton:STRING, messagestatus:STRING, messagetype:STRING, mtscore:STRING, parentmessageid:STRING, phonenumber:STRING, productid:STRING, productiddescription:STRING, productname:STRING, productsubtype:STRING, programid:STRING, remoteipaddress:STRING, responsecode:STRING, responsecodedescription:STRING, sourceaddress:STRING, subaccount:STRING, updateddate:STRING, useragent:STRING, userdataheader:STRING, userdefined1:STRING, userdefined2:STRING}), rowcount=1.0, cumulative cost={1.0 rows, 0.0 cpu, 0.0 io}
Set#1, type: RecordType(VARCHAR messageid)
	rel#10938:Subset#1.NONE.[], best=null, importance=0.81
		rel#10937:LogicalProject.NONE.[](input=rel#10936:Subset#0.NONE.[],messageid=$15), rowcount=100.0, cumulative cost={inf}
		rel#10939:LogicalSort.NONE.[0](input=rel#10938:Subset#1.NONE.[],sort0=$0,dir0=ASC), rowcount=100.0, cumulative cost={inf}
		rel#10948:LogicalProject.NONE.[0](input=rel#10947:Subset#0.NONE.[15],messageid=$15), rowcount=100.0, cumulative cost={inf}
		rel#10950:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"sms_messages_detail"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"filter":null,"columns":["messageid"],"legacy":false,"context":{"sqlQueryId":"5c1cdc19-37dd-4be1-b1c5-ab1fbc2651fa"},"descending":false,"granularity":{"type":"all"}},signature={messageid:STRING}), rowcount=1.0, cumulative cost={inf}
	rel#10943:Subset#1.NONE.[0], best=null, importance=0.9
		rel#10939:LogicalSort.NONE.[0](input=rel#10938:Subset#1.NONE.[],sort0=$0,dir0=ASC), rowcount=100.0, cumulative cost={inf}
		rel#10948:LogicalProject.NONE.[0](input=rel#10947:Subset#0.NONE.[15],messageid=$15), rowcount=100.0, cumulative cost={inf}
	rel#10944:Subset#1.DRUID.[0], best=null, importance=0.45
		rel#10942:AbstractConverter.DRUID.[0](input=rel#10943:Subset#1.NONE.[0],convention=DRUID,sort=[0]), rowcount=100.0, cumulative cost={inf}
	rel#10957:Subset#1.DRUID.[], best=rel#10956, importance=0.45
		rel#10942:AbstractConverter.DRUID.[0](input=rel#10943:Subset#1.NONE.[0],convention=DRUID,sort=[0]), rowcount=100.0, cumulative cost={inf}
		rel#10956:DruidQueryRel.DRUID.[](query={"queryType":"scan","dataSource":{"type":"table","name":"sms_messages_detail"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"filter":null,"columns":["messageid"],"legacy":false,"context":{"sqlQueryId":"5c1cdc19-37dd-4be1-b1c5-ab1fbc2651fa"},"descending":false,"granularity":{"type":"all"}},signature={messageid:STRING}), rowcount=1.0, cumulative cost={1.001 rows, 0.0 cpu, 0.0 io}

SQLState:  00000
ErrorCode: -1`

**Comment by gianm** [comment]
Hey @DanoOM,

This is happening because currently, Druid does not support non-aggregation queries that sort by anything other than `__time`.
