### ISSUE TITLE
Druid Web console button sometime not available

### ISSUE THREAD

**Issue by hueiyuan** [apache/incubator-druid#7548]
Hello everyone.

I have built druid 0.14.
Then, When I use druid console(port 8888), some button can not be use.
For example, I want to disable datasource. I should  click "drop data" in datasource page, right?
But.. it always not be disable and running there.

Have someone can help or tell me solution.

Thanks,
Max

**Comment by vogievetsky** [comment]
Hi Max,

Could you post a screenshot please?

**Comment by hueiyuan** [comment]
Hi, vogievetsky

the screenshot is following:
<img width="1428" alt="螢幕快照 2019-04-26 下午2 38 33" src="https://user-images.githubusercontent.com/49678319/56788135-30079400-6831-11e9-8e71-52672c116ce2.png">

Thanks.
Max

**Comment by vogievetsky** [comment]
We have reworked that button and added more actions to each data source as part of: https://github.com/apache/incubator-druid/pull/7528

![image](https://user-images.githubusercontent.com/177816/57235610-1f48e200-6fd8-11e9-8671-e26023d30519.png)

Hopefully that change will address this issue as it make the Actions column much narrower.

**Comment by vogievetsky** [comment]
@clintropolis I believe this can be closed now (also tag plz!)

**Comment by clintropolis** [comment]
Closed by #7528
