### ISSUE TITLE
Druid Console 0.14.0 scroll bar not shown in sql pane

### ISSUE THREAD

**Issue by DanoOM** [apache/incubator-druid#7559]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

0.0.14

### Description
The SQL editor/pane allows you to select number of rows to show, however, when incresing the rows count, ..it appears to 'show' them, but they are not visible, as you cannot scroll down to the rows.

**Comment by vogievetsky** [comment]
I can confirm that this is an issue, should be tagged as Web console / Bug
