### ISSUE TITLE
SQL Editor and queryContext?

### ISSUE THREAD

**Issue by DanoOM** [apache/incubator-druid#7560]
Is there anyway to set queryContext parameters when using the sql editor pane?
### Affected Version

0.0.14

### Description
I would like to run a query:
`select count(DISTINCT id) from messgaes;`
but would like to set the flag: 
`useApproximateCountDistinct=false`

**Comment by vogievetsky** [comment]
There is no way to do this right now. This should be tagged as a Web console / Feature request
