### ISSUE TITLE
DISTINCT count and useApproximateCountDistinct=false not working as expected?

### ISSUE THREAD

**Issue by DanoOM** [apache/incubator-druid#7561]
I am running 0.0.14, and I am using the avatica driver, I'm guessing that maybe I am not in fact setting the SQLContext properly? I assumed it would be a connectionString parameter?

My Connection String:
jdbc:avatica:remote:url=http://uswest2-dev-querynode-001.aws-dev:8082/druid/v2/sql/avatica/?useApproximateCountDistinct=false

Running the first query multiple times yields different unique counts each time, so I'm sure it still using HLL.

My Queries:
select count(*) as total, count(DISTINCT messageid) as unique_messageIds from
sms_messages_detail
where __time >= TIMESTAMP '2018-12-01 00:00:00' and __time < TIMESTAMP '2018-12-02 00:00:00'
RESULT:
total	        unique_messageIds
22220779	20523099

select messageid from sms_messages_detail 
where __time >= TIMESTAMP '2018-12-01 00:00:00' and __time < TIMESTAMP '2018-12-02 00:00:00'
group by messageid
having count(*) > 1
RESULT:
NO ROWS RETURNED

**Comment by gianm** [comment]
It should be in the JDBC connection properties, which are separate from the URL. There's an example on http://druid.io/docs/latest/querying/sql.
