### ISSUE TITLE
Local variable names shouldn't start with capital

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7609]
Should be possible to catch violations with a [Structural Search pattern](https://github.com/apache/incubator-druid/blob/master/dev/teamcity.md#creating-a-custom-inspection-from-a-structural-search-pattern).

**Comment by sashidhar** [comment]
@leventov, I would like to work on this. Let me know how to begin with as I'm new to making contributions. Please share any document for beginner contributors to Druid. Thanks in advance.

**Comment by leventov** [comment]
Hi @sashidhar, welcome to the community!

You can add [LocalVariableName](http://checkstyle.sourceforge.net/config_naming.html#LocalVariableName) and [LocalFinalVariableName](http://checkstyle.sourceforge.net/config_naming.html#LocalFinalVariableName) patterns to this file: https://github.com/apache/incubator-druid/blob/master/codestyle/checkstyle.xml. Then trying to `mvn install -DskipTests` from the root of the project, Checkstyle will show you all violations.

**Comment by lml2468** [comment]
@sashidhar , have you started working on this yet?

**Comment by sashidhar** [comment]
Yes, I've started working on this. I'll update once I've made code changes.

**Comment by sashidhar** [comment]
@leventov 

1. This is the match pattern I'm currently using for Local Variable names '^[a-z_](_?[a-zA-Z0-9_]+)*$' considering variables starting with and ending with underscores as well. Let me know if this is fine.

2. There are several occurrences of variables which are not constants (i.e non static fields) which have variables all capitalized for instance,    Pattern DOT_OR_WHITESPACE = Pattern.compile("[\\s]+|[.]+");    etc. I'm changing these to lower case. Is that fine ?

**Comment by sashidhar** [comment]
@leventov,

3. For local final variables example here http://checkstyle.sourceforge.net/config_naming.html#LocalFinalVariableName suggests names that are only upper case letters and digits `"^[A-Z][A-Z0-9]*$"`.  

As per this pattern, following variable should be changed  from
final ObjectMapper mapper = new ObjectMapper(); to
final ObjectMapper MAPPER = new ObjectMapper();

I'm not sure if this makes sense changing non static variable names to all caps !!

**Comment by gianm** [comment]
> There are several occurrences of variables which are not constants (i.e non static fields) which have variables all capitalized for instance, Pattern DOT_OR_WHITESPACE = Pattern.compile("[\s]+|[.]+"); etc. I'm changing these to lower case. Is that fine ?

For some of these, it might be an indication that the variable was intended to be a static constant, but the original developer just forgot to include the static keyword. So I would approach these with an open mind to fixing bugs like that too, not necessarily just fixing the names to match the current state.

> For local final variables example here http://checkstyle.sourceforge.net/config_naming.html#LocalFinalVariableName suggests names that are only upper case letters and digits "^[A-Z][A-Z0-9]*$".

IMO, this is silly, I don't see a reason to require this pattern. In fact, I'd be more inclined to require the _opposite_ (local final variables should start with lowercase letters).

**Comment by sashidhar** [comment]
How do I create a pull request ? I've made changes in a local branch and unable to commit the local branch to remote. I was thinking to push local branch to remote and then raise a pull request.

**Comment by leventov** [comment]
@sashidhar it looks like there is a collision and @lml2468 has already solved this problem. In general, please consult to Github Help and web search to resolve such questions: https://help.github.com/en/articles/creating-a-pull-request
