### ISSUE TITLE
sql injection violation

### ISSUE THREAD

**Issue by iamxiaojuan** [apache/incubator-druid#7620]
insert into rank_month_trade(data_time,rank_type,rank,group_id,total_value)
		select ?,0,@rank:=@rank + 1 AS rank_no,a.group_id,a.real_value
		from(
		select group_id,sum(total_pay) as real_value
		from daily_group_trade
		where data_time >=? and data_time <?
		group by group_id
		order by real_value desc
		)a,(select @rank:=0) b
		on duplicate key update group_id = values (group_id),total_value = values (total_value);

The sql can lead to SQL injection problems,the complete mistake is
![image](https://user-images.githubusercontent.com/13642031/57423433-9c798e80-7246-11e9-925f-1bce92495e8d.png)

**Comment by vogievetsky** [comment]
I am pretty sure nothing about that error is supported

**Comment by iamxiaojuan** [comment]
> I am pretty sure nothing about that SQL statement is supported

What do you think the reason is for that?
and,thank you for your reply.

**Comment by vogievetsky** [comment]
Druid SQL does not support inserts (or variables). It is a read only query interface. You ingest data in other ways: http://druid.io/docs/latest/ingestion/index.html

**Comment by iamxiaojuan** [comment]
> Druid SQL does not support inserts (or variables). It is a read only query interface. You ingest data in other ways: http://druid.io/docs/latest/ingestion/index.html

thank you very much!

**Comment by gianm** [comment]
You might also be thinking about https://github.com/alibaba/druid, a different project.
