### ISSUE TITLE
Provide segment size property that includes replicated segments

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#7733]
### Description

I'd like to a new property `replicatedSize` to the tier-specific result of `druid/coordinator/v1/datasources?simple` and `/druid/coordinator/v1/datasources/{dataSourceName}` which would provide the segment size that includes replication.
### Motivation
Presently the datasources endpoint provides the unreplicated segment size of each tier within a datasource. A replicated segment size property for each tier would be useful for services to monitor total tier usage periodically.

**Comment by gianm** [comment]
It sounds useful to me. If it's not computationally or memory intensive to compute, I don't see why not.
