### ISSUE TITLE
How to get the SQL or the entire query by queryId?

### ISSUE THREAD

**Issue by aoeiuvb** [apache/incubator-druid#7771]
No such API is found in the documentation

**Comment by gianm** [comment]
If you want to see the query that was issued, turn on request logging: http://druid.io/docs/latest/configuration/index.html#request-logging

**Comment by aoeiuvb** [comment]
> If you want to see the query that was issued, turn on request logging: http://druid.io/docs/latest/configuration/index.html#request-logging

Thank you very much. I will try this configuration
