### ISSUE TITLE
kafka indexing service should always use earliest offset for newly discovered topic-partitions instead of useEarliestOffset config

### ISSUE THREAD

**Issue by c0de0ff** [apache/incubator-druid#7776]
### Description

Kafka-indexing-service currently uses `useEarliestOffset` config whenever it can't find any data for a topic-partition. This happens when the supervisor is running for the first time or when there is a new partition for this topic in kafka. The config is also used to reset the offsets ( if `resetOffsetAutomatically` is set to true ).

In 2 of the above 3 scenarios, it makes sense to use `useEarliestOffset` config. However, it doesn't seem like indexing service should use this config on newly discovered partitions. If `useEarliestOffset` is set to false then this might result in data loss. In production environment, with large kafka clusters and many long running supervisors, adding new partitions to kafka topics would be a common occurrence and therefore this config must always remain true to avoid any data loss.

A typical use case in large kafka clusters is to start the new supervisor from latest offset and keep consuming without any data loss ( exactly once ). In order to achieve this currently, we have to start supervisor with `useEarliestOffset` set to false and then wait for it to start running and then set the config back to true to avoid data loss in new partitions. User may also want to reset to latest offsets manually using the reset api, in this case also, he need to remember setting the config back to true which can be error prone.

The solution to this might be to not use the config while getting offsets for new partitions ( always use earliest ), however, i am not sure how we can differentiate the 2 events "new partitions added" vs "supervisor first run".

### Motivation

- Currently in order to avoid data loss from new partitions, we must always keep `useEarliestOffset` set to true, which creates the need to manually change the config back and forth in case we want to use the diff option for first-start/reset.

**Comment by gianm** [comment]
This is arguably a bug, so I'll mark it as one. Thanks for the detailed description. I'm not sure of the best way to fix it, either, but it seems like we do need some way to differentiate first-run (or first-run-since-reset) from not-first-run.

**Comment by SEKIRO-J** [comment]
Seems like this feature already exists based on code:
https://github.com/apache/incubator-druid/blob/7f2b6577ef19f18523e8353336ad496e8dc4a270/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2550
And a simple test on Kinesis tells this code works functionally. (always starts from earliest offset for new discovered partitions, otherwise, it depends on the `useEarliestOffset ` config)

Let me know if there is anything I missed.

**Comment by jihoonson** [comment]
Hi @c0de0ff, I found a bug around this issue. Would you tell me what was your Druid version?

**Comment by jihoonson** [comment]
I think the bug is, `partitionIds` [here](https://github.com/apache/incubator-druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L486) is never updated in Kafka. It should work for kinesis as @SEKIRO-J said.

**Comment by jihoonson** [comment]
All releases since 0.14.0 have the same issue.
