### ISSUE TITLE
How can we do health checks on Druid processes?

### ISSUE THREAD

**Issue by OItsMAK** [apache/incubator-druid#7778]
We use Druid and would like a way to know when its processes have started up successfully. 
Something like the `ruok` check on zookeeper (explained [here](https://zookeeper.apache.org/doc/r3.1.2/zookeeperAdmin.html), example [here](https://stackoverflow.com/a/55609944)).

The point of this is problematic starts and/or rolling updates of the Druid Docker containers, where HealthChecks come in handy.

Currently, the methods that come to my mind are simple `min_healthy_time` waits,
Or checking the announcements of Druid nodes in `Zookeeper`, which is a weird method since it includes setting up some sort of monitoring on registered `ZK` nodes, or contacting `ZK` directly.

**Comment by gianm** [comment]
You can call `/status` on each server over HTTP. It is a very basic check but it's a start. For some other ideas try checking out http://druid.io/docs/latest/operations/api-reference.html.

**Comment by OItsMAK** [comment]
Will set it up. thanks.

Btw, What I found to do the job for me is:

* `/status/health` for Coordinator, Overlords, and MiddleManager processes

* `/druid/broker/v1/loadstatus` for Broker processes

* `/druid/historical/v1/readiness` for Historical processes

Cheers.
