### ISSUE TITLE
Make StatusResponseHandler singleton

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7833]
It's also never instantiated with anything except `UTF_8`.

**Comment by sashidhar** [comment]
@leventov, 

1. I see instantiations using default charset in tests - JettyTest.java and JettyQosTest.

`new StatusResponseHandler(Charset.defaultCharset())`

 Can they be safely changed to use UTF_8 ?

2. What singleton pattern do you suggest ? Early instantiation using a static member or a lazy instantiation using a double locking mechanism.

**Comment by leventov** [comment]
> Can they be safely changed to use UTF_8 ?

It seems to me that yes

> What singleton pattern do you suggest ? Early instantiation using a static member or a lazy instantiation using a double locking mechanism.

No need for DCL here, just static final

**Comment by sashidhar** [comment]
@leventov , please review https://github.com/apache/incubator-druid/pull/7969

**Comment by jihoonson** [comment]
Fixed in #7969.
