### ISSUE TITLE
No scrolling in Web Interface

### ISSUE THREAD

**Issue by CalvinSchulze** [apache/incubator-druid#7836]
When I open for example the Dynamic Settings Editor, I can't access all options, because the list is longer than my screen and there's no scroll bar (scrolling with mouse wheel has no effect). Same for the query window. I can't read my 100 entries, because I see only the top 10.

### Affected Version

 0.14.2-incubating on Ubuntu 19.04 in Firefox

### Description

- Configurations in use: The Quickstart Tutorial config
- Steps to reproduce the problem:
1. Start the server (using the Quickstart Config)
2. Open the Web View
3. Open the Dynamic Settings Assitant
4. Try to see all options

**Comment by vogievetsky** [comment]
The dynamic settings editor scrolling have been fixed and will be released as part of 0.15.0.
The query view has been fixed in master (did not make it for 0.15.0), it has also been made resizable so you can adjust the space between the query part and the results.

**Comment by CalvinSchulze** [comment]
Thank you very much for sorting that out. Is a specific release date planned?

**Comment by vogievetsky** [comment]
0.15.0 release candidate 1 will be probably out early next week. It would be great if you could test and verify that the scrolling issue is indeed fixed there.

**Comment by jihoonson** [comment]
Related to https://github.com/apache/incubator-druid/issues/7869.

**Comment by vogievetsky** [comment]
With  #7871 this issue will be fully fixed in the 0.15.0 release.

**Comment by vogievetsky** [comment]
This issue was fixed in 0.15 (and is still fixed in 0.16 :-p )
