### ISSUE TITLE
Make required S3 permissions consistent for pushing segments and task logs

### ISSUE THREAD

**Issue by dclim** [apache/incubator-druid#7875]
### Description

The code for pushing task logs and segments to S3 deep storage is mostly shared, but the segment code path has some additional logic to possibly get the bucket owner (by fetching the bucket ACL) and set the ACL of the segment object to give the bucket owner full access. See:

https://github.com/apache/incubator-druid/blob/master/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3DataSegmentPusher.java#L147

and compare with: 

https://github.com/apache/incubator-druid/blob/master/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3TaskLogs.java#L138

The additional ACL permissions required for pushing segments can lead to scenarios where the task logs succeed in being written to S3 but the segment PUT request fails with an Access Denied. There is no reason that the ACL on the segment should be set but not on the task log, and making this consistent will avoid future debugging headache.

Additionally - consider having a fallback where if the putObject request fails after setting the ACL, it retries without setting the ACL, even if `druid.storage.disableAcl=false`.

**Comment by sashidhar** [comment]
@dclim I would like to work on this improvement.

**Comment by sashidhar** [comment]
@dclim  Please look at my questions and comments at https://github.com/apache/incubator-druid/pull/7907/files.   

Also I was unable to find a test class corresponding to S3TaskLogs.java. Can you please point me to the corresponding test class ?

**Comment by dclim** [comment]
@sashidhar thank you for your contribution! I left a few comments on your PR.

Regarding the test class - I couldn't find one either. If you could create a simple one that exercises the functionality you added, that would be great.

For the fallback - I think it's fine either way, whether you want to do it here or elsewhere. I'm thinking something really simple - like, wrapping the call in a try-catch and then retrying it one time without getting the bucket ACL / setting the object ACL if it fails. I'd add a log in the catch statement as well so that it's clear that the initial call failed and it's doing a fallback.

**Comment by sashidhar** [comment]
@dclim, Please review the changes and check my comments in the PR.

These are the changes 
1. Added a new test class with 2 tests cases covering the changes made.
2. Extracted common method to a method in utils class.

The PR doesn't cover the fallback will do it in another PR.
