### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by clemTJ** [apache/incubator-druid#7923]
Hi everyone. 

I'm trying to install Druid on Ubuntu 18.04.2 LTS (on VirtualBox). I'm having some difficulties following the quickstart protocol on druid.io... 
I am a beginner and I hope it will be obvious for some of you. 

After downloading apache-druid and zooKeeper (already in the zk file).

Then I start the zooKeeper server : ./bin/zkServer.sh start (I don't know if it is really necessary ... ?)

Then when I hit enter after righting  `bin/supervise -c quickstart/tutorial/conf/tutorial-cluster.conf`  I have well :
 
`[Wed Feb 27 12:46:13 2019] Running command[zk], logging to[/apache-druid-0.14.2-incubating/var/sv/zk.log]: bin/run-zk quickstart/tutorial/conf
[Wed Feb 27 12:46:13 2019] Running command[coordinator], logging to[/apache-druid-0.14.2-incubating/var/sv/coordinator.log]: bin/run-druid coordinator quickstart/tutorial/conf
[Wed Feb 27 12:46:13 2019] Running command[broker], logging to[/apache-druid-0.14.2-incubating/var/sv/broker.log]: bin/run-druid broker quickstart/tutorial/conf
[Wed Feb 27 12:46:13 2019] Running command[router], logging to[/apache-druid-0.14.2-incubating/var/sv/router.log]: bin/run-druid router quickstart/tutorial/conf
[Wed Feb 27 12:46:13 2019] Running command[historical], logging to[/apache-druid-0.14.2-incubating/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Feb 27 12:46:13 2019] Running command[overlord], logging to[/apache-druid-0.14.2-incubating/var/sv/overlord.log]: bin/run-druid overlord quickstart/tutorial/conf
[Wed Feb 27 12:46:13 2019] Running command[middleManager], logging to[/apache-druid-0.14.2-incubating/var/sv/middleManager.log]: bin/run-druid middleManager quickstart/tutorial/conf
`  

But then I have a serie of errors : 

`[Wed Jun 19 10:36:57 2019] Command[broker] exited (pid = 1829, signal = 9)
[Wed Jun 19 10:36:57 2019] Command[broker] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/broker.log
[Wed Jun 19 10:36:59 2019] Command[historical] exited (pid = 1831, exited = 1)
[Wed Jun 19 10:36:59 2019] Command[historical] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log
[Wed Jun 19 10:37:00 2019] Running command[broker], logging to[/home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/broker.log]: bin/run-druid broker quickstart/tutorial/conf
[Wed Jun 19 10:37:02 2019] Running command[historical], logging to[/home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Jun 19 10:38:50 2019] Command[historical] exited (pid = 2417, exited = 1)
[Wed Jun 19 10:38:50 2019] Command[historical] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log
[Wed Jun 19 10:38:53 2019] Running command[historical], logging to[/home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Jun 19 10:38:53 2019] Command[historical] exited (pid = 2770, exited = 1)
[Wed Jun 19 10:38:53 2019] Command[historical] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log
[Wed Jun 19 10:38:56 2019] Running command[historical], logging to[/home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Jun 19 10:38:57 2019] Command[historical] exited (pid = 2787, exited = 1)
[Wed Jun 19 10:38:57 2019] Command[historical] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log
[Wed Jun 19 10:39:00 2019] Running command[historical], logging to[/home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Jun 19 10:39:00 2019] Command[historical] exited (pid = 2801, exited = 1)
[Wed Jun 19 10:39:00 2019] Command[historical] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log
[Wed Jun 19 10:39:03 2019] Running command[historical], logging to[/home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log]: bin/run-druid historical quickstart/tutorial/conf
[Wed Jun 19 10:39:04 2019] Command[historical] exited (pid = 2815, exited = 1)
[Wed Jun 19 10:39:04 2019] Command[historical] failed, see logfile for more details: /home/clement/Documents/apache-druid-0.14.2-incubating/var/sv/historical.log`

If someone know what it is due to .. 

Then I have some errors trying to access the consol but it's another problem...

Thanks !

**Comment by fjy** [comment]
Please use the user groups for these types of problems: https://groups.google.com/forum/#!forum/druid-user

In particular, if you read the error message, it is pointing you to the logs which will contain the actual errors preventing startup.
