### ISSUE TITLE
how to change __time columns？

### ISSUE THREAD

**Issue by heyaping388** [apache/incubator-druid#7930]
description ：
   I created a kafka index service timestampSpec that specifies 'update_time' and now I need to specify timestampSpec that specifies 'create_time', I tried to submit a task to supervisor, timestampSpec specifies 'create_time', but the data using the statistics of timestampSpec is still 'update_time',
Instead of 'create_time'. How can I change the 'create_time' query by arbitration? Looking forward to reply.
thank you.

**Comment by vogievetsky** [comment]
In general if you want to change which column __time is being populated from then you need to update your supervisor spec (not submit a task). If you post your specs here I might be able to provide more detail.

**Comment by vogievetsky** [comment]
With Druid 0.16.0 you can also use the point-and-click data loader to reindex your data with a different time column

![image](https://user-images.githubusercontent.com/177816/65658293-f1425980-dfdb-11e9-927d-6771ebb5a00c.png)

Either way, marking this as solved. Please reopen if needed.
