### ISSUE TITLE
druid is free

### ISSUE THREAD

**Issue by ThreeEarthGod** [apache/incubator-druid#7960]
HI:
    Druid is completely free, why is this for me within 300g for free, thank you！

![image](https://user-images.githubusercontent.com/43139217/60087072-dd821f80-976e-11e9-834b-eea178b73f2d.png)

**Comment by RoseDaniel** [comment]
Hi @ThreeEarthGod this relates to available space and not any relation to financial costs.

**Comment by vogievetsky** [comment]
If you are referring to the `n + 1.0` label it really is not saying much you have no data in your cluster so you could lose all the nodes and 'the data' will still be available.

Druid now has a new console:

![image](https://user-images.githubusercontent.com/177816/60111769-6a06f080-9723-11e9-8b74-3385339636d6.png)

It displays that information in a better way. You can read more about it here: https://druid.apache.org/docs/latest/operations/druid-console.html

**Comment by ThreeEarthGod** [comment]
Thanks
