### ISSUE TITLE
a Compaction Task question

### ISSUE THREAD

**Issue by shizhengchao** [apache/incubator-druid#7975]
If the state of the segment is flying, it is not publish, can the compaction task compress these segments normally? @gianm

**Comment by vogievetsky** [comment]
What is a flying segment? IIRC compaction only works on published segments?

**Comment by shizhengchao** [comment]
> What is a flying segment? IIRC compaction only works on published segments?

I mean is that no published segments.

**Comment by shizhengchao** [comment]
> What is a flying segment? IIRC compaction only works on published segments?

So your reply is a positive sentence, not a question, is it?

**Comment by vogievetsky** [comment]
Yes sorry for the confusion. Compaction only works on published segments.
