### ISSUE TITLE
How do I install druid as a cluster?

### ISSUE THREAD

**Issue by ighack** [apache/incubator-druid#7989]
on official web

https://druid.apache.org/docs/latest/operations/example-cluster.html
Not Found

How can I get a readme.

**Comment by justinborromeo** [comment]
Based on #7749, it seems as if the example-cluster doc was replaced by a clustering tutorial.  Is https://druid.apache.org/docs/latest/tutorials/cluster.html#fresh-deployment what you're looking for?

**Comment by vogievetsky** [comment]
Should there be a redirect there?

**Comment by jon-wei** [comment]
#7749 should be backported to 0.15.0 docs, it was missed, will do that shortly

**Comment by ighack** [comment]
I looking for "Clustered deployment"

**Comment by fjy** [comment]
@ighack https://druid.apache.org/docs/latest/tutorials/cluster.html

**Comment by vogievetsky** [comment]
Closing as fixed by #7749
