### ISSUE TITLE
indexer/time/run/millis metric doesn't work

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#802]
It is always zero. This is interesting because the default duration (in TaskStatus) is -1.

**Comment by noddi** [comment]
Current name of this metric is **task/run/time**, and it is already fixed.

**Comment by zzl0** [comment]
@noddi is this a bug, as the fig shows, index task's duration is always 0, 

- Druid version: 0.9.0
- Problem:
<img width="914" alt="screen shot 2016-05-05 at 3 54 26 pm" src="https://cloud.githubusercontent.com/assets/4735446/15038848/274f163a-12da-11e6-89b8-8708dcfd4dc6.png">

**Comment by jfmwz** [comment]
Hi

![image](https://user-images.githubusercontent.com/3073892/33953249-a776ea76-e034-11e7-9639-366b5403c165.png)

I think that this bug is fixed. I have tested, and the column duration it is not more 0
