### ISSUE TITLE
PagingIdentifiers are not right when  query  data with select query

### ISSUE THREAD

**Issue by duanxuelin** [apache/incubator-druid#8025]
### Affected Version
0.14.0-incubating

### Description

I hava a kafka-indexing-service running. when query data with select and interval end at right now, the query result would contain wrong pagingIdentifiers.

Wrong pagingIdentifiers I mentioned mean that when I query next page with pagingIdentifiers I got in the last query, the result contains records last query has already returned.

I guess that part of query results are come from peon process, which may cause this. So changed interval and pagination works just like expected.
my query is like：
```
{
    "queryType": "select",
    "dataSource": "messages",
    "descending": true,
    "dimensions": [],
    "metrics": [],
    "granularity": "all",
    "filter": {
        "type": "and",
        "fields": [
            {
                "type": "selector",
                "dimension": "uid",
                "value": "201010000001"
            }
        ]
    },
    "intervals": [
        "2019-07-03T08:13:49.944Z/2019-07-04T08:13:49.944Z"
    ],
    "pagingSpec": {
        "pagingIdentifiers": {
        },
        "threshold": 10
    }
}
```

**Comment by vogievetsky** [comment]
Does the scan query (which is a better version of `select` and will one day completely replace it) work correctly?

**Comment by kalidask21** [comment]
Does druid query support row_number function like MSSQL ? or any otheroption to implement pagination in query ?

Example: 
Retrieve only data between 25 to 50 rows from 100 rows result.

Thanks

**Comment by duanxuelin** [comment]
>The major difference between the two is that the Scan query does not support pagination. However, the Scan query type is able to return a virtually unlimited number of results even without pagination, making it unnecessary in many cases.

@vogievetsky  Documents show that scan query does not support pagination.

**Comment by vogievetsky** [comment]
@duanxuelin the scan query streams results which is like a built in pagination

**Comment by JiajianQtl** [comment]
I met the same issue, have any solution? @duanxuelin @vogievetsky

**Comment by fjy** [comment]
Select query has been deprecated in favor of scan query. I am closing this issue. We recommend everyone move over to the scan query. The select query is extremely inefficient and no long recommended for any production use.

**Comment by JvalantPatel-MS** [comment]
@JiajianQtl  @duanxuelin  @vogievetsky how did you solve this problem ? We are experiencing this in 0.15.1 Druid version and we are not in a position where we can simply replace `select` query with `scan` in short time.

@duanxuelin was your setup having multiple replicas for the ingestion operation ? any help on this would be greatly appreciated
