### ISSUE TITLE
Undocumented, seemingly random choosing of inital value timestamp for SQL results

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#8041]
### Affected Version

0.14.2

### Description
 
video:
https://www.screencast.com/t/A7cuiFxXlL

Note the change of timerange in the query and the timestamp of initial value.

With timerange starting at :

07:00 returned initial timestamp: 07:00
07:50 returned initial timestamp: 07:00
07:58 returned initial timestamp: 08:00

Why do results switch to 08:00 with query at 07:58 and not with query at 07:50

**Comment by gianm** [comment]
Is it possible you don't have any data points from 07:58 to 08:00?

**Comment by pdeva** [comment]
yess! i just came to the same conclusion. 
we ingest at every 10 seconds, so thats why its jumping at 07:58.

However, take the query timestamp of 07:50:

Given the query 07:50 to 00:37, with granularity PT60S, i expected the rollup to be as follows:

07:50 - 08:50
08:50 -09:50, 
etc.

However, druid automatically assumes the begin time to be 07:00 which is not intended, since begin time is explicitly specified at 07:50.

How does one achieve the above desired result then with druid sql?

**Comment by pdeva** [comment]
to clarify, with the 07:50-37:00 time range example, i am saying:

```
starting at 07:50
rollup results in 60 second batches,
do so till you hit 37:00
```
thus results with timerange 07:50-08:50, 08:50-09:50, etc.

However, druid interprets as :

```
starting at 07:00,
rollup results in 60 second batches,
but wait, initial timestamp is 07:50, 
so for first value specify timestamp at 07:00, but consider values from 07:50 to 08:00
```

resulting in 07:00-08:00, 08:00-09:00, etc..

which seems very random....

**Comment by pdeva** [comment]
seeing the generated sql query, it seems the issue is that by default 'origin' is not specified.

i tried specifying the origin in the TIME_FLOOR in SQL, but it resulted in the following exception:

![image](https://user-images.githubusercontent.com/3190176/60854032-8b4fee00-a1b3-11e9-843f-8e6e3ae247fb.png)

**Comment by pdeva** [comment]
simplied the query, so i can see the full exception.

video:
https://www.screencast.com/t/6urBmhP1rWHL

Exception:
![image](https://user-images.githubusercontent.com/3190176/60854123-f39ecf80-a1b3-11e9-9a7b-ba88b65de880.png)

**Comment by pdeva** [comment]
ahh. should be the literal 'TIMESTAMP' before the timestamp value.
closing.
