### ISSUE TITLE
Add missing docs for druid.indexer.logs.disableAcl

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#8042]
See https://github.com/apache/incubator-druid/pull/7907#issuecomment-509462715

**Comment by sashidhar** [comment]
Raised https://github.com/apache/incubator-druid/pull/8046 for the documentation fix. Let me know if any other documentation change is needed for this. 

With regards to release notes, help me where and what change needs to be done.

**Comment by gianm** [comment]
@sashidhar Thanks for the PR!

For the release notes, typically we use these labels to remind release managers about patches that need special calling out. There isn't any need for you to do anything, but it would help the next manager if you drafted a blurb for the "upgrading from previous" versions section of the notes. Something that mentions the new property and describes to users when they should think about setting it. The idea would just be to avoid surprising people.
