### ISSUE TITLE
Issue while using Docker build 

### ISSUE THREAD

**Issue by santoshdvn** [apache/incubator-druid#8054]
Hi ,

Trying to install the Apache Druid using docker .
`docker build -t druid:tag -f distribution/docker/Dockerfile .`

I am getting below error 

> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (generate-license) on project distribution: Command execution failed.: Process exited with an error: 127 (Exit value: 127) -> [Help 1]

Can anyone help me with this ? 

Thanks,
Santosh

**Comment by gianm** [comment]
Does it work if you build from the `druid-0.15.0-incubating` tag? (Just wondering if something changed since the last release)

**Comment by ilhanadiyaman** [comment]
@santoshdvn I had the similar problem. [This PR](https://github.com/apache/incubator-druid/pull/7997) solved my issues regarding docker image. I hope they'll review and merge as soon as possible.
