### ISSUE TITLE
add aggregators for computing mean/average

### ISSUE THREAD

**Issue by himanshug** [apache/incubator-druid#8071]
### Motivation

I have use case of querying mean value of certain columns and need an easy and efficient way to do same.

### Proposed changes

We would introduce `DoubleMeanAggregatorFactory` implementation and other related classes e.g. `DoubleMeanAggregator` . It would work by using following well known algorithm.

```
// maintain following variables
long count;
double mean;

// update with a value v
count++;
mean = mean + (v - mean)/count;

// merging
count = count1 + count2;
mean = (mean1*count1 + mean2*count2)/count;
```

consequently a new aggregator type called `doubleMean` would be made available.

### Rationale
In comparison to the alternatives, proposed implementation is most straightforward and least overhead way to get mean of a column.

Alternative#1:
Use `doubleSum` , `doubleCount` aggregators and use `arithmetic` or `expression` post aggregator to do the division to compute mean. It becomes tedious for system generating the druid query and mean is a very common aggregation being available out of the box. 

Alternative#2:
Add a `MeanPostAggregator` that extracts the mean from `VarianceAggregatorCollector` maintained by `VarianceAggregator` OR  add a option to `VarianceAggregatorFactory` to 
 output mean in `finalizeComputation(obj)` method. However, this would unnecessarily maintain variables for variance.

### Operational impact
None

### Test plan (optional)
Changes proposed here would be easily unit testable.

### Future work (optional)

Maybe a `floatMean` aggregator if some use case is too paranoid about saving few bytes at query time. However, I don't think mean is a stat that should be indexed and stored in segment so `floatMean` is not important I think.

**Comment by gianm** [comment]
Would the algorithm you mention be more or less efficient than the following -- which is what people mostly do today in Druid?

```
// maintain following variables
long count;
double sum;

// update with a value v
count++;
sum += v;

// merging
count = count1 + count2;
sum = sum1 + sum2;

// finalizing
result = sum / count;
```

I think yours has less likelihood of overflowing `sum`, but it involves a division on every update, and that might slow things down. (I haven't benchmarked it.)

Btw, some comments related to Druid SQL:

- In Druid SQL it's already easy. You can write `AVG(value)` and it will generate the sum and count aggs and the necessary postagg. I'm hoping that in general, people looking for easy ways to do stuff will gravitate towards SQL.
- If we do end up adding native mean aggregators that are better than doing the sum+count+postagg thing, then we can also modify Druid SQL to use them. The code is in `AvgSqlAggregator`.

**Comment by himanshug** [comment]
yeah that algorithm is to avoid overflowing `sum` . You are right that instructions for divisions are slower in theory (but hardware has come a long way...), but I will benchmark the division based algo presented here and post the findings. 
That said, for some users it might be important to not have overflow problem even if division in this algorithm can potentially make things slower and Using sum, count aggs with a post agg for division would still be available.

That said, I think main reason for introducing a mean aggregator is for convenience of its usage in druid native query spec which is what currently being used in my project. (Actually real story is 
 slightly more complicated :P ) .

**Comment by himanshug** [comment]
I ran following benchmark on an idle `t3.medium` EC2 instance.

```
@State(Scope.Benchmark)
@Fork(1)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Warmup(iterations = 5)
@Measurement(iterations = 5)
public class MeanAggregationBenchmark
{
  @Param({"10", "100", "1000", "10000", "100000", "1000000"})
  private int n;

  @Benchmark
  public void sumcountalgo(Blackhole blackhole)
  {
    double sum = 0;
    long count = 0;

    for (int i = 1; i <= n; i++) {
      count++;
      sum += i;
    }

    double mean = sum/count;
    blackhole.consume(mean);
  }

  @Benchmark
  public void divbasedalgo(Blackhole blackhole)
  {
    double mean = 0;
    long count = 0;

    for (int i = 1; i <= n; i++) {
      count++;
      mean = mean + (i - mean)/count;
    }

    blackhole.consume(mean);
  }
}
```

that produced

```
Benchmark                                  (n)  Mode  Cnt        Score       Error  Units
MeanAggregationBenchmark.divbasedalgo       10  avgt    5       30.601 ±     0.123  ns/op
MeanAggregationBenchmark.divbasedalgo      100  avgt    5      613.996 ±     4.428  ns/op
MeanAggregationBenchmark.divbasedalgo     1000  avgt    5     7130.145 ±    90.105  ns/op
MeanAggregationBenchmark.divbasedalgo    10000  avgt    5    71296.475 ±   627.211  ns/op
MeanAggregationBenchmark.divbasedalgo   100000  avgt    5   712208.125 ±  5066.485  ns/op
MeanAggregationBenchmark.divbasedalgo  1000000  avgt    5  7117593.058 ± 78224.014  ns/op
MeanAggregationBenchmark.sumcountalgo       10  avgt    5        8.600 ±     0.106  ns/op
MeanAggregationBenchmark.sumcountalgo      100  avgt    5       99.377 ±     1.028  ns/op
MeanAggregationBenchmark.sumcountalgo     1000  avgt    5     1282.228 ±    29.673  ns/op
MeanAggregationBenchmark.sumcountalgo    10000  avgt    5    12790.421 ±   127.669  ns/op
MeanAggregationBenchmark.sumcountalgo   100000  avgt    5   128994.367 ±  2068.910  ns/op
MeanAggregationBenchmark.sumcountalgo  1000000  avgt    5  1281204.111 ± 12692.807  ns/op
```

From that it is clear that "div based" algo is about 6 times slower compared to "sum based"  . With div based algo, it is about ~7ms for 1mn aggregations compared to ~1ms for sum based , and that might be make a difference for some users but not most.
I think, for the mean aggregator introduced here, we can have both algos be present in the code with `div based` being the default but ability to switch to `sum based` if need be.
