### ISSUE TITLE
Unified console broken: resizeSensor.js unexpected token { on line 88

### ISSUE THREAD

**Issue by trtg** [apache/incubator-druid#8074]
### Affected Version
0.15.0

### Description

The unified console does not load at all- I get a blank page and the javascript error included at the end of this description appears in the JS console. The unified console worked fine in 0.14.0.

- 3 R5.2xlarge instances in cluster
- only steps to reproduce- try to load the unified console by going to node:8888

Here is the error that appears in the JS console:
`
resizeSensor.js:88 Uncaught SyntaxError: Unexpected token {
    at Object../node_modules/@blueprintjs/core/lib/esnext/components/resize-sensor/resizeSensor.js (web-console-0.15.0.js:2323)
    at __webpack_require__ (web-console-0.15.0.js:20)
    at eval (popover.js:15)
    at Module../node_modules/@blueprintjs/core/lib/esnext/components/popover/popover.js (web-console-0.15.0.js:2239)
    at __webpack_require__ (web-console-0.15.0.js:20)
    at eval (contextMenu.js:15)
    at Module../node_modules/@blueprintjs/core/lib/esnext/components/context-menu/contextMenu.js (web-console-0.15.0.js:1771)
    at __webpack_require__ (web-console-0.15.0.js:20)
    at eval (index.js:3)
    at Module../node_modules/@blueprintjs/core/lib/esnext/components/index.js (web-console-0.15.0.js:2083)
`

**Comment by vogievetsky** [comment]
Hello, this is strange. I can not reproduce this at all. 
What browser are you using? What is the OS of the computer on which the browser is running? Also can you please post a screenshot of the error in the console (maybe of the entire browser?)

**Comment by vogievetsky** [comment]
Also if anyone else can repro this please shout out!

**Comment by trtg** [comment]
This is running an admittedly older version of chrome(65.0.3325.146) on gentoo linux. I'll try again with a more up to date version of chrome- this also randomly started happening this morning, as earlier it was not an issue with the same version of druid.

<a href="//imgur.com/a/LHsiKsx">screenshot</a>

**Comment by vogievetsky** [comment]
I just downloaded and tested that exact version of Chrome for MacOS and I can not repro the issue there... gotta try Linux. Can you please try Firefox / newer version of Chrome. Whatever the issue is this seems to be coming from Blueprint.js and between Druid 0.14.0 and Druid 0.15.0 we upgraded it from 1.0.1 to 3.17.0 and also started using the ResizeSensor so that would at least explain why you are not seeing this in the older Druid.

**Comment by vogievetsky** [comment]
Ok, I can repro it on that version of Chrome on linux (ubuntu).
I tested Chrome 75 and it works, also FF works on linux.
Will look into what can be done to fix this. I guess the workaround for now is to update your chrome or switch to FF.

**Comment by trtg** [comment]
Will hopefully upgrade this weekend, same issue appeared in Brave, so I guess it must be linked to some revision of chromium

**Comment by vogievetsky** [comment]
Ok I believe that this incompatibility that is throwing off old chromium is fixed here: https://github.com/apache/incubator-druid/pull/8007

**Comment by trtg** [comment]
@vogievetsky thanks so much for following up. I'll be back at my computer by tomorrow and will try just compiling current chromium

**Comment by vogievetsky** [comment]
No rush. Just want to make sure this is taken care of :-)
