### ISSUE TITLE
maxBytesInMemory not work at index_hadoop task

### ISSUE THREAD

**Issue by hellobabygogo** [apache/incubator-druid#8096]
index_hadoop failed with exception: Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File hdfs://hdfs/user/druid/verify/hadoop-tmp/test_hadoop/2019-07-17T140111.109Z_362ab04047f041ce99adf0f3c385100c/segmentDescriptorInfo does not exist.

### Affected Version

Druid version: 0.13.0

### Description

Map reduce success but druid task failed with segmentDescriptorInfo does not exist. I'm sure indexing process did produce any segments.

**Comment by surekhasaharan** [comment]
@hellobabygogo check this https://groups.google.com/forum/#!topic/druid-user/eIcb3WH3hg0 or https://groups.google.com/forum/#!topic/druid-user/SVVHQ4-9Rlw , if it helps.
