### ISSUE TITLE
Provide official Docker Image in a public container registry

### ISSUE THREAD

**Issue by gerbal** [apache/incubator-druid#8103]
Currently several people (including me) are hosting their own builds of the Druid Docker image on docker hub. 

It would be very helpful to have an official docker image provided by this project so we aren't reliant on building our own or trusting an unknown docker image.

**Comment by xvrl** [comment]
Apache does not provide official docker images. We can however provide convenience binaries on the apache dockerhub account. I just requested to have automated builds be setup there (see https://jira.apache.org/jira/browse/INFRA-18887)

**Comment by xvrl** [comment]
https://hub.docker.com/r/apache/incubator-druid is set up. A new image will be pushed automatically with the next release.

**Comment by clintropolis** [comment]
>https://hub.docker.com/r/apache/incubator-druid is set up. A new image will be pushed automatically with the next release.

Awesome, I'll be sure to add it to the release notes for 0.16.0

**Comment by asdf2014** [comment]
Well done! I also raised up a new PR https://github.com/apache/incubator-druid/pull/8403 to add a docker shield with this official dockerhub link.
