### ISSUE TITLE
The dimension field contains the '.' symbol, how should it be queried?

### ISSUE THREAD

**Issue by shuaidonga** [apache/incubator-druid#8104]
The dimension field contains the '.' symbol, how should it be queried?

![image](https://user-images.githubusercontent.com/16378509/61472430-033dc580-a9b7-11e9-9d72-ae6e9b8333de.png)

I try to use  SELECT * FROM bro2 WHERE id.orig_h='64.233.188.188'
The following error occurred
Unknown exception / org.apache.calcite.runtime.CalciteContextException: From line 1, column 41 to line 1, column 42: Table 'id' not found / org.apache.calcite.tools.ValidationException

**Comment by vogievetsky** [comment]
Try `SELECT * FROM bro2 WHERE "id.orig_h"='64.233.188.188'`

**Comment by shuaidonga** [comment]
thank you very much
