### ISSUE TITLE
sys.segment's is_realtime flag once set, is never unset

### ISSUE THREAD

**Issue by surekhasaharan** [apache/incubator-druid#8142]
### Affected Version

0.15

### Description

In the system schema's `sys.segments` table, the `is_realtime` flag is set when a segment is added via `segmentAdded` callback in `DruidSchema`. But it's not unset when a segment is dropped from realtime task and published on historicals. So when `serverSegmentRemoved` is called, the `is_realtime` flag should be unset. 
This was reported here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/t-215-pIJO4/yG9Y5VRLDwAJ

**Comment by gianm** [comment]
@dclim to review https://github.com/apache/incubator-druid/pull/8154
