### ISSUE TITLE
Auto-compaction should forward the maxBytesInMemory setting to the compaction tasks

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#8262]
### Description

Right now maxBytesInMemory is not sent from the auto compaction tuningConfg (https://druid.apache.org/docs/latest/configuration/index.html#compact-task-tuningconfig) to 
the compaction task tuningConfig ( https://druid.apache.org/docs/latest/ingestion/native_tasks.html#tuningconfig )

### Motivation

Ideally most of the keys available in the compaction task tuningConfig should be settable from the auto compaction tuningConfig. `maxBytesInMemory` is particularly useful for when you need to tune memory in a specific way (maybe you have a ton of lookups or whatever).

**Comment by gianm** [comment]
Fixed by #8274
