### ISSUE TITLE
LEFT() and RIGHT() functions do not work in DruidSQL

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#8266]
### Affected Version

0.15.0, 0.16.0-snapshot

### Description

LEFT and RIGHT are documented:

https://druid.apache.org/docs/latest/querying/sql

![image](https://user-images.githubusercontent.com/177816/62728389-878cd280-b9d0-11e9-8750-1cbc409a9f82.png)

but they do not seem to be supported in Calcite:

![image](https://user-images.githubusercontent.com/177816/62728417-9a9fa280-b9d0-11e9-8fff-e609563964c6.png)

**Comment by jon-wei** [comment]
Related: https://issues.apache.org/jira/browse/CALCITE-3005

Upgrading to Calcite 1.20.0+ seems to work, investigating/testing more

**Comment by jon-wei** [comment]
Also related: https://github.com/apache/incubator-druid/pull/8406
