### ISSUE TITLE
Load from Kafka: UnsupportedVersionException. Failed to sample data: The broker does not support LIST_OFFSETS with version in range[2,4]. The supported range is [0,1].

### ISSUE THREAD

**Issue by mingzeng21** [apache/incubator-druid#8279]
Load from Kafka: UnsupportedVersionException. Failed to sample data: The broker does not support LIST_OFFSETS with version in range[2,4]. The supported range is [0,1].

### Affected Version

The Druid version is 0.15.0

### Description

I am trying to load data from Kafka using Druid Kafka ingestion. I get error message: UnsupportedVersionException. Failed to sample data: The broker does not support LIST_OFFSETS with version in range[2,4]. The supported range is [0,1].

I know that the version of the Kafka broker should be 0.10.x or newer. 
I am using a CDH cluster. The Kafka version shown on CM is 0.10.2+kafka2.2.0. The KAFKA dir under cloudera/parcels is KAFKA-2.2.0-1.2.2.0.

It seems like my Kafka version has met the requirement. But why this fatal exception has happened?

**Comment by jihoonson** [comment]
Hi, the minimum supported Kafka version is changed to 0.11.0 in 0.15.0. See https://github.com/apache/incubator-druid/releases/tag/druid-0.15.0-incubating for more details.

**Comment by pphust** [comment]
```
    final Map<String, Object> consumerConfigs = KafkaConsumerConfigs.getConsumerProperties();
    final Properties props = new Properties();
    addConsumerPropertiesFromConfig(props, sortingMapper, consumerProperties);
    props.putAll(consumerConfigs);
```
According to above code, consumerProperties(from KafkaSupervisorIOConfig) will be overwritten by consumerConfigs which is set in KafkaConsumerConfigs class.
It looks a bit strange for me that user custom setting is NOT prior to static setting. Is it a good idea if we just change the order like below? Druid user will get more flexibility on kafka connect setting and the new `isolation.level=read_uncommitted` will work well also.
```
    final Map<String, Object> consumerConfigs = KafkaConsumerConfigs.getConsumerProperties();
    final Properties props = new Properties();
    **props.putAll(consumerConfigs);**
    addConsumerPropertiesFromConfig(props, sortingMapper, consumerProperties);
```
