### ISSUE TITLE
Port for coordinator and overlord in tutorial is mixed up?

### ISSUE THREAD

**Issue by lejinghu** [apache/incubator-druid#8284]
In the druid data loading tutorial [https://druid.apache.org/docs/latest/tutorials/tutorial-batch.html](url), we are posting the data to port 8081 with 

`bin/post-index-task --file quickstart/tutorial/wikipedia-index.json --url http://localhost:8081`.

However in [https://github.com/apache/incubator-druid/blob/master/examples/bin/post-index-task-main](url) we can see "--url" points to the overlord, which is default to be 8090, while "--coordinator-url" would be 8081.

Is this mixed up? Thanks.

**Comment by jon-wei** [comment]
The example single server configs run the coordinator and overlord in the same process (`druid.coordinator.asOverlord.enabled=true`), so the overlord APIs are served from 8081 as well.

It's briefly mentioned on the single server overview page: https://druid.apache.org/docs/latest/operations/single-server.html

**Comment by lejinghu** [comment]
Thank you @jon-wei . I didn't see this.
