### ISSUE TITLE
apache-druid-0.15.0-incubating always auto stopped

### ISSUE THREAD

**Issue by unixtommy** [apache/incubator-druid#8307]
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version
apache-druid-0.15.0

### Description
I started the druid with "nohup bin/start-micro-quickstart &" ,but I found that  the druid process always auto stopped ,and i didn't run kill.
I don't know if it stoped because of the tasked finished.

the druid's nohup log as follows:
[Wed Aug 14 18:00:15 2019] Running command[zk], logging to[/data/apache-druid-0.15.0-incubating/var/sv/zk.log]: bin/run-zk conf
[Wed Aug 14 18:00:15 2019] Running command[coordinator-overlord], logging to[/data/apache-druid-0.15.0-incubating/var/sv/coordinator-overlord.log]: bin/run-druid coordinator-overlord conf/druid/single-server/micro-quickstart
[Wed Aug 14 18:00:15 2019] Running command[broker], logging to[/data/apache-druid-0.15.0-incubating/var/sv/broker.log]: bin/run-druid broker conf/druid/single-server/micro-quickstart
[Wed Aug 14 18:00:15 2019] Running command[router], logging to[/data/apache-druid-0.15.0-incubating/var/sv/router.log]: bin/run-druid router conf/druid/single-server/micro-quickstart
[Wed Aug 14 18:00:15 2019] Running command[historical], logging to[/data/apache-druid-0.15.0-incubating/var/sv/historical.log]: bin/run-druid historical conf/druid/single-server/micro-quickstart
[Wed Aug 14 18:00:15 2019] Running command[middleManager], logging to[/data/apache-druid-0.15.0-incubating/var/sv/middleManager.log]: bin/run-druid middleManager conf/druid/single-server/micro-quickstart
[Wed Aug 14 19:01:28 2019] Sending signal[15] to command[middleManager] (timeout 10s).
[Wed Aug 14 19:01:36 2019] Command[middleManager] exited (pid = 13735, exited = 143)
[Wed Aug 14 19:01:36 2019] Sending signal[15] to command[coordinator-overlord] (timeout 10s).
[Wed Aug 14 19:01:36 2019] Sending signal[15] to command[broker] (timeout 10s).
[Wed Aug 14 19:01:36 2019] Sending signal[15] to command[router] (timeout 10s).
[Wed Aug 14 19:01:36 2019] Sending signal[15] to command[historical] (timeout 10s).
[Wed Aug 14 19:01:37 2019] Command[router] exited (pid = 13733, exited = 143)
[Wed Aug 14 19:01:38 2019] Command[broker] exited (pid = 13732, exited = 143)
[Wed Aug 14 19:01:38 2019] Command[historical] exited (pid = 13734, exited = 143)
[Wed Aug 14 19:01:39 2019] Sending signal[9] to command[zk].
[Wed Aug 14 19:01:39 2019] Sending signal[9] to command[coordinator-overlord].
[Wed Aug 14 19:01:39 2019] Command[zk] exited (pid = 13730, signal = 9)
[Wed Aug 14 19:01:39 2019] Command[coordinator-overlord] exited (pid = 13731, signal = 9)
[Wed Aug 14 19:01:39 2019] Exiting.

**Comment by lswyyy** [comment]
I found the same issue in 0.15.1 also

**Comment by lswyyy** [comment]
try to use exit command after "nohup bin/start-micro-quickstart &"

**Comment by 123hgr** [comment]
你好，我也遇到这个自动退出问题，请问你们都是怎么解决的

**Comment by lswyyy** [comment]
> 你好，我也遇到这个自动退出问题，请问你们都是怎么解决的

nohup ... & 启动后，使用 exit 退出当前终端，否则断开时会被认为异常退出
