### ISSUE TITLE
Druid Jetty Exception

### ISSUE THREAD

**Issue by suntyu** [apache/incubator-druid#8312]
#java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms
#Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.ini
tial
#org.eclipse.jetty.http.BadMessageException: 500: No version

**Comment by suntyu** [comment]
1.hadoop2.6.0-cdh5.15;
2.all web-ui is 500;

**Comment by suntyu** [comment]
The connection failed because the common configuration file changed the host incorrectly. Sorry；

Use 0.15.1

**Comment by zhangxin12138** [comment]
请教下the common configuration file changed the host incorrectly是什么问题，碰到相同问题

**Comment by zhangxin12138** [comment]
> The connection failed because the common configuration file changed the host incorrectly. Sorry；
> 
> Use 0.15.1

请教下the common configuration file changed the host incorrectly是什么问题，碰到相同问题
