### ISSUE TITLE
S3 Extensions Does Not Support IAM Role, Only Secret Key

### ISSUE THREAD

**Issue by smokemonster99** [apache/incubator-druid#8435]
Hi,
The s3 extensions require the following parameters in the s3 deep storage config
druid.s3.accessKey
druid.s3.secretKey
druid.storage.bucket
druid.storage.baseKey

My organization does not allow the use of AWS Secret keys when running applications int he cloud. All applications are expected to support IAM role. Therefore I am unable to use S3 deep storage although it would allow me to create a great disaster recovery strategy using s3 replication, RDS replicas etc.

Is there any way to use IAM role with s3 extensions instead of access key id and secret key? If not, is this feature on the roadmap?

thanks!

**Comment by gianm** [comment]
Hi @smokemonster99, if you just leave out `druid.s3.accessKey` and `druid.s3.secretKey` then Druid will start trying to use instance roles.

**Comment by smokemonster99** [comment]
@gianm Thanks very much for this information, I'll try this today and close the issue when I am able to get it to work!

**Comment by smokemonster99** [comment]
@gianm It's is working now after commenting out the accessKey and secretKey then changing disableACL to true. I'll close, thanks again for your help this is a huge feature for us.
