### ISSUE TITLE
In DirectDruidClient, Future cancellation listener shouldn't run in HTTP library thread

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#8445]
This `Futures.addCallback()` call:

https://github.com/apache/incubator-druid/blob/984958122b962ab019a590f4fd01792de81b75df/server/src/main/java/org/apache/druid/client/DirectDruidClient.java#L453-L500

Uses `MoreExecutors.sameThreadExecutor()` by default, which leads to canceling query (with waiting for one second) in the HTTP client thread (in `org.apache.druid.java.util.http.client.HttpClient`). This is undesirable because `HttpClient` is an asynchronous client.

**Comment by licl2014** [comment]
I also have a problem about `cancel query`, the scenario is as follows:
1. I execute a big query which will runs 1 minute .the timeout is default 5 minutes, after it runs 3 second, we cancel it through `curl -X DELETE "http://broker:8082/druid/v2/queryid"` and it will be canceled success and all historical nodes will cancel it success too.
2. but if it runs more than 10 secnods , after we cancel it with the DELETE API,  we find the query will be canceled ,but not all historical nodes cancel it too.

for 2,  after DELETE ,we find some `futures` removed from `queries`  in QueryManager ,so `cancelQuery`  can't cancel these `futures` .
