### ISSUE TITLE
Fix batch index task naming convention to accommodate simultaneous tasks

### ISSUE THREAD

**Issue by a2l007** [apache/incubator-druid#8494]
### Description
Modify the batch indexing task ID generation logic from

 `<index_type_name>_<datasource>_timestamp` to 
`<index_type_name>_<datasource>_<random_id>`
This would impact native index tasks as well as hadoop index tasks.

### Motivation
With the existing task naming convention, if there are multiple indexing tasks submitted at the same time for a datasource, only one of the tasks gets accepted and the remaining tasks fail with  `Task[xxx] already exists`. I'd like to modify the naming convention to the one mentioned above, so that this issue can be avoided.
@jihoonson Any comments regarding this?

**Comment by jihoonson** [comment]
@a2l007 thanks for raising this issue! I like it. One question. Do we still need the timestamp at the end of the id? I guess its intention was also to avoid duplicate task IDs.

**Comment by a2l007** [comment]
@jihoonson Oops sorry, I meant to remove the timestamp from the new convention. I've updated the description accordingly.

**Comment by jihoonson** [comment]
Ah thanks. It sound good!
