### ISSUE TITLE
Add a search bar to Docusaurus docs

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#8508]
**Problem**: Searchability is essential to documentation and a search bar no longer exist in the new docs.

**Solution**: Add a search bar.

This Docusaurus feature might be handy: https://docusaurus.io/docs/en/search

**Comment by vogievetsky** [comment]
💯 on this. It is my belief that we need to publish the doc site (at the final URL) so that algolia can crawl the docs and index them. Was planning on implementing search within hours of release and site publish.

**Comment by vogievetsky** [comment]
Update here: I submitted the Druid docs for indexing.

<img width="627" alt="Screen Shot 2019-09-28 at 7 56 58 PM" src="https://user-images.githubusercontent.com/177816/65836196-8a0afa80-e2a4-11e9-8040-a2c69bb6aa75.png">
