### ISSUE TITLE
Regarding Ingestion Data Formats : Regex

### ISSUE THREAD

**Issue by chariot1498** [apache/incubator-druid#8555]
I was trying to use regex as the parseSpec . My regex should be able to partition on basis of space alone . I couldn't find any examples of what exactly should be the regex format that would be expected . Like I tried simply putting \s which should partition on whitespace but it doesn't work . Can you please tell how exactly is the regex supposed to be formatted 
Example of Record :
Version AccountID CustomerHash
1 12334 123
1 42455 424

**Comment by vogievetsky** [comment]
Hi!

This kind of question is exactly why in Druid 0.16.0 we are introducing a `Paste data` inline data option! Let's have a looky-look with your data:

![image](https://user-images.githubusercontent.com/177816/65471830-91a24d80-de25-11e9-86d3-bbc0178894f1.png)

Clicking next to go to the next step...

![image](https://user-images.githubusercontent.com/177816/65471879-c910fa00-de25-11e9-84e2-ec159518d24f.png)

We see that you can use a pattern of `(.*)\s(.*)\s(.*)` and set columns to `version, accountId, customerHash` or whatever.

Note that your data has a header, your probably want to remove it as you do not want it to be a row in your data.

**Comment by chariot1498** [comment]
Oh ok cool I actually also got a solution of it : 
 ([a-zA-Z0-9_\-\.]+) ([a-zA-Z0-9_\-\.]+) ([a-zA-Z0-9_\-\.]+)
So I guess basically you have to give the regex representation of the whole String you are trying to partition instead of giving the regex of partitioner (in this case space) . 
Would be great if we can have one example of this in druid docs though, will make life a lot easier

**Comment by vogievetsky** [comment]
Agreed on the example part.
Quick question were you writing a spec by hand or using the web console data loader (as I did in the screenshots?)

**Comment by chariot1498** [comment]
Initially when I posted the question by hand . Later shifted to the console data loader

**Comment by vogievetsky** [comment]
Nice.

**Comment by vogievetsky** [comment]
I added an issue to be able to skip a header in the regex parser - thank for the inspiration!

I am closing this issue as solved. Please reopen if there is followup discussion.
