### ISSUE TITLE
druid批量update语句不支持。

### ISSUE THREAD

**Issue by 136900923** [apache/incubator-druid#8588]
详情见https://blog.csdn.net/mrczr/article/details/78903468

**Comment by jihoonson** [comment]
Hi @136900923, would you please write this issue in English?

**Comment by zeroro88** [comment]
I think this issue belongs https://github.com/alibaba/druid, it should be closed

**Comment by asdf2014** [comment]
@136900923 这个问题不属于 Apache Druid 数据库，是关于 Alibaba Druid 连接池框架的。

**Comment by jihoonson** [comment]
@zeroro88 @asdf2014 thank you for the checking.

**Comment by asdf2014** [comment]
@jihoonson You are welcome.
