### ISSUE TITLE
Docs "edit" link is broken

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#8592]
To reproduce, go to https://druid.apache.org/docs/0.16.0-incubating/design/index.html or https://druid.apache.org/docs/latest/design/index.html and click "edit". The issue is that the extra `/latest/` or `/0.16.0-incubating/` is being passed along to the GitHub URL, leading to broken links like https://github.com/apache/incubator-druid/edit/master/docs/0.16.0-incubating/design/index.md. I think this is related to the `editUrl` in siteConfig.js (currently set to `https://github.com/apache/incubator-druid/edit/master/docs/`).

Btw, a minor related thing: it'd be better to use https://github.com/apache/druid rather than https://github.com/apache/incubator-druid. That way, the links still work when we move to a TLP.

**Comment by clintropolis** [comment]
Fix is live at druid.apache.org
