### ISSUE TITLE
Cannot find data if big number used in where clause

### ISSUE THREAD

**Issue by Vaduz** [apache/incubator-druid#8602]
I get `Query returned no data` error when I specify big number in where clause at query console ui.

## Affected Version

0.16.0

### Cluster size

* 2 x Master (8 CPU, 32GB Mem, SSD)
* 2 x Query (8 CPU, 32GB Mem, SSD)
* 2 x Data (20 CPU, 64GB Mem, SSD)

### Configurations in use

* MySQL as metadata storage
* S3 as deep storage
* master jvm xmx: 24g
* broker jvm xmx: 12g
* router jvm xmx: 1g
* historical jvm xmx: 8g
* historical jvm max direct memory size: 25g
* druid_historical_processing_numThreads: 15
* druid_historical_processing_numMergeBuffers: 4
* druid_historical_processing_buffer_sizeBytes: 500000000
* druid_server_maxSize: 300000000000

### Steps to reproduce the problem

Query like this:

```sql
SELECT * FROM table WHERE id = 9223372036854775807
```

- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.

You'll see  `Query returned no data` error

- Any debugging that you have already done

We can find and verify data that are stored properly if I don't use where clause.

```sql
SELECT * FROM table LIMIT 100
```

And group by query also works.

```sql
SELECT id, COUNT(*) FROM table GROUP BY id
```

This query returns count of big number rows.

**Comment by vogievetsky** [comment]
What is the type of the `id` column?

**Comment by Vaduz** [comment]
It's `long`.

**Comment by vogievetsky** [comment]
I just tried this and I can not repro:

![image](https://user-images.githubusercontent.com/177816/66004571-009f2800-e45e-11e9-93c3-694ec397e001.png)

And then:

![image](https://user-images.githubusercontent.com/177816/66004608-157bbb80-e45e-11e9-9ae0-54c23ae0db6f.png)

Are there more filters in your query? Anything that could provide hints.

**Comment by Vaduz** [comment]
Sorry, the original number I posted was too small.
Please try much bigger number like: `9223372036854775807`

**Comment by Vaduz** [comment]
I figured out cause of this problem. So I created an another issue #8617. Please check.
