### ISSUE TITLE
sql query generation in web console doesnt work

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#8640]
### Affected Version
0.16

### Description

Video:
https://www.screencast.com/t/lmyr1yHf

as can be seen, the filter clause is never generated

**Comment by vogievetsky** [comment]
Could you please post the query from the video here? I am trying to recreate the bug but everything seems to be working

![image](https://user-images.githubusercontent.com/177816/66521363-d96cda00-ea9f-11e9-8938-ae508ca98588.png)

**Comment by pdeva** [comment]
somehow its working now...
i will reopen this if it happens again.
