### ISSUE TITLE
Historicals can't work with multiple druid.segmentCache.locations

### ISSUE THREAD

**Issue by Laboltus** [apache/incubator-druid#8667]
Historicals can't work with multiple druid.segmentCache.locations after upgrade from 0.12.3 to 0.16.0

### Affected Version

At least 0.16.0

### Description

We use from 3 to 6 volumes on historicals with such configs:
druid.segmentCache.locations=[{"path": "/storage1", "maxSize": 1360000000000},{"path": "/storage2\", "maxSize": 1360000000000},{"path": "/storage3", "maxSize": 1360000000000}]

After the upgrade I see that the usage of /storage1 is growing, but all other locations do not change.

**Comment by Laboltus** [comment]
I just realized that historical process reads from all segmentCache locations during startup. So the problem is only with segments saving from deep storage.

**Comment by jihoonson** [comment]
Hi @Laboltus, this bug is fixed in https://github.com/apache/incubator-druid/pull/8038 which will be included in 0.17.0.

**Comment by jihoonson** [comment]
I'm going to close this issue but please feel free to open it again if you have more issues about this.
