### ISSUE TITLE
Druid coordinator dynamic compaction failure

### ISSUE THREAD

**Issue by mr0al** [apache/incubator-druid#8674]
Druid 0.14.1

I've set up druid dynamic compaction config on a realtime datasource but it seems this is even failing to launch a task. 
If helps, I have long running indexer 5h with an intermediateHandoffPeriod of 5mins.
Couldn't find anything anywhere on the below.. any ideas pls?

![Screen Shot 2019-10-15 at 10 06 49] (https://user-images.githubusercontent.com/5665595/66819286-a52d6980-ef36-11e9-92a3-1701b29dd083.png)

**Comment by vogievetsky** [comment]
What is you `druid.indexer.runner.type` set to?

**Comment by mr0al** [comment]
Sorry for delay - it was local. Changing to remote seems to fix it.. I see https://github.com/apache/incubator-druid/issues/8683 has been raised since as well.
