### ISSUE TITLE
Add canonical links to web site

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#8712]
The Druid website is hosted at a number of URLs. The canonical URL should be https://druid.apache.org/. To help Google out we should include canonical URLs: https://support.google.com/webmasters/answer/139066

**Comment by vogievetsky** [comment]
I'll take a look

**Comment by vogievetsky** [comment]
Adding to everything but the docs: https://github.com/apache/incubator-druid-website-src/pull/67
