### ISSUE TITLE
Docusaurus: Right sidebar is sometime missing

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#8726]
### Affected Version

0.16.0 Documentation

### Description

The right sidebar doesn't appear for all pages. It also has other side effects (see below).

This page has it:
https://druid.apache.org/docs/latest/querying/sql.html
This doesn't:
https://druid.apache.org/docs/latest/querying/groupbyquery.html

In pages that don't have the sidebar, the page width is shorter than usual and ends abruptly with a white area, without a scrollbar to suggest further text exists. 
Example:
https://druid.apache.org/docs/latest/querying/query-context.html

I suggest to fix it in a way that all pages will have the right sidebar and the same width.

**Comment by vogievetsky** [comment]
Hmm good catch it looks like https://druid.apache.org/docs/latest/querying/groupbyquery.html starts with an h3 (instead of h2). I bet that is the issue.
