### ISSUE TITLE
Ability to provide different sort ordering for Druid SQL queries.

### ISSUE THREAD

**Issue by abhishekrb19** [apache/incubator-druid#8800]
### Description

Native Druid queries support different [sort ordering](https://druid.apache.org/docs/latest/querying/sorting-orders.html
) and can be specified like [this]( https://druid.apache.org/docs/latest/querying/topnmetricspec.html):
```json
"metric": {
    "type": "dimension",
    "ordering": "lexicographic",
    "previousStop": "<previousStop_value>"
}
```
AFAIK, Druid SQL always defaults to `lexicographic` ordering - having the ability to express another ordering would be great. My first thought was an `ordering` param could be added to a query context like the following:
```json
"context": {"timeout": 1000, "ordering": "numeric"}
```
If `ordering` is supplied, DruidSql and NativeDruid will honor that. Thoughts?

**Comment by vogievetsky** [comment]
I think DruidSQL orders depending on what the data type is. If you have a string value that represents numbers then you could cast it `CAST('foo' AS BIGINT)`

**Comment by abhishekrb19** [comment]
Oh, yes, the `CAST` worked! Thanks @vogievetsky, I will close this issue.
