### ISSUE TITLE
web console: Load rule includeFuture flag is not visible or editable

### ISSUE THREAD

**Issue by glasser** [apache/incubator-druid#8855]
### Affected Version

Tested on 0.15.1. From source examination, still problematic on 0.16/master.

### Description

https://github.com/apache/incubator-druid/pull/6414 added an includeFuture flag to loadByPeriod and dropByPeriod rules, but the web console doesn't let you see or edit this flag.

**Comment by vogievetsky** [comment]
Good one. Will add.
