### ISSUE TITLE
Unable to get kafka consumer group information

### ISSUE THREAD

**Issue by mggger** [apache/incubator-druid#8873]
<img width="1413" alt="屏幕快照 2019-11-15 下午12 46 09" src="https://user-images.githubusercontent.com/13358284/68917590-f636b480-07a5-11ea-8742-70316c6a0413.png">

I am looking forward to a consumer group named kafka-supervisor-%s

**Comment by qianmoQ** [comment]
yes, kafka index service not implements kafka group, kafka task init group id is null("").
