### ISSUE TITLE
Datasources shows 0% available fo any dataset and never starts

### ISSUE THREAD

**Issue by rodolfo-flores-tierconnect-com** [apache/incubator-druid#8874]
### Affected Version
0.16.0

### Description
Hi there, Trying to follow the druid Tutorial, I got stuck on the first steps.
Datasources is showing 0% available in any datasets after publishing of Task
![image](https://user-images.githubusercontent.com/18538611/68958739-0f8a3180-07a3-11ea-8539-9399d8e03d40.png)

- Cluster size
     Single Machine
- Configurations in use
     Single Machine, service started with start-micro-quickstart command
- Steps to reproduce the problem
     Go to Load Data, Select a Json or CSV format, next on all steps and publish the task
     Go to Tasks and it shows that it was executed successfully
![image](https://user-images.githubusercontent.com/18538611/68958924-760f4f80-07a3-11ea-802f-af1b759291ac.png)
      Go to DataSources and it shows 0% available "1 segment, 1 segment unavailable"

Thanks in advance

**Comment by vogievetsky** [comment]
Please verify that you are running Java 8 (run `java -version`) this is a known issue with Druid when running on Java 9, 10, 11, 12

**Comment by rodolfo-flores-tierconnect-com** [comment]
Thanks @vogievetsky , I changed to java 8 and it's working fine!!
![image](https://user-images.githubusercontent.com/18538611/69177676-6151f500-0ade-11ea-8357-b49d6e53d13c.png)
