### ISSUE TITLE
changing segment granularity on realtime nodes causes ingestion to stop

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#888]
discussed and described in detail on 
https://groups.google.com/forum/#!msg/druid-development/P3xjuX9xp30/HWGFubDjf0sJ

The solution given, to delete the directory of the realtime node is incorrect since it will result in loss of data

**Comment by vogievetsky** [comment]
This is not an issue with the newer [Kafka indexing service](http://druid.io/docs/latest/development/extensions-core/kafka-ingestion) right?

**Comment by pdeva** [comment]
dont think so..l
