### ISSUE TITLE
Support DRUID_JAVA_HOME (or just JAVA_HOME)

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#8928]
Currently Druid just uses `java` (see [verify-java](https://github.com/apache/incubator-druid/blob/934547a2159e0580845055cbc12f5bcdf7b705cd/examples/bin/verify-java) script), which is not very developer-friendly outside of containers.

Java 11+ may already be the default java on the developer's machine. So for the purposes of Druid start, it would be nice to support `DRUID_JAVA_HOME` (or, at least, just `JAVA_HOME`) environment variable with a path to Java 8.

FYI @jon-wei @gianm

**Comment by jon-wei** [comment]
That sounds good to me

**Comment by himanshug** [comment]
I would +1 for supporting `JAVA_HOME`  instead of `DRUID_JAVA_HOME` as that is pretty standard in any java project for similar situation.
