### ISSUE TITLE
Parsing is failing for Pipe Separated Values

### ISSUE THREAD

**Issue by himanshushukla254** [apache/incubator-druid#8936]
I am currently using the druid-Incubating-0.16.0 version. While uploading the pipe separated data like following

```
pushdate|name|rollno|department|result|cgpa
2019-06-14 05:00:11|amar|42|cse|pass|8.6
2019-06-14 05:00:12|rohini|21|ece|fail|3.2
2019-06-14 05:00:13|aman|23|cse|pass|8.9
2019-06-14 05:00:14|rahul|45|ee|fail|4.6
2019-06-14 05:00:17|suvam|68|me|pass|8.2
2019-06-14 05:00:15|pratik|65|cse|pass|7.2
2019-06-14 05:00:16|raunak|23|me|pass|9.1
```
I am getting **unparseable timestamp** error.
As per my debugging, It is not able to parse the given **pushdate** column to **_time**  because the whole row is coming as one column. I have seen the case where druid has detected the timestamp field automatically and parsed it correctly but here it is failing.

I want to know if the druid has support for pipe separated files because it is working when I am keeping it as comma-separated.

If it has pipe separated support then any specific configuration is needed. 
PFA image.

![druid-issue](https://user-images.githubusercontent.com/15158684/69537377-00c32c00-0fa6-11ea-84cd-6106e314596f.PNG)

**Comment by jihoonson** [comment]
Hi @himanshushukla254, I guess your data is not being parsed properly. What did you choose for your parser in `Parse data` step?

**Comment by himanshushukla254** [comment]
Hi @jihoonson, i chose csv for these pipe separated rows. When i am uploading comma separated value, druid is automatically considering it as CSV and showing a proper tabular view but for pipe separated it is selecting regex by default and even after selecting csv from drop-down the tabular view is not coming.

**Comment by jihoonson** [comment]
Ah, the default separator is a comma in CSV. You probably can see your data parsed properly by selecting `tsv` parser.

**Comment by himanshushukla254** [comment]
But for tsv the value should be tab separated right? I chose tsv also as parser but found the same issue.

**Comment by jihoonson** [comment]
`tsv` is actually for delimited file formats and its default separator is a tab. But you should be able to set a custom delimiter by adding a `delimiter` parameter as below.

```json
        "parseSpec" : {
          "format" : "tsv",
          "delimiter": "|",
          "timestampSpec" : {
            "column": "l_shipdate",
            "format": "yyyy-MM-dd"
          },
```

**Comment by gianm** [comment]
@vogievetsky how is this meant to work in the console?

**Comment by vogievetsky** [comment]
unfortunately the `delimiter` property is not exposed in the console UI in 0.16.0. You can add it manually by going to the `Edit JSON spec` tab and adding it into the `parseSpec`. This shortcoming will be addressed in 0.17.0

**Comment by himanshushukla254** [comment]
Hi @jihoonson @vogievetsky @gianm, I am able to upload the data as per the changes suggested by @jihoonson but there is some issue with timestamp field. 

I am able to see date alone (e.g 2019-06-14T00:00:00.000Z**)  in the **_time** column however I was expecting it like **2019-06-14T05:00:12.000Z**  instead of **2019-06-14T00:00:00.000Z**. 

FYI, I have given the **yyyy-MM-dd HH:mm:ss** in **timestampSpec -> format**

**Comment by vogievetsky** [comment]
You probably have queryGranularity set to HOUR, that truncates your time column.

Here is a video I made about it: https://www.youtube.com/watch?v=u551R7voe7w (around 10min mark I talk about query granularity)

**Comment by himanshushukla254** [comment]
Thanks, @vogievetsky @jihoonson  for the clarification.
