### ISSUE TITLE
Issue while updating the data in Datasource

### ISSUE THREAD

**Issue by himanshushukla254** [apache/incubator-druid#8966]
I am currently using the druid-Incubating-0.16.0 version.  As mentioned in [https://druid.apache.org/docs/latest/tutorials/tutorial-update-data.html](https://druid.apache.org/docs/latest/tutorials/tutorial-update-data.html) tutorial link, we can use combining firehose to update and merge the data for a data source.

**Step : 1**
I am using the same sample data with initial structure as 
```
┌──────────────────────────┬──────────┬───────┬────────┐
│ __time                   │ animal   │ count │ number │
├──────────────────────────┼──────────┼───────┼────────┤
│ 2018-01-01T01:01:00.000Z │ tiger    │     1 │    100 │
│ 2018-01-01T03:01:00.000Z │ aardvark │     1 │     42 │
│ 2018-01-01T03:01:00.000Z │ giraffe  │     1 │  14124 │
└──────────────────────────┴──────────┴───────┴────────┘

```
Step 2:
I updated the data for **tiger** with **{"timestamp":"2018-01-01T01:01:35Z","animal":"tiger", "number":30} with appendToExisting = false and rollUp = true** and found the result 
```
┌──────────────────────────┬──────────┬───────┬────────┐
│ __time                   │ animal   │ count │ number │
├──────────────────────────┼──────────┼───────┼────────┤
│ 2018-01-01T01:01:00.000Z │ tiger    │     2 │    130 │
│ 2018-01-01T03:01:00.000Z │ aardvark │     1 │     42 │
│ 2018-01-01T03:01:00.000Z │ giraffe  │     1 │  14124 │
└──────────────────────────┴──────────┴───────┴────────┘
```
Step 3:
Now i am updating **giraffe** with **{"timestamp":"2018-01-01T03:01:35Z","animal":"giraffe", "number":30} with appendToExisting = false and rollUp = true** and getting the following result
```
┌──────────────────────────┬──────────┬───────┬────────┐
│ __time                   │ animal   │ count │ number │
├──────────────────────────┼──────────┼───────┼────────┤
│ 2018-01-01T01:01:00.000Z │ tiger    │     1 │    130 │
│ 2018-01-01T03:01:00.000Z │ aardvark │     1 │     42 │
│ 2018-01-01T03:01:00.000Z │ giraffe  │     2 │  14154 │
└──────────────────────────┴──────────┴───────┴────────┘
```

My doubt is, **In step 3 the count of the tiger is getting decreased by 1 but I think it should not be changed since there are no changes in step 3 for tiger and there is no number change also** 

FYI, count and number are metricSpec and they are **count** and **longSum** respectively.
Please clarify.

@gianm @vogievetsky @jihoonson

**Comment by himanshushukla254** [comment]
any updates?

**Comment by himanshushukla254** [comment]
Any updates?

**Comment by jon-wei** [comment]
> My doubt is, In step 3 the count of the tiger is getting decreased by 1 but I think it should not be changed since there are no changes in step 3 for tiger and there is no number change also

Between step 2 and 3, the datasource only has 1 "tiger" row.

If you reingest that datasource with a "count" aggregator, the "count" aggregator will only see 1 row, hence "tiger" with "count=1" in step 3.

If you want to preserve the counts during reingestion, you'll want to use a longSum aggregator on the "count" column instead
