### ISSUE TITLE
Tasks fail on upgraded middlemanager 0.12.3 ==> 0.16.0 with error "Granularity is not supported"

### ISSUE THREAD

**Issue by AvinoamBN** [apache/incubator-druid#8995]
After upgrading the middleManagers from 0.12.3 the compact tasks that have been sent to the overlord have been failing. 

The Druid version is 0.16.0

tasks that have been sent before the upgrade show the following INFO in the logs:
{
  "type" : "compact",
  "id" : "compact_s_b_2019-12-05T07:45:02.184Z",
  "resource" : {
    "availabilityGroup" : "compact_s_b_2019-12-05T07:45:02.184Z",
    "requiredCapacity" : 1
  },
  "dataSource" : "s_b",
  "interval" : "2019-10-31T00:00:00.000Z/2019-10-31T23:59:59.000Z",
  "segments" : null,
  "tuningConfig" : null,
  "context" : { },
  "groupId" : "compact_s_b_2019-12-05T07:45:02.184Z",
  "dimensionsSpec" : null
}

tasks that have been sent after the upgrade show the following INFO in the logs:
{
  "type" : "compact",
  "id" : "compact_s_b_2019-12-05T13:45:02.394Z",
  "resource" : {
    "availabilityGroup" : "compact_s_b_2019-12-05T13:45:02.394Z",
    "requiredCapacity" : 1
  },
  "dataSource" : "s_b",
  "interval" : "2019-10-16T00:00:00.000Z/2019-10-16T23:59:59.000Z",
  "segments" : null,
  "dimensionsSpec" : null,
  **"metricsSpec" : null,
  "segmentGranularity" : null,
  "targetCompactionSizeBytes" : null,**
  "tuningConfig" : null,
  "context" : { },
  "groupId" : "compact_s_b_2019-12-05T13:45:02.394Z"
}

im not sure what is the source of the problem, and im not sure if i need to change my ingestions or something in the middleManagers.

any help would be appreciated,
thank you

**Comment by jon-wei** [comment]
> After upgrading the middleManagers from 0.12.3 the compact tasks that have been sent to the overlord have been failing.

Are all nodes running version 0.16.0 when you see this? If not, try upgrading them all to the same version.

Do you have the stack trace for the error?

**Comment by AvinoamBN** [comment]
Hi jon-wei, thank you for your reply.

you were right! after finishing the rolling updates for the rest of the nodes - coordinator & overlord in this case - the **segmentGranularity** received the values and the error was gone.

So seems like it was an issue of the overlord not being on the same version as the middlemanagers.

Thank you very much!
