### ISSUE TITLE
druid dynamic configuration

### ISSUE THREAD

**Issue by Maplejw** [apache/incubator-druid#9016]
The 'sw_template_behavior' datasource generates 24 segements each day. I want to compact 24 to 1 segements every day dynamicly.
This is my config and datasource.
![avatar](http://storage.ikeeplock.com/common/1576120164353-2198b422575f4f3ca8624ab733a16fa5.png)
```curl
druid.coordinator.period.indexingPeriod=PT1800S
curl http://172.26.51.19:8081/druid/coordinator/v1/config/compaction
{
"compactionConfigs":[
    {
    "dataSource":"sw_template_behavior",
    "taskPriority":25,
    "inputSegmentSizeBytes":419430400,
    "targetCompactionSizeBytes":419430400,
    "maxRowsPerSegment":null,
    "maxNumSegmentsToCompact":150,
    "skipOffsetFromLatest":"P1D",
    "tuningConfig":null,
    "taskContext":null
    }
],
"compactionTaskSlotRatio":0.2,
"maxCompactionTaskSlots":5
}
```
when 1800s comming,the log only shows
```log
org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentCompactor - Found [1] available task slots for compaction out of [1] max compaction task capacity
```
So I check the source code DruidCoordinatorSegmentCompactor.java. iterator.hasNext()  is false? I see the iterator is about exclue skip interval segement. Do I set skipOffsetFromLatest wrong?
```code
for (; iterator.hasNext() && numSubmittedTasks < numAvailableCompactionTaskSlots;) {
                          ............
}
```

Please help me. Thanks

**Comment by vogievetsky** [comment]
What you want to do is "adjust the segment granularity" from 1 hour to 1 day. That is not something that the auto compaction job runner (the one accessed by `/druid/coordinator/v1/config/compaction`) can do right now.
To change segment granularity you would have to manually issue `compact` jobs (see https://druid.apache.org/docs/latest/tutorials/tutorial-compaction.html )

**Comment by Maplejw** [comment]
@vogievetsky 
Sorry，I made a mistake. I thought there is a way to automatically merge small segment. And I used ./bin/post-index-task --file ./compact.json --url http://172.26.51.19:8081 to merge segment.
Thanks
